### ISSUE TITLE
release tarballs are missing bibtex-forms.bcf and bibtex-forms.bib

### ISSUE THREAD

**Issue by cbm755** [plk/biber#100]
As originally noted in #72, this leads to `bcfvalidation` tests failing.

Is it just a matter of adding them to MANIFEST?  I could send a pull request but wasn't sure about this.

**Comment by plk** [comment]
Actually those two files shouldn't be there at all - the forms stuff was removed a while ago from the main branches. I will remove them in the dev branch.
