### ISSUE TITLE
output_align in tool mode

### ISSUE THREAD

**Issue by thorade** [plk/biber#101]
According to the manual and to the `--help`, one should use `--output_align=false` to disable alignment with spaces (default is true). But when I try to use that, biber tells me: `Option output_align does not take an argument`. What would be the correct syntax to turn off alignment?

Using biber 2.1 on xubuntu 15.10

**Comment by plk** [comment]
Ah, this is a bug - that option should default to false and the boolean `--output-align` should set it to true. Fixed in DEV branch.

**Comment by thorade** [comment]
Thanks for the quick fix.
So in the future it will default to false and if I want to turn it on, I specify the option without argument?
Then the manual and the `--help` also need to be updated.

**Comment by thorade** [comment]
Sorry for the noise, you already answered the questions in your previous post.

**Comment by plk** [comment]
2.3 DEV binaries are updated on Sourceforge.
