### ISSUE TITLE
feature suggestion: sorting in tool mode

### ISSUE THREAD

**Issue by thorade** [plk/biber#102]
I want to use biber in tool mode for sorting a bib file. If I understand section 3.12.2 of the manual correctly, sort order can only be specified using a config file. It would be nice if I could use the same [sorting options that I can specify from biblatex](http://tex.stackexchange.com/a/51439/8569), e.g. something like `biber --tool --sorting=ynt references.bib`

Here is a possibly related question on TeX.SE
http://tex.stackexchange.com/questions/269242/how-to-sort-a-bib-file-with-biber

**Comment by plk** [comment]
I don't want to start replicating biblatex options for biber like this as it gets messy - to have pre-defined sorting like "ynt", you'd also have to have all of these defined in the config file just in case someone wants to use them.
