### ISSUE TITLE
Allow erroring out on datamodel constraint violations

### ISSUE THREAD

**Issue by t-b** [plk/biber#105]
I'm using a self defined custom data model in biber/biblatex from texlive 2015.
I also added constraints to be able to check the validity of the datamodel.

Calling biber with `--validate-datamodel file` outputs a message that constraints are violated.
I'm a bit suprised that violations of datamodel constraints are reported as *warnings* and not errors.

I would like biber to **abort** on datamodel violations.

Two implementation ideas come to my mind:
- Add a `nodieonwarning` flag to biber similiar to nodieonerror. Defaulting to the current setting `true`.
- Add a special `dieoninvaliddatamodel` flag, defaulting to false. This option would be nice to be able to set from biblatex as well. Or maybe even from the model definition itself?

Thanks for all your work on biber/biblatex project, very much appreciated!

**Comment by plk** [comment]
I have added a biber "dieondatamodel" error, defaults to false. When true, the first validation error will cause biber to report it and abort. This is in the DEV branch. I will rebuild binaries tomorrow and upload, updating this ticket.

**Comment by plk** [comment]
Development binaries on SF are now updated with this change.

**Comment by t-b** [comment]
@plk Thanks a lot! I've verified that the new switch/config option works using the dev win binariy.
