### ISSUE TITLE
Encoding for *.bbl file

### ISSUE THREAD

**Issue by MartinABCD** [plk/biber#106]
Since v2.3 of biber the encoding set by using `inputenc` together with `biblatex` package is ignored from biber and the `*.bbl` file is always written in UTF8. In the `*.bcf` file the right encoding options are set. 
Even when explicitly using the `texencoding=ansinew` option from `biblatex` the `*.bbl` file is UTF8. Though the output message from biber is:
`INFO - Writing 'document.bbl' with encoding 'ansinew'`

This behavior can be observed with TeXLive2015 (Win and Ubuntu) and MikTeX.
When using the commandline option `--output-encoding=ansinew` the encoding is done as expected.

As minimum example see [document.zip](https://github.com/plk/biber/files/88881/document.zip).

**Comment by plk** [comment]
This is already fixed in biber DEV 2.4 on Sourceforge. Please can you try this? You will also need biblatex 3.3 DEV version from Sourceforge.

**Comment by MartinABCD** [comment]
The new DEV version fixed the problem.
Thank you!
