### ISSUE TITLE
windows 10: biber application error (2.2, 2.3 and development version)

### ISSUE THREAD

**Issue by adv1112** [plk/biber#108]
error stating "The application was unable to start correctly (0xc0000142)...". Windows 10 insider preview 14251.

Biber <=2.1 working fine.

**Comment by plk** [comment]
I just tried the latest DEV binary build and also 2.3 binary on a fresh windows 10 VM and it was fine. I wonder if it is the preview windows you are using. Nobody else has reported this either and I would have expected a lot of reports if it was broken since Windows is a major platform for biber.

**Comment by plk** [comment]
There is no (in DEV at least), a windows 1-built 64-bit version.

**Comment by adv1112** [comment]
Biber seems to be working fine on windows 10 prev. 14271!
