### ISSUE TITLE
Handle corrupt .bcf files

### ISSUE THREAD

**Issue by MaxNoe** [plk/biber#109]
In the moment, if LaTeX exits with an error,
the `.bcf` file gets corrupted and calling biber will fail.

This leads to an endless cycle when using `latexmk`.

Could biber delete the corrupt file? Or handle it somehow, so this gets avoided?

**Comment by plk** [comment]
Did you try the development 2.4 version (which needs the development 3.3 biblatex too)? I thought that bug had been fixed there.

**Comment by MaxNoe** [comment]
Ah, no. Great if this is fixed already.

**Comment by plk** [comment]
Let me know if it's not fixed.

**Comment by MaxNoe** [comment]
It's not fixed in biber 2.4.

bibers output is 
```
INFO - This is Biber 2.4
INFO - Logfile is 'test.blg'
Use of uninitialized value $output in unlink at /tmp/par-6d61786e6f65/cache-ab2aa2ece61cc988b50d107b05c5c3fad9d00256/inc/lib/Biber.pm line 297.
Use of uninitialized value $output in concatenation (.) or string at /tmp/par-6d61786e6f65/cache-ab2aa2ece61cc988b50d107b05c5c3fad9d00256/inc/lib/Biber.pm line 298.
ERROR - test.bcf is malformed, last biblatex run probably failed. Deleted 
INFO - ERRORS: 1
```

But the `.bcf` file is still there.

**Comment by plk** [comment]
Actually, it's supposed to delete the output file, in this case the `.bbl`, not the `.bcf`. That "Delete" is supposed to have the name of the `.bbl` after it. Looking into it.

**Comment by plk** [comment]
This should be properly fixed now in 2.5 DEV on SourceForge.

**Comment by tugit** [comment]
Still happens with 2.7:

```
INFO - This is Biber 2.7 (beta)
INFO - Logfile is 'build/article.blg'
ERROR - build/article.bcf is malformed, last biblatex run probably failed. Deleted build/article.bbl
INFO - ERRORS: 1

Latexmk: Failed to find one or more biber source files: NONE

Biber error: [36] Utils.pm:180> ERROR - build/article.bcf is malformed, last biblatex run probably failed. Deleted build/article.bbl
```

**Comment by plk** [comment]
What exactly is the problem?

**Comment by tugit** [comment]
It seems using the -f option in latexmk is very sensible once the case is triggered that the bbl gets deleted.
I can't really provide a minimal example mine is very complex but I can reproduce that case everytime. 
When I trigger a syntax error in my document and after the failed compilation I fix it, latexmk gets stuck on the malformed bcf file error (unless I specify -f option).

What causes malformed bcf files?

**Comment by plk** [comment]
Generally a bad parser error and problem with the .bib file.

**Comment by tugit** [comment]
Ok so a texfile with incorrect syntax malforms the bcf file?

**Comment by plk** [comment]
Yes, can do - the .bcf is written by biblatex and consumed by biber so if you have a malformed .bcf, it means that something went wrong with the tex run which created it.
