### ISSUE TITLE
Missing biber file

### ISSUE THREAD

**Issue by glennmschultz** [plk/biber#111]
INFO - Logfile is 'cache.blg'
read_file '/var/folders/54/hl7tfh_d27s7fzdfb5r70vdr0000gn/T/par-676c656e6e736368756c747a/cache-6bef3f811cde577dd70e44f9f5046ebc66712c46//inc/lib/Biber/LaTeX/recode_data.xml' - sysopen: No such file or directory at /var/folders/54/hl7tfh_d27s7fzdfb5r70vdr0000gn/T/par-676c656e6e736368756c747a/cache-6bef3f811cde577dd70e44f9f5046ebc66712c46/60940e05.pm line 115.

biber fails and when I follow the error to the cache the file is missing - however, I did not delete this file and the last time I complied my document everything was fine.  I often have to reinstall MacTex to fix biber problems.

**Comment by plk** [comment]
Which version of biber? This is an old error that should have been fixed a couple of revisions ago.

**Comment by glennmschultz** [comment]
whichever comes with MacTex2015.  Just fixed it today by reinstalling MacTex2015.  The most recent version for ElCapitain
