### ISSUE TITLE
= in annote field makes biber warning

### ISSUE THREAD

**Issue by maieul** [plk/biber#112]
Consider this MWE

`````
\documentclass{article}
\usepackage[style=reading]{biblatex}
\bibliography{biber.bib}
\begin{document}
\cite{toto}
\printbibliography
\end{document}
``````

`````
@book{toto,
	Annote = {
		a = B
},
	Publisher = {Toto},
	Title = {Toto},
	Year = {1900}}
```````

The ligne `a = B` make biber create  warning `WARN - BibTeX subsystem: /var/folders/0g/vh5y8yv93js6v76gmjpnt4mr0000gr/T/5r_VO5fQAv/biber.bib_10557.utf8, line 3, warning: possible runaway string started at line 2`

**Comment by plk** [comment]
Changing it to `Annote = {a = B},` works. This is a minor issue and to fix it I would have to hack the underlying C parsing library and I'd rather not do that for such a small thing.

**Comment by maieul** [comment]
I understand. In my real example I have more line with equal, but as you tell, it is a lot of work for a  little bug.
