### ISSUE TITLE
Sourceforge MD5SUM check for biber-linux_x86_64.tar.gz fails.

### ISSUE THREAD

**Issue by globetrotterdk** [plk/biber#114]
Using slpkg to install texlive with biber-linux_x86_64.tar.gz as a dependency:

Expected: 64715ade77a7d659fd43be8773ebfdb9
Found: 90a6a4d6207ea244f04be0c64abe292e

My system is Salix64 OS MATE 14.1.

**Comment by plk** [comment]
I'm not sure what this indicates? Where does the expected checksum come from? I don't generate any.

**Comment by globetrotterdk** [comment]
Thanks for the quick reply. I am not sure. Could it be Sourceforge that is generating these md5sums on their repos? If so, the lack of a md5sum match would either mean that their copy of the package is corrupted or compromised. Do you know how to contact Sourceforge to get this corrected?

**Comment by plk** [comment]
Which version are you doing this against? Current 2.4 MD5 on SF (which I think they generate themselves on upload):

8879eb5f9b2195b156e78ec6928057d2

and it matches ok when I download.

**Comment by globetrotterdk** [comment]
The version being pulled in appears to be 1.8. Here is the full output (there seems to be a lot of 302 errors on the Sourceforge mirrors):
`[3/3][ Download ] --> biber-linux_x86_64.tar.gz

--2016-03-20 22:35:55--  http://downloads.sourceforge.net/project/biblatex-biber/biblatex-biber/1.8/binaries/Linux/biber-linux_x86_64.tar.gz
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.34.181.59
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://vorboss.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/1.8/binaries/Linux/biber-linux_x86_64.tar.gz [following]
--2016-03-20 22:36:22--  http://vorboss.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/1.8/binaries/Linux/biber-linux_x86_64.tar.gz
Resolving vorboss.dl.sourceforge.net (vorboss.dl.sourceforge.net)... 5.10.152.194
Connecting to vorboss.dl.sourceforge.net (vorboss.dl.sourceforge.net)|5.10.152.194|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://downloads.sourceforge.net/mirrorproblem?failedmirror=vorboss.dl.sourceforge.net [following]
--2016-03-20 22:36:48--  http://downloads.sourceforge.net/mirrorproblem?failedmirror=vorboss.dl.sourceforge.net
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.sourceforge.net/project/biblatex-biber/biblatex-biber/development/binaries/Linux/biber-linux_x86_64.tar.gz?failedmirror=vorboss%7Cvorboss.dl.sourceforge.net [following]
--2016-03-20 22:36:50--  http://downloads.sourceforge.net/project/biblatex-biber/biblatex-biber/development/binaries/Linux/biber-linux_x86_64.tar.gz?failedmirror=vorboss%7Cvorboss.dl.sourceforge.net
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://netix.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/development/binaries/Linux/biber-linux_x86_64.tar.gz [following]
--2016-03-20 22:36:50--  http://netix.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/development/binaries/Linux/biber-linux_x86_64.tar.gz
Resolving netix.dl.sourceforge.net (netix.dl.sourceforge.net)... 87.121.121.2
Connecting to netix.dl.sourceforge.net (netix.dl.sourceforge.net)|87.121.121.2|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://downloads.sourceforge.net/mirrorproblem?failedmirror=netix.dl.sourceforge.net [following]
--2016-03-20 22:37:11--  http://downloads.sourceforge.net/mirrorproblem?failedmirror=netix.dl.sourceforge.net
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://heanet.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/development/binaries/Linux/biber-linux_x86_64.tar.gz [following]
--2016-03-20 22:37:15--  http://heanet.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/development/binaries/Linux/biber-linux_x86_64.tar.gz
Resolving heanet.dl.sourceforge.net (heanet.dl.sourceforge.net)... 193.1.193.66, 2001:770:18:aa40::c101:c142
Connecting to heanet.dl.sourceforge.net (heanet.dl.sourceforge.net)|193.1.193.66|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://downloads.sourceforge.net/mirrorproblem?failedmirror=heanet.dl.sourceforge.net [following]
--2016-03-20 22:37:16--  http://downloads.sourceforge.net/mirrorproblem?failedmirror=heanet.dl.sourceforge.net
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://netcologne.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/development/binaries/Linux/biber-linux_x86_64.tar.gz [following]
--2016-03-20 22:37:18--  http://netcologne.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/development/binaries/Linux/biber-linux_x86_64.tar.gz
Resolving netcologne.dl.sourceforge.net (netcologne.dl.sourceforge.net)... 78.35.24.46, 2001:4dd0:1234:6::5f
Connecting to netcologne.dl.sourceforge.net (netcologne.dl.sourceforge.net)|78.35.24.46|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://downloads.sourceforge.net/mirrorproblem?failedmirror=netcologne.dl.sourceforge.net [following]
--2016-03-20 22:37:18--  http://downloads.sourceforge.net/mirrorproblem?failedmirror=netcologne.dl.sourceforge.net
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://iweb.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/development/binaries/Linux/biber-linux_x86_64.tar.gz [following]
--2016-03-20 22:37:20--  http://iweb.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/development/binaries/Linux/biber-linux_x86_64.tar.gz
Resolving iweb.dl.sourceforge.net (iweb.dl.sourceforge.net)... 70.38.0.134, 2607:f748:10:12::5f:2
Connecting to iweb.dl.sourceforge.net (iweb.dl.sourceforge.net)|70.38.0.134|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://downloads.sourceforge.net/mirrorproblem?failedmirror=iweb.dl.sourceforge.net [following]
--2016-03-20 22:37:22--  http://downloads.sourceforge.net/mirrorproblem?failedmirror=iweb.dl.sourceforge.net
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://jaist.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/development/binaries/Linux/biber-linux_x86_64.tar.gz [following]
--2016-03-20 22:37:22--  http://jaist.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/development/binaries/Linux/biber-linux_x86_64.tar.gz
Resolving jaist.dl.sourceforge.net (jaist.dl.sourceforge.net)... 150.65.7.130, 2001:df0:2ed:feed::feed
Connecting to jaist.dl.sourceforge.net (jaist.dl.sourceforge.net)|150.65.7.130|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://downloads.sourceforge.net/mirrorproblem?failedmirror=jaist.dl.sourceforge.net [following]
--2016-03-20 22:37:30--  http://downloads.sourceforge.net/mirrorproblem?failedmirror=jaist.dl.sourceforge.net
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://tenet.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/development/binaries/Linux/biber-linux_x86_64.tar.gz [following]
--2016-03-20 22:37:30--  http://tenet.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/development/binaries/Linux/biber-linux_x86_64.tar.gz
Resolving tenet.dl.sourceforge.net (tenet.dl.sourceforge.net)... 2001:4200:fffc::245
Connecting to tenet.dl.sourceforge.net (tenet.dl.sourceforge.net)|2001:4200:fffc::245|:80... failed: Network is unreachable.

+==============================================================================
| MD5SUM check for texlive-20140525-source.tar.xz [ PASSED ]
+==============================================================================


+==============================================================================
| MD5SUM check for texlive-texmf-tetexish-20140525.tar.xz [ PASSED ]
+==============================================================================


+==============================================================================
| MD5SUM check for biber-linux_x86_64.tar.gz [ FAILED ]
+==============================================================================
| Expected: 64715ade77a7d659fd43be8773ebfdb9
| Found: 90a6a4d6207ea244f04be0c64abe292e
+==============================================================================
`
I hope this helps.

**Comment by plk** [comment]
Hmm, I think you will have to speak to Sourceforge admin - they have an email contact on the site, I'm not sure what is going on there. I would say that biber 1.8 is quite old now and if you are packaging anything, I would do it with anything older than 2.0.

**Comment by globetrotterdk** [comment]
OK, cheers. It looks like I will have to run this manually.
