### ISSUE TITLE
Biber 2.4 fails on OS X 10.11.4

### ISSUE THREAD

**Issue by nanoant** [plk/biber#116]
I don't know if it is a fault of OS X or faulty packaging, but Biber 2.4 fails on my OS X machines with lots of warnings and one final error, and it is unable to produce valid output.
~~~
$ ~/Downloads/biber test
INFO - This is Biber 2.4
INFO - Logfile is 'test.blg'
INFO - Reading 'test.bcf'
WARN - Warning: Found biblatex control file version 2.9, expected version 3.0
Use of uninitialized value in lc at /var/folders/8y/fkcsg_7x47s5gv7gjj11mmhh0000gn/T/par-6f6e6f/cache-826ca9a6e77eb8aa8c31af944f2499820d908274/inc/lib/Biber.pm line 419.
Use of uninitialized value in lc at /var/folders/8y/fkcsg_7x47s5gv7gjj11mmhh0000gn/T/par-6f6e6f/cache-826ca9a6e77eb8aa8c31af944f2499820d908274/inc/lib/Biber.pm line 424.
... lines above repeating ~200 times ...
INFO - Found 0 citekeys in bib section 0
INFO - Using all citekeys in bib section 1
INFO - Found 0 citekeys in bib section 0
INFO - Using all citekeys in bib section 2
INFO - Found 0 citekeys in bib section 0
Use of uninitialized value $snksn in lc at /var/folders/8y/fkcsg_7x47s5gv7gjj11mmhh0000gn/T/par-6f6e6f/cache-826ca9a6e77eb8aa8c31af944f2499820d908274/inc/lib/Biber/SortList.pm line 87.
Use of uninitialized value $lsnksn in concatenation (.) or string at /var/folders/8y/fkcsg_7x47s5gv7gjj11mmhh0000gn/T/par-6f6e6f/cache-826ca9a6e77eb8aa8c31af944f2499820d908274/inc/lib/Biber.pm line 799.
Use of uninitialized value $snksn in string eq at /var/folders/8y/fkcsg_7x47s5gv7gjj11mmhh0000gn/T/par-6f6e6f/cache-826ca9a6e77eb8aa8c31af944f2499820d908274/inc/lib/Biber/SortLists.pm line 77.
Use of uninitialized value $snksn in lc at /var/folders/8y/fkcsg_7x47s5gv7gjj11mmhh0000gn/T/par-6f6e6f/cache-826ca9a6e77eb8aa8c31af944f2499820d908274/inc/lib/Biber/SortList.pm line 87.
Use of uninitialized value $lsnksn in concatenation (.) or string at /var/folders/8y/fkcsg_7x47s5gv7gjj11mmhh0000gn/T/par-6f6e6f/cache-826ca9a6e77eb8aa8c31af944f2499820d908274/inc/lib/Biber.pm line 799.
INFO - Processing section 1
INFO - Looking for bibtex format file 'test.bib' for section 1
INFO - Decoding LaTeX character macros into UTF-8
INFO - Found BibTeX data source 'test.bib'
Use of uninitialized value in string eq at /var/folders/8y/fkcsg_7x47s5gv7gjj11mmhh0000gn/T/par-6f6e6f/cache-826ca9a6e77eb8aa8c31af944f2499820d908274/inc/lib/Biber/DataModel.pm line 201.
Use of uninitialized value in string eq at /var/folders/8y/fkcsg_7x47s5gv7gjj11mmhh0000gn/T/par-6f6e6f/cache-826ca9a6e77eb8aa8c31af944f2499820d908274/inc/lib/Biber/DataModel.pm line 204.
... lines above repeating ~100 times ...
Can't locate object method "get_sortnamekeyscheme" via package "Biber::Entry::Names" at /var/folders/8y/fkcsg_7x47s5gv7gjj11mmhh0000gn/T/par-6f6e6f/cache-826ca9a6e77eb8aa8c31af944f2499820d908274/inc/lib/Biber/Internals.pm line 1281.
~~~
However previous (downgraded) version 2.3 works just fine, no errors, no warnings whatsoever.

So I humbly ask to provide a "hotfix" and upload it to TeXLive repo, as currently "tlmgr install biber" installs faulty 2.4 version for OS X users.

**Comment by plk** [comment]
The first warning shows that you are using a version of biblatex compatible only with biber <=2.3 and that's the issue. See the compat matrix in the biber or biblatex PDF docs.

**Comment by nanoant** [comment]
@plk That don't justify emitting 300 lines of warnings and final line of error. Does it?

Moreover if 2.4 does not work with biblatex 2.9 bundled with latest 2015, why it was uploaded to TeXLive repo?

Running `tlmgr install biber` on latest 2015 TeXLive installs 2.4 which apparently does not work with it.

**Comment by plk** [comment]
You have to update biblatex and biber together if the compat matrix says so - that has always been the case. The versions of both shipped with TL 2015 were compatible. Perhaps the error could be more explicit but it's rare that anyone comes across this because people temd to update everything in a TL install all at once.

**Comment by nanoant** [comment]
@plk To be honest, it is hard to pick up the warning about incompatible version at the very top of the terminal, if your terminal screen is cluttered with 300 lines of Perl warnings and scrolled down. So I think first of all there should be no Perl warnings, and the version incompatibility message should be more descriptive, asking either to upgrade biblatex or downgrade biber to 2.3.

**Comment by plk** [comment]
It's impossible to know in advance what, if any, errors an incompatible version will issue on a particular document. I fact I plan to make the imcompatible data format message fatal in 2.5. The issue isn't about biber/biblatex versions but is about their data interchange format versions (.bcf/.bbl)

**Comment by moewew** [comment]
Would it make sense to make the version error message a bit more informative in that it also mentions the expected `biblatex` version alongside the bcf version? On TeX.SX I often see people confusing the bcf version and their `biblatex` version. Or you could simply bump the bcf version to be in line with the `biblatex` version.

**Comment by plk** [comment]
This is done already in 2.5 - it now reports, on .bcf mismatch, the biber and biblatex versions and explicitly says there is a mismatch. Such errors are now fatal too, as it was just confusing people.

**Comment by moewew** [comment]
Ah, great! Sorry for not checking the code first.
