### ISSUE TITLE
Knowing if a main entry was added by a crossref or by an explicit reference

### ISSUE THREAD

**Issue by maieul** [plk/biber#119]
The biblatex-opcite-booktitle use the crossref mechanism to use abreviation when citing a contribution in a book already citated.

Cf this following MWE
```
\documentclass{article}
\usepackage[mincrossrefs=0,citestyle=verbose-trad1,bibstyle=verbose]{biblatex}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
	@incollection{Klausner1997,
	Author = {David N. Klausner},
	Crossref = {Izydorczyk1997},
	Pages = {403-425},
	Title = {The \emph{Gospel of Nicodemus} in the Literature of Medieval Wales}}

 @incollection{Ogorman1997,
	Author = {Richard O'Gorman},
	Crossref = {Izydorczyk1997},
	Pages = {103-131},
	Title = {The \emph{Gospel of Nicodemus} in the Vernacular Literatur of Medieval France}}

 @collection{Izydorczyk1997,
	Address = {Tempe},
	Editor = {Izydorczyk, Zbigniew},
	Publisher = {Medieval \& Renaissance Texts \& Studies},
	Subtitle = {Texts, Intertexts, and Contexts in Western Europe},
	Title = {The Medieval \emph{Gospel of Nicodemus}},
	Shorttitle = {The Medieval \emph{Gospel of Nicodemus}},
	Year = {1997}}
\end{filecontents}
\bibliography{\jobname.bib}
\usepackage{biblatex-opcit-booktitle}
\begin{document}
\cite{Ogorman1997}

\cite{Klausner1997}

\printbibliography
\end{document}
```

Hoewever, there is no way, for now, to know if a book was added in the .bbl because of the crossref mechanism, or if it was added because of an explicit call in a <code>\cite</code> command.

Should it be possible to biber to add a boolean field:
- set to TRUE if the entry was mentionned in the <code>.bcf</code> file
- set to FALSE if the entry was not mentionned in the <code>.bcf</code> file but only added by crossref mechanism ?

The idea will be to allow to exclude easily the entry in the <code>\printbibliography</code> using a filter / checkbib.

**Comment by plk** [comment]
Done - two new tests `\ifcrossrefsource` and `\ifxrefsource`  which are true if the entry was crossrefed/xrefed more than mincrossrefs/minxrefs times.

**Comment by maieul** [comment]
I will make test this week-end.
But as I can read from your message, I am not sur the "true" value is the correct answer to my problem. Suppose for example that, in my previous MWE, I add `\cite{Izydorczyk1997}`
As `Ogorman1997` has been cited, the `\ifcrossrefsource` will be true for `Izydorczyk1997` , despite, for my need, I require an false (because I would have cited Izydorczyk1997 directly).

**Comment by plk** [comment]
Ok, I have changed it so that it will always be false if an entry was directly cited, even if it is also cross/xrefed > mincrossrefs/minxrefs times.

By the way, `mincrossrefs=0` is effectively the same as `mincrossrefs=1` since it will just include any entry mentioned in a `crossref` or `xref` field.

**Comment by maieul** [comment]
Thanks. It works perfectly ! Do you have any idea in which time biblatex v 3.4 will be released ?

**Comment by plk** [comment]
We have a few backwards compat things to do with bibtex which I hope will be done in the next few days and then I aim to release - it won't make it into TL 2016 before the freeze because there are too many large changes with 3.4 and we'd rather make it an update option for TL 2016.

**Comment by maieul** [comment]
ok. In my sense, the most large change was in 3.3 ;-) good luck for final coding.
