### ISSUE TITLE
Biber 2.5 libc requirement on GNU/Linux

### ISSUE THREAD

**Issue by dfussner** [plk/biber#122]
I'm just wondering whether you've upped the version of libc required on GNU/linux boxes in the latest binary release.  On my old machine, with the standard biber-linux_x86_32.tar.gz downloaded today from Sourceforge, I'm getting:

./biber: /lib/libc.so.6: version `GLIBC_2.11' not found (required by ./biber)

I admit my version of libc is very old, but I've been using a dev version of biber 2.5 for a month on this box and it has been working fine -- is the library upgrade a requirement?  (Can't find it in the docs.)

Thanks.

**Comment by plk** [comment]
Yes, My old ubuntu 9 build VMs were becoming unmaintainable and so I had to install the next best thing - 10.10 Ubuntu and this is the reason. I'm afraid I have to up the requirments every few years to make things maintainable.

**Comment by dfussner** [comment]
I understand thoroughly -- many thanks for getting back to me so quickly.
