### ISSUE TITLE
defaults for relatedoptions

### ISSUE THREAD

**Issue by dcpurton** [plk/biber#124]
Not so much a bug, but slightly unintuitive behaviour.

The default for `relatedoptions` is `dataonly` which sets the various options as explained in the manual. This is good and makes sense.

But if the entry pointed to by `related` also has options, e.g. `useeditor=false`, then this is not automatically transferred to the related clone. So the output when used as a related entry is different to when cited directly. For (what I think is) intuitive behaviour, you need to then set `relatedoptions = {dataonly, useeditor=false}`.

Would it not make sense to *append* `dataonly` to the `options` field of the clonesource and use that as the default for `relatedoptions`?

It's not a big deal, and the manual is clear. So feel free to ignore if you think the current behaviour is better, or there are technical issues in doing this.

**Comment by plk** [comment]
I agree that this should behave as you mention, copying the options which can be then overridden. Fixed with regression test in latest 2.6. It's good that you are stretching the related functionality so we can pick up these edge cases.

**Comment by dcpurton** [comment]
Nice! It works. Except I realise now that this doesn't actually help in most of my cases :(.

I have an idea how what I want could be included as a feature. But I think it better fits with `biblatex`. I'll open an issue there.
