### ISSUE TITLE
Match version of biber to the biblatex version

### ISSUE THREAD

**Issue by JelteF** [plk/biber#127]
Right now it is very confusing to match the correct version of biber to its matching biblatex version.
For almost all of the previous releases of biblatex, biber also had to be updated (see https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES).

Because of this I think it would make a lot of sense to match the version numbers of the two. This way it is clear what versions match right away instead of needing to look it up. This would also mean that the errors caused by a version mismatch would be much clearer as it would be clear right away that the displayed versions would match biblatex and biber.

**Comment by plk** [comment]
This will probably happen for biblatex 4.0. Anyway, biblatex 3.4/biber 2.5 has a more sensible version mismatch reporting message, which is now fatal.

**Comment by JelteF** [comment]
Sounds good, although I'm not sure how many releases would come before 4.0. I've also seen the new version mismatch reporting. But one thing that makes it still quite unclear is that the biblatex control file version does not seem to match either the biblatex version or the biber version. The following is for biblatex 3.5 and biber 2.5:
```
Biber error: [151] Utils.pm:165> ERROR - Error: Found biblatex control file version 3.2, expected version 3.1.
```

**Comment by plk** [comment]
This is true - the .bbl and .bcf versions don't necessarily change with programs which is a way to track which versions work together. There have been, however, many program versions that incremement the .bbl and .bc versions so this is mostly just confusing and will be rationalised around version 4.0 of biblatex.

**Comment by JelteF** [comment]
Alright, I'll be looking forward to 4.0 then.
