### ISSUE TITLE
Hash / Label name combining two fields

### ISSUE THREAD

**Issue by maieul** [plk/biber#128]
The biblatex-realauthor "style" allow us to insert the real name of the autor if printed with pseudonyme. The standard output will be `PUBLISHED NAME [= REAL NAME], etc.` or `[REAL NAME], etc.` for works published anonymously.

The authorname bibliographic style use the field `fullhash` to insert a dash for two consecutives entry with the same author.

However, in the case of realeditor, this hash should be calculated with the two fields \verb+author+ and \verb+realauthor+, as two works published with the same name can be, theorically, from two different real author.

ps: I don't think there is emergency. The case is very rare. My priority is to #121

**Comment by plk** [comment]
Realistically, this won't happen in the core because it would mean serious additions in biber internals. The name hashes are available in the .bbl (assuming that realname is declared as a name list in the datamodel) and you could simply concatenate the hashes in the style.

**Comment by maieul** [comment]
ok. Will do it.

**Comment by maieul** [comment]
The realname hash is available on the .bbl, really. But how could I get it ? The biblatex handbook told use  that the hash field is available only in name formatting directives, but I need it out of formatting directive.

Here an extract of the .bbl file 

`````
\entry{Simon1686}{book}{}
      \name{author}{1}{}{%
        {{hash=d9bafd434661af3e49fc660ccc58b415}{%
           family={{Prieur\bibnamedelimb de\bibnamedelimb Bolleville}},
           family_i={P\bibinitperiod}}}%
      }
      \name{realauthor}{1}{}{%
        {{hash=6888e07ac8440b3bea794b7843c4229c}{%
           family={Simon},
           family_i={S\bibinitperiod},
           given={Richard},
           given_i={R\bibinitperiod}}}%
      }
      \list{location}{1}{%
        {Rotterdam}%
      }
      \list{publisher}{1}{%
        {Reinier Leers}%
      }
      \strng{namehash}{d9bafd434661af3e49fc660ccc58b415}
      \strng{fullhash}{d9bafd434661af3e49fc660ccc58b415}
      \field{sortinit}{P}
      \field{sortinithash}{c0a4896d0e424f9ca4d7f14f2b3428e7}
      \field{labelnamesource}{author}
      \field{labeltitlesource}{title}
      \field{title}{Réponse au livre intitulé sentimens de quelques Theologiens de Hollande sur l'Histoire Critique du Vieux Testament}
      \field{year}{1686}
    \endentry
`````

I have tried to save it using a special NameFormating
````
\DeclareNameFormat{save:real}{%
 \nameparts{#1}%
 \savefield{hash}{\bbx@hash@realname}%
}

called via 

`````
 \printnames[save:real]{realauthor}
````

However, it is not a useful way, as it pertubarte the unit system.
