### ISSUE TITLE
DeclareSourceMap \perrefsection

### ISSUE THREAD

**Issue by sistlind** [plk/biber#130]
Is it possible to filter within a DeclareSourceMap a specific refsection, just like the filename?

I would like to use the same bib-file in two refsection. While the first refsection contains the "normal" entries, cited with \cite{}, the second refsection contains a nocite{*} command and the bibliography shows all off my own publication.

Now i ran in some problems with tex capacity errors, because the bbl files got too big. Therefore, I would like to have a DeclareSourceMap filter, where i can filter out all entry without my name, but only at the second refsection.

By now, my workaround is symlink the file to another name and use the \perdatasource switch, but the better solution would be to directly filter by refsection.

Best regards, Stefan

**Comment by plk** [comment]
I'm afraid that's not possible directly as sourcemapping doesn't know anything about refsections - it is datasource centric. I would recommend posting to tex.stackexchange.com so we can get some ideas about how to do this.

**Comment by sistlind** [comment]
I had a closer look to the source code and if i understand it correctly, the section information is known at the filtering step:
https://github.com/plk/biber/blob/dev/lib/Biber/Input/file/bibtex.pm#L387

The only problem could be the cached parsing, this has to be disabled, if a perrefsection filter exists.
https://github.com/plk/biber/blob/dev/lib/Biber/Input/file/bibtex.pm#L393

Or did i misunderstood the code?

Best regards,
Stefan

PS: As you mentioned, i had also opened an issue [here](http://tex.stackexchange.com/questions/316682/declaresourcemap-filter-by-perrefsection) with an MWE

**Comment by plk** [comment]
Please download biblatex 3.5 and biber 2.6 development versions from sourceforge. There is now a `refsection` option on the `\maps` command which lets you specify a particular reference section to apply the `\map` commands inside to. I have tested a bit and it seems alright. Please try it. There may be odd side effects if you create clones/new entries with maps inside a specific refsection only but I doubt it.

**Comment by sistlind** [comment]
Thanks a lot, the filtering is working perfectly!
Nevertheless, there seems to be a bug, if i want to use different \maps, e.g:
```
\DeclareSourcemap{
    \maps[datatype=bibtex,overwrite=true,refsection=1]{
    \map{
        \step[fieldsource=author, notmatch=\regexp{Lindner,\sS},final]
        \step[entrynull]
     }
    \map{ 
      \step[fieldset=abstract, null]
      \step[fieldset=keywords, null]
      \step[fieldsource=note, match={published},fieldset=note,null]
      \step[fieldsource=type, match={prize},fieldset=type,null]
    }
   }
   \maps[datatype=bibtex,overwrite=true,refsection=0]{
     \map{ 
       \step[fieldset=abstract, null]
       \step[fieldset=keywords, null]
       \step[fieldsource=note, match={published},fieldset=note,null]
       \step[fieldsource=type, match={prize},fieldset=type,null]
     }
     }
}
```

The second \maps-section will be ignored. Also if i remove the refsection-option.

Best regards, Stefan

**Comment by plk** [comment]
Was a little too quickly done - the `refsection` option needs to be on the `\map` element(s), not the `\maps` as there can only be one of those. The docs are changed and you will need to download both biblatex and biber again.

```
\DeclareSourcemap{
  \maps[datatype=bibtex,overwrite=true]{
    \map[refsection=1]{
      \step[fieldsource=author, notmatch=\regexp{Lindner,\sS},final]
      \step[entrynull]
    }
    \map[refsection=1]{ 
      \step[fieldset=abstract, null]
      \step[fieldset=keywords, null]
      \step[fieldsource=note, match={published},fieldset=note,null]
      \step[fieldsource=type, match={prize},fieldset=type,null]
    }
  }
  \maps[datatype=bibtex,overwrite=true]{
    \map[refsection=0]{ 
      \step[fieldset=abstract, null]
      \step[fieldset=keywords, null]
      \step[fieldsource=note, match={published},fieldset=note,null]
      \step[fieldsource=type, match={prize},fieldset=type,null]
    }
  }
}
```

**Comment by sistlind** [comment]
Now it is working as apected, thanks a lot for the fast help!
-->closed
