### ISSUE TITLE
Fetching a remote bibfile not working at some servers

### ISSUE THREAD

**Issue by sistlind** [plk/biber#131]
Hi,
i have some problems to fetch a remote file via biber. Exactly the same file can be fetched by wget and curl from two different servers, but not from biber.
Here is a MWE:
```
\documentclass{scrbook}
\usepackage{biblatex}
%not working remote location
\addbibresource[location=remote]{https://www.lte.techfak.uni-erlangen.de/wp-content/papercite-data/bib/getbib.php}
%working remote location
%\addbibresource[location=remote]{https://www.dropbox.com/s/m6hgzv6i62bl6vv/elib_latex.bib?dl=1}

\begin{document}
\cite{small}
\printbibliography
\end{document}
```

And here is the erroneous biber log:
```
stefan@red-pc:~/Desktop/bibremotetest$ biber remotetestINFO - This is Biber 2.5
INFO - Logfile is 'remotetest.blg'
INFO - Reading 'remotetest.bcf'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex format file 'https://www.lte.techfak.uni-erlangen.de/wp-content/papercite-data/bib/getbib.php' for section 0
INFO - Data source 'https://www.lte.techfak.uni-erlangen.de/wp-content/papercite-data/bib/getbib.php' is a remote BibTeX data source - fetching ...
ERROR - Could not fetch 'https://www.lte.techfak.uni-erlangen.de/wp-content/papercite-data/bib/getbib.php'
INFO - ERRORS: 1
stefan@red-pc:~/Desktop/bibremotetest$ cat remotetest.blg
[0] Config.pm:343> INFO - This is Biber 2.5
[0] Config.pm:346> INFO - Logfile is 'remotetest.blg'
[48] biber:290> INFO - === So Jun 26, 2016, 16:53:34
[68] Biber.pm:351> INFO - Reading 'remotetest.bcf'
[175] Biber.pm:776> INFO - Found 1 citekeys in bib section 0
[195] Biber.pm:3493> INFO - Processing section 0
[210] Biber.pm:3657> INFO - Looking for bibtex format file 'https://www.lte.techfak.uni-erlangen.de/wp-content/papercite-data/bib/getbib.php' for section 0
[211] bibtex.pm:134> INFO - Data source 'https://www.lte.techfak.uni-erlangen.de/wp-content/papercite-data/bib/getbib.php' is a remote BibTeX data source - fetching ...
[471] Utils.pm:165> ERROR - Could not fetch 'https://www.lte.techfak.uni-erlangen.de/wp-content/papercite-data/bib/getbib.php'
[471] Biber.pm:112> INFO - ERRORS: 1
```
Best regards,
Stefan

**Comment by plk** [comment]
Hmm, it works for me with biber 2.6 beta and there are no remote changes in 2.6. Can you try the `--ssl-noverify-host` and `--ssl-nointernalca` options to biber? Could be your local cert database is out of date.

**Comment by sistlind** [comment]
No difference with any combinations of both options,
I also tried a non-ssl server with the same file:
`\addbibresource[location=remote]{http://www.ortsjugend.de/test.bib}`
But it appears always the same error at the logfile

**Comment by plk** [comment]
This is because those servers don't like the User Agent string from the Perl LWP module. I will change this in version 2.6 to use a standard Mozilla string. I tested this and it works with all of your example. An updated 2.6 will appear on SourceForge in the few days (which requires the development 3.5 version of biblatex).

**Comment by sistlind** [comment]
ok, thanks a lot! Can i change something at the serverside to get it running with the current version?

**Comment by plk** [comment]
I've just pushed new builds of biber 2.6 to SF including this fix. You'll also need, as I mentioned, biblatex 3.5 dev version also on SF. You could probably change the web server config on the server if you have access to it but it depends on the web server and how it's configured ...

**Comment by sistlind** [comment]
Just for your information: i have asked our admin, and there is no filter rule blocking libwww-perl. I have also written a small perl-testscript and it isn't blocked.
It was only blocked at my non-SSL testserver(ortsjugend.de) :(
Therefore i allowed the http access to the uni-erlangen.de webserver and it is working.

To sum up my investigations:
* \addbibresource[location=remote]{http://www.lte.techfak.uni-erlangen.de/wp-content/papercite-data/bib/getbib.php} --> working at linux and windows(both texlive 2016)
* \addbibresource[location=remote]{https://www.lte.techfak.uni-erlangen.de/wp-content/papercite-data/bib/getbib.php} -->working at windows texlive 2016, **not** working at my Linux system(also tried the internal-ca  and no-verify switches)

This testscript using the same user agent is working:

```
use strict;
use warnings;
use LWP::Simple;

my $source  = 'https://www.lte.techfak.uni-erlangen.de/wp-content/papercite-data/bib/getbib.php';
my $file = 'test';
my $retcode;
$LWP::Simple::ua->agent('LWP::Simple/6.13 libwww-perl/6.13');

$retcode = LWP::Simple::getstore($source, $file);
unless (LWP::Simple::is_success($retcode)) {
print ("Could not fetch $source (HTTP code: $retcode)\n");
}	
print $retcode."\n";
```


For me the problem is solved by allowing non-ssl access to the datefile, but there seems to be a further problem somewhere.

**Comment by plk** [comment]
Try setting the UA string to "Mozilla/5.0"

**Comment by sistlind** [comment]
I have changed the file /tmp/par-73746566616e/cache-d539ef2a281164d048fcb87d8100e67c3da19d43/inc/lib/Biber/Input/file/bibtex.pm according to your commit(changing UA and adding returncode).
Now, in the logfile i can find the error code is 500.
This should be a server error, but i can fetch the file without any problems by wget, curl and the perl scipt shown above?

Do you have a further idea?

**Comment by sistlind** [comment]
To get some more information, i included the following code in Input/file/bibtex.pm:

```
my $response = $LWP::Simple::ua->get($source);
if ( $response->is_success ) {
    biber_warn($response->decoded_content);
}
else {
    biber_error($response->status_line);
}
```

The resulting error is:
`ERROR - 500 Can't connect to www.lte.techfak.uni-erlangen.de:443`
This is correct, because i can not connect to to this adress without the trailing https, but why is this missing? The source string is the correct one with https

**Comment by plk** [comment]
One possibility it the Mozilla::CA module version. I updated it in 2.6 DEV but it was quite old in 2.5. It's possible that setting `--ssl-nointernalca` and using more up-to-date CAs from your environment will work. The best way of testing is to check out the git biber DEV tree, do "perl Build.PL;./Build installdeps; ./Build install" and use the unpacked version to get the latest version.

**Comment by sistlind** [comment]
I don't know really why, but it is now working with version 2.6beta. Perhaps it is the new Mozilla version or changes at the packed perl version.

-->Finally closed
