### ISSUE TITLE
Wrong/Confusing Biber and Biblatex version requirement number at ctan site

### ISSUE THREAD

**Issue by Siedlerchr** [plk/biber#132]
At the CTAN website biblatex apa  ctan website https://www.ctan.org/pkg/biblatex-apa?lang=de
 it is stated:

>  This ver­sion of the pack­age re­quires use of BibLaTeX v2.4 and biber v3.3 (at least). 

I think you meant biblatex v.3.3 and biber v.2.4, because there is no biber v.3.3 existing...

**Comment by plk** [comment]
I'm not sure who added that - I don't control that CTAN page ... I'll see if I can have it fixed.
