### ISSUE TITLE
Parsing of bibliography stops without error if entry malformed

### ISSUE THREAD

**Issue by humenda** [plk/biber#134]
Consider the minimal example below. Running lualatex on it and then biber gives the output below the minimal example. It is not obvious that an error happened, except for the return code and this does not give a hint about what went wrong.

\documentclass{scrartcl}
\usepackage[backend=biber]{biblatex}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article"invalid,
  author    = "Goossens, Michel and Mittelbach,
               Frank and Samarin, Alexander",
  title     = "The LaTeX Companion",
  publisher = "Addison-Wesley",
  location  = "Reading, Mass.",
  year      = "1994",
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}

Output for lualatex y.tex && biber y:
$ lualatex y.tex
This is LuaTeX, Version 0.95.0 (TeX Live 2016/Debian) 
[...]
$ biber y
INFO - This is Biber 2.5
INFO - Logfile is 'y.blg'
INFO - Reading 'y.bcf'
INFO - Using all citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex format file 'y.bib' for section 0
INFO - Decoding LaTeX character macros into UTF-8
INFO - Found BibTeX data source 'y.bib'
$ echo $?
1

Thanks

**Comment by plk** [comment]
This is quite tricky as the error is from the underlying `libbtparse` C library which doesn't SEGFAULT or anything sensible here, it just throws a warning. I can look into it but it may be difficult/impossible to have anything sensible passed up through XS to perl in order to deal with this cleanly.

**Comment by humenda** [comment]
I see. Thanks for looking into it!

**Comment by sistlind** [comment]
In such cases, i am trying to open the bibfile with jabref. Jabref often gives a hint, where to search for the erroneous entry

**Comment by plk** [comment]
In biber 2.6 dev (which requires biblatex 3.5 dev), if you run with either `--debug` or `--trace`, then you will  now see such errors from the underlying library. This is the best that can be done with this particular sort of error I'm afraid but thankfully, it's a rare case.

**Comment by humenda** [comment]
I'm unable to set up both development versions quickly now, so unfortunately I
cannot test your changes. However I have tried -debug and if this information is
reported this way, that's absolutely fine. Thanks for the quick fix!
