### ISSUE TITLE
Local version of remote bibfile

### ISSUE THREAD

**Issue by sistlind** [plk/biber#135]
Hi,
the fetched copy of the remote bib file is now stored at a file in the tmp directory with random filename and will deleted after processing. It would be great if a persistent local copy of the fetched remote file could be saved in the latex-source-directory with a configurable filename.

This would have several advantages:
 - Compilation is also possible, if the remote site is not available
 - The file could be search with, e.g.,  jabref
 - The auto-completion function of latex-editors, e.g., texstudio will work.

Best regards,
Stefan

**Comment by plk** [comment]
I'm not sure I want to make biber into a file-fetching tool  really - the advantages listed are the same if the user just downloads the file using a browser and then uses it locally, which makes sense if it's needed locally. A biber option would be less convenient than this as you'd have to specify a filename in some config location which is much less convenient that just typing into a browser download box once ...
