### ISSUE TITLE
Feature request: No warning when replacing "year" value with identical value from "date"

### ISSUE THREAD

**Issue by ClaudiusL** [plk/biber#136]
If a bib entry has a `year` and a `date` field, biber raises a warning that the `year` field will be overwritten:

> WARN - Overwriting field 'year' with year value from field 'date' for entry …

**Request**: Suppress the warning if the original year value and the year value from the `date` field are identical.

Warnings in the log always slow me down because I have to check if something is going wrong. In this case however, there is nothing to take care of, because original and new value are identical. Therefore, suppressing the message would be helpful.

Just leaving the `year` field empty is no equivalent alternative because having a populated `year` field can be helpful for sorting/searching in other tools (like JabRef).

**Comment by plk** [comment]
This will be implemented in the next version (2.6) which will be uploaded to the development folder this evening.

**Comment by ClaudiusL** [comment]
This was amazingly quick – thank you!
