### ISSUE TITLE
\textregistered not printed at bibliography

### ISSUE THREAD

**Issue by sistlind** [plk/biber#137]
Hi,
if i use \textregistered (from textcomp-package) in th title-field of my bibfile, at the .bbl file it is set in math mode, e.g.:
```
    Bibfile:      Title             = {RO4000\textregistered{} Series},
    .bbl:        \field{title}{RO4000{$\textregistered$}{} Series}
```
I think this is a bug, because in math-mode the symbol ist not shown, but it is working, if i remove the math-dollar-signs manually from the bbl file.

Is there a trick to force textmode at the bibfile? Not even the following is working:
```
    Bibfile:      Title             = {RO4000{\textnormal{\textregistered{}}} Series},
    .bbl:        \field{title}{RO4000{\textnormal{{$\textregistered$}{}}} Series}
```

Best regards,
Stefan

**Comment by plk** [comment]
Can you post a MWE with this? I need to see the biblatex options etc.

**Comment by sistlind** [comment]
Sure, and another strange thing: \textcopyright will be converted to $\copyright$?
```
\documentclass{article}
\usepackage{textcomp}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@misc{me,
    author  = "Me",
    title   = "({CTAN})\textregistered{} \textcopyright{}",
}
\end{filecontents}
\usepackage{biblatex}
\addbibresource{\jobname.bib}

\begin{document}

\nocite{*}
    \printbibliography

\end{document}
```
.bbl file:
```
% $ biblatex auxiliary file $
% $ biblatex bbl format version 2.8 $
% Do not modify the above lines!
%
% This is an auxiliary file used by the 'biblatex' package.
% This file may safely be deleted. It will be recreated by
% biber as required.
%
\begingroup
\makeatletter
\@ifundefined{ver@biblatex.sty}
  {\@latex@error
     {Missing 'biblatex' package}
     {The bibliography requires the 'biblatex' package.}
      \aftergroup\endinput}
  {}
\endgroup


\refsection{0}
  \sortlist[entry]{nty/global/}
    \entry{me}{misc}{}
      \name{author}{1}{}{%
        {{hash=318b2739ddc2c16c97b33c9b04b79f3e}{%
           family={Me},
           family_i={M\bibinitperiod}}}%
      }
      \strng{namehash}{318b2739ddc2c16c97b33c9b04b79f3e}
      \strng{fullhash}{318b2739ddc2c16c97b33c9b04b79f3e}
      \strng{authornamehash}{318b2739ddc2c16c97b33c9b04b79f3e}
      \strng{authorfullhash}{318b2739ddc2c16c97b33c9b04b79f3e}
      \field{sortinit}{M}
      \field{sortinithash}{2684bec41e9697b92699b46491061da2}
      \field{labelnamesource}{author}
      \field{labeltitlesource}{title}
      \field{title}{({CTAN}){$\textregistered$}{} {$\copyright$}{}}
    \endentry
  \endsortlist
\endrefsection
\endinput
```
Result:
![biber_error](https://cloud.githubusercontent.com/assets/6959674/17458609/b59b4514-5c16-11e6-8539-ff284b495dc1.png)

Btw: If somebode has the same problem, my temporary solution is to use \registered{} at the bibfile and redefine it in my latex file with \newcommand{\registered}{\textnormal{\textregistered}}

Best regards,
Stefan

**Comment by plk** [comment]
I agree that this is really a bug. Please try the 2.6 dev version on Sourceforge. You'll also need the latest biblatex 3.5 dev version.

**Comment by sistlind** [comment]
I am sorry, but i could not test it, because ubuntu has only perl version 5.22 and i have no idea how to update :(
Nevertheless, i am sure, it is working now and thanks for fast help!

**Comment by sistlind** [comment]
Ok, i got it working...
But there are some strange things happening :) 
If i compile the above example with pdflatex:
``\field{title}{({CTAN})\textregistered{} \textregistered{}

Using lualatex:
``\field{title}{({CTAN})®{} ©{}}

In my opinion both cases are wrong. with pdflatex, the copyright is changed to textregistered and in the luatex case, there are utf8 symbols in the bbl-file. Using no further package, both will not be printed. The latter is perhaps not really a bug, because it can be solved using fontspec, but it could be irritating people, who just start.

**Comment by plk** [comment]
Ah, that duplicated output was a bug, fixed now in DEV. It is true that some output will require additional packages - I can change this a little but currently the recoding prefers `\text` variants - I can change this if you think it is necessary (although recoding can be user-customised anyway). The lualatex example isn't a bug really as lualatex users mostly use UTF-8 in their .bib files anyway and so recoding isn't even necessary.

**Comment by sistlind** [comment]
Great, now it is working with pdflatex.
The problem i see at the luatex-build is that the output of the above MWE is not correct, in fact it doesn't print R or C. This only works loading additionally explicitly the fontspec package.
But if you think, this is not a problem -> closed.
