### ISSUE TITLE
Outputting biblatexml to stdout

### ISSUE THREAD

**Issue by chneukirchen** [plk/biber#138]
To convert .bib to .xml without temporary files, I used

    biber --tool -q -O /dev/stdout --output-format=biblatexml min.bib

In Biber 2.5 (TexLive rev 41193), this prints the XML preamble twice, resulting in invalid XML. (Output to a file works fine.)

Alternatively, consider supporting `-O -` to print to stdout. (Like e.g. `wget`.)

(This is probably because you call set_output_target_file and it can't "overwrite" stdout...)

**Comment by chneukirchen** [comment]
(FTR, this worked in biber 2.2 from TeXLive 2015.)

**Comment by plk** [comment]
Thank you for spotting this. Please try 2.6 dev version (you will also need biblatex 3.5 dev version) from Sourceforge. The duplicate headers are fixed and you can now do `-O -`.

**Comment by chneukirchen** [comment]
Unfortunately I don't have Perl 5.24 yet so it wont run.

**Comment by plk** [comment]
You don't need it if you use the pre-built binaries.

**Comment by chneukirchen** [comment]
Ah yes, found them on SourceForge now.

Works, thanks!
