### ISSUE TITLE
numeric-comp and labelprefix result in "[0]" references.

### ISSUE THREAD

**Issue by AlexanderWillner** [plk/biber#139]
Steps that will reproduce the problem?
1.  Use the latex LaTeX packages (e.g., update via tlmg)
2. pdflatex mwe; biber mwe; pdflatex mwe; pdflatex mwe; open mwe.pdf

What is the expected result?
References with letters and numbers.

What happens instead?
References are all ```[0]```.

Possible workaround:
Use ```style=numeric``` instead of ```style=numeric-comp```

Any additional information:
 
File ```mwe.tex```:

```
\documentclass{article}
\usepackage{filecontents}
\begin{filecontents}{references.bib}
  @inproceedings{test-conference,
    author = {Test Author 1},
    title = {Test Title 1},
    booktitle = {Test Booktitle 1},
    year = {2016},
    keywords = {C}
  }
  @inproceedings{test-workshop,
    author = {Test Author 2},
    title = {Test Title 2},
    booktitle = {Test Booktitle 2},
    year = {2016},
    keywords = {W}
  }
\end{filecontents}
\usepackage[style=numeric-comp, bibencoding=ascii, defernumbers=true, maxnames=10]{biblatex}
\addbibresource{references.bib}
\begin{document}
Conference paper: \cite{test-conference}
Workshop paper: \cite{test-workshop}.
\defbibnote{conference}{Conference Papers}
\defbibnote{workshop}{Workshop Papers}
\newrefcontext[labelprefix=C]
\printbibliography[prenote=conference, keyword=C] 
\newrefcontext[labelprefix=W]
\printbibliography[prenote=workshop, keyword=W] 
\end{document}
```

**Comment by plk** [comment]
Can you check the development biblatex and biber versions on sourceforge - I think that this is fixed there.

**Comment by AlexanderWillner** [comment]
Happy to test as soon as the packages are available via tlmgr (or brew on the Mac).

**Comment by moewew** [comment]
The issue does not re-occur with `biblatex` 3.5/Biber 2.6 (now on CTAN and in TeX live) of me.
