### ISSUE TITLE
verbatim fields aren't verbatim

### ISSUE THREAD

**Issue by u-fischer** [plk/biber#141]
If I compile this example:

```
\documentclass{article}

\usepackage[utf8]{inputenc}
\usepackage[backend=biber]{biblatex}

\addbibresource{test.bib}

\begin{document}
\cite{verbatim}
\end{document}
```

with this bib-entry

```
@article{verbatim,
  author = {Jane Doe},
  title = {Title},
  year = {2016},
  verba={\=y.\"a}
}
```

then biber (version 2.6) translates the "characters" in the verbatim field and I get in the bbl

```
      \verb{verba}
      \verb ȳ.ä
      \endverb
```

**Comment by plk** [comment]
Hmm, that must have been the case for a long time. Tricky to deal with too. Looking into it.

**Comment by u-fischer** [comment]
Yes I checked in tl14 and it was already there. Which means that until now nobody had a problem with it or they even liked the side effect to get non-ascii in file names ... 

I only tripped over the problem through a question on tex.sx where the OP mapped an url to verba to prevent URI-escaping:
https://tex.stackexchange.com/questions/330702/how-can-i-emulate-unicode-input-without-actually-typing-the-letters

**Comment by plk** [comment]
I'd prefer if it really didn't get touched I think.

**Comment by u-fischer** [comment]
Me too. verbatim should be verbatim and it is never good to rely on undocumented side-effects.

**Comment by plk** [comment]
Please try `biblatex` 3.7 and `biber` 2.7 in development on Sourceforge - this should be fixed now.
