### ISSUE TITLE
Build/Run deps are sooooo unclear

### ISSUE THREAD

**Issue by norbusan** [plk/biber#142]
Hi
Norbert from Debian and TeX Live here.

I tried to update the Debian packages to 2.6, but it is a huge pain. You request perl 5.24, but do not mention that several other modules are necessary, too:

- DateTime
- DateTime::Format::Builder
- DateTime:::Calendar::Julian

Here I am stuck because the last one is not available in Debian. 

Before I continue working on packaging, I would be *very* interested to get a list of actual dependencies. The Changes file does not mention a word.

This is not a way you are making distributors happy, sorry to say that.

Thanks

Norbert

**Comment by plk** [comment]
I'm a bit confused. Firstly, biber is generally distributed as a packed binary which contains everything, it doesn't even require perl to be installed, let alone any modules. If the raw perl version is being used, "perl Build.PL;Build installdeps" will install all required modules since the Build.PL lists all direct dependencies and automatically install them.  If it's being installed in any other way, it's not technically supported and I have never listed all dependencies anywhere because it's never been needed nor has anyone ever asked ...

**Comment by norbusan** [comment]
Hi Phil,
no, distribution is *not* done with the packed binaries. This is only done in TeX Live, but most Linux distributions, for sure Debian, SuSE, RedHat, etc, will *not* use pre-built binaries and require to rebuild the packages from source.

Furthermore, at least in Debian, no internet access can be made by the actual build process, all build requirements need to be written out beforehand. I guess rpm (RedHat, SuSE) is doing the same.

So for those who want to distribute biber in any of the mainstream Linux distributions, we need to know the list of dependencies.

I have now extracted them from the Build.PL script, but need to package DateTime::Calendar::Julian first...

**Comment by cbm755** [comment]
@norbusan very late to this bug, but in case it helps, we package it in Fedora and spent some time documenting the dependencies in the `.spec` file: https://pkgs.fedoraproject.org/cgit/rpms/biber.git

**Comment by norbusan** [comment]
thanks @cbm755 biber is in Debian since wire some time by now, but indeed, there are always new surprises and needs. I had to package another Perl library to build 2.6.

**Comment by cbm755** [comment]
@norbusan if you post a single-click URI for your packaging script and maybe I'll compare dependencies next time I'm looking at Biber on Fedora.

If you want to do the same, Fedora's .spec file is at https://pkgs.fedoraproject.org/cgit/rpms/biber.git/tree/biber.spec

**Comment by norbusan** [comment]
@cbm755 Hi Colin, here it is: https://sources.debian.net/src/biber/2.6-2/debian/control/
Look for Build-Depends

**Comment by cbm755** [comment]
Thanks: I found at least dep we were missing.

FYI: I didn't do it very carefully in the other direction but I did notice Fedora depends on `perl(Encode::EUCJPASCII)` (which is used in tests) and you depend on `libencode-eucjpms-perl` (which doesn't seem to be used).

**Comment by cbm755** [comment]
@plk sorry for hijacking your thread for packaging discussions!

**Comment by plk** [comment]
The Encode modules may be dynamically loaded depending on the particular document encodings and so they may well not be used explicitly.
