### ISSUE TITLE
Fetching remote file fails even though file is accessible otherwise

### ISSUE THREAD

**Issue by jeremywales** [plk/biber#148]
In thesis.tex I have:
\addbibresource[location=local]{http://localhost:23119/better-bibtex/collection?/0/Citations.biblatex}

When I run biber on thesis.tex it gives me:
INFO - This is Biber 2.6
INFO - Logfile is 'thesis.blg'
INFO - Reading 'thesis.bcf'
INFO - Found 155 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex format file 'http://localhost:23119/better-bibtex/collection?/0/Citations.biblatex' for section 0
INFO - Data source 'http://localhost:23119/better-bibtex/collection?/0/Citations.biblatex' is a remote BibTeX data source - fetching ...
ERROR - Could not fetch 'http://localhost:23119/better-bibtex/collection?/0/Citations.biblatex' (HTTP code: 500)

I was getting this problem with biber 2.4/biblatex 3.4 so I updated to biber 2.6/biblatex 3.6, but I'm getting same problem.

The tool providing the bibtex data at the url is the Better Bibtex extension to Zotero. If the take the bibtex data from the url in Firefox, paste into straight into a bib file and modify \addbibresource accordingly, everything works perfectly. So it's not the url, and it's not the data, so it looks like something wrong with biber's remote file access.

**Comment by jeremywales** [comment]
Oh, I just realised I left [location=local] in there. Obviously that's meant to be [location=remote], but I wanted to see what happened. It does exactly the same thing whether locations is remote or local.

**Comment by plk** [comment]
I don't use this but I need to replicate the issue - can you tell me where one sets the local http URL in the plugin? I assume the port is set somewhere but I can't seem to find it.

**Comment by jeremywales** [comment]
You actually don't set the URL yourself, the Better Bib(La)Tex plugin to Zotero sets it for you and just lets you know what it is. The [Pull Export doco](https://github.com/retorquere/zotero-better-bibtex/wiki/Push-and-Pull-Export) explains it, and [Configuration doco](https://github.com/retorquere/zotero-better-bibtex/wiki/Configuration) doesn't suggest it can be customised. So to get a URL you create a collection in Zotero, add resources to it, right-click on the collection, choose BibLaTex URL, and copy the given URL.

**Comment by plk** [comment]
Hmm, if I try the URL I get in any brower, even firefox with Zotero open, it gives an error - doesn't seem that any web service is running on the port - do you have to turn this on somewhere else?

**Comment by jeremywales** [comment]
Oh, OK. I should have said, I run Zotero Standalone which has the embedded HTTP server enabled by default. Zotero in Firefox has it disabled by default but [this says how to easily turn it on]{https://www.zotero.org/support/dev/client_coding/connector_http_server}.

**Comment by jeremywales** [comment]
Thanks for looking at this. A bit more data is that if I do a cURL request to the same url into a file and specify that file in \addbibresource then biber works fine. So the url works fine when via Firefox browser and cURL command line, just not when its accessed by biber directly.

**Comment by plk** [comment]
With the current biber 2.7/biblatex 3.7 dev versions on Sourceforge, this works fine for me:

```
\documentclass{article}
\usepackage{biblatex}
\addbibresource[location=remote]{http://localhost:23119/better-bibtex/collection?/0/6VJK5VDX.biblatex}
\begin{document}
Test
\nocite{*}
\printbibliography
\end{document}

```

**Comment by jeremywales** [comment]
That's good. As I was saying I'm on 2.6/3.6, because they're the latest versions that TexLive gives me. Did the biber http code (or package it relies on) change at all between 2.6 and 2.7? If so I guess I can just close this one and open another if I happen to find I it still doesn't work for me once I'm on 2.7/3.7.
