### ISSUE TITLE
tests failing wrt sorting

### ISSUE THREAD

**Issue by norbusan** [plk/biber#149]
Hi,

down here at Debian we again get errors during tests, and all the diffs look like
`````
# -      \\field{sortinithash}{0aa614ace9f3a40ef5a67e7f7a184048}
# +      \\field{sortinithash}{8343b463aacf48517c044b4d2c9c45ed}
`````

(see https://tests.reproducible-builds.org/debian/rbuild/unstable/amd64/biber_2.6-1.rbuild.log)

perl is at version 5.24.1

Do you have an insight in what could be wrong?

Thanks

Norbert

**Comment by plk** [comment]
Hmm, can you send me the complete output from a failed test run?

Pk

> On 9 Nov 2016, at 1:01 am, Norbert Preining <notifications@github.com> wrote:
> 
> Hi,
> 
> down here at Debian we again get errors during tests, and all the diffs look like
> 
> # -      \\field{sortinithash}{0aa614ace9f3a40ef5a67e7f7a184048}
> # +      \\field{sortinithash}{8343b463aacf48517c044b4d2c9c45ed}
> 
> (see https://tests.reproducible-builds.org/debian/rbuild/unstable/amd64/biber_2.6-1.rbuild.log)
> 
> perl is at version 5.24.1
> 
> Do you have an insight in what could be wrong?
> 
> Thanks
> 
> Norbert
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Dr Philip Kime

**Comment by norbusan** [comment]
Colleagues from the Debian perl team found the source of the problem: I was using the separately packaged libunicode-collate package as it was necessary in former times (perl 5.18 or so), and it is still used instead of the perl-internal version of Unicode::Collate.

Now, the sort key of Unicode::Collate has changed again, Niko send on the [bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843711) list the following output:
`````
% perl -MUnicode::Collate -le 'print $Unicode::Collate::VERSION, " ",
Unicode::Collate->new->viewSortKey("Foo")'

gives this output with the versions available on jessie and sid:

1.04 [1680 176D 176D | 0020 0020 0020 | 0008 0002 0002 | FFFF FFFF FFFF |]

1.07 [1680 176D 176D | 0020 0020 0020 | 0008 0002 0002 | FFFF FFFF FFFF |]

1.14 [19A9 1AA1 1AA1 | 0020 0020 0020 | 0008 0002 0002 | FFFF FFFF FFFF |]

1.17 [1C60 1D58 1D58 | 0020 0020 0020 | 0008 0002 0002 | FFFF FFFF FFFF |]
```````

In contrast, building with the perl internal U::C (not installing libunicoda-collate-perl) gives a successful build.


It is very unfortunate that the two versions (perl internal and separately packaged) produce different outputs, but I guess from now on I will not request libunicode-perl-lib for building.

I guess this issue can be closed, I hope this information is useful for you.

All the best

Norbert

**Comment by plk** [comment]
Yes, the version of U::C matters - Build.PL always mentions the version needed and "perl Build.PL" should tell you of any mismatch.

**Comment by ntyni** [comment]
Hi, just wanted to note that the problem is specifically with newer versions of Unicode::Collate from CPAN. AFAICS Build.PL requires >= 1.14 but the tests fail with 1.17. So it looks like something similar to 9bebd3ef0cb57b5ca4f15885d0cbfecc4939a835 will be needed sooner or later...

Apologies if this was obvious already.

**Comment by plk** [comment]
Ok, this is due to Unicode 8 changes in U::C. the test failures can be ignored, they don't impact anything but I will update the dev version of biber to use the 1.18 version, including the tests.
