### ISSUE TITLE
Breaking change in 2.6: year vs. date

### ISSUE THREAD

**Issue by bersbersbers** [plk/biber#150]
Since version 2.6, "biber --tool --output-format=bibtex" combines "year" and "month" fields into "date" fields, which "bibtex" does not understand. The "year" field is missing. The changelog (https://github.com/plk/biber/blob/dev/Changes) says:

> 2.6    (2016-09-10)
>        * Improved tool mode bibtex output. This has some normalisation
>          consequences for YEAR and custom fields. See PDF doc.

However, the PDF doc (http://ctan.mackichan.com/biblio/biber/documentation/biber.pdf) says nothing about that in the "Important changes"

Lacking time to read the 55-pages documentation completely, I need to ask here: How can I maintain the "year" field in bibtex output?

**Comment by bersbersbers** [comment]
It seems the "Important changes" about 2.6 have been integrated a little late - in the documentation for 2.7. Anyway:

> +\item Dates are normalised into \bibfield{DATE} fields. Legacy
>  +  \bibfield{YEAR} fields are never output in \bibtex format data output.

How can I tell biber to behave as it previously did, not touching year fields?

**Comment by plk** [comment]
Yes, it was added later. The thing is, if you are using biber, why do you need the `YEAR` field?

**Comment by plk** [comment]
You can always use a sourcemap to transform `DATE` into `YEAR` as part of another tool mode run.

**Comment by bersbersbers** [comment]
I user biber to process and clean up a .bib file. I thought this is what "biber --tool --output-format=bibtex" is for, and it worked quite well. I guess I can deal with a "date" field, but my bst file (spbasic.bst) does not expect the date field to contain anything but the year.
