### ISSUE TITLE
\DeclareNosort has contra-intuitive consequences

### ISSUE THREAD

**Issue by moewew** [plk/biber#151]
Consider the following MWE

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[ngerman]{babel}
\usepackage{csquotes}
\usepackage[backend=biber, style=authoryear]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@online{AVTest,
   author = {{AV-TEST GmbH}},
   title = {Die besten Antivirus Programme},
   date = {2016-08-23},
   url = {https://www.av-test.org/de/antivirus/privat-windows/windows-8/},
   urldate = {2016-11-19},
}
\end{filecontents}

\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}

\nocite{AVTest,sigfridsson}

\begin{document}
\printbibliography
\end{document}
```

If run, "AV-Test" is sorted after "Sigfridsson" (it's sorted under "T" instead of "A").

From what I can tell `\p{L}{2}\p{Pd}` drops all Letters before a dash-like character, but from the comment you probably only want to drop lowercase letters: `\p{Ll}{2}\p{Pd}`.
```
\DeclareNosort{
  % strip prefixes like 'al-' when sorting names
  \nosort{setnames}{\regexp{\A\p{Ll}{2}\p{Pd}}}
  % strip diacritics when sorting names
  \nosort{setnames}{\regexp{[\x{2bf}\x{2018}]}}
}
```
What also makes me wonder is that this rule even applies for authors protected by braces. (But that could of course be intentional.)

**Comment by moewew** [comment]
I had another look at the Biber manual and I was mistaken, sorry.

According to the comment there, we also want to drop prefixes with capital letter like "El-" in nosort (but we only drop lowercase in `noinit`).

Is there any reason for that distinction?

**Comment by plk** [comment]
No special reason for the defaults, just because it seems that people expect "El-{M}allah" to initialise as "E-M" but to sort as "Mallah".

**Comment by moewew** [comment]
I see, I got confused because the patters were different.
