### ISSUE TITLE
The v2.7 mingw64 release breaks collation

### ISSUE THREAD

**Issue by Witiko** [plk/biber#152]
The biber 2.7 mingw64 binary available from <http://biblatex-biber.sourceforge.net/> includes an incomplete version of the `Unicode::Collate::Locale` Perl module. The directory `<CACHE>\inc\lib\Unicode\Collate\Locale` (where `<CACHE>` equals the output of `biber --cache`) contains only the `bg.pl`, `fr.pl`, and `ru.pl` files instead of [all the locale files it should contain](http://search.cpan.org/~sadahiro/Unicode-Collate-1.19/Collate/Locale.pm#A_list_of_tailorable_locales). This prevents pretty much any collation from taking place:
```
$ cat > test.tex
\documentclass{article}
\usepackage[polish]{babel}
\usepackage[backend=biber]{biblatex}
\begin{filecontents}{test.bib}
@PATENT{ehlinger06,
  author   = {EHLINGER, JR., Philip Charles},
  title    = {Device for the treatment of hiccups},
  type     = {US Patent},
  location = {US},
  date     = {2006},
  number   = {7062320},
  langid   = {english}}
\end{filecontents}
\addbibresource{test.bib}
\begin{document}
  \nocite{*}
  \printbibliography
\end{document}
```
```
$ pdflatex test.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (MiKTeX 2.9.6100 64-bit)
entering extended mode
(test.tex
LaTeX2e <2016/03/31> patch level 3
<< snipped >>
```
```
$ biber test.bcf
INFO - This is Biber 2.7
INFO - Logfile is 'test.blg'
INFO - Reading 'test.bcf'
INFO - Found 1 citekeys in bib section 0
Unicode/Collate/Locale/pl.pl can't be found at C:\Users\foobar\AppData\Local\Temp\par-776974696b\cache-69151563abf9cd50c34eb13e2ece29c7269d919d\inc\lib/Biber.pm line 902.
```
This affects anyone who downloads the precompiled `biber` binary off <http://biblatex-biber.sourceforge.net/> or who uses an up-to-date MikTeX / ProTeXt.

***

Installing the biber pre-requisites and running the `build.bat` inside `dist\MSWIN64` with the latest Strawberry Perl (5.24.0.1 (64bit)) emits the following error:
```
C:\Strawberry\perl\site\bin/pp: Cannot find file or directory C:/strawberry/perl/lib/Unicode/Collate/allkeys.txt for packing
```
And indeed, the `allkeys.txt` file is missing from `C:\strawberry\perl\lib\Unicode\Collate` and so are all the locale files. Strawberry Perl claims that `Unicode::Collate::Locale` is installed, but the installation is crippled. This is what needs to be done to produce a binary that contains all the locale files and passes the above test:
1. Run `force install Unicode::Collate::Locale` from cpan to install the complete `Unicode::Collate::Locale` module into `C:\Strawberry\perl\site\lib\Unicode\Collate`,
2. replace each occurance of `perl/lib/Unicode/Collate` in `dist\MSWIN64\biber.files` with `perl/site/lib/Unicode/Collate`, and
3. re-run `build.bat` inside `dist\MSWIN64`.

The `MSWIN32` architecture is likely to be also affected.

The curious thing is that `C:\strawberry\perl\lib\Unicode\Collate\Locale` contains the entire `Unicode::Collate::Locale` module after a clean Strawberry Perl installation. To me the only possible explanation is that the locale files go missing during the installation of biber pre-requisites. I don't currently have the time to reinstall the pre-requisites one-by-one again, but If you manage to pinpoint the exact cause, then this should be reported to the Strawberry Perl devs.

**Comment by plk** [comment]
Thank you for reporting this, for some reason, U::C has taken to installing in site/ again as it did years ago ...

**Comment by plk** [comment]
Binaries for windows have been replaced on SF.
