### ISSUE TITLE
Sorting problems

### ISSUE THREAD

**Issue by simifilm** [plk/biber#153]
This is a quite strange issue: I have two installations of `biber`, one for development builds in `/opt/local/bin` and a regular one in the path installed by `MacTeX`. Both are up to date, meaning version 2.7.

As I just noticed, these two installations of `biber` sort entries differently. Consider the following MWE

> % !TEX TS-program = lualatex
> % !BIB TS-program = biber
> \documentclass{article}
> \usepackage{fontspec}
> \setmainfont{TeX Gyre Pagella}
> \usepackage[style=fiwi,]{biblatex}
> \usepackage{filecontents}
> \begin{filecontents*}{bib.bib}
> @incollection{Muller.M:2014a,
> 	Address = {Baden-Baden},
> 	Author = {Müller, Martin},
> 	Booksubtitle = {Zum Staatsverständnis in den klassischen Utopien},
> 	Booktitle = {Idealstaat oder Gedankenexperiment?},
> 	Editor = {Schölderle, Thomas},
> 	Pages = {287--304},
> 	Publisher = {Nomos},
> 	Title = {Richard Rortys \emph{Contingency, Irony, and Solidarity} (1989)},
> 	Year = {2014}}
> @book{Marzin.F:1982,
> 	Address = {Frankfurt a.\,M.},
> 	Author = {Marzin, Florian F.},
> 	Publisher = {Peter Lang},
> 	Subtitle = {Eine Gattungsstudie},
> 	Title = {Die phantastische Literatur},
> 	Year = {1982}}
> \end{filecontents*}
> \addbibresource{bib.bib}
> \begin{document}
> \cite{Marzin.F:1982,Muller.M:2014a}
> \printbibliography
>  \end{document}

When I run `biber` from MacTeX on this, `Müller` gets sorted before `Marzin` (which is wrong); if I use my hand-installed `biber` it's sorted correctly. 

The .log files do also differ. This from `MacTeX`

> INFO - This is Biber 2.7
> INFO - Config file is '/Users/simi/Library/biber/biber.conf'
> INFO - Logfile is 'Untitled3.blg'
> INFO - Reading 'Untitled3.bcf'
> INFO - Found 2 citekeys in bib section 0
> INFO - Processing section 0
> INFO - Looking for bibtex format file 'bib.bib' for section 0
> INFO - Decoding LaTeX character macros into UTF-8
> INFO - Found BibTeX data source 'bib.bib'
> INFO - Overriding locale 'de_phone' defaults 'variable = shifted' with 'variable = non-ignorable'
> INFO - Overriding locale 'de_phone' defaults 'normalization = NFD' with 'normalization = prenormalized'
> INFO - Sorting list 'nyt/global/' of type 'entry' with scheme 'nyt' and locale 'de_phone'
> INFO - Writing 'Untitled3.bbl' with encoding 'UTF-8'
> INFO - Output to Untitled3.bbl

And this is the other one:

> INFO - This is Biber 2.7 (beta)
> INFO - Config file is '/Users/simi/Library/biber/biber.conf'
> INFO - Logfile is 'untitled3.blg'
> INFO - Reading 'untitled3.bcf'
> INFO - Found 2 citekeys in bib section 0
> INFO - Processing section 0
> INFO - Looking for bibtex format file 'bib.bib' for section 0
> INFO - Decoding LaTeX character macros into UTF-8
> INFO - Found BibTeX data source 'bib.bib'
> INFO - Overriding locale 'de_phone' defaults 'normalization = NFD' with 'normalization = prenormalized'
> INFO - Overriding locale 'de_phone' defaults 'variable = shifted' with 'variable = non-ignorable'
> INFO - Sorting list 'nyt/global/' of type 'entry' with scheme 'nyt' and locale 'de_phone'
> INFO - Writing 'untitled3.bbl' with encoding 'UTF-8'
> INFO - Output to untitled3.bbl

As you can see, there is a difference in the order the overridings take place, but I have no idea what is triggering this.

**Comment by simifilm** [comment]
Could this be related to #152 ?

**Comment by plk** [comment]
Hmm, someone reported a Unicode Collate issue
with Windows recently - the latest version installed into a site local location and so the build missed out all the locale files. Perhaps this impacts all platforms. What a pain. I'll look at it.

**Comment by plk** [comment]
Hmm, I have tried your example using my local raw install, the latest 2.7 from SF and the latest MacTeX and I always get Marzin before Müller ... LC environment variables do you have set? Any biber config file with different settings?

**Comment by simifilm** [comment]
That's really interesting. `biber.conf` in `~/Library/texmf` includes the line `
<sortlocale>de_phone</sortlocale>`. Without this line, it sorts ok.

There are several things I don't get here:

- I thought that the different German sorting schemes only concern how umlauts are treated in respect to non-umlauts, so in this case whether `ü` is treated as `u` or as `ue`. This shouldn't really influence my example.

- Why does my own installation of `biber` ignore this.

- And finally, why didn't I notice this before. I haven't changed `biber.conf` for years, and I am quite sure that I would have noticed such a fundamental sorting error.

**Comment by plk** [comment]
Hmm, can you check for .confs in all of the searched locations? The search path is described in the biber PDF manual on page 12?

~/Library/texmf isn't one of the explicit paths (it's ~/Library/biber).

**Comment by simifilm** [comment]
Sorry, my bad, I meant ` ~/Library/biber`.
