### ISSUE TITLE
Please prepare a proper release

### ISSUE THREAD

**Issue by norbusan** [plk/biber#157]
Hi,
it is quite a pain to have biber 2.7 in TeX Live with support packages requiring bier 2.7, but there is no proper release tarball, because the github release files and the normal release files on sourceforge are considerably different.

It would be great if you could *either* switch to *one* distribution method, *or* align releases with updates to the release files.

Thanks a lot, your support is much appreciated

Norbert
TeX Live Team, Debian TeX Live Team

**Comment by plk** [comment]
I am a bit confused - TL only depends on the packages pulled from Sourceforge as far as I know - Github doesn't come into it? The binary build packages is only released on SF.

**Comment by norbusan** [comment]
I'm using the released source packages for packaging biber for Debian, where I cannot use the prebuilt packages of TeX Live. I usually downloaded the source packages on SF.

**Comment by plk** [comment]
So you are using the SF source tar.gz? How would you like this structured?

**Comment by norbusan** [comment]
yes, I use that one. the one on github does not have META.json etc, but dist directory etc. nothing needs to change from the previous source.tar on SF, they have been used always as is.

**Comment by plk** [comment]
So you want the one on Github looking the same as SF?

**Comment by norbusan** [comment]
that will not work, as the github releases are automatically made from the checked in files, I guess.
how did you prepare the previous source releases at SF?

**Comment by plk** [comment]
I'm still confused as to what you need - isn't everything you need on SF?

**Comment by norbusan** [comment]
release 2.7 is not on SF, but I'm TeX Live

**Comment by plk** [comment]
I'm still confused. Release 2.7 is "current" on SF.

**Comment by norbusan** [comment]
aaahhh, OK, that was not obvious to me. thanks, I'll use that source package.

**Comment by plk** [comment]
Sorry if that was not clear - I had to do this because the TL pull scripts had to be changed every time otherwise ...
