### ISSUE TITLE
Unicode::Collate does not have Hebrew locale

### ISSUE THREAD

**Issue by mkamensky** [plk/biber#158]
The Unicode::Collate package that biber uses is missing the Hebrew locale, `Unicode/Collate/Locale/he.pl`. I am using version 2.7 of biber.

**Comment by plk** [comment]
Biber 2.8 develpment version has updated dependency on Unicode::Collate 1.19 which includes Hebrew support. You can try the 2.8 DEV version from sourceforge - to use this, you will need biblatex dev version 3.8 also on Sourceforge.
