### ISSUE TITLE
getting both url version: percent encoded url  and not encoded url

### ISSUE THREAD

**Issue by u-fischer** [plk/biber#159]
With the option `--nouri-encode` one can disable the percent encoding of an url. That's good for the printing of urls with non-ascii chars (when using an unicode engine) but bad for the links. Imho it would be better if both versions were available. Then urls could be printed like this:

     \href{https://ru.wikipedia.org/wiki/SLAM_(%D0%BC%D0%B5%D1%82%D0%BE%D0%B4)}{\nolinkurl{https://ru.wikipedia.org/wiki/SLAM_(метод)}}

Would it be possible for biber to create e.g. a field urlencode and urldecode?

**Comment by Himura2la** [comment]
I agree, this will be the best way. Reader ever needs the percent-encoding, yet some very old browsers may need it...

**Comment by plk** [comment]
Please try biber 3.8 DEV version. The `--nouri-encode` option is removed and `url` is always encoded. A new .bbl field `urlraw` will always be output too which may be the same as `url` if there is no encoding necessary.
