### ISSUE TITLE
Non-percent-encoded unicode URLs are broken in PDFLaTeX

### ISSUE THREAD

**Issue by Himura2la** [plk/biber#160]
I described the problem [on stackexchange](http://tex.stackexchange.com/questions/355136/how-to-disable-percent-encoding-in-urls). 
Briefly: I need to insert the following URL 
`https://ru.wikipedia.org/wiki/SLAM_(метод)`
without percent-encoding. For some reasons, I can't use XeLaTeX. I used the flag `--nouri-encode` and got the following result
` https://ru.wikipedia.org/wiki/SLAM_(РёРҳСЂР«Рұ)`
I even disabled the \url command to be sure it's biber
`\renewcommand{\url}[1]{#1}`
and the result remained the same.

**Comment by u-fischer** [comment]
As I tried to explain in the comments on tex.sx it is imho "not biber's fault".

**Comment by Himura2la** [comment]
Now when I checked the .bbl file, I see it's OK... But the URL is included in some unusual way...

```
    \entry{Wiki:SLAM}{incollection}{}
      \list{language}{1}{%
        {russian}%
      }
      \list{location}{1}{%
        {США}%
      }
      \list{organization}{1}{%
        {Wikimedia Foundation, Inc.}%
      }
      \field{sortinit}{2}
      \field{sortinithash}{0aa614ace9f3a40ef5a67e7f7a184048}
      \field{labeltitlesource}{title}
      \field{booktitle}{Википедия~"--- свободная энциклопедия}
      \field{day}{23}
      \field{month}{5}
      \field{title}{SLAM (метод)}
      \field{urlday}{22}
      \field{urlmonth}{2}
      \field{urlyear}{2017}
      \field{year}{2016}
      \field{dateera}{ce}
      \field{urldateera}{ce}
      \verb{url}
      \verb https://ru.wikipedia.org/wiki/SLAM_(метод)
      \endverb
    \endentry
```

**Comment by u-fischer** [comment]
This here is *really* the wrong place to discuss this things. This is not a biber problem. So close the issue and move the discussion to a better place.

**Comment by Himura2la** [comment]
I still don't understand why biber generates  \verb{url} instead of \field{url}, because in the latter case the solution to my problem could be much easier...

**Comment by u-fischer** [comment]
\field{url}  makes the handling of your special url easier. But quite a lot of urls (e.g. all the one which uses a %) would simply explode.
