### ISSUE TITLE
Possible regression in version 2.7 in tool mode when translating date and journaltitle fields with sourcemap

### ISSUE THREAD

**Issue by AndersFenger** [plk/biber#162]
With Biber 2.4 (TeX Live 2015) when I execute
```sh
biber --tool --configfile=test.conf test.bib
```
with the following configuration file (`test.conf`)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<config>
  <sourcemap>
    <maps datatype="bibtex">
      <map>
        <map_step map_field_source="journaltitle" map_field_target="journal"/>
        <map_step map_field_source="date" map_field_target="year"/>
      </map>
    </maps>
  </sourcemap>
</config>
```
and the following database (`test.bib`)
```
@Article{test2017,
	date = {2017},
	journaltitle = {A Journal},
        title = {The title of the article},
	pages = {1-10},
	volume = {10},
	number = {1},
	author = {Bar, foo}
}
```
I get the intended result:
```
@ARTICLE{test2017,
  AUTHOR = {Bar, foo},
  JOURNAL = {A Journal},
  NUMBER = {1},
  PAGES = {1-10},
  TITLE = {The title of the article},
  VOLUME = {10},
  YEAR = {2017},
}
```
That is, as expected, `journaltitle` is translated to `journal`, and `date` is translated to `year`.  However, when I do the same in version 2.7, I get the following unexpected result
```
@ARTICLE{test2017,
  AUTHOR = {Bar, foo},
  DATE = {2017},
  NUMBER = {1},
  PAGES = {1--10},
  TITLE = {The title of the article},
  VOLUME = {10},
}
```
That is, `journaltitle` and `date` are not translated to `journal` and `year` (In fact `date` passes through and `journaltitle` is removed). Is this intended behaviour?

I am aware of #150, but I believe that what I am trying to do is indeed the suggestion to [use a sourcemap to transform date to year](https://github.com/plk/biber/issues/150#issuecomment-261378737).

**Comment by plk** [comment]
With version 2.6, `biber` now properly converts tool mode data into its own internal data model making more conversions possible. This means that, in your case:

- `journal` will never be output because it's not a valid field in the default data model (it's always coerced to `journaltitle` by the default source maps.
- `year` won't be output in your case because it wasn't present in the original data.

**Comment by AndersFenger** [comment]
My goal is to convert my biblatex & biber compatible database to a natbib & bibtex compatible database.

1. Is it possible to change the data model such that `journal` and `year` are valid fields that can be outputted?
   1. If the answer is yes would you recommend this approach for my use case?
2. If approach 1 is not possible/recommended would you then suggest to post-process the database and    use regular expressions to change the field names?

**Comment by plk** [comment]
I wouldn't recommend messing about with the data model as these defaults are a core part of biblatex. I have never really seen anyone wanting to use biblatex to downgrade the data model - if you need to do this, I would just post-process with regexps since all you need it "JOURNALTITLE"->"JOURNAL" and "DATE"->"YEAR".

**Comment by AndersFenger** [comment]
That sounds as a fine solution. Many thanks.

**Comment by Nyavlys** [comment]
Just a few comments if people are looking to solve this problem:

- the 'journal' field can be added in the the data model of the conf file (see the content of the `biber --tool-conf` as an example)
- when --output-format is set to bibtex, it seems it's not possible to keep the "year" field (it's always deleted). The solution is to map it to some existing field ('usera' for instance) and post-process the resulting bib file (`sed -e 's/Usera/Year/'`).

A reason to "downgrade" the data model is to generate .bib file that still can be processed following any given .bst style (for instance as proposed by a publisher that did not yet move to biber/biblatx. Unfortunately, there still are some-:) I used this feature a lot with biber 1.9.

**Comment by bersbersbers** [comment]
> I would just post-process with regexps since all you need it "JOURNALTITLE"->"JOURNAL" and "DATE"->"YEAR".

This leaves the alignment incorrect if `journaltitle` happens to be the longest key.

**Comment by bersbersbers** [comment]
> I have never really seen anyone wanting to use biblatex to downgrade the data model

Also, the same behavior is seen by people (me) who use `biber` not for downgrading their biblatex file, but to use the tool mode to process a pure bibtex file. That change is pretty unfortunate.

**Comment by bersbersbers** [comment]
For anyone else stumbling across this: in #322, the undocumented(?) `--output-field-replace=location:address,journaltitle:journal` is helpful!
