### ISSUE TITLE
° rewritten to \textdegree without closing macro

### ISSUE THREAD

**Issue by sistlind** [plk/biber#163]
Hi,
i am not sure, if this is intended or a bug, but some utf8-characters are rewritten to latex-macros without an appriate closing of the macro.

For example, ° is changed to \textdegree, where i would expect \textdegree{}.
This behaviour often leads to problems, when ° is followed by ,e.g., Celsius or Fahrenheit:

MWE:
```
% !TeX program = pdflatex
% !BIB program = biber
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}

\begin{filecontents}{\jobname.bib}
@book{Mamu,
    editor = {Mustermann, Manfred},
    title = {100°C is very hot!},
    date = {2004},
}
\end{filecontents}
\usepackage[safeinputenc=true]{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```
Error: 
```! Undefined control sequence.
<argument> 100\textdegreeC

                           is very hot!
l.22 \end
         {document}
```
The same problem occurs at \textquoteright, \textquotedblright, ...

EDIT: Tested version: Biblatex v3.7 and Biber v2.7
Best regards,
Stefan

**Comment by plk** [comment]
Please try DEV version 2.8 where this should be fixed.

**Comment by sistlind** [comment]
Yes, its fixed, thanks for the fast response!
