### ISSUE TITLE
Please add ala-lc.rus transliterated sorting support

### ISSUE THREAD

**Issue by ndlecic** [plk/biber#165]
In Russian bibliographies sometimes a need arises to sort Cyrillic entries according to their Latin equivalent (with or without actual transliteration).

ALA-LC from Lingua::Translit works as expected with `\DeclareSortTranslit{\translit{russian}{ala-lc.rus}}` -- tested on a real life material.

**Comment by plk** [comment]
Ok - but are you saying you already tried it by just adding that `\DeclareSortTranslit` line? That shouldn't be enough as there are internals to change too.

**Comment by plk** [comment]
I have updated biblatex 3.8 and biber 2.8 - please can you check. The from/to strings to use with `\DeclareSortTranslit` are "russian" and "ala-lc" as per Table 11 in the docs.

**Comment by ndlecic** [comment]
> Ok - but are you saying you already tried it by just adding that \DeclareSortTranslit line? 
> That shouldn't be enough as there are internals to change too.

Sorry for the unnecessary brevity, of course I changed Utils.pm accordingly.

> I have updated biblatex 3.8 and biber 2.8 - please can you check. The from/to strings
> to use with \DeclareSortTranslit are "russian" and "ala-lc" as per Table 11 in the docs.

Great, thanks, it works. There is yet another transliteration of Russian that is needed in biber (BGN/PCGN), but it's currently unsupported by Lingua::Translit. I'll submit tables to them and open a new ticket here after that.

**Comment by plk** [comment]
Ok, great - let me know and I'll make the new version of Lingua::Translit a requirement.
