### ISSUE TITLE
BGN/PCGN transliterated sorting support for Russian needed

### ISSUE THREAD

**Issue by ndlecic** [plk/biber#166]
A new Lingua::Translit (0.27) is released. It contains two tables with BGN/PCGN transliteration for Russian (Strict and Standard). For sorting purposes "BGN/PCGN RUS Standard" is needed.

**Comment by plk** [comment]
I have updated the `Lingua::Translit` requirement for `biber` and added the transliteration pairs for "russian" and both  "bgn/pcgn-strict" and "bgn/pcgn-standard". Please can you pull biblatex 2.8 dev version and biber 3.8 dev version to test? See Table 11 on p. 188 of the biblatex 3.8 PDF manual.

**Comment by ndlecic** [comment]
Great, thanks! I could be wrong, but I'd say that "Strict" variant is probably not needed for sorting purposes in biber, but for real transliteration only. It is much complicated than "Standard", however, on user level the only difference is the presence of the interpunct character (you can compare test files 33 and 34 from Lingua::Translit). The interpunct character can actually break sorting, right?

**Comment by plk** [comment]
Hmm, not sure about that character - given that we can sort Unicode, maybe not - perhaps you can try it. Anyway, for now I've added standard as an option - if you think it's pointless, I can remove it.

**Comment by ndlecic** [comment]
1. A couple of corrections to your latest commits is needed:
  * you should update @valid_to list;
  * Return -> return in three places (forgot to write about it when you added ALA-LC)

2. As for Strict vs. Standard, please take a look at this example:
```
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage{russian}
\setotherlanguage{english}
\setmainfont{Old Standard}
\usepackage[style=gost-authoryear,language=auto,autolang=other]{biblatex}

\DeclareSortTranslit{
	\translit{russian}{bgn/pcgn-strict}
}

\begin{filecontents}{\jobname.bib}
@Book{book1,
        author = {Никитский, С.},
        title = {Название 1},
        location = {М.},
        publisher = {Мысль},
        year = {1989},
        language = {russian},
        langid = {russian},
}
@Book{book2,
        author = {Никитин, С.},
        title = {Название 2},
        year = {1989},
        location = {М.},
        publisher = {Мысль},
        language = {russian},
        langid = {russian},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
\cite{book1,book2}
\printbibliography
\end{document}
```
(These are real families, i.e. this is not just a theoretical example.)

Wth bgn/pcgn-strict, we get the following:
![Strict](http://anthesphoria.net/tmp/1.png)
"Nikitskiy" is before "Nikitin" because in Strict variant there is a medial dot between t and s in the first family ("Nikit·skiy"). I can't imagine that someone wants this.

With bgn/pcgn-standard we have
![Standard](http://anthesphoria.net/tmp/2.png)
-- which is normal and expected.

So I'd say that Strict is pointless in biber, even if a bibliography is typeset with real transliteration.

**Comment by plk** [comment]
Thanks - must have been asleep. Code is updated and Strict is removed.

**Comment by ndlecic** [comment]
... Strict should also be removed from biblatex documentation.

**Comment by plk** [comment]
Also done now.
