### ISSUE TITLE
sortlocale ignored

### ISSUE THREAD

**Issue by floriandk** [plk/biber#168]
As of Biber 2.7/biblatex v3.7 (TL 16) `sortlocale` is ignored for at least Danish and Norwegian. Letters with diacritics are placed at non-sensical places (i.e. not even like the base character). The xelatex/lualatex-mwe

```latex
\documentclass{article}
\usepackage{polyglossia}
    \setdefaultlanguage{danish}
\usepackage[style = authoryear, sortlocale = da_DK]{biblatex}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{andersen,
    AUTHOR = "Hans Christian Andersen",
    TITLE = "Bogtitel",
    YEAR = "2010"}
@book{endersen,
    AUTHOR = "Hans Christian Endersen",
    TITLE = "Bogtitel",
    YEAR = "2010"}
@book{indersen,
    AUTHOR = "Hans Christian Indersen",
    TITLE = "Bogtitel",
    YEAR = "2010"}
@book{ondersen,
    AUTHOR = "Hans Christian Ondersen",
    TITLE = "Bogtitel",
    YEAR = "2010"}
@book{aandersen,
    AUTHOR = "Hans Christian Åndersen",
    TITLE = "Bogtitel",
    YEAR = "2010"}
@book{aendersen,
    AUTHOR = "Hans Christian Ændersen",
    TITLE = "Bogtitel",
    YEAR = "2010"}
@book{oendersen,
    AUTHOR = "Hans Christian Øndersen",
    TITLE = "Bogtitel",
    YEAR = "2010"}
@book{Zandersen,
    AUTHOR = "Hans Christian Zandersen",
    TITLE = "Bogtitel",
    YEAR = "2010"}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```
yields

A,E,Æ,Ø,Å,I,O,Z

while Biber 2.6/biblatex v3.6 and Biber 2.4/biblatex v3.3 (TL 15) used to sort correctly:

A,E,I,O,Z,Æ,Ø,Å

The same problem has been [observed (2.1/3.0) and resolved (2.2) earlier](https://tex.stackexchange.com/questions/263900/sortlocale-no-longer-works-with-current-versions-of-biblatex-and-biber).

**Comment by plk** [comment]
Can you try biblatex 3.8+biber 2.8 currently in DEV on sourceforge? With these, your example is fine for me.

**Comment by floriandk** [comment]
Unfortunately I can't get it to work here: It requires Log4perl.pm to the non-preinstalled perl 5.24. The module install isn't straightforward on homebrew.

Could you perhaps include the new version to the TL pretest? I'd be happy to test from there.

**Comment by plk** [comment]
You don't need to use the unpacked version - you can get pre-compiled DEV versions from Sourceforge as long as you are using linux, mac or windows:

https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/

**Comment by floriandk** [comment]
Thanks for the pointer, it's a bit puzzeling with the development/tracking going on in different places…But unfortunately [biber 2.8 (beta)](https://netcologne.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/development/binaries/OSX_Intel/biber-darwin_x86_64.tar.gz) and [biblatex 2017/04/29 v3.8](https://netcologne.dl.sourceforge.net/project/biblatex/development/biblatex-3.8.tgz) with TL 16 on MacOS 10.12.4 still doesn't sort properly. Anything else I could try?

**Comment by plk** [comment]
Hmm, perhaps you can ask a question on tex.stackexchange.com to see if anyone else has the issue? I am using the same versions as you and it's correct for me. I'd like to see if anyone else has the issue.

**Comment by moewew** [comment]
Sorts correctly for me. This could be related to https://github.com/plk/biber/issues/164

**Comment by plk** [comment]
Yes, if you are not using a pre-packed version then you need to run 'perl Build.PL' to check your modules are the required versions.

**Comment by perstar** [comment]
I get the same erroneous results floriandk, and that even with texlive 2017.  (I also get the same erroneous results as reported for eg9's test in #164.)

I think from the discussion in #164 that it is because biber doesn't work unless your perl Unicode::Collage module is rather new. I have been testing on a Centos 7 system. Centos (as RHEL) is not cutting edge at all, but certainly something that ought to be supported, I think. It has perl 5.16.3.

**Comment by plk** [comment]
There is nothing that can be done if the Unicode::Collate module is not recent enough and you are using a non-packaged biber. The biber requirements are for version >= 1.19 - this provides the tailored locales for sorting you need. Why are people using an unpackaged biber on CentOS 7 anyway when the packaged linux version will work and has the latest Unicode::Collate?

**Comment by perstar** [comment]
Are you asking why people are installing texlive instead of installing all packages individually one by one? That's rather obvious, isn't it? The texlive that comes with Centos is *really* old.

I'm sure there are people that care particularly about Biblatex/Biber that install them explicitly, but I really don't think it is reasonable to expect many users to do that. I think it is very important that this "just works" in a freshly installed texlive 2017. I thought the way forward was to find what actually triggers this very strange behaviour and change whatever it is that biber does then, but maybe it's better to see this as a texlive issue where it should be changed what texlive includes?


I don't know what to do now. I regret I didn't catch this in texlive beta, and reported it to the texlive team then.

**Comment by plk** [comment]
Oh, I see. Well, if a system has a really old TL, no possibility to update and people don't want to install new versions of things from SF then I don't know what to do ... older things just don't do things that newer things do. Old TL had a version of biber with an older version of Unicode::Collate which doesn't do CLDR tailoring ...

**Comment by floriandk** [comment]
If I run the latest precompiled Biber 2.8 (beta) (3rd June) with biblatex 2017/06/15 v3.8 on a fresh TL17 (MacOS 10.12.5) the wrong sorting persists. The `.blg` shows that `locale_version     => 1.14` is used. I'm not sure, that I understand all implications of the discussion on #164 but shouldn't the updated version use the updated locale? Or do I have to replace other files, too?

**Comment by plk** [comment]
Apologies, this was a problem with the build. `Unicode::Collate` irritatingly switched install location on OSX with the last version and the build was picking up the default perl install version. Please try the 2.8 pre-built binary now.

**Comment by floriandk** [comment]
Great, the new one rapports `locale_version => 1.19` and works both with the mwe and with real-life files! This issue seems to be solved as far as I can see from here.
