### ISSUE TITLE
biber is incompatible with covington.sty

### ISSUE THREAD

**Issue by keithbriggs** [plk/biber#169]
Biber normalizes \u| into \u{|}, which breaks the covington package (https://www.ctan.org/tex-archive/macros/latex/contrib/covington ).

Please see https://tex.stackexchange.com/questions/370788/twoacc-fails-in-bibliography for details.

**Comment by plk** [comment]
It is very difficult to make utf8<->latex macro encoding/decoding cover all cases. If the new version of covington makes this work again, I'd rather not put more special cases into biber. It is preferable to use UTF8 in the bibliography directly when possible as this is one of the main original motivations of biber in the first place.

**Comment by jspitz** [comment]
Note, though, that the covington macro provides something that is not covered by UTF-8 (arbitrary stacked diacritics).
