### ISSUE TITLE
Feature request: Resolve XData only, not CrossRef

### ISSUE THREAD

**Issue by equaeghe** [plk/biber#172]
Currently, with `biber --tool --resolve`, it is possible to resolve all references, `XData`, `CrossRef`, and `XRef`. It would be useful to be able to choose which type to resolve. For example, Jabref currently knows `CrossRef`, but not `XData`. So to make a bibfile with `XData` references suitable for Jabref, resolving `XData` but not `CrossRef` is useful.

(I asked about this on tex.stackexchange.com: <https://tex.stackexchange.com/q/374705>.)

**Comment by plk** [comment]
This is now implemented in 2.8 DEV version. `--output-resolve` is now a meta-option which sets all of the more granular `--output-resolve-xdata`, `--output-resolve-crossrefs` and `--output-resolve-sets` options.
