### ISSUE TITLE
2.5 to 2.7 update creates new warnings

### ISSUE THREAD

**Issue by rbost** [plk/biber#174]
I just updated my TeXLive distribution from TeXLive 2016 to 2017 (the MacTex version to be completely precise).

Without changing any of the source files, I now get perl errors messages:
```
Use of uninitialized value in lc at /var/folders/mf/[some temp path]/inc/lib/Biber/Output/bbl.pm line 279.
```
which points to the following block (I highlighted the line):
```perl
  # Output list fields
  foreach my $listfield ($dmh->{lists}->@*) {
    # Performance - as little as possible here - loop over DM fields for every entry
    if (my $lf = $be->get_field($listfield)) {
      if ( lc($lf->[-1]) eq Biber::Config->getoption('others_string') ) { # <-- THIS LINE
        $acc .= "      \\true{more$listfield}\n";
        pop $lf->@*; # remove the last element in the array
      }
      my $total = $lf->$#* + 1;
      $acc .= "      \\list{$listfield}{$total}{%\n";
      foreach my $f ($lf->@*) {
        $acc .= "        {$f}%\n";
      }
      $acc .= "      }\n";
    }
  }
```
Note that this does not prevent the .bbl file to be output and the bibliography to be properly display in the final output. 

I reproduced the same error on two different machines with the same TeXLive distrib.
It also appears I am not the only one to experience this problem, according to [this](http://www.guitex.org/home/en/forum/5-tex-e-latex/110309-biber-e-quse-of-uninitialized-valueq).

FYI, I don't have the same number of errors (15) than in the previous link (17); something in the .tex or .bib sources must raise this error (but it is hard to tell what does exactly, the error log is quite sparse).
If it is a syntax error in the bib file, it would be great to signal it explicitely.

**Comment by plk** [comment]
I would need to see the .bib entry that triggers this?

**Comment by rbost** [comment]
Sure, but I have to warn you that it is huge.
It is the crypto.bib file from the [Cryptobib repo](https://github.com/cryptobib/export).
I selected only the entries I use in the attached file. 
I am using the abbrev3.bib file as a macro file, and I import them in the source with the following lines:
```latex
\addbibresource{cryptobib/abbrev3.bib}
\addbibresource{selected_crypto.bib}
```
Everything is in the zip archive.

[biblio.zip](https://github.com/plk/biber/files/1125422/biblio.zip)


PS: It has to be a problem with the way files are parsed, as I tried with an hand-made file without any errors showing.

**Comment by plk** [comment]
In that case it's likely a problem with the bib - if you can identify the bad entry, we can decide if it's a bug or not. I am afraid I don't have the time to diagnose the .bib.

**Comment by rbost** [comment]
It is a problem with the 'empty' address field:
```
@InProceedings{EC:BelRog06,
  author =       "Mihir Bellare and Phillip Rogaway",
  title =        "The Security of Triple Encryption and a Framework for Code-Based Game-Playing Proofs",
  pages =        "409--426",
  editor =       "Serge Vaudenay",
  booktitle =    "EUROCRYPT~2006",
  volume =       "4004",
  address =      "",
  month =        "5",
  publisher =    "Springer, Heidelberg",
  series =       "{LNCS}",
  year =         2006
}
```
is not ok, while
```
@InProceedings{EC:BelRog06,
  author =       "Mihir Bellare and Phillip Rogaway",
  title =        "The Security of Triple Encryption and a Framework for Code-Based Game-Playing Proofs",
  pages =        "409--426",
  editor =       "Serge Vaudenay",
  booktitle =    "EUROCRYPT~2006",
  volume =       "4004",
  address =      "toto",
  month =        "5",
  publisher =    "Springer, Heidelberg",
  series =       "{LNCS}",
  year =         2006
}
```
is alright.

Previously, biber did output a warning for empty address fields, which no longer the case in version 2.7.
