### ISSUE TITLE
\guillemotleft, \guillemotright converted into math mode

### ISSUE THREAD

**Issue by moewew** [plk/biber#175]
Via https://tex.stackexchange.com/q/382745/35864

Consider the following MWE
```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[british]{babel}
\usepackage[style=authoryear]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article{Guinet:Torp,
  author={Louis Guinet},
  title={Les toponymes normands \guillemotleft Torp(s)\guillemotright, \guillemotleft Torpt\guillemotright, \guillemotleft Tourp(s)\guillemotright, \guillemotleft Tour(s)\guillemotright},
  journal={Annales de Normandie},
  volume=30,
  number=2,
  pages="193--197",
  year=1980,
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
Les toponymes normands \guillemotleft Torp(s)\guillemotright, \guillemotleft Torpt\guillemotright, \guillemotleft Tourp(s)\guillemotright, \guillemotleft Tour(s)\guillemotright

\cite{Guinet:Torp}
\printbibliography
\end{document}
```
in the `.bbl` we find
```
field{title}{Les toponymes normands {$\guillemotleft$}Torp(s){$\guillemotright$}, {$\guillemotleft$}Torpt{$\guillemotright$}, {$\guillemotleft$}Tourp(s){$\guillemotright$}, {$\guillemotleft$}Tour(s){$\guillemotright$}}
```
For some reason the guillemots are wrapped into math mode. This seems undesirable.

**Comment by plk** [comment]
Please try biber 2.8 DEV - the macro/UTF8 conversion is full of exceptions, this is another one ...

**Comment by moewew** [comment]
Thank you, it works.

I now get
```
\field{title}{Les toponymes normands \guillemotleft{}Torp(s)\guillemotright{}, \guillemotleft{}Torpt\guillemotright{}, \guillemotleft{}Tourp(s)\guillemotright{}, \guillemotleft{}Tour(s)\guillemotright{}}
```
Is there a way to stay true to the original input and not have the empty groups after the macros? Ideally the output would just be equal to the input.

**Comment by plk** [comment]
It's tricky because things come in "classes" in the conversion routines and a lot of things in that class need the groups so things don't break. The reason this is happening at all is because internally conversion to UTF8 is happening for collation purposes and then because of the combinations of options/encodings, reverse conversion is being done on the way out which is an intrinsically messy business.

**Comment by moewew** [comment]
I feared as much, oh well ....
Maybe there could be an option to output fields exactly as they are given in the input, in that case Biber could either still convert to UTF-8 for sorting and not convert back, or not convert at all for sorting.

**Comment by plk** [comment]
I've looked at this a few times and it's complicated because the recoding happens at the file level currently, for speed reasons. It would have to be switched to per-entry to save two version of each internal entry object.

**Comment by moewew** [comment]
Ah, OK. That would make things more complicated.

**Comment by keithbriggs** [comment]
Thanks to everyone for help on this.   I found that biber 2.8 DEV doesn't build on Ubuntu 16 as it needs a newer version of perl, so for now I just wrote a post-processor to fix my .bbl file.   I look forward to using biber 2.8 soon when the pre-requisites support it.
