### ISSUE TITLE
Perl 5.26 on MacPorts

### ISSUE THREAD

**Issue by simifilm** [plk/biber#176]
This is only indirectly related to `biber`, so if you think this is inappropriate, just close the issue.

Current builds of `biber` require `Perl` 5.26. In the past, I had no problem with `biber's` `Perl` requirements, I just installed the appropriate version with `MacPorts`. With version 5.26 this does not seem to work anymore. There is a `Perl 5.26` port, but when I install it, I still only have version 5.24 available. I tried all kind of ways, deactivating or uninstalling version 5.24, but nothing helps. Whenever I install version 5.26, `Macports` insists on installing and activating version 5.24.

I realise that this is more of a `Macports` issue, but how do you get `Perl 5.26` running on OSX?

**Comment by plk** [comment]
You are right - it seems that the perl5 port doesn't have a +5.26 variant yet. I had to do it manually. This basically means installing the 5.26 port directly, not using the perl5 port with a variant. Then, forcing remove of 5.24. Then you have to manually remove all the 5.24 bits like:

```
sudo \rm -rf /opt/local/lib/perl5/5.24
sudo \rm -rf /opt/local/lib/perl5/site_perl/5.24
sudo \rm -rf /opt/local/libexec/perl5.24
sudo \rm -rf /opt/local/share/perl5.24
sudo rm /opt/local/bin/perl5.24*
sudo rm /opt/local/bin/*-5.24
```
Then link the defaults to the 5.26 versions.
```
for file in *-5.26; do sudo ln -sf $file `basename $file -5.26`; done
```
