### ISSUE TITLE
\addbibressource[location=remote] returns HTTP 500 : internal Server error

### ISSUE THREAD

**Issue by gtoubekis** [plk/biber#178]
Hello,
I am using the Firefox extension Better BibLatex (BBT) with Firefox and use [the pull export funtion](https://github.com/retorquere/zotero-better-bibtex/wiki/Push-and-Pull-Export)  with BibLaTeX remote statement which returns me HTTP code:500 in latex build and thus creates no reference list.

Error message is 
[550] Biber.pm:3840> INFO - Looking for bibtex format file 'http://localhost:23119/better-bibtex/collection?/0/HKF8JH6P.biblatex' for section 0
[551] bibtex.pm:138> INFO - Data source 'http://localhost:23119/better-bibtex/collection?/0/HKF8JH6P.biblatex' is a remote BibTeX data source - fetching ...
[1763] Utils.pm:180> ERROR - Could not fetch 'http://localhost:23119/better-bibtex/collection?/0/HKF8JH6P.biblatex' (HTTP code: 500)

but the embedded web server is accessible and can be reached via all my browser's interfaces (Firefox, Chrome, Chromium) as long as Firefox(plus extension) is running it returns valid Bibtex/BibLatex format.  When I export the references with BBT to a .bib file and add the resource locally it produces the expected result. Seems that the \addbibressource[location=remote] function cannot connect to the embedded web server.

Is there any firewall restriction within the Biber package that can be checked or altered by the user?
I use the latest version of MiKTeX with Biber/Biblatex 2.7/3.9
Thanks

**Comment by plk** [comment]
This works for me with the 2.8 DEV release of biber (and worked with 2.7 for me too) using the embedded server in firefox and zotero 4. Error 500 is a server internal error - are there any server logs you can find?
