### ISSUE TITLE
Document Biber's behaviour for handling entries with duplicate keys

### ISSUE THREAD

**Issue by logological** [plk/biber#181]
When Biber encounters two entries with the same key, it outputs a warning that indicates the second entry is being ignored rather than overriding the first entry:

```
WARN - Duplicate entry key: 'foo' in file 'test2.bib', skipping ...
```

As far as I can tell, this behaviour is not described in the documentation.  It would be useful to mention it there so that users don't need to guess or experiment to see what happens.  (Consider the case where you have two .bib files that contain some overlapping entries, but for these overlapping entries, one of these .bib files has better information. There is no way of knowing what order to include the two files in without trial and error.)

**Comment by plk** [comment]
It is mentioned in the biber doc that the `--help` output is a major source of information and there you will find the `--noskipduplicates` option - does that help?

**Comment by logological** [comment]
Well, the exact wording is that `--help` "is the most useful *brief* source of usage information" (my emphasis), so I assumed that the PDF documentation would be more comprehensive.  So yes, now that you mention it, the `--help` output does help, but given what the manual says, I would never have thought it necessary to look there.

**Comment by plk** [comment]
Yes, I think you are right. I have altered the `biber` doc for the next release.
