### ISSUE TITLE
The order of `keyalias` commands in `bbl` file changes nondeterministically

### ISSUE THREAD

**Issue by ziggystar** [plk/biber#182]
This file reproduces the bug

The problem with this is, that `latexmk` (and possibly other tools) keeps running forever, because the `bbl` and `bcf` files keep changing.

The data of the entries shouldn't matter, though I tried first with minimal @misc entries and it didn't produce the bug. Maybe I made a mistake.

```
\documentclass{article}

\usepackage[backend=biber]{biblatex}
\begin{filecontents*}{main_biber.bib}
@InProceedings{Bacchus2002,
  author       = {Bacchus, Fahiem and Dalmao, Shannon and Pitassi, Toniann},
  title        = {Value elimination: Bayesian inference via backtracking search},
  booktitle    = {Proceedings of the Nineteenth conference on Uncertainty in Artificial Intelligence},
  year         = {2002},
  ids          = {bacchus2002value},
}
@InCollection{Bidyuk2003,
  author         = {Bidyuk, Bozhena and Dechter, Rina},
  title          = {Cycle-cutset sampling for Bayesian networks},
  booktitle      = {Advances in Artificial Intelligence},
  year           = {2003},
  ids            = {bidyuk2003cycle},
}
@InBook{Biere2009,
  author    = {Biere, Armin},
  title     = {Handbook of satisfiability},
  year      = {2009},
  publisher = {Ios PressInc},
  chapter   = {Model Counting},
  ids       = {Biere2009b},
}
@InProceedings{Bouchard2009,
  author       = {Bouchard, Guillaume and Zoeter, Onno},
  title        = {Split variational inference},
  booktitle    = {Proceedings of the 26\textsuperscript{th} Annual International Conference on Machine Learning},
  year         = {2009},
  ids          = {bouchard2009split},
}

@InProceedings{Boutilier1996,
  author       = {Boutilier, Craig and Friedman, Nir and Goldszmidt, Moises and Koller, Daphne},
  title        = {Context-specific independence in Bayesian networks},
  booktitle    = {Proceedings of the Twelfth international conference on Uncertainty in artificial intelligence},
  year         = {1996},
  ids          = {boutilier1996context},
}

\end{filecontents*}

\addbibresource{main_biber.bib}

\begin{document}
    \parencite{bacchus2002value}
    \parencite{bidyuk2003cycle}
    \parencite{Biere2009b}
    \parencite{bouchard2009split}
    \parencite{boutilier1996context}
    \printbibliography
\end{document}
```

**Comment by moewew** [comment]
See also  https://github.com/plk/biblatex/issues/618. The MWE does not work with BIbTeX, the `id`s are not resolved.  Not sure if that can be done with BibTeX.

**Comment by ziggystar** [comment]
I tried adding a `sort` before the hash that gets traversed at https://github.com/plk/biber/blob/a29463dbe2f565cf1986520107d885ce6cae5a4a/lib/Biber/Output/base.pm#L339.

But this didn't fix it. I don't understand what happens here:
https://github.com/plk/biber/blob/a29463dbe2f565cf1986520107d885ce6cae5a4a/lib/Biber/Output/bbl.pm#L167

I assume that the relevant code for this issue is in `bbl.pl` and `base.pl`.

**Comment by plk** [comment]
I have corrected the non-determinism in the .bbl output - please try `biber` 2.8 DEV version (on Sourceforge). You will also need biblatex 3.8 DEV version to use this.

**Comment by ziggystar** [comment]
I haven't yet upgraded biblatex, but I'm getting this, and I think this is a Perl issue:

> INFO - This is Biber 2.8 (beta)
> INFO - Logfile is 'main.blg'
> Use of bare << to mean <<"" is deprecated at /home/thomas/workspace/biber/lib/Biber/Output/bbl.pm line 42.
> ERROR - Error loading data source package 'Biber::Output::bbl': syntax error at /home/thomas/workspace/biber/lib/Biber/Output/bbl.pm line 42, near "<<~"
> Compilation failed in require at (eval 339) line 2.
> 
> INFO - ERRORS: 1
>

**Comment by plk** [comment]
That means you are not using the pre-built biber - presumably you are using your own perl installation but biber 2.8+ requires perl 26.0+ and you seemingly don't have that (`<<~` constructions are perl 26.0+).

**Comment by ziggystar** [comment]
Yes, I'm running the source from Git. Can I get a binary of the dev branch somehow?

**Comment by plk** [comment]
Yes, in the development folder on Sourceforge: https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/

**Comment by ziggystar** [comment]
I can confirm that the order of the entries within the `bbl` file now stays the same with the current dev version.

**Comment by ziggystar** [comment]
I checked with my minimal example and with my project. `latexmk` fails to complete with the old code, and completes after three runs with the new code.

**Comment by plk** [comment]
Ok, then I'll close this.

**Comment by plk** [comment]
Ok, then I'll close this.
