### ISSUE TITLE
biber safechar and \dots/\dag

### ISSUE THREAD

**Issue by baem2** [plk/biber#184]
I'm using biber 2.7 beta (that's what comes with debian stretch) with the option --output_safechars.

For some reason doing this turns ``\dots`` into ``$\dots$`` and ``\dag`` into ``$\dag$``. For (other) technical reasons I'm trying to avoid the math mode. Is there any way to change that behaviour of biber? 

An by the way, is this a bug or a feature?

**Comment by plk** [comment]
Can you try biber 2.8 beta from Sourceforge? You will also need biblatex 3.8 beta to use this.

**Comment by baem2** [comment]
Thanks for your reply. I'll try to have a look in the next days.

**Comment by baem2** [comment]
Yap, sorry, I did not come to install the latest versions. As I do no longer use --output_safechars, I'm fine with closing this one.
