### ISSUE TITLE
TeX package for symbol macro \textrevcommaabove

### ISSUE THREAD

**Issue by baem2** [plk/biber#186]
In a bib-file I'm using a greek letter (``Ἱ``), which is transformed by ``biber --output_safechars`` to 

```\textrevcommaabove{Ι}```

I can't find which package to load to enable this command. I read (ftp://ftp.dante.de/tex-archive/biblio/biber/documentation/utf8-macro-map.html) that I can find it in the file loaded by ```texdoc symbols``` -- but I can't find the command in that file. Do you know where to look? Otherwise I could ask on of the mailing lists.

**Comment by baem2** [comment]
(Or is there a way to define ``\textrevcommaabove`` myself?)

**Comment by u-fischer** [comment]
There is a definition for `\textrevcommaabove` in l8uenc.def but this is an internal encoding not meant for printing. Imho the option --output_safechars`  is not a so good idea if you are using such chars but for an on-time-shot you can define the command e.g. like this (for pdflatex, with lualatex it would be different):

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[LGR,T1]{fontenc}
\newcommand\textrevcommaabove[1]{{\fontencoding{LGR}\selectfont\accdasia#1}}
\begin{document}
\textrevcommaabove{I}
\end{document}
```

**Comment by baem2** [comment]
Thank you for your reply! It solves the \textrevcommaabove-problem, but there seem to be more.

Is there a better way than doing it with ``--output_safechars``? For this project I'm probably bound to pdflatex, but I have to use utf-8 greek. All fine so far, the only problem is the bibliography ...

(If you prefer, I can start a discussion on the tex-d-l list, instead of this one here.)

**Comment by u-fischer** [comment]
I probably wouldn't use --output_safechars but use normal utf8 export but mark up the greek in the bib correctly so that pdflatex then can handle it. But here is imho not the place to ask about this. Better use a sensible usenet list or tex.sx.

**Comment by baem2** [comment]
As I always had weird problems with the utf8 output, I was using --output_safechars. Now I tried without it, and after some changes in the bib files (regarding turkish \.i) it's all fine w/o --output_safechars. So thank you for your help!
