### ISSUE TITLE
testing fails in sorting.t at $biber->prepare

### ISSUE THREAD

**Issue by norbusan** [plk/biber#188]
Hi Phil,

I prepared a new Debian package and now I get failures building biber. In contrast to previous ones it is not an error of some hash sums, but the test is breaking early:

`````
t/sorting.t .. 
1..51
AAA
# Looks like your test exited with 25 before it could output anything.
Dubious, test returned 25 (wstat 6400, 0x1900)
Failed 51/51 subtests 
`````

The `AAA` you see is from me adding debug statements to find out where it dies, and it is right in the line `$biber->prepare` (after which I added a print statement which is never shown).

Any idea what this could be?

Thanks

Norbert

**Comment by plk** [comment]
Hmm, not sure currently - FreeBSD is reporting similar things but I have no issues at all on OSX, linux, windows. It seems to be something to do with the Text::BibTeX module but FreeBSB reports that this module tests fine when installed from CPAN. If you do `Build install` followed by `perl t/basic-misc.t`, you should get more details.

**Comment by plk** [comment]
It may be a compat issue with libxml2. The FreeBSD maintainer fixed it by upgrading his environment and I suspect, as I remember vaguely this happened several releases ago, that upgrading libxml2 and re-installing/updating the XML::LibXML module may help.

**Comment by norbusan** [comment]
Hi
thanks for your anser. Your explanation would sound ok when using the pre-built "binary", but I am rebuilding everything from source, so the version of libxml2 and XML perl module are the very same.

Does that mean that you have some stricter requirement on the versions of libxml2 and XML perl modules?

**Comment by dcpurton** [comment]
@norbusan, I regularly use the git version of both `biber` and `biblatex` under Debian Testing. I have to install a couple of extra perl modules (libencode-eucjpascii-perl, libmozilla-ca-perl_20160104—I gather you adjust `biber` not to need these) and I had to build a new version of liblingua-translit-perl (0.28) which isn't built for Debian yet.

I don't get any errors when I run the tests (including t/sorting.t).

I don't make a binary to run it though (I never really figured out how to...) I have multiple versions of `biber` in my development directory and call them using `perl -Mblib=$BIBERPATH $BIBERPATH/blib/script/biber` where `$BIBERPATH` contains the `blib` directory for a particular version.

Let me know if I can check anything for you.

**Comment by norbusan** [comment]
@dcpurton thanks for your comment, interesting. First of all, yes, libencode-eucjpascii and libmozilla-... are patched out, that hasn't been a problem since years.

Your comment about liblingua-translit-perl is interesting, is this documented? I am using - as you know - the packaged version 0.27-1, could this be the problem?

The point is I cannot simply use outside modules because I'm the maintainer and want to upload a new package at some point, and then it must build with what there is in Debian/unstable.

What puzzles me is that there is *no* error message or warning or output *what* *so* *ever*, isn't that strange? I would expect some output/error ...

**Comment by dcpurton** [comment]
@norbusan, when I ran `perl Build.PL`, I got an error about outdated liblingua-translit-perl and the required version number. So I just make a new Debian package (using dh-make-perl). Once that was installed `perl Build.PL` runs without errors. I can then run `./Build` and `./Build test`. No errors are generated. If I want to build a new version, I always run `./Build distclean` and start again with `perl Build.PL` to make sure I have the correct perl packages and versions installed.

The Lingua::Translit requirement was bumped in commit 78f2858227051710acc827870adc94ecf0ac30db, so I assume that this package will need to be updated in Debian also.

I've often found that the perl requirements for `biber` are ahead of what is available in the main Debian repository, but I have always had success building my own temporary packages until the official ones catch up.

**Comment by plk** [comment]
Lingua::Translit 0.28 is a requirement due to a recent update in Russian transliteration - it would not cause an error to have 0.27.

PK

> On 7 Nov 2017, at 12:56 am, Norbert Preining <notifications@github.com> wrote:
> 
> @dcpurton thanks for your comment, interesting. First of all, yes, libencode-eucjpascii and libmozilla-... are patched out, that hasn't been a problem since years.
> 
> Your comment about liblingua-translit-perl is interesting, is this documented? I am using - as you know - the packaged version 0.27-1, could this be the problem?
> 
> The point is I cannot simply use outside modules because I'm the maintainer and want to upload a new package at some point, and then it must build with what there is in Debian/unstable.
> 
> What puzzles me is that there is no error message or warning or output what so ever, isn't that strange? I would expect some output/error ...
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Dr Philip Kime

**Comment by norbusan** [comment]
Hmm, I need to retry with an updated Lingua::Translit and see whether this was the problem.

I am still surprised that biber just collapses without any output/error.

**Comment by norbusan** [comment]
Hmm, I need to retry with an updated Lingua::Translit and see whether this was the problem.

I am still surprised that biber just collapses without any output/error.

**Comment by plk** [comment]
I assume this is ok now?

**Comment by remyoudompheng** [comment]
I encountered a similar issue (as the maintainer of the ArchLinux package) and solved it by installing PerlIO::utf8_strict that was missing.

**Comment by norbusan** [comment]
Sorry, was off for company work. Yes, PerlIO::utf8_strict was the trick. The Lingua::Translit is not a problem if at .27
Thanks
