### ISSUE TITLE
Misplaced id stuck in recursive loop

### ISSUE THREAD

**Issue by dpeterson3** [plk/biber#189]
I messed up 2 .bib entries having the regular id and sub-id be the same
[code]
@article{apn-journal,
  ids={apn-journal, yucelendistributed},
  title={Distributed Control of Active-Passive Networked Multiagent Systems},
  author={Yucelen, Tansel and Peterson, John Daniel},
  publisher={IEEE},
  journal={Transactions on Control of Networked Systems},
  month={03},
  year={2016}
}
[/code]

When this happens, biber gets stuck in a recursive look at line 4032 saying "deep recursion". Enabling trace gives
[code]
      [2847] Biber.pm:4029> TRACE - Recursing in get_dependents with: apn-journal
[/code]

I eventually have to kill the process as it eats so much ram it will crash the machine otherwise. I realize its a simple fix since its a messed up .bib file, but I think there could be a check put in place so the machine doesn't end up crashing as a result.

**Comment by plk** [comment]
This is implemented in biber 2.9 DEV which will warn and ignore a recursive alias such as this.
