### ISSUE TITLE
Undefined value as an ARRAY reference (biber 2.8 TOOL mode)

### ISSUE THREAD

**Issue by ruempel** [plk/biber#192]
Running `biber --tool test.bib` with 
```
@BOOK{test1,
  AUTHOR = {Terrence Test},
  TITLE = {Testing is Trying and Troubling},
  YEAR = {1987},
}
```
produces the following problem with Biber 2.8, but worked in Biber 2.7:
`Can't use an undefined value as an ARRAY reference at .../Internals.pm line 1100.`

This was tested with Windows 64 bit release binaries.

**Comment by plk** [comment]
Thanks for reporting, was a typo in one conf file without a test case attached. Can you try biber 2.9 from the development folder on Sourceforge? You will also need biblatex 3.9 from its development folder on SF.

**Comment by ruempel** [comment]
Thank you for fixing. It works now using biber 2.9 (beta) from the SF development folder.

**Comment by plk** [comment]
Thanks for checking. I will plan to release 2.9 as soon as possible.

**Comment by kleinschmidt** [comment]
I'm having a similar issue with 2.9 beta, when using `biber --output_format=bibtex` (I'm using it to extract only the references I've actually cited into a .bib file).  Running in normal mode (omitting the output format) everything works fine.  I'm having trouble finding a MRE but if I get time I'll try later.  If you have any tips on how to enable better debug logging (`--debug` and `--sortdebug` don't seem to add much) let me know.

**Comment by plk** [comment]
@kleinschmidt - can you open a new ticket with an example? 2.9 is released now.
