### ISSUE TITLE
biber doesn't like CR line endings 

### ISSUE THREAD

**Issue by u-fischer** [plk/biber#193]
I got a bib-file which uses CR as line endings (I have no idea how it was created). The bib-file starts with a comment line: `% Encoding: UTF-8`. 

biber wasn't able to process this bib-file. The error message was:

~~~~
[938] Utils.pm:180> ERROR - BibTeX subsystem: C:\Users\USER\AppData\Local\Temp\FoHt2Ym11b\DissBib6-test.bib_8704.utf8, line 1, syntax error: at end of input, expected "@"
[939] Biber.pm:113> INFO - ERRORS: 1
~~~~

This sounds as if biber processed the whole file as one long line, and as it started with a comment nothing was in it from biber's view.

**Comment by plk** [comment]
That's an old MAC format file. Your diagnosis is correct. I have put in a special correction for this situation in 2.9.

**Comment by plk** [comment]
Do you have an example file?

**Comment by u-fischer** [comment]
@plk I think you commented the wrong issue. I'm not sure if "thelittleO" will see this.
