### ISSUE TITLE
default sorting option in the bibliography

### ISSUE THREAD

**Issue by govoni** [plk/biber#194]
Dear Biber authors,

in the effort of keeping my tools up-to-date I switched to Biber to handle the bibliography of my works. Unfortunately, I got the unpleasant surprise that one the very nice feature for the common user is somehow very hard to reproduce with my setup.
In fact, I was used to Latex sorting the reference list such that its order follows the one of the citations in the text.
What a disappointment to discover that it's not the case any longer, and that I am browsing the internet since quite a while to understand how to reproduce such a simple thing!

May I suggest you to have this as a default for Biber?

Best regards.

**Comment by plk** [comment]
It's best to ask such questions on tex.stackexchange.com. Since biber is a backend for biblatex, biber obeys the defaults for biblatex and the default sorting is the `nty` (Name, Title, Year). If you want citation order, simply specify `sorting=none` as a package option to biblatex:

```
\usepackage[sorting=none]{biblatex}
```

**Comment by govoni** [comment]
thanks for your precious feedback!
