### ISSUE TITLE
“\textasciitilde” wrongly mapped to “~”

### ISSUE THREAD

**Issue by njbart** [plk/biber#195]
MWE:

```
\documentclass{article}
\usepackage[style=authoryear]{biblatex}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@BOOK{item1,
  TITLE      = {This is a Tilde: \textasciitilde},
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\cite{item1}
\printbibliography
\end{document}
```

Output:

![screen shot 2017-11-25 at 17 15 07](https://user-images.githubusercontent.com/2765811/33232335-63c33c9e-d1fc-11e7-9b76-99482a029e0f.png)

The `.bbl` file contains `\field{title}{This is a Tilde: ~}` – so biber seems to wrongly map “\textasciitilde” to “~”

**Comment by plk** [comment]
Was a missing entry in the default recode map. Fixed in dev branch.
