### ISSUE TITLE
Bug with non breaking space in name

### ISSUE THREAD

**Issue by maieul** [plk/biber#196]
Hi, 

with biblatex 3.9 and biber 2.9.

Consider this MWE
```latex

\documentclass{article}
\usepackage{filecontents}
\usepackage{biblatex}
\begin{filecontents}{\jobname.bib}
@book{Richard857,
	Address = {Bruxelles},
	Author = {Franchi de' Cavalieri, Pio Petro},
	Publisher = {Société des Bollandistes},
	Title = {Catalogus codicum hagiographicorum graecorum Bibliothecae Vaticanae},
	Year = {1899}}

@book{Richard857bis,
	Address = {Bruxelles},
	Author = {Franchi de'~Cavalieri, Pio Petro},
	Publisher = {Société des Bollandistes},
	Title = {Catalogus codicum hagiographicorum graecorum Bibliothecae Vaticanae},
	Year = {1899}}

\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

The only difference between the entries is the `~` in the authorfield.

In the bbl file, we get for `Richard857`

````latex
           family={Franchi\bibnamedelimb de'\bibnamedelima Cavalieri},
````

and for Richard857bis

````latex
           family={Franchi\bibnamedelima de'\bibnamedelima Cavalieri},
````

In the last case, if I well understood the handbook, we should have get 

````latex
           family={Franchi\bibnamedelimb de'\bibnamedelima Cavalieri},
````

More generally, I know that there is ````\setcounter{highnamepenalty}{100000}````  to avoid breaking space for  `\bibnamedelima`. But I think that if someone add expressly a `~`  in a name part in the `.bib`  file, that should take account automaticcaly by biber/biblatex.

**Comment by plk** [comment]
Hmm, I'm not sure I want to fix such really specific things - it can be fixed by just not using ties or by using the alternative name format with biber.

**Comment by maieul** [comment]
Maybe the bug is linked to an other one?

**Comment by plk** [comment]
Hmm, isn't this correct since `\bibnamedelima` should come between the last elements and `de' Cavalieri` is the surname. @moewe - what do you think?

**Comment by moewew** [comment]
I think it is OK that Biber normalises `~` in fields to spaces in name fields. But if there is real and legitimate demand to retain `~` then that might need to be honoured. In name fields I don't see this as necessary.

Related for `page` fields https://tex.stackexchange.com/q/350255/35864

**Comment by plk** [comment]
I think we can close this? Names are special fields which must be parsed into components and internal spaces are not so important there.
