### ISSUE TITLE
Month macros only recognised in first bib file

### ISSUE THREAD

**Issue by moewew** [plk/biber#199]
Consider the following MWE
```
\documentclass{article}
\usepackage{biblatex}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@inproceedings{foo,
  author       = {Foo},
  title        = {Foo},
  booktitle    = {Foo},
  year         = {2017},
  month = jan,
}
\end{filecontents}

\addbibresource{biblatex-examples.bib}
\addbibresource{\jobname.bib}

\begin{document}
\cite{foo}
\printbibliography
\end{document}
```

With `biblatex` 3.9/Biber 2.9 I get the warning
```
Utils.pm:169> WARN - BibTeX subsystem: C:\Users\Moritz\AppData\Local\Temp\z858WUEh1k\gleaseflest.bib_2484.utf8, line 10, warning: undefined macro "jan"
```
And the month is not printed.

This happens only if the `.bib` file that uses the macro is not the first file loaded with `\addbibresource`. If the two `\addbibresource` lines are switched, there is no warning.

**Comment by logological** [comment]
Works fine with Biber 2.7, so the problem was probably introduced in 2.8 or 2.9.

**Comment by plk** [comment]
Fixed in 2.10 dev version. Will upload and plan bugfix release soon.

**Comment by plk** [comment]
Please try the 2.10 dev version - should be fixed

**Comment by moewew** [comment]
The MWE works for me now.
Thank you for the quick fix.

**Comment by ambs** [comment]
in 2020, and Mint still ships 2.9 :(

**Comment by moewew** [comment]
Yeah, Ubuntu's repository TeX live that you get from `apt`/`apt-get` is basically frozen at the point of release (or a while before that) and never updated after release, so especially with LTS versions your TeX live version may end up way behind current development. (Ubuntu 18.04 seems to be especially problematic because they ship Biber 2.9, but `biblatex` 3.10 ... https://bugs.launchpad.net/ubuntu/+source/biber/+bug/1770516).

The go-to way to obtain a more up-to-date system is to  install a vanilla TeX live from TUG.org: https://tex.stackexchange.com/q/1092/35864
