### ISSUE TITLE
Biber 2.10 Dev cannot map to unicode correctly

### ISSUE THREAD

**Issue by JacobD10** [plk/biber#201]
It seems that Biber 2.10 Dev cannot map to unicode correctly.
MWE:
```
\documentclass{article}
\usepackage[backend=biber]{biblatex}
\addbibresource[location=remote]{https://www.dropbox.com/s/wo4i7lgsg2j6vlx/example_ref.bib?dl=1}		% Patents
\begin{document}
Some citation \cite{Nobody17}.
\printbibliography
\end{document}
```

Gives the error:
```
>biber document.bcf
INFO - This is Biber 2.10 (beta)
INFO - Logfile is 'document.blg'
INFO - Reading 'document.bcf'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex format file 'https://www.dropbox.com/s/wo4i7lgsg2j6vlx
/example_ref.bib?dl=1' for section 0
INFO - Data source 'https://www.dropbox.com/s/wo4i7lgsg2j6vlx/example_ref.bib?dl
=1' is a remote BibTeX data source - fetching ...
ERROR - Data file 'C:\Users\username\AppData\Local\Temp\e1c1l7SDkC\biber_remote_da
ta_source_S1wRs.bib' cannot be read in encoding 'ascii': ascii "\xC3" does not m
ap to Unicode at C:\Users\username\AppData\Local\Temp\par-6a7264303839\cache-31db2
d07df1b8932b37fa334e1cc414663b3b997\inc\lib/File/Slurper.pm line 63.

INFO - ERRORS: 1
```

**Comment by JacobD10** [comment]
Looks like this might have happened from the change from `File::Slurp` to `File::Slurper`?
When I forcefully set the encoding to `utf-8` it seems to work as expected.

**Comment by JacobD10** [comment]
Ok, I don't think this is a bug, just that `ascii` encoding is set by default now. (I guess something was different in previous versions)
Using
`\usepackage[backend=biber,bibencoding=utf8]{biblatex}`
reads the characters correctly. Silly me.

**Comment by moewew** [comment]
With pdfLaTeX UTF-8 is only used automatically if you also load `inputenc`.

@plk This change causes quite some problems for people that have non-ASCII chars in their `.bib` files. Especially those that have unused `abstract`s. See for example https://tex.stackexchange.com/q/402714/35864 Is there anything that could be done to make things for them without setting `bibencoding=utf8`?

**Comment by plk** [comment]
I’m a bit confused - is the idea that something has changed? I haven’t changed the default encoding stuff.

**Comment by moewew** [comment]
People are complaining that files that used to run don't any more (https://tex.stackexchange.com/q/402714/35864). This is because older versions were more forgiving (2.7 could apparently read `.bib` files that were UTF-8 encoded even if Biber thought they were ASCII only - whether the output was good I don't know, often the problematic characters probably resided in files that were ignored anyway). I suspect this is due to a new File::Sluper or similar.
But the problematic cases are arguably ones where there is a user error.

**Comment by JacobD10** [comment]
In the midst of narrowing this problem down, I did notice that in Biber 2.7 (and earlier versions would probably be the same) a warning was displayed that noted some characters could not be encoded in ASCII and that those characters would be recoded. I'll try find that warning ...

**Comment by JacobD10** [comment]
> INFO - This is Biber 2.7
INFO - Logfile is 'document.blg'
INFO - Reading 'document.bcf'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex format file 'https://www.dropbox.com/s/wo4i7lgsg2j6vlx/example_ref.bib?dl=1' for section 0
INFO - Data source 'https://www.dropbox.com/s/wo4i7lgsg2j6vlx/example_ref.bib?dl=1' is a remote BibTeX data source - fetching ...
INFO - Decoding LaTeX character macros into UTF-8
INFO - Found BibTeX data source 'C:\Users\username\AppData\Local\Temp\dEL8JvIgxU\biber_remote_data_source_Iu23e.bib'
INFO - Overriding locale 'en-US' defaults 'normalization = NFD' with 'normalization = prenormalized'
INFO - Overriding locale 'en-US' defaults 'variable = shifted' with 'variable = non-ignorable'
INFO - Sorting list 'nty/global/' of type 'entry' with scheme 'nty' and locale 'en-US'
INFO - No sort tailoring available for locale 'en-US'
INFO - Writing 'document.bbl' with encoding 'ascii'
**WARN - The entry 'Nobody17' has characters which cannot be encoded in 'ascii'. Recoding problematic characters into macros.**
INFO - Output to document.bbl
INFO - WARNINGS: 1
> 
> Process exited normally

**Comment by JacobD10** [comment]
So indeed, "problematic" ascii (unicode) was recoded even when utf8 wasn't explicitly specified. This is the conclusion I cam to and that I should have made more clear in my earlier comments.

**Comment by JacobD10** [comment]
> _This change causes quite some problems for people that have non-ASCII chars in their .bib files. Especially those that have unused abstracts._

For me it was because some author names use unicode characters, in particular, accented characters.

> _Is there anything that could be done to make things for them without setting bibencoding=utf8?_

Is there a solid reason why the encoding isn't utf8 by default? It seems as though that was essentially the behaviour in 2.7 and earlier, albeit, with a warning.

**Comment by plk** [comment]
Ok, it must be `File::Slurper` which is more strict about UTF-8. This isn't a bad thing per se but I see the point. The warning you notice is on output of .bbl, not input of .bcf and would still happen if it got past the input. Looking at it.

**Comment by plk** [comment]
I am inclined to leave this as the detection routines which write the `input_encoding` option in the `.bcf` seem correct to me - they only set to utf8 if `inputenc` is loaded with the `utf8` encoding. I can put a note in the changes files about this but technically perhaps I don't think it's necessarily a good thing to silently accept the wrong encoding when it's just a matter of loading `inputenc` or using a UTF-8 engine.

**Comment by moewew** [comment]
I agree that the detection routine is good.
It is a bit unfortunate that things used to work for so long without an error. But that's just how it is. The more I think about it the less I think that something sensible could or should be done.

**Comment by moewew** [comment]
Just one idea popped into my mind.
Instead of reading ASCII files as ASCII Biber could read them as UTF-8. Since UTF-8 is backwards compatible with ASCII there is no problem if the file is indeed ASCII-only. And if not, UTF-8 is probably a good guess. Biber could then emit a warning if it finds non-ASCII chars that the file is assumed to be UTF-8 now. (I'm not sure if that is possible easily.)

**Comment by plk** [comment]
Yes, that's all possible but I'm just a bit concerned about misaligning the input encoding with what is actually specified - if so, we should change the input encoding written to the `.bcf` so that it's never `ascii`.

**Comment by moewew** [comment]
But then Biber will not be able to warn people explicitly that they selected ASCII but probably want UTF-8.

**Comment by plk** [comment]
Hmm, what if they really do want ascii and want all non-ascii mapped to macros?

**Comment by moewew** [comment]
What they probably want is that the `.bib` file is read as UTF-8 and the `.bbl` is ASCII (with non-ASCII as macros).

My suggestion would have been to read the `.bib` file as UTF-8 if `bibencoding` is set to `ASCII` and then warn explicitly that Biber is guessing if it encounters non-ASCII chars. The `.bbl` encoding is always as requested by `texencoding`(?). So in this scenario with auto detection probably ASCII with macros.

**Comment by plk** [comment]
Ok, done on DEV. binaries will be up shortly.

**Comment by moewew** [comment]
Just tested and it works great so far.
Would it be possible to log an explicit warning in the `.blg` if a non-ASCII char is read that it might be garbled (because UTF-8 is assumed)? Independent of the `WARN - The entry 'Kim2013' has characters which cannot be encoded in 'ascii'. Recoding problematic characters into macros.` warnings, I mean?

**Comment by JacobD10** [comment]
So now the only use for `bibencoding=utf8` is to remove the warnings and doesn’t in fact change the encoding? Should the documentation be updated to mention this? 

And now the behaviour with the warnings is how it was prior to version 2.8.

**Comment by plk** [comment]
Well, what happens is that if bibencoding is ascii, it’s read as utf8 and a message is logged saying this. So bibencoding “ascii” just means “utf8” now.

**Comment by plk** [comment]
It will already fail on bad encodings - it's too messy to point out the problematic chars on reading.
