### ISSUE TITLE
URLRAW replaces URL (TOOL mode)

### ISSUE THREAD

**Issue by ruempel** [plk/biber#202]
Processing the following file `test.bib`
```
@BOOK{test1,
  AUTHOR = {Terrence Test},
  TITLE = {Testing is Trying and Troubling},
  YEAR = {1987},
  URL = {https://example.com},
}
```
with `biber --tool test.bib` (biber release 2.9) yields the following output:
```
@BOOK{test1,
  AUTHOR = {Test, Terrence},
  DATE = {1987},
  TITLE = {Testing is Trying and Troubling},
  URLRAW = {https://example.com},
}
```
That is, the `URLRAW` field is copied from the original `URL` field, but the result misses the new `URL` field, which should contain the encoded URL.

**Comment by plk** [comment]
Fixed on current DEV branch. `urlraw` shouldn't appear at all in bibtex output as it's an internal field only relevant to printed URLs.

**Comment by tnull** [comment]
Is there any way to circumvent this until the next stable version is released? I use the biber tool to keep my bibliography pretty in place:
```
biber --tool --outfile test.bib test.bib
```

However, with this bug, the first run converts `URL` to `URLRAW`. Then, a repeated run does not recognise the `URLRAW` field and removes it, leading to deletion of all URLs in the bib file...

**Comment by plk** [comment]
You can just download biber 2.10 dev version from sourceforge and just replace your current biber binary.
