### ISSUE TITLE
biber 2.9/2.10 beta doesn't work with files whose names contain umlauts

### ISSUE THREAD

**Issue by m-vogel** [plk/biber#203]
Other than biber 2.8 the newer versions of biber do not find bcf-files whose names contain umlauts. 

[0] Config.pm:302> INFO - This is Biber 2.10 (beta)
[0] Config.pm:305> INFO - Logfile is 'MWE-Umlaut-ä-bibliography.blg'
[26] biber-MSWIN64:313> INFO - === 
[390] Utils.pm:185> ERROR - Cannot find control file 'MWE-Umlaut-ä-bibliography.bcf'! - did you pass the "backend=biber" option to BibLaTeX?
[391] Biber.pm:114> INFO - ERRORS: 1

Attached you find two MWE that only differ in name.

[MWE-no-Umlaut-ae-bibliography.txt](https://github.com/plk/biber/files/1521425/MWE-no-Umlaut-ae-bibliography.txt)
[MWE-Umlaut-ä-bibliography.txt](https://github.com/plk/biber/files/1521426/MWE-Umlaut-a-bibliography.txt)

**Comment by plk** [comment]
I can't reproduce this with the latest 2.10 biber release - it works fine for me - can you try the latest 2.10?

**Comment by moewew** [comment]
I can reproduce the behaviour on a Windows 10 machine. On Linux (Ubuntu 17.10) things worked fine, except for a `Wide character in print at ...` message in the `.blg`.

**Comment by plk** [comment]
Do you have  MWE that reproduces even the wide char warning? I don’t see that either.

**Comment by moewew** [comment]
The widechar warning only occured in the screen output, not in the `.blg`, sorry. I should have checked that.

I can not reproduce the wide char warning with consistently, let me check that.

But the Windows behaviour can be reproduced from any sample document with `ä` in its name. Even with 2.10 (dev).

**Comment by m-vogel** [comment]
I just tried the latest 2.10 release, but the error is still there. I'm on a Windows 10 (64-bit) machine.

**Comment by plk** [comment]
Looking at it - it's almost certainly a Unicode NFC/NFD issue - filesystems aren't consistent on this between OSes.

**Comment by plk** [comment]
Please try 2.10 DEV now. Windows filesystem UTF8 handling is really terrible.

**Comment by moewew** [comment]
Biber works OK now on Windows 10.
When called with latexmk the file names don't match, but latexmk seems to have its own problems with file names...

There is another problem: If the following MWE is saved under a name with non-ASCII chars and compiled with pdfLaTeX the `.bcf` contains
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{biblatex}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@ARTICLE{Born_1926,
author = {Born, M.},
title = "{Zur Quantenmechanik der Sto{\ss}vorg{\"a}nge}",
journal = {Zeitschrift fur Physik},
 year = 1926,
month = dec,
volume = 37,
pages = {863-987},
  doi = {10.1007/BF01397477}
 }
\end{filecontents}
\addbibresource{biblatex-examples.bib}
\addbibresource{\jobname.bib}
\begin{document}
\cite{markey,Born_1926}
\end{document}
```
the `.bib` file as in `<bcf:datasource type="file" datatype="bibtex">gn\IeC {\"a}\IeC {\ss }ft\IeC {\"a}gkm\IeC {\"o}\IeC {\"u}.bib</bcf:datasource>`. Obviously Biber can't find such a file.

**Comment by plk** [comment]
What you are seeing here is a problem with `inputenc`. If you comment that out, it's fine ...I am of a mind that that people should be using a real utf-8 engine in such cases since this is to do with file/file system interfaces rather than internal biblatex encoding. There is only so much can be do with pseudo-utf-8 engines like pdftex ...

**Comment by moewew** [comment]
Yup, I guessed that `inputenc` was problematic and I assume it has been this way for quite some time. I just thought that maybe we could do something about this on the `biblatex` side, but I'm not sure.

**Comment by m-vogel** [comment]
I cannot confirm that new biber 2.10 DEV runs without problems. While a file named without an umlaut runs through the umlaut equivalent gives:

[0] Config.pm:302> INFO - This is Biber 2.10 (beta)
[0] Config.pm:305> INFO - Logfile is 'MWE-Umlaut-ä-bibliography.blg'
[30] biber-MSWIN64:313> INFO - === 
[52] Utils.pm:209> ERROR - MWE-Umlaut-ä-bibliography.bcf is malformed, last biblatex run probably failed. Deleted MWE-Umlaut-ä-bibliography.bbl
[52] Biber.pm:114> INFO - ERRORS: 1

BTW compiling with latexmk now results in:
Biber error: [60] Utils.pm:209> ERROR - MWE-Umlaut-Ã¤-bibliography.bcf is malformed, last biblatex run probably failed. Deleted MWE-Umlaut-Ã¤-bibliography.bbl

**Comment by plk** [comment]
Can you give a MWE?

**Comment by m-vogel** [comment]
I attached the test-file I'm working with...

[MWE-Umlaut-ä-bibliography.txt](https://github.com/plk/biber/files/1525044/MWE-Umlaut-a-bibliography.txt)

**Comment by moewew** [comment]
When I run your test file from the command line (latexmk does not work as mentioned above) I get 
```
INFO - This is Biber 2.10 (beta)
INFO - Logfile is 'mwe-ä.blg'
INFO - Reading 'mwe-ä.bcf'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex format file 'mwe-\IeC {\"a}.bib' for section 0
ERROR - Cannot find 'mwe-\IeC {\"a}.bib'!
INFO - ERRORS: 1
```
Did you recompile from scratch? With pdfLaTeX called from the command line as well?

The problem here is that the `.bib` file is not written to the `.bcf` correctly, so that can't work. The question is, did this ever work at all?

**Comment by m-vogel** [comment]
I copied the text of your `mwe-ä.tex` and saved it as `MWE-ä.tex`. Than I compiled it from scratch by invoking commands from command line:

`pdflatex MWE-ä` and `biber MWE-ä`

Now the `biber` run results in:

```
> [0] Config.pm:302> INFO - This is Biber 2.10 (beta)
> [0] Config.pm:305> INFO - Logfile is 'MWE-ä.blg'
> [27] biber-MSWIN64:313> INFO - === 
> [50] Biber.pm:371> INFO - Reading 'MWE-ä.bcf'
> [129] Biber.pm:857> INFO - Found 1 citekeys in bib section 0
> [141] Biber.pm:3976> INFO - Processing section 0
> [154] Biber.pm:4137> INFO - Looking for bibtex format file 'gunther.bib' for section 0
> [156] Utils.pm:209> ERROR - Data file 'gunther.bib' cannot be read in encoding 'UTF-8': Can't decode ill-formed UTF-8 octet sequence <E4> at C:\Users\Mo\AppData\Local\Temp\par-4d6f\cache-e951c233fc3c7e6104a7c71c111ac3013b0dbe11\inc\lib/File/Slurper.pm line 63.
> [158] Biber.pm:114> INFO - ERRORS: 1
```

I'm not completely sure that earlier versions of `biber` managed to compile files with umlauts in their name. But I ran into these problems after the update to `biber` 2.9 working with a file that to my memory compiled before.

**Comment by moewew** [comment]
Mhh, I don't get the
```
[156] Utils.pm:209> ERROR - Data file 'gunther.bib' cannot be read in encoding 'UTF-8': Can't decode ill-formed UTF-8 octet sequence <E4> at C:\Users\Mo\AppData\Local\Temp\par-4d6f\cache-e951c233fc3c7e6104a7c71c111ac3013b0dbe11\inc\lib/File/Slurper.pm line 63.
```
line.

Can you try the MWE again with `filecontents*` instead of `filecontents`? (I have edited it.)

**Comment by plk** [comment]
@m-vogel - are you sure you are using the latest 2.10 dev version? It has been upated several times in recent days.

**Comment by m-vogel** [comment]
@plk I used the version dated 03.12.2017 17:00 which is the newest version on the server.
@moewew I tried `filecontents*` and that did the job! 

Many Thanks!

**Comment by moewew** [comment]
Mhhh, `filecontents*` is more of a work-around than a real solution. The `filecontents` environment writes a header to the `.bib` file which `filecontents*` suppresses, that header contained an `ä`. But the file should have been written as UTF-8 (as it was on my machine), so there should not be a problem there. Weird ...

**Comment by plk** [comment]
Is there still an issue here or can we close?

**Comment by moewew** [comment]
Well, the message
```
> [156] Utils.pm:209> ERROR - Data file 'gunther.bib' cannot be read in encoding 'UTF-8': Can't decode ill-formed UTF-8 octet sequence <E4> at C:\Users\Mo\AppData\Local\Temp\par-4d6f\cache-e951c233fc3c7e6104a7c71c111ac3013b0dbe11\inc\lib/File/Slurper.pm line 63.
```
that @m-vogel got could be an issue. I can't reproduce it. But with the MWE (using unstarred `filecontents`) it should not appear, and if it does consistently that would be a problem.
The message is related to reading the `.bib` file as UTF-8 though, so it seems to be an encoding issue and not a file name issue.

Other than that I think Biber now handles non-ASCII filenames as well as one would expect.

**Comment by m-vogel** [comment]
I still get the `/Slurper.pm` message by compiling a file with an unstarred `filecontents` environment. This message does not appear with the starred version. In real life files that do not contain a filecontents environment the situation is as follows:

Compiling a file (`a.tex` or `ä.tex`) does not produce errors as long the `bib`-file has no umlauts in its name. But `\addbibresource{günther.bib}` will end up with

```
[0] Config.pm:302> INFO - This is Biber 2.10 (beta)
[0] Config.pm:305> INFO - Logfile is 'MWE-a.blg'
[30] biber-MSWIN64:313> INFO - ===
[55] Biber.pm:371> INFO - Reading 'MWE-a.bcf'
[139] Biber.pm:857> INFO - Found 1 citekeys in bib section 0
[152] Biber.pm:3976> INFO - Processing section 0
[165] Biber.pm:4137> INFO - Looking for bibtex format file 'g\IeC {\"u}nther.bib' for section 0
[527] Utils.pm:209> ERROR - Cannot find 'g\IeC {\"u}nther.bib'!
[527] Biber.pm:114> INFO - ERRORS: 1
```

(This btw is also true for compiling with `latexmk`) Since this is an intelligible error message I can live with that. In cases of `\addbibresource{\jobname.bib`} one will have to take care of the filename.

**Comment by moewew** [comment]
@m-vogel Can you check that the `.bib` file produced with an unstarred `filecontents` is really UTF-8 encoded? The one in the MWE above will contain an `ä` in the header of the `.bib`, but it should be saved as UTF-8, so Biber should have no grounds to complain.

**Comment by m-vogel** [comment]
Here are my results:

(1) `tex`-file without umlaut

	(a) bib-Filename with umlaut
		(i)  starred: `bib`-file without header, utf-8
		(ii) unstarred: `bib`-file with header, ANSI (see below (A))

	(b) bib-filename without umlaut
		(i)  starred: `bib`-file without header, utf-8
		(ii) unstarred: `bib`-file with header, utf-8

(2) `tex`-file with umlaut

	(a) bib-Filename with umlaut
		(i)  starred: bib-file without header, ANSI
		(ii) unstarred: bib-file with header, ANSI (see below (B))

	(b) bib-filename without umlaut
		(i)  starred: bib-file without header, utf-8
		(ii) unstarred: bib-file with header, ANSI (see below (B))

(A)
```
%% LaTeX2e file `g𮴨er.bib'
%% generated by the `filecontents' environment
%% from source `MWE-a' on 2017/12/06.
%%

```
(B)
```
%% LaTeX2e file `gunther.bib'
%% generated by the `filecontents' environment
%% from source `MWE-䧠on 2017/12/06.
%%
```

**Comment by moewew** [comment]
Mhhh, if the `filecontents` package is loaded the files should be properly UTF-8 encoded. Can you check that `filecontents.sty` is installed? Run the MWE with `\listfiles` added to the top.

<details>
<summary>click for MWE with <code>\listfiles</code></summary>
  <p>

```\listfiles
\documentclass[11pt]{article}
\usepackage[german]{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german=guillemets]{csquotes} % just to avoid the warning
\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
@BOOK{Millikan:LanguageThought,
  title        = {Language, Thought, and Other Biological Categories. New Foundations for Realism},
  author       = {Millikan, Ruth Garrett},
  date         = {1984},
  language     = {english},
  location     = {Cambridge MA, London},
  publisher    = {The MIT Press},
  hyphenation  = {english},
}
\end{filecontents}

\usepackage[backend=biber,style=authoryear]{biblatex}
\addbibresource{jobname.bib}

\begin{document}
Some Text, with a reference: See \cite{Millikan:LanguageThought}.
\end{document}
```
</p></detail>

You should see
```
filecontents.sty    2011/10/08 v1.3 Create an external file from within a LaTeX
```
or similar in the `.log` file. If there is no line about `filecontents` the problem is probably due to not loading that package. Only with the `filecontents` package are UTF-8 files written out as such. The examples you show make me suspect this is only an issue of the `.bib` file encoding.

**Comment by m-vogel** [comment]
Compiling the MWE with \listfiles writes

`filecontents.sty    2011/10/08 v1.3 Create an external file from within a LaTeX document`

into the `log` file. I'm using TexLive 2017 with all updates installed.

I hope that the results of my tests are not confusing. The information whether a file is ANSI or utf-8 came from the status line of Notepad++, an editor that has been pretty reliable in that respect in the past.

**Comment by moewew** [comment]
OK, thanks for checking that.
Maybe I was wrong in thinking that `filcontents` writes in the correct encoding when the `filecontents` package is loaded. Anyway, this is definitely not a Biber problem. If the files are encoded correctly, Biber reads them correctly.
