### ISSUE TITLE
Test failures due to different Unicode::Collate versions

### ISSUE THREAD

**Issue by lorem-ipsum** [plk/biber#207]
As already discussed in #149 different versions of Unicode::Collate cause the tests to fail. This is a problem for packaging (I package biber & biblatex for Gentoo) as tests which previously work might fail as soon as people upgrade to newer versions of Unicode::Collate. As an example the tests for biber 2.7 were fine when it was new, but fail now with U::C 1.21.

You mentioned these test failures can be ignored. Would it be possible to change the build system to ignore these failures?

**Comment by plk** [comment]
This is really difficult as U::C is so integral to biber, its impact is not isolated to specifix places or tests.

**Comment by perstar** [comment]
Then maybe biber should pack its own version of Unicode::Collate and use that one? It's unfortunate when the same LaTeX file with the same versions of classes and packages can produce different output. Can that happen now when a future version of Unicode::Collate changes the default UCA_Version?

**Comment by lorem-ipsum** [comment]
Mhm. Would it be possible to add some labels with which versions the tests are expected to pass? Currently the system only complains about too old versions, but not about recent versions.

Please don't bundle any libraries, it makes packaging only more difficult as I would have to remove them for system wide installation.

**Comment by plk** [comment]
It is usually when the default UCA changes (as with 1.21) since this changes all collation keys which is directly reflected in most tests due to the hashes generated from sorting. It impacts many tests and I can’t really see a way around this other than running just an end to end test that produces a PDF without check intermediary .

**Comment by lorem-ipsum** [comment]
Okay. If it only occurs on some versions changes of U::C  it should not be to bad.
Could you check the UCA against the expected setting and issue a warning if they differ?

**Comment by lorem-ipsum** [comment]
Okay. If it only occurs on some versions changes of U::C  it should not be to bad.
Could you check the UCA against the expected setting and issue a warning if they differ?
