### ISSUE TITLE
LaTeX Error: Missing \begin{document}., l.3776   australian,newzealand}

### ISSUE THREAD

**Issue by nschloe** [plk/biber#209]
Since upgrading my LaTeX installation earlier today, running `lualatex` on
```latex
\documentclass{article}

\usepackage{biblatex}

\begin{document}
\end{document}
```
gives
```
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.3776   australian,newzealand}
```
The error occurs when biblatex is used.

**Comment by moewew** [comment]
Not our fault https://tex.stackexchange.com/questions/413898/biblatex-broken-overnight, https://github.com/josephwright/etoolbox/issues/19.

This is an issue in `etoolbox` that has been fixed already. The fixed version is on CTAN, but will take a few hours (days?) to arrive in TeX live and MikTeX.

**Comment by nschloe** [comment]
Alright, thanks for the swift reply.
