### ISSUE TITLE
Unknown fields in biber tool mode

### ISSUE THREAD

**Issue by gusbrs** [plk/biber#211]
From https://tex.stackexchange.com/q/415007/105447

Consider the following `biber-tool.conf`:

```
<?xml version="1.0" encoding="UTF-8"?>
<config>
	<output_fieldcase>lower</output_fieldcase>
	<output_indent>2</output_indent>
	<output_align>true</output_align>
	<sourcemap>
		<maps datatype="bibtex" map_overwrite="1">
			<map map_overwrite="1">
				<map_step map_field_set="abstract" map_null="1"/>
				<map_step map_field_set="review" map_null="1"/>
				<map_step map_field_set="group" map_null="1"/>
				<map_step map_field_set="file" map_null="1"/>
			</map>
		</maps>
	</sourcemap>
</config>
```

and the following bibfile:

```
 @Thesis{Author_18_TheThesis,
  author      = {Mr Author},
  title       = {The Thesis},
  type        = {Doctoral Dissertation},
  institution = {Department of Documents, University of Stackexchange},
  year        = {2018},
  abstract    = {This is the abstract.},
  file        = {:author/Author_18_TheThesis.pdf:PDF},
  review      = {This is the review.},
  groups      = {publications},
  ispreprintpublic = {test},
}
```

The use of biber's tool mode with these settings will not only clear the fields specified in the sourcemap, but also silently drop the field `ispreprintpublic` which is unknown to the datamodel.

I'm not sure what's possible here, and I'm not sure if it is desirable for biber to keep fields out of the data model. But that it does it silently and undocumented is unfortunate.

I'd say one or more of the following would be welcome (in the following order of desirability, from an user's point of view):

1 - that biber does not drop the field.
2 - that if it must do so, it issues a warning.
3 - or that this behavior is described in the documentation.

**Update**: I stand corrected and it is documented in the "Important changes" section for version 2.6. From what is written there, I understand this behavior is by design. So my request boils down for a clearer statement of this behavior in the section dealing with tool mode. Sorry for the fuss.

**Comment by plk** [comment]
This is indeed reported if you use the `--validate-datamodel` option. The warnings don't appear by default by user request because this was making the output on messy data files too noisy.
