### ISSUE TITLE
biblatex release for 2.11 ?

### ISSUE THREAD

**Issue by zarniwhoop73** [plk/biber#213]
Can we have a release of the matching biblatex-3.11 tds, please ?

**Comment by plk** [comment]
Nothing should be released for biblatex 3.11/biber 2.11 yet as SOurceforge has upload issues which are blocking the release currently.

**Comment by zarniwhoop73** [comment]
On Sat, Feb 17, 2018 at 09:56:52AM +0000, plk wrote:
>    Nothing should be released for biblatex 3.11/biber 2.11 yet as SOurceforge
>    has upload issues which are blocking the release currently.
> 
Thanks.  I saw some of sourceforge was back, will wait until normal
service is resumed.

-- 
Truth, in front of her huge walk-in wardrobe, selected black leather
boots with stiletto heels for such a barefaced truth.
                                     - Unseen Academicals
