### ISSUE TITLE
Can't locate Biber.pm in @INC

### ISSUE THREAD

**Issue by nise** [plk/biber#214]
Installing biber on Ubuntu 16:04 is a painful endeavor since Perl upgrades are necessary. I know it is a problem of Ubuntu, but compatibility should a priority. Finally, I ended Up with this error:

> biber -v
> Can't locate Biber.pm in @INC (you may need to install the Biber module) (@INC contains: /usr/local/lib/perl5/site_perl/5.24.1/x86_64-linux-thread-multi /usr/local/lib/perl5/site_perl/5.24.1 /usr/local/lib/perl5/5.24.1/x86_64-linux-thread-multi /usr/local/lib/perl5/5.24.1 .) at /usr/bin/biber line 17.
> BEGIN failed--compilation aborted at /usr/bin/biber line 17.

Where can I finde Biber.pm? Is it a perl module that should be installed via cpan?

**Comment by plk** [comment]
This means you haven't done `Build install` in the biber source dir. `Biber.pm` is part of biber itself.

**Comment by nise** [comment]
Yes, this is the problem. The `Build install` command does not move the `bin` folder to the specified location. After copying the folder manually it worked. 

Unfortunately I needed to work with biber 2.4 because of dependency of latex package. So the described bug might have been fixed already.

**Comment by nise** [comment]
First I have upgraded my system perl installation (ubuntu). Then I realized that it destroys the whole `deb.conf` and `apt` environment. After downgrading to` perl 5.22` I was able to build `biber 2.6` with `perl 5.22`. When executing the binary it still required `perl 5.24`

Is there a way to tell `biber` a specific perl path (e.g. `/opt/perl`) as in the `Build` file?

**Comment by nise** [comment]
Sorry for commenting all my debuggin steps, but I ended up by changing the perl path in the installation folder (bin/biber) from /usr/bin/perl to /opt/perl
Then I copied the local biber script to /usr/bin/biber

**Comment by plk** [comment]
biber will use the perl tree which is first used to run the `Build.PL` e.g. if you first do:

`/opt/perl/bin/perl Build.PL`

then biber will install to that perl tree. If you are trying this several times, you should run `Build realclean` to reset the state before creating the `Build` file again with the above command.

**Comment by a2975667** [comment]
I had the same issue but I installed biber via apt-get install biber.
Do I need to install it from source?

**Comment by tueda** [comment]
If I look into `/usr/bin/biber` installed by `apt get` on Ubuntu 20.04, the first line is
```perl
#!/usr/bin/env perl
```
which comes from `bin/biber` in this repository, I guess:

https://github.com/plk/biber/blob/d1f707085c274d40eb4822e22a8a1d088739c7f5/bin/biber#L1

This can be a headache because `/usr/bin/env perl` may invoke a wrong `perl` and easily cause the `Can't locate Biber.pm in @INC` error. Maybe `Build.PL` can rewrite the shebang line to specify the correct `perl` to be used.

**Comment by plk** [comment]
Well, how can an installer know which perl is the right one to use on an arbitrary system? That line is quite good cross-platform and can be fixed easily by just setting your `PATH` correctly.

**Comment by tueda** [comment]
Could it be `perl` used in the build (which must be able to access to `Biber.pm`)? I am not sure how Ubuntu or other distributions are made and maybe it needs some consideration.

It is difficult to arrange `PATH` for `/usr/bin/env perl` in such a way that `biber` expects it must be `/usr/bin/perl` while another app (which also uses `/usr/bin/env perl` in the shebang line) expects `perl` in another place (though I could arrange `PERL5LIB` to use both perl trees, praying no confliction occurs).

**Comment by tueda** [comment]
> (though I could arrange PERL5LIB to use both perl trees, praying no confliction occurs).

Indeed, I got a version conflict (Ubuntu 20.04 vs. Linuxbrew)
```
MoreUtils.c: loadable library and perl binaries are mismatched (got handshake key 0xcd00080, needed 0xed00080)
```
so I have settled on a workaround: `/usr/bin/perl /usr/bin/biber`, which can be aliased or wrapped in a shell script.
