### ISSUE TITLE
Regression: unmatched brace in bbl output when using {\relax{}Th} construct

### ISSUE THREAD

**Issue by cedb12** [plk/biber#215]
Using the construct `{\relax{}Th}omas` to abbreviate Thomas as 'Th.' instead of 'T.', as suggested in [this StackExchange answer](https://tex.stackexchange.com/a/26347), worked in biber 2.10 but not anymore in 2.11. An extra closing brace appears in the `.bbl` file after the `\name` part of the entry.

I am using biblatex 3.10

Minimal working example:
```latex
\documentclass{article}
\usepackage{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@ARTICLE{testarticle,
  author = {Author, {\relax{}Th}omas},
  title = {Title},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
\cite{testarticle}
\end{document}
```

Resulting `.bbl` file:
```tex
% $ biblatex auxiliary file $
% $ biblatex bbl format version 2.9 $
% Do not modify the above lines!
%
% This is an auxiliary file used by the 'biblatex' package.
% This file may safely be deleted. It will be recreated by
% biber as required.
%
\begingroup
\makeatletter
\@ifundefined{ver@biblatex.sty}
  {\@latex@error
     {Missing 'biblatex' package}
     {The bibliography requires the 'biblatex' package.}
      \aftergroup\endinput}
  {}
\endgroup


\refsection{0}
  \datalist[entry]{nty/global//global/global}
    \entry{testarticle}{article}{}
      \name{author}{1}{}{%
        {{hash=49295f9379fe6ac30dfbe71b278e8298}{%
           family={Author},
           familyi={A\bibinitperiod},
           given={{\relax{}Th}omas},
           giveni={\relax{}Th}\bibinitperiod}}}%
      }
      \strng{namehash}{49295f9379fe6ac30dfbe71b278e8298}
      \strng{fullhash}{49295f9379fe6ac30dfbe71b278e8298}
      \strng{bibnamehash}{49295f9379fe6ac30dfbe71b278e8298}
      \strng{authorbibnamehash}{49295f9379fe6ac30dfbe71b278e8298}
      \strng{authornamehash}{49295f9379fe6ac30dfbe71b278e8298}
      \strng{authorfullhash}{49295f9379fe6ac30dfbe71b278e8298}
      \field{sortinit}{A}
      \field{sortinithash}{3248043b5fe8d0a34dab5ab6b8d4309b}
      \field{labelnamesource}{author}
      \field{labeltitlesource}{title}
      \field{title}{Title}
    \endentry
  \enddatalist
\endrefsection
\endinput
```

**Comment by plk** [comment]
These sorts of cases are just too tricky to deal with due to the UTF-8/macro mapping code. If you want a specific initial for a name and you are using biber, it’s best to use the extended name format which biber supports.

**Comment by cedb12** [comment]
Thank you for bringing the extended name format to my attention, which solves my use case! It is still a bit unfortunate that the extended format is not compatible with BibTeX, but that is not an issue for me.

Here is the fixed MWE, for the record:
```latex
\documentclass{article}
\usepackage{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@ARTICLE{testarticle,
  author = {family=Author, given=Thomas, given-i={Th}},
  title = {Title},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
\cite{testarticle}
\end{document}
```

**Comment by moewew** [comment]
I think the thing that broke this was the fix for https://github.com/plk/biber/issues/210 (https://github.com/plk/biber/commit/078ed12fcaf790ddc28435126d4f08adb820c197). It seems you can't keep anybody happy with the amount of braces stripped or not stripped from a (name) field. But maybe we should approach this systematically (listing the possible useful input and expected output) once we have time and try to find out if there is a way to keep most people happy.

**Comment by plk** [comment]
It’s an impossible task, to syntactically account for every macro in a field. Pushing UTF-8 is the best policy apart froms cases which just can’t do this (maths, for example)

**Comment by vvavrychuk** [comment]
@plk I am not very advanced in LaTeX but I thought that the ability of LaTeX to express diacritic like accent or umlaut with simple ASCII is an advantage. Therefore it sounds sad if it diverges from that.
