### ISSUE TITLE
@strings not resolved

### ISSUE THREAD

**Issue by moewew** [plk/biber#218]
Via https://tex.stackexchange.com/q/420103/35864

In the following MWE `@string`s are not resolved and so the journal is missing in the output
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article{steendam,
  author   = {H. Steendam and T. Q. Wang and J. Armstrong},
  title    = {Theoretical Lower Bound for Indoor Visible Light Positioning Using Received Signal Strength Measurements and an Aperture-Based Receiver},
  journal  = IEEE_J_JLT,
  date     = {2017-01},
  volume   = {35},
  number   = {2},
  pages    = {309-319},
  doi      = {10.1109/JLT.2016.2645603},
}
\end{filecontents}
\begin{filecontents}{myIEEEfull.bib}
@string{IEEE_J_JLT = {Journal of Lightwave Technology}}
\end{filecontents}

\addbibresource{\jobname.bib}
\addbibresource{myIEEEfull.bib}

\begin{document}
\cite{steendam}
\printbibliography
\end{document}
```

Things work as expected again if we use a different order for the `.bib` instead
```latex
\addbibresource{myIEEEfull.bib}
\addbibresource{\jobname.bib}
```

I'm using Biber 2.11.

This is similar to #204 where you can get the same effect if you use `\bibliography{\jobname, abbrv2, abbrv3}` instead of `\bibliography{abbrv2, abbrv3, \jobname}`

**Comment by plk** [comment]
Well, a string has to be defined before it’s used ...

**Comment by moewew** [comment]
Yes that makes sense. When I had sent this out I realised that a solution would probably entail having to read files twice that's probably undesirable...

**Comment by moewew** [comment]
It would be nice if order did not matter. But please feel free to close this if you don't think it is worth investigating. The trade-off is quite likely not worth it...

**Comment by plk** [comment]
The complication in doing this isn’t worth it I think.
