### ISSUE TITLE
Converts "{\textasciicircum}" to "{^}"

### ISSUE THREAD

**Issue by tomaquek** [plk/biber#219]
On a .bib entry containing "{\textasciicircum}", biber outputs a .bbl entry containing "{^}". For instance the .bib entry:
```
@article{isles_what_1992,
 title = {What evidence is there that 2{\textasciicircum}65536 is a natural number?},
 journal = {Notre Dame Journal of Formal Logic},
 author = {Isles, David}
}
```
leads to a .bbl entry containing:
```
  \field{labeltitlesource}{title}
  \field{journaltitle}{Notre Dame Journal of Formal Logic}
  \field{title}{What evidence is there that 2{^}65536 is a natural number?}
```
which leads to BibLaTeX throwing a series of "Missing $ inserted", "Missing { inserted", "Missing $ inserted" etc errors. This is described in a tex.stackexchange question [here](https://tex.stackexchange.com/questions/420150/biber-textasciicircum-error?noredirect=1#comment1051639_420150), where commentors advised posting this as an issue here (I don't know biber well enough to know whether this is unintended).

The behaviour only occurs when "\textasciicircum" is placed within braces, as "{\textasciicircum}", which is how Zotero outputs it.

**Comment by plk** [comment]
Fixed in 2.12 DEV.
