### ISSUE TITLE
Parse error in cite_key with long alphanumeric keys 

### ISSUE THREAD

**Issue by wahspilihp** [plk/biber#224]
There appears to be a bug parsing keys with very long hex-like strings in them: if it matches [0-9a-fA-F]{32} those characters appear to be removed.

This happens in version 2.7, which is the version in my TexLive installation, though I haven't tried in a later version.

(As for why I want an ugly key like that - I was trying to use the MatWeb GUID in my cite key.)
[MatWeb_problem_demo_bibertool.bib.txt](https://github.com/plk/biber/files/1949413/MatWeb_problem_demo_bibertool.bib.txt)
[MatWeb_problem_demo.bib.txt](https://github.com/plk/biber/files/1949414/MatWeb_problem_demo.bib.txt)

**Comment by moewew** [comment]
I can not reproduce the problem with Biber 2.11 (the current release) if I just run Biber in `--tool` mode on your `.bib` file.

I assume you ran Biber in `--tool` mode? Does the problem occur with all `--configfiles` you tried or only specific ones? Can you describe in more detail what exactly you did?

**Comment by wahspilihp** [comment]
It worked for me too in 2.11. 

Having done some digging through the changelogs, it appears the characters were being mistaken for a verbatim field marker by `$text =~ s/([a-f0-9]{32})/$saveverb->{$1}/gie;` in Recode.pm
which has since been deleted.

I was using the default configuration installed with macports.
