### ISSUE TITLE
\dots wrapped in math mode

### ISSUE THREAD

**Issue by moewew** [plk/biber#225]
Via https://tex.stackexchange.com/q/431932/35864

Consider the following MWE
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber, texencoding=ascii]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@Article{DeDeVa00a,
  author    = {Lieven {De Lathauwer} and Bart {De Moor} and Joos Vandewalle},
  doi       = {10.1137/S0895479898346995},
  journal   = {SIAM Journal on Matrix Analysis and Applications},
  number    = {4},
  title     = {On the Best Rank-1 and Rank-{$(R_1, R_2, \dots, R_N)$} Approximation of Higher-order Tensors},
  volume    = {21},
  year      = {2000},
  pages     = {1324-1342},
}
\end{filecontents}

\addbibresource{\jobname.bib}


\begin{document}
\cite{DeDeVa00a}
\printbibliography
\end{document}
```

Note the `texencoding=ascii` to make sure that the `.bbl` is written as ASCII and not as UTF-8 where the `\dots` is translated into the UTF-8 character `…` (I happen to find this unfortunate as well and would much prefer if `\dots` were left untouched, but this is not the main point of concern here)

The `.bbl` produced by Biber reads
```
\field{title}{On the Best Rank-1 and Rank-{$(R_1, R_2, {$\dots$}, R_N)$} Approximation of Higher-order Tensors}
```
I.e. the `\dots` is incorrectly wrapped in `{$` and `$}`. This throws up the math processing quite a bit here.

**Comment by plk** [comment]
Please try the DEV versions of biblatex and biber. `\dots` is no longer decoded/encoded.

**Comment by moewew** [comment]
Works good. Thank you.
