### ISSUE TITLE
Line numbers for encoding errors?

### ISSUE THREAD

**Issue by moewew** [plk/biber#226]
When Biber encounters a file with bad encoding, currently the error is similar to
```
[202] Utils.pm:209> ERROR - Data file 'fghjk.bib' cannot be read in encoding 'UTF-8': Can't decode ill-formed UTF-8 octet sequence <F6> at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-9d6b46fefde4bd584f892f8159e8daefd64788a3\inc\lib/File/Slurper.pm line 63.
``` 
Would be it be possible to make the error message point to the line number in the `.bib` file? (Maybe by reading the file line by line if the module does not support line numbers. If there are performance impacts maybe that could be solved by catching that error and reading the file again line by line to isolate the problematic line.) That would make it much easier for users to spot the problematic character.

MWE (saved in `latin1`)
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[latin1]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber, bibencoding=utf8]{biblatex}


\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {Röstaroma Schloß €úrô},
  date    = {1980},
}
\end{filecontents}

\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,appleby}
\printbibliography
\end{document}
```

**Comment by plk** [comment]
It's a pain to do for what seems to be a minor gain ...

**Comment by plk** [comment]
I think it's hardly worth it. I'm using a fast library for reading whole files at once which means there are no "lines" that it really recognises. Switching to a line-based library would be slower for very little gain.

**Comment by kiryph** [comment]
@plk I would like to use `biber -V` as a linter tool in my text editor.

If I understand you correctly, there is no possibility that biber could add line numbers to the messages.

This would increase the speed people fix bibfile issues which I consider is a good enough gain. There is a reason why vim has a *quick*fix list and similar functionality exists in most text editors.

Right now I have 50 warnings returned by biber, going through them takes some time. I would like to step through them within vim which is not possible without line numbers.

What about having a switch to enable line numbers with the warning that biber becomes slower?
