### ISSUE TITLE
Segfault: error 139

### ISSUE THREAD

**Issue by svenper** [plk/biber#227]
My guess is that this is because of perl module updates, but the error is very sparse in information.

On a known working document:

```
$ perl -d /usr/bin/biber --debug main

Loading DB routines from perl5db.pl version 1.51
Editor support available.

Enter h or 'h h' for help, or 'man perldebug' for more help.

main::(/usr/bin/biber:24):      my $opts = {};
  DB<1> r
INFO - This is Biber 2.11
INFO - Logfile is 'main.blg'
INFO - DEBUG mode: all messages are logged to 'main.blg'
Signal SEGV at (eval 362)[/usr/bin/biber:357] line 1.
        eval 'require Biber::Output::bbl' called at /usr/bin/biber line 357
zsh: abort      perl -d /usr/bin/biber --debug main
perl -d /usr/bin/biber --debug main  0.97s user 0.06s system 57% cpu 1.781 total
```

**Comment by plk** [comment]
Which OS and version? Binary biber or raw perl script version and if the latter, which version of perl?

**Comment by svenper** [comment]
I have the raw perl script version, sorry I forgot to mention.

perl v5.26.1
linux 4.16.12 (void linux)
musl libc 1.1.19

**Comment by svenper** [comment]
If it’s any use the perl module versions [are here also](https://gist.github.com/svenper/d2bf1d05684a24da28142e041e4ea3b9/raw/dca77da0785a6dd37daf56e64e660cc019cf70cd/perl-modules)

**Comment by svenper** [comment]
It appears it was caused by [a small distro patch of `Time::HiRes`][1].

[1]: https://github.com/voidlinux/void-packages/commit/ce6a59df4d87497d981eecbd4271eb33211ef63c
