### ISSUE TITLE
uniquename with baseless template: unqiuepart still shows "base"

### ISSUE THREAD

**Issue by moewew** [plk/biber#234]
Consider the following MWE
```latex
\documentclass{article}

\begin{filecontents*}{corp.dbx}
\DeclareDatamodelConstant[type=list]{nameparts}{prefix,family,suffix,given,long,short}
\end{filecontents*}

\usepackage[style=authoryear,citecounter,citetracker,datamodel=corp]{biblatex}

\DeclareSortingNamekeyTemplate[corp]{
  \keypart{
    \namepart{long}
  }
}

\DeclareUniquenameTemplate[corp]{
  \namepart{short}
  \namepart{long}
}

\DeclareNameFormat{sortname}{\thefield{uniquepart}}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{SCA,
  author = {long={Some Corporate Author}, short={SCA}, nametemplates=corp},
  title = {Title},
  location = {Location},
  publisher = {Publisher},
  date = {2018}
}
@book{ACA,
  author = {long={Another Corporate Author}, short={ACA}, nametemplates=corp},
  title = {Title},
  location = {Location},
  publisher = {Publisher},
  date = {2018}
}

\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\parencite{SCA,ACA}
\printbibliography
\end{document}
```
with a uniquename template that has no base part.

With those two entries the output is as expected

> short (2018). Title. Location: Publisher.
> short (2018). Title. Location: Publisher.

and in the `.bbl` we find

```
    \entry{ACA}{book}{}
      \name{author}{1}{}{%
        {{uniquename=1,uniquepart=short,labelalphanametemplatename=corp,sortingnamekeytemplatename=corp,uniquenametemplatename=corp,hash=b538d361e4472c86dfbc4fb33dfdd878}{%
           long={Another\bibnamedelimb Corporate\bibnamedelimb Author},
           longi={A\bibinitperiod},
           longun=0,
           short={ACA},
           shorti={A\bibinitperiod},
           shortun=1}}%
      }

    \entry{SCA}{book}{}
      \name{author}{1}{}{%
        {{uniquename=1,uniquepart=short,labelalphanametemplatename=corp,sortingnamekeytemplatename=corp,uniquenametemplatename=corp,hash=6077400f9809af4e1e56d39c3b488988}{%
           long={Some\bibnamedelimb Corporate\bibnamedelimb Author},
           longi={S\bibinitperiod},
           longun=0,
           short={SCA},
           shorti={S\bibinitperiod},
           shortun=1}}%
      }
```

But if we only cite one of the two entries, the output is

> base (2018). Title. Location: Publisher.

and the `.bbl` shows

```
    \entry{SCA}{book}{}
      \name{author}{1}{}{%
        {{uniquename=0,uniquepart=base,labelalphanametemplatename=corp,sortingnamekeytemplatename=corp,uniquenametemplatename=corp,hash=6077400f9809af4e1e56d39c3b488988}{%
           long={Some\bibnamedelimb Corporate\bibnamedelimb Author},
           longi={S\bibinitperiod},
           longun=0,
           short={SCA},
           shorti={S\bibinitperiod},
           shortun=0}}%
      }
```

It seems that if the name is unique without a doubt that Biber just says `uniquename=base` even if the template has no base setting.

**Comment by plk** [comment]
Does this actually cause a problem or are you just noticing this in the `.bbl`? I think there has to be at least one `base` component otherwise there is nothing to disambiguate from.

**Comment by wahspilihp** [comment]
The problem appears when doing customised handling of the names in different citations, as in [this stackexchange answer](https://tex.stackexchange.com/questions/449052/biblatex-long-author-names-in-first-citation-followed-by-shortnames-thereafter/449082#449082). 

It isn't too hard to work around, and there may be a better solution to that problem anyway, but it does have a practical effect.

**Comment by moewew** [comment]
Indeed in https://tex.stackexchange.com/a/449082/35864 I used a `base`-less name format (the MWE here is just a simplified version that shows the undesired behaviour with less code). The idea being that we have *either* `short` *or* `long`, but never both. A scheme with `base` on the other hand always shows the base and only adds other name parts on top.

I naively thought it might be possible to simply turn `short` into `base` here, but my ideas did not work here since not all names are supposed to have a `short` part. Some acronyms only have a `long` form.

**Comment by plk** [comment]
So, what would the desired behaviour be? `uniquepart=?` in sich a baseless case?

**Comment by moewew** [comment]
I'd have expected `short` in the example, i.e. the first `namepart` in the `\DeclareUniquenameTemplate` list.

**Comment by plk** [comment]
Does that MWE work for you? It gives me an error with `\namepartfamily`. Probably a minor cut/paste thing but I don't have time to diagnose.

**Comment by moewew** [comment]
Works with 3.11, but does not work with 3.12 `dev`. I'll have a look - not sure if I can manage to find the issue today, though.

**Comment by moewew** [comment]
Ah OK, here is a fix that makes the MWE work without error.

```
\documentclass{article}

\begin{filecontents*}{corp.dbx}
\DeclareDatamodelConstant[type=list]{nameparts}{prefix,family,suffix,given,long,short}
\end{filecontents*}

\usepackage[style=authoryear,citecounter,citetracker,datamodel=corp]{biblatex}

\DeclareSortingNamekeyTemplate[corp]{
  \keypart{
    \namepart{long}
  }
}

\DeclareUniquenameTemplate[corp]{
  \namepart{short}
  \namepart{long}
}

\DeclareNameFormat{labelname}{\thefield{uniquepart}}
\DeclareNameFormat{sortname}{\thefield{uniquepart}}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{SCA,
  author = {long={Some Corporate Author}, short={SCA}, nametemplates=corp},
  title = {Title},
  location = {Location},
  publisher = {Publisher},
  date = {2018}
}
@book{ACA,
  author = {long={Another Corporate Author}, short={ACA}, nametemplates=corp},
  title = {Title},
  location = {Location},
  publisher = {Publisher},
  date = {2018}
}

\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\parencite{SCA,ACA}
\printbibliography
\end{document}
```

I'll still have to figure out what changed, though...

**Comment by plk** [comment]
Ok, try DEV biber again.

**Comment by moewew** [comment]
Works great so far.

I found the cause of the `\namepartfamily` error: It's https://github.com/plk/biblatex/pull/731. I not only introduced name grouping, I also removed the then pretty much pointless (or so I thought) name initialisation. That means that all `\namepart...`s are now undefined and not `\@empty`. For the most part that does not matter since we guard against *void* (undefined, `\relax` *or* empty) name parts in the name formats. But `\namepartfamily` is normally assumed to exist without a test. In the MWE it did not exist and so we get the error. In normal situations that error should not come up since `\namepartfamily` will always have some value.

I actually like it that calling undefined name formats gives an error now instead of silently outputting nothing and prefer the conceptual behaviour of undefined name parts over empty ones. Plus it saves the loop. But I could also see that there is a slight chance this causes backwards compatibility issues for people who do weird stuff and don't guard against it properly and for people who against all advice use `\ifdefempty` instead of `\ifdefvoid` in the name formatting directives.

I have a fix ready in https://github.com/plk/biblatex/compare/dev...moewew:blanknameparts to address this, but I'd like to hear your opinion whether or not the old behaviour should be brought back.

**Comment by plk** [comment]
I don't mind either way if there is a commit ready to fix it anyway. I can see the value in in the error.

**Comment by moewew** [comment]
OK I think I will not add the commit this to `dev` now, but I will keep it in the back of my head in case bug reports flood in after an update. We can then easily push out an update.

If you can find the time I'd appreciate if you could have a look at a few Biber-related issues at the `biblatex` bugtracker: https://github.com/plk/biblatex/issues/805, https://github.com/plk/biblatex/issues/738, https://github.com/plk/biblatex/issues/697

I have also not yet merged all pull requests because some of them are about 'policy' or could have a greater impact than I initially thought, so a second pair of eyes to sign off the changes and comment would be appreciated.

Then there are a few open issues like https://github.com/plk/biblatex/issues/752, https://github.com/plk/biblatex/issues/793, https://github.com/plk/biblatex/issues/803, https://github.com/plk/biblatex/issues/804 where a second opinion would also be valued.
