### ISSUE TITLE
Process `notfield=annote,entrynull=true`

### ISSUE THREAD

**Issue by holtzermann17** [plk/biber#238]
I would want this MWE to result in blanking entries without an `annote` field, but it blanks the entry *with* an annotation.  I raised this [issue on Stack Exchange and received an answer](https://tex.stackexchange.com/questions/454815/biblatex-reading-style-how-to-remove-entries-without-an-annotation/454867#454867) that does what I needed in multiple steps, though I still find it confusing.  According to the documentation:

> If notfield is used then only apply the step if the ⟨entryfield⟩ does not exist.

The behaviour seems to be the reverse of that?

``` latex
\documentclass{article}

\usepackage[style=reading,
            entryhead=true,
            entrykey=false,
            natbib,
            hyperref=false,
            url=false,
            doi=false,
            %style=apa,
            sorting=nyt,
            isbn=false,
            %backref=true,
            firstinits=true,
            minnames=13,
            maxnames=35,
            minbibnames=10,
            maxbibnames=100,
            parentracker=true,
            defernumbers=true,
            backend=biber]{biblatex}

\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map{
     \step[notfield=annote,entrynull=true]
    }
  }
}

\begin{filecontents}{\jobname.bib}
@inproceedings{ABCDFG,
  annote = {This is a very nice paper.},
  author = {GGPB},
  booktitle = {BOEUS},
  keywords = {clipping},
  title = {NOAP},
  volume = {0},
  year = {2005},
}
@inproceedings{XXXXXX,
  author = {PQR},
  booktitle = {BBC},
  keywords = {LLM},
  title = {ARP},
  year = {2010},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}

\nocite{*}

\printbibliography

\end{document}
```

**Comment by plk** [comment]
The docs are a bit misleading. A multi-step map is required, as mentioned on TSE. Mapping steps are typically one option unless the documentation for an option says otherwise.
