### ISSUE TITLE
Packaging biber for Homebrew

### ISSUE THREAD

**Issue by spl** [plk/biber#240]
In response to @moewew's comment at https://github.com/plk/biber/issues/221#issuecomment-433305178, I'm creating this issue.

I'm working on packaging Biber (and then BibLaTeX, along with other TeX-related software) for [Homebrew](https://brew.sh). I ran into the issue I described in https://github.com/plk/biber/issues/221#issuecomment-433040609, which, given its length, I won't repeat here.

Other than discussing the issues I'm facing (including #239), I'd like to get general feedback on what I'm doing. The current version of the Homebrew formula is [spl/homebrew-tex@4ae51b96/Formula/biber.rb](https://github.com/spl/homebrew-tex/blob/4ae51b96ad48489bb8868aa3fb9611e981baf37b/Formula/biber.rb).

I'm not currently building a `PAR::Packer` binary at the moment. I haven't yet looked into it, and I'm not sure at this point how to do it. Should I?

Is there anything else I should keep in mind for the Homebrew `biber.rb` formula?

**Comment by spl** [comment]
I'd just like to clarify that I have a successfully building formula, and the binary passes one of the tests in `t/tdata`. So, the issues in https://github.com/plk/biber/issues/221#issuecomment-433040609 and #239 are just things I discovered along the way and not showstoppers for me. Rather, I'm posting these issues to help others and to help improve Biber. It could be, for example, that I'm not doing things the “usual” way (maybe not the CTAN/Tex Live way?), but maybe it's also good for Biber to see that kind of usage.

That said, any feedback on the way I package Biber would be greatly appreciated. I'm just doing it because (a) I think TeX-related packages need to be available to macOS users via Homebrew and not just TeX Live and (b) nobody else has yet done this as far as I know.

**Comment by plk** [comment]
Since homebrew installs perl, there is no particular reason you would need build a biber binary with `PAR::Packer`. If you run `perl Build.PL` on a checkout out biber source tree, and then `Build installdeps` followed by `Build install`. This will put `biber` into the site perl location for the perl which ran `perl Build.PL`.

However, `biber` and `biblatex` versions are fairly closely coupled and the only guaranteed way to keep them in sync is to use a real TeX distro on OSX like MacTeX since this comes with `biber` and `biblatex` and can be updated.

**Comment by spl** [comment]
> Since homebrew installs perl, there is no particular reason you would need build a biber binary with `PAR::Packer`.

Okay, thanks. The only reason for a `biber` binary that I can think of is to reduce the number of things installed. But that reason hasn't convinced me enough to try to figure it out.

> If you run `perl Build.PL` on a checkout out biber source tree, and then `Build installdeps` followed by `Build install`. This will put `biber` into the site perl location for the perl which ran `perl Build.PL`.

Thanks for that suggestion. Currently, I follow the pattern of other Perl Homebrew formulae and put the dependencies explicitly in the formula. But, given that it's a lot of work, I may later decide letting Perl automatically figure out the dependencies.

Related question: Does `Build installdeps` download all the latest dependencies from CPAN and install them? 

> However, `biber` and `biblatex` versions are fairly closely coupled and the only guaranteed way to keep them in sync is to use a real TeX distro on OSX like MacTeX since this comes with `biber` and `biblatex` and can be updated.

Homebrew uses `git` for versioning a collection of formulae, so, while it's not absolutely guaranteed that the `biber` and `biblatex` formulae stay in sync, if both are updated in the same commit, then it's extra work for a user to update one and not the other, which is good enough, I think.

**Comment by plk** [comment]
`Build installdeps` does what you expect - it gets all the deps needed to run biber (not necessarily all the deps to run the tests but they are easy to install).
