### ISSUE TITLE
Unknown entry types not remapped to @misc

### ISSUE THREAD

**Issue by moewew** [plk/biber#242]
The `biblatex` documentation states

> All unknown entry types are generally **exported** as `@misc`.

and indeed earlier this year I posted https://tex.stackexchange.com/a/434285/35864 on TeX.SX where the MWE
```
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber, dashed=false]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{appleby1,
  author   = {Humphrey Appleby},
  title    = {On the Importance of the Civil Service},
  subtitle = {The Book},
  date     = {1981},
}
@software{appleby2,
  author   = {Humphrey Appleby},
  title    = {On the Importance of the Civil Service},
  subtitle = {The Software},
  date     = {1982},
}
@flobbel{appleby3,
  author   = {Humphrey Appleby},
  title    = {On the Importance of the Civil Service},
  subtitle = {The Nonsense},
  date     = {1983},
}
\end{filecontents}

\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}

\DeclareFieldFormat{entrytype}{\texttt{@#1}}
\renewbibmacro*{begentry}{\printtext{Hello, I'm a \printfield{entrytype}}\newunit}

\begin{document}
\cite{appleby1,appleby2,appleby3}
\printbibliography
\end{document}
```
gave
> Hello, I'm a `@misc`.

for the `@flobbel` entry.
![screenshot from TeX.SX](https://i.stack.imgur.com/mP0KQ.png)

But with a current Biber 2.12 the MWE passes the `@flobbel` right through, so I get
![Hello, I'm a `@flobbel`.](https://user-images.githubusercontent.com/6755835/48129024-95b69280-e288-11e8-9953-4e873228513b.png)

Have there been any changes to this area?

I though I'd check with 2.11 and 2.10 from Sourceforge to see where the behaviour went overboard and found that neither of the two shows
> Hello, I'm a `@misc`.

as I expected. Instead both give

> Hello, I'm a `@flobbel`.

So now I'm wondering if I went mad or if the behaviour changed at some point.

**Comment by plk** [comment]
Hmm, I have a vague memory that this was changed because silently correcting data model errors was felt to be a mistake? What is your opinion?

**Comment by plk** [comment]
Ok, I have removed that line from the doc. I can also add a `biber` warning about unrecognised types as I believe we do about unrecognised fields?

**Comment by moewew** [comment]
There is no Biber warning about unknown fields with the default settings at the moment (indeed, it is one of the features of BibTeX that unknown fields are discarded silently), so I think it is OK not to issue a warning for unknown types. A warning will be issued by `biblatex` if no driver is found, that should be enough for most users.

**Comment by plk** [comment]
Ah, right, I think we took out the field warning for exactly that reason. Ok, then I think it's all ok.
