### ISSUE TITLE
\constraintfields(x)or for more than two items

### ISSUE THREAD

**Issue by moewew** [plk/biber#243]
In the light of https://github.com/plk/biblatex/commit/b66a1d53a825c6631bcbb17475a252b071b84b99 I was looking into the data model specifications for `@online` and thought it might be useful to not only allow `doi` and `eprint`, but also relax the requirements for `--validate-datamodel` to accept `@online` entries with either of the fields `url`, `doi`, `eprint`. So I would like to be able to write

```
\DeclareDatamodelConstraints[online]{
  \constraint[type=mandatory]{
    \constraintfield{title}
    \constraintfieldsor{
      \constraintfield{url}
      \constraintfield{doi}
      \constraintfield{eprint}
    }
  }
}
```
to allow either of the three fields.
Currently that does not seem to be working as I hoped, the DOI specification is ignored, only the `url` and `eprint` are picked up.

Indeed
```
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage{filecontents}

\begin{filecontents}{constraints.dbx}
\ResetDatamodelConstraints
\DeclareDatamodelConstraints[online]{
  \constraint[type=mandatory]{
    \constraintfield{title}
    \constraintfieldsor{
      \constraintfield{url}
      \constraintfield{doi}
      \constraintfield{eprint}
    }
  }
}
\end{filecontents}

\usepackage[style=authoryear, backend=biber, datamodel=constraints]{biblatex}

\begin{filecontents}{\jobname.bib}
@online{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  date    = {1980},
  url     = {http://example.com}
}
@online{bppleby,
  author  = {Humphrey Bppleby},
  title   = {On the Importance of the Civil Service},
  date    = {1981},
  doi     = {12345/6789}
}
@online{cppleby,
  author  = {Humphrey Cppleby},
  title   = {On the Importance of the Civil Service},
  date    = {1982},
  eprint  = {1234556}
}
\end{filecontents}

\addbibresource{\jobname.bib}


\begin{document}
\cite{bppleby,appleby,cppleby}
\printbibliography
\end{document}
```
produces the validation report
```
[261] Utils.pm:193> WARN - Datamodel: Entry 'bppleby' (osffssiss.bib): Missing mandatory field - one of 'url, eprint' must be defined
```

**Comment by plk** [comment]
That was a long-standing bug only visible when there are more than two OR or XOR constraints, a silly error in the validation code. Fixed in 2.13 DEV.

**Comment by moewew** [comment]
Works brilliantly now, thank you. Committed https://github.com/plk/biblatex/commit/4c18e0fce96c76f27c21ef898ea918c500faf9af to only require one of `url`, `doi` or `eprint` for `@online`.

**Comment by plk** [comment]
DEV biblatex is updated with this on SF
