### ISSUE TITLE
Feature request: add all bib resources from a directory

### ISSUE THREAD

**Issue by nbarto** [plk/biber#246]
I asked on TeX SE whether with biber one can add all bib resources from a specified directory without specifying them one by one. [https://tex.stackexchange.com/questions/459222](https://tex.stackexchange.com/questions/459222)
I seem to be not the only one interested in this; it was previously asked for BibTeX: [https://tex.stackexchange.com/questions/192917](https://tex.stackexchange.com/questions/192917)

Would that be possible?

**Comment by plk** [comment]
Please try biber 3.13 from the DEV folder on SourceForge. You can now use BSD style globbing with `\addbibresource` like:

- `\addbibresource{bibfile*.bib}`
- `\addbibresource{bibfile?.bib}`
- `\addbibresource(bibfile{1,2}.bib}`

etc.
