### ISSUE TITLE
Biber errors when reading empty file

### ISSUE THREAD

**Issue by moewew** [plk/biber#248]
Biber throws an error when it tries to read an empty file.

The following MWE
```
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}


\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
\end{filecontents*}

\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson}
\printbibliography
\end{document}
```
produces
```
[0] Config.pm:304> INFO - This is Biber 2.12
[0] Config.pm:307> INFO - Logfile is 'jksknsjkks.blg'
[35] biber-MSWIN64:315> INFO - === 
[68] Biber.pm:371> INFO - Reading 'jksknsjkks.bcf'
[167] Biber.pm:889> INFO - Found 1 citekeys in bib section 0
[185] Biber.pm:4093> INFO - Processing section 0
[200] Biber.pm:4254> INFO - Looking for bibtex format file 'jksknsjkks.bib' for section 0
[201] Utils.pm:209> ERROR - Data file 'jksknsjkks.bib' cannot be read in encoding 'utf8': 
[202] Biber.pm:114> INFO - ERRORS: 1
```
It is true that empty files are probably not going to be very useful, but throwing an error seems a bit excessive. Would it be possible not to throw an error (if you think a message is useful here, could it be downgraded to a warning)?

**Comment by moewew** [comment]
Mhhh, adding comments to the `.bib` file (using `filecontents` instead of `filecontents*` in the MWE above) we get
```
ERROR - BibTeX subsystem: C:\Users\Moritz\AppData\Local\Temp\n34c5PhSoD\jksknsjkks.bib_4204.utf8, line 5, syntax error: at end of input, expected "@"
```
does that mean that this is an error of the underlying parsing library, which always needs at least one `@`entry?

**Comment by plk** [comment]
Hmm, yes, that comes from `btparse`. However, it's relatively easy to check this before it gets passed to `brtparse` - I already do this with name format edge cases which cause `btparse` to SEGFAULT.

**Comment by plk** [comment]
@moewew  - What format did you use for the comments?

**Comment by plk** [comment]
Ok, can you try 2.13 DEV? This now detects empty files and files with only comments and no macros. These are also warnings now, not errors.

**Comment by moewew** [comment]
Tried with the following MWE
```
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}


\usepackage{filecontents}
% this file will be empty
\begin{filecontents*}{\jobname-a.bib}
\end{filecontents*}
% this file will have a filecontents publicity blurb ala
%
\begin{filecontents}{\jobname-b.bib}
\end{filecontents}
% should this trigger the warning?
\begin{filecontents}{\jobname-c.bib}
@comment{foobar}
\end{filecontents}
\begin{filecontents}{\jobname-d.bib}
%%% hello my mail is spam@spam.com
\end{filecontents}

\addbibresource{\jobname-a.bib}
\addbibresource{\jobname-b.bib}
\addbibresource{\jobname-c.bib}
\addbibresource{\jobname-d.bib}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson}
\printbibliography
\end{document}
```
works well so far, but I have two comments

1. Please don't ignore `@comment` entries. It is a nice feature that adding a `@comment` entry suppresses a warning and guarantees a silent Biber run.
2. As `\jobname-d` shows the `@` detection is easily tricked. But I assume that one could only get things right if one would parse the entire file with BibTeX parsing rules already. It would probably be easier to just ask `btparse` to be more lenient on empty files.

**Comment by plk** [comment]
I was trying to avoid that because that means likely messing about with the C library. I'm afraid you're right the only way to do this reliably is to parse it, which is what causes the problem. It gets even worse when we have to take into account custom data models with their own entrytypes ...

**Comment by plk** [comment]
Ok, the `@Comment` macros are now not treated specially. There will be edge cases as you mentioned with email addresses but I think such things are very unlikely.

**Comment by moewew** [comment]
Thank you. Tested with Biber 2.13 dev just uploaded and the results are as expected.
