### ISSUE TITLE
Conditional append in sourcemap?

### ISSUE THREAD

**Issue by moewew** [plk/biber#251]
Consider the following MWE where the value of a field `fpp` is appended to the `note` field. In `appleby` the `note` field is already populated and things go smoothly, but in `hacker` the field is not existent and so we end up with a leading comma. Additionally `biber --trace` is unhappy
```
Use of uninitialized value $orig in concatenation (.) or string at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-b499addb80b3706a003bc9fcde51a97832c83aee\inc\lib/Biber/Input/file/bibtex.pm line 806.
Use of uninitialized value $orig in concatenation (.) or string at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-b499addb80b3706a003bc9fcde51a97832c83aee\inc\lib/Biber/Input/file/bibtex.pm line 808.
```

```
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}


\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map[overwrite]{
      \step[fieldsource=foo, final]
      \step[fieldset=note, fieldvalue={,}, append]
      \step[fieldset=note, origfieldval, append]
    }
  }
}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{appleby,
  author    = {Humphrey Appleby},
  title     = {On the Importance of the Civil Service},
  date      = {1980},
  foo       = {A},
  note      = {foo,bar},
}
@book{hacker,
  author    = {James Hacker},
  title     = {On the Importance of the Civil Service},
  date      = {1981},
  foo       = {B},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\DeclareFieldFormat{note}{\mkbibbold{#1}}

\begin{document}
\cite{appleby,hacker}
\printbibliography
\end{document}
```
It is possible to work around this issue with a more clunky definition such as
```
\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map[overwrite]{
      \step[fieldsource=note, final]
      \step[fieldsource=foo, final]
      \step[fieldset=note, fieldvalue={,}, append]
      \step[fieldset=note, origfieldval, append]
    }
    \map{
      \step[fieldsource=foo, final]
      \step[fieldset=note, origfieldval, append]
    }
  }
}
```
See also https://tex.stackexchange.com/q/420294/35864
But that feels a bit awkward and repetitive. 

1. Would it be possible to add a new kind of `append` keyword `condappend` (or `appendifnonempty` or `appendifexists` ...) or similar that only appends its value if the field exists already?
2. Would it be possibly to make `append` slightly more robust against non-existing fields, so that `biber --trace` does not have to complain?

**Comment by plk** [comment]
Bug fixed and new option `appendstrict` implemented which only appends to non-empty fields.

**Comment by plk** [comment]
Can you try this again with the latest biblatex/biber? Your example works fine for me now.

**Comment by moewew** [comment]
The MWE and another example I tried work as hoped and expected now. Thank you.
