### ISSUE TITLE
entrykey in \DeclareLabelalphaTemplate

### ISSUE THREAD

**Issue by moewew** [plk/biber#259]
Via https://tex.stackexchange.com/q/481732/35864.

It doesn't really make a lot of sense, I think, but still the following MWE
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=alphabetic, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\DeclareLabelalphaTemplate{
  \labelelement{
    \field[final]{entrykey}
  }
}


\begin{document}
\cite{sigfridsson,worman,geer}
\printbibliography
\end{document}
``` 
does not seem to work as expected. I would have liked to see the keys as labels and not the string `entrykeya`, ...

**Comment by plk** [comment]
This is already possible using `citekey` instead of `entrykey` but I have added the latter as an equivalent alias for consistency with source maps in 2.13.

**Comment by moewew** [comment]
Works very well. Thank you very much. And sorry for not being able to read the docs.

**Comment by plk** [comment]
We all know the docs are too large ....
