### ISSUE TITLE
biber issue. How do I set 

### ISSUE THREAD

**Issue by mario6097** [plk/biber#260]
Hi 
I have a php script to produce a .tex/.pdf files. I am not able to call biber from within my script, see [here](https://tex.stackexchange.com/questions/484677/biber-error-message-at-file-pm-line-151)
On my Linux (Fedora 29) machine the script is called from the user apache, which has not write permission on the /tmp/ directory. Since I understand that Biber unpacks its executable into a temporary directory, in my case something like /tmp/par-...../, that is an issue. 

It seems I need to set the  environment variable PAR_GLOBAL_TEMP to a different folder. How do I do that?

**Comment by plk** [comment]
This is just a question about general environment variable setting. For example, just precede the biber call with the variable, like this:

```
PAR_GLOBAL_TEMP=/some/dir/you/have/access/to biber
```

Or set the environment variable in the environment of the apache user.
