### ISSUE TITLE
Please document the return error code 2

### ISSUE THREAD

**Issue by MdAyquassar** [plk/biber#266]
Consider the following run of biber:

```
$ biber --isbn-normalise my_file ; echo $?
INFO - This is Biber 2.12
INFO - Logfile is 'my_file.blg'
ERROR - my_file.bcf is malformed, last biblatex run probably failed. Deleted my_file.bbl
INFO - ERRORS: 1
2
```

So, error code 2 is returned on some error. (Reason: my_file.bcf was output truncated. What the input files look like exactly, is not important at the moment.) However, the documentation `texdoc biber` says: "Biber returns an exit code of 0 on success or 1 if there was an error."  So, the documentation should be improved and document the error code 2 in addition.

**Comment by plk** [comment]
Hmm, in fact biber always exits with code 2 on error, never 1. I believe this was something to do with latexmk compat but I can't quite remember. I will update the docs for the next release.

**Comment by MdAyquassar** [comment]
I'd be happy if you update the documentation and thank you in advance.

An aside has to be made. In my opinion, it's more latexmk that has to be compatible with you than the other way round. There are a few build scripts around (cf. https://ctan.org/recommendations/latexmk); I guess you cannot be compatible with every one of them. So, if you can differentiate between various types of errors via various positive error codes, my subjective opinion is that you should probably consider feeling free to do it.
