### ISSUE TITLE
how to install biber in termux on andriod phone

### ISSUE THREAD

**Issue by hushidong** [plk/biber#268]
I have installed termux on andriod phone , and installed texlive for it, with
```
pkg install texLive
tlmgr install scheme-full

```

but when i compile the texfile, it issued no biber command, I am not familiar with perl ,and have no idea to install it, what can i do to install biber?

**Comment by hushidong** [comment]
can I just download a binary to be placed in termux? which binary should i use ?

**Comment by hushidong** [comment]
thanks ， problem has solved.

steps are:

手机小米max2
系统miui 10.2
未root(从实践看不影响安装，尽管安装了proot但没用)

1. 安装 termux(用的pp助手下载，这里头软件比较全)
设置termux权限，允许读写手机存储

2.安装texlive
pkg install texlive
tlmgr install scheme-full


3.编译biber
pkg install clang (用于基础c编译)
apt install make (安装make，否则安装cpanm无法编译)(这两步用于解决后面编译时出现的No such file or directory错误。见 https://github.com/termux/termux-packages/issues/979)
pkg install perl (安装perl，若termux没有默认安装的话)
cpan App::cpanminus (便于安装依赖模块，好处见https://wiki.termux.com/wiki/Perl，如果因为缺少YAML安装失败，那么用命令cpan YAML 先安装YAML)
git clone https://github.com/plk/biber.git （下载biber）
cpanm Module::Build (安装依赖文件)
cpanm PAR::Packer (安装依赖文件，如果因为Archive::Zip失败，那么用cpanm Archive::Zip --force强制安装，然后重新安装)
cd biber（进入biber目录）
perl ./Build.PL （利用自动脚本安装，但肯定会有依赖缺乏，出现问题，利用下一步安装依赖。）
apt-get install libxslt-dev
apt-get install libxml2
apt-get install libiconv
apt-get install libiconv-dev
apt-get install libssh
apt-get install libssh-dev
cpanm ExtUtils::LibBuilder --force
cpanm Text::BibTeX --force
cpanm PkgConfig --force
cpanm XML::LibXML
cpanm XML::LibXML::Simple
pkg install openssl
pkg install openssl-dev
pkg install openssl-tool
cpanm LWP::Protocol::https
mv MYMETA.json META.json
mv MYMETA.yml META.yml
./Build installdeps （安装biber需要的依赖）
./Build test
./Build install

4. 安装biber
./Build install

5.测试tex 编译
cd /storage/emulated/0/a/
latexmk egtest
但会发现texlive中的biblatex刚编译的最新的biber不能配合。那么还要去biblatex下最新的biblatex

6.使用最新的biblatex
cd ~
git clone https://github.com/plk/biblatex.git
cd biblatex
./obuild/build.sh install 3.13 /data/data/com.termux/files/usr/share/texlive/texmf-dist

7.再次测试tex
xelatex egtest
biber egtest
xelatex egtest
成功打开pdf

**Comment by hushidong** [comment]
see 
https://github.com/lsq/lsq.github.com/issues/1

**Comment by plk** [comment]
Thank you for documenting this fix.

**Comment by bubifengyun** [comment]
现在可以直接 pkg install biber了，接着调用 termux-install-biber 就好了。
