### ISSUE TITLE
Crash with set

### ISSUE THREAD

**Issue by bastien-roucaries** [plk/biber#277]
The following file lead to crash:

\documentclass{minimal}

\usepackage{filecontents}

\begin{filecontents}{chokeme.bib}
@set{patentfamilly-JP4691163-中塚:2009,
   set = {patent-JP4691163-中塚:2009},
 }
 
@Patent{patent-JP4691163-中塚:2009,
  author =	 {宏 中塚 and 慶治 大西 and 岳彦 山川},
  title =	 {周波数可変音響薄膜共振器、フィルタ、及びそれを用いた通信装置},
  number =	 {4691163},
  type =	 {patentjp},
  date =	 {2009-12-24},
  fileddate =	 {2006-08-03},
  granteddate =	 {2011-06-01},
  expireddate =	 {2015-02-25},
  holder =	 {パナソニック株式会社},
  language =	 {langjapanese},
  langid =	 {japanese},
}
\end{filecontents}

\usepackage[backend=biber,style=numeric-comp]{biblatex}
\addbibresource{chokeme.bib}

\begin{document}
\cite{patentfamilly-JP4691163-中塚:2009}
\end{document}

INFO - This is Biber 2.12
INFO - Logfile is 'test.blg'
INFO - Reading 'test.bcf'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex format file 'chokeme.bib' for section 0
INFO - LaTeX decoding ...
INFO - Found BibTeX data source 'chokeme.bib'
INFO - Overriding locale 'en-US' defaults 'normalization = NFD' with 'normalization = prenormalized'
INFO - Overriding locale 'en-US' defaults 'variable = shifted' with 'variable = non-ignorable'
INFO - Sorting list 'nty/global//global/global' of type 'entry' with template 'nty' and locale 'en-US'
INFO - No sort tailoring available for locale 'en-US'
Can't use an undefined value as an ARRAY reference at /usr/share/perl5/Biber.pm line 3621.

**Comment by plk** [comment]
The bib file is incorrect, the `@set` entry should be:

```
@set{patentfamilly-JP4691163-中塚:2009,
  entryset = {patent-JP4691163-中塚:2009},
}
```

**Comment by bastien-roucaries** [comment]
On Sat, Aug 17, 2019 at 7:49 PM plk <notifications@github.com> wrote:

> The bib file is incorrect, the @set entry should be:
>
> @set{patentfamilly-JP4691163-中塚:2009,
>
>   entryset = {patent-JP4691163-中塚:2009},
>
> }
>
> Thanks it was a typo nevertheless undefined value crash instead of nice
error message in not really helpful

**Comment by plk** [comment]
I'll look into that for the next release.

**Comment by moewew** [comment]
```latex
\documentclass{article}

\begin{filecontents}{\jobname.bib}
@set{set,
  set = {appleby},
}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  date    = {1980},
}
\end{filecontents}

\usepackage[backend=biber,style=numeric-comp]{biblatex}
\addbibresource{\jobname.bib}

\begin{document}
\cite{set}
\end{document}
```
still fails with a cryptic
```
Can't use an undefined value as an ARRAY reference at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-4fc2c1696c50d50c472fd431edbebce2a8b48080\inc\lib/Biber.pm line 3790.
```
(that is not reported in the `.blg` file).

1. Would it be possible to ensure that errors like this end up in the `.blg` file?
2. Maybe it would make sense to just check if a `@set` entry has an `entryset` field and stop processing it if it doesn't.

**Comment by plk** [comment]
Should be fixed in DEV. Such errors are hard bugs and shouldn't happen at all and so it's barely worth getting them into the .blg as they should be very visible and reported.

**Comment by moewew** [comment]
Thank you very much.

The problem with not sending these kind of errors to the `.blg` file is that sometimes users (or those trying to help users) only have reliable access to the `.blg` files (I'm thinking Overleaf, but also some editors). If the error message does not get to the `.blg` file, it is essentially lost, making debugging *much* harder.
