### ISSUE TITLE
Clearer error message for nulled entries

### ISSUE THREAD

**Issue by moewew** [plk/biber#287]
Via https://tex.stackexchange.com/q/454815/35864 (specifically https://tex.stackexchange.com/a/508811/35864, which might be deleted soon since it does not constitute an answer, but is placed in the answer space).

In the following MWE
```latex
\documentclass{article}
\usepackage[style=reading, backend=biber]{biblatex}

\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map{
     \step[notfield=annote, final]
     \step[notfield=annotation, final]
     \step[entrynull]
    }
  }
}

\begin{filecontents}{\jobname.bib}
@inproceedings{ABCDFG,
  annote    = {This is a very nice paper.},
  author    = {GGPB},
  booktitle = {BOEUS},
  keywords  = {clipping},
  title     = {NOAP},
  volume    = {0},
  year      = {2005},
}
@inproceedings{XXXXXX,
  author    = {PQR},
  booktitle = {BBC},
  keywords  = {LLM},
  title     = {ARP},
  year      = {2010},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
%\nocite{*}
\cite{XXXXXX}
\printbibliography
\end{document}
```
the only cited entry is removed by way of the source map. Biber complains about that with the somewhat cryptic
```
Can't call method "get_field" on an undefined value at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-22aed6f1f9a514cb780d82b9ae47207654b29c4f\inc\lib/Biber.pm line 4488.
```
Would it be possible to have Biber reply with a different message? In particular it would be helpful to explain that the relevant key was found, but has subsequently been nulled by the source map (not sure if that is easily possible).

**Comment by sieversMartin** [comment]
Thank you for taking this to the issue tracker. Indeed I did not realise, that this happens when all cited entries are removed. In my real-world file, there are many refsections and the general rule in my bbx file obvious makes some of them completely empty.

Changing the error message certainly helps to understand the problem, but the question remains: Is there a way to use such a rule even when it makes some refsections empty?

⁣Gesendet mit TypeApp ​

**Comment by plk** [comment]
Looking at the code for this, it was envisaged that `entrynull` would only be used with `\nocite{*}` as citing something you then remove in a map is a bit odd (why not just not cite it ...). I can probably make this error go away and generate a warning (cited but removed).

**Comment by moewew** [comment]
Absolutely, and the new mapping verbs (https://github.com/plk/biber/commit/8611f69d64deaaee35ffddbcb8e9f027a52bae28) for https://tex.stackexchange.com/a/507668/35864 help make this map sensible even without `\nocite{*}` by restricting it to these cases. With 2.14
```latex
\documentclass{article}
\usepackage[style=reading, backend=biber]{biblatex}

\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map{
     \step[allnocited, final]
     \step[notfield=annote, final]
     \step[notfield=annotation, final]
     \step[entrynull]
    }
  }
}

\begin{filecontents}{\jobname.bib}
@inproceedings{ABCDFG,
  annote    = {This is a very nice paper.},
  author    = {GGPB},
  booktitle = {BOEUS},
  keywords  = {clipping},
  title     = {NOAP},
  volume    = {0},
  year      = {2005},
}
@inproceedings{XXXXXX,
  author    = {PQR},
  booktitle = {BBC},
  keywords  = {LLM},
  title     = {ARP},
  year      = {2010},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
%\nocite{*}
\cite{XXXXXX}
\printbibliography
\end{document}
```
gives very sensible output.

**Comment by plk** [comment]
Yes, I agree with that last point - it should behave as if there was no cite and no entry at all. Looking at it.

**Comment by moewew** [comment]
@sieversMartin As I commented under you TeX.SX post, at least with the upcoming `biblatex`  3.14/Biber 2.14 there will be a way around this specific issue, but in general I'd say the behaviour of Biber here is not completely unreasonable. If you choose to `null` the entry you cite, then it is expected that the entry will not appear.

**Comment by sieversMartin** [comment]
Am 18.09.19 um 17:48 schrieb moewew:
> Absolutely, and the new mapping verbs (8611f69
> <https://github.com/plk/biber/commit/8611f69d64deaaee35ffddbcb8e9f027a52bae28>)
> for https://tex.stackexchange.com/a/507668/35864 help make this map
> sensible even without |\nocite{*}| by restricting it to these cases.
> With 2.14

Thank you. I'll check this. To give you an idea what I need this for: I
have hundreds of letters which each have several different customized
entry types associated within separate refsections.

All this comes automatically from a virtual research environment. I have
to check for occurrences, where specific fields are undefined or empty,
because these entries are not supposed to be printed in the letters
"bibliography". That's why they are cited and then removed.

Another solution for me could be to remove them within the export routine.

**Comment by sieversMartin** [comment]
Am 18.09.19 um 18:01 schrieb moewew:
> If you choose to |null| the entry you cite, then it is expected that the
> entry will not appear.

Well, that is clear and intended. However, I hoped to just get "nothing"
for the specific refsections (where all cited entries are set to
"null"), but still get results for all others.

I was surprised, that there is no bibliography output at all.

**Comment by moewew** [comment]
You can restrict maps to specific refsections with the the `refsection` option to `\map`. Not sure if that helps.

**Comment by plk** [comment]
I think that the failure is unreasonable - it should give a message, remove the citation and succeed. Try 2.14 DEV now. This should give a meaningful warning and not die. However, latex is always going to report an unresolved reference as there won't be anything in the `.bbl` for the citation.

**Comment by moewew** [comment]
@plk Just tested the MWE with 2.14 dev. The new message is much more helpful. Thank you very much.

**Comment by plk** [comment]
More importantly, it doesn't die and so it will generate a `.bbl` as normal, which was a larger problem as mentioned by @sieversMartin.

**Comment by sieversMartin** [comment]
Am 18.09.19 um 18:20 schrieb plk:
> More importantly, it doesn't die and so it will generate a |.bbl| as
> normal, which was a larger problem as mentioned by @sieversMartin
> <https://github.com/sieversMartin>.

Yes, indeed. Thank you very much.

**Comment by sieversMartin** [comment]
For the record: for my concrete problem I implemented an alternative solution, which works without removing entries:
``` latex
\map{%
   \pertype{documenttype36_extend_134}%
   \step[notfield=doksigle,final]%
   \step[fieldset=keywords,fieldvalue={DELETED}]%
}
\map{%
   \pertype{documenttype36_extend_134}%
   \step[fieldsource=doksigle,notmatch=\regexp{\A\Z},final]%
   \step[fieldset=keywords,fieldvalue={DELETED}]%
} 
...
\printbibliography[notkeyword={DELETED}]%
```

**Comment by plk** [comment]
It scares me, the things people do with sourcemaps these days ... they are probably Turing Complete ...

**Comment by sieversMartin** [comment]
Probably.
Sourcemaps have saved me a lot of work as my data often come from Zotero or other tools where the export is not "biblatex-complete" and/or has to be normalized/regularized some way.
I think, sourcemaps are one of the great advantages of the modern biblatex/biber workflow.

**Comment by plk** [comment]
I agree although I never thought they would be so useful when I implemented the first basic version years ago - it's clear that they are part of the modern "messy data independence" movement which the "too much data" age has necessitated ..

**Comment by moewew** [comment]
The MWE from the first post generates a more useful Biber warning in version 2.14, so I'm closing this.
