### ISSUE TITLE
Not parsing spaces

### ISSUE THREAD

**Issue by crumka** [plk/biber#288]
I just updated biber and my work doesn't compile correctly anymore.  Output is as below:

```
INFO - This is Biber 2.13
INFO - Logfile is 'main.blg'
INFO - Reading 'main.bcf'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
INFO - Globbing data source 'C:\\Users\\kcrum\\Desktop\\DW AI SoW\\main.bib'
INFO - Globbed data source 'C:\\Users\\kcrum\\Desktop\\DW AI SoW\\main.bib' to C:\Users\kcrum\Desktop\DW,AI,SoW\main.bib
INFO - Looking for bibtex format file 'C:\Users\kcrum\Desktop\DW' for section 0
ERROR - Cannot find 'C:\Users\kcrum\Desktop\DW'!
INFO - ERRORS: 1
```

I get correct compiling when I modify the path to preclude any spaces.

**Comment by plk** [comment]
Are you able to try the DEV version (2.14) on Sourceforge? I think this is fixed there.

**Comment by crumka** [comment]
Happy to try if you talk me through the process.

**Comment by moewew** [comment]
You'll need a dev version of `biblatex` as well, so the process is a bit tricky.

As a temporary measure you can try protecting the file name with quotation marks. See also https://github.com/plk/biber/issues/280.
