### ISSUE TITLE
More descriptive error for unknown datatype

### ISSUE THREAD

**Issue by moewew** [plk/biber#289]
See https://tex.stackexchange.com/q/509837/35864

Consider
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\addbibresource[datatype=biblatex]{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson}
\printbibliography
\end{document}
```
Biber will complain
>```
>[0] Config.pm:304> INFO - This is Biber 2.13
>[0] Config.pm:307> INFO - Logfile is 'jhsgsjsgsghsswzwetrte.blg'
>[32] biber-MSWIN64:315> INFO - === 
>[52] Biber.pm:375> INFO - Reading 'jhsgsjsgsghsswzwetrte.bcf'
>[169] Biber.pm:905> INFO - Found 1 citekeys in bib section 0
>[185] Biber.pm:4196> INFO - Processing section 0
>[187] Utils.pm:75> INFO - Globbing data source 'biblatex-examples.bib'
>[196] Utils.pm:91> INFO - Globbed data source 'biblatex-examples.bib' to biblatex-examples.bib
>[197] Utils.pm:316> ERROR - Error loading data source package 'Biber::Input::file::biblatex': 
>  Can't locate Biber/Input/file/biblatex.pm in @INC (you may need to install the Biber::Input::file::biblatex module)
>  (@INC contains:
>  C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-04a19264eaffcea447b2351b2a1f132a70bdc8b1\inc\lib
>  C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-04a19264eaffcea447b2351b2a1f132a70bdc8b1\inc
>  CODE(0x3a33e30) CODE(0x3a34028)) at (eval 366) line 1.
>[197] Biber.pm:114> INFO - ERRORS: 1
>```

Could Biber check if the `datatype` is valid before it tries to include the relevant module and error with a more helpful error message?

If you think it would be useful I could also look at producing a warning on the `biblatex` side. But I'm not sure if that is a good idea, because (theoretically) Biber's support for datatypes could be expanded without `biblatex` knowing about that.

**Comment by plk** [comment]
Actually it is doing that at `[197]` above but it's also including the raw error, which is perhaps too much information. I've changed this in DEV so that it doesn't do that and reports the valid type/datatype combinations.

**Comment by moewew** [comment]
Thank you very much. The message is less daunting and clearer now. I'm wondering if it could be made more informative in informing the user of the place where the `datatype` comes from (the `biblatex` documentation mentions data type or datatype quite a lot).

I also think it would make the message more useful if the `file/` could be dropped to make the relevant datatypes stand out more. Would that make sense?

**Comment by plk** [comment]
The 'file' is there because it was planned at some point to allow non-file datasources (SQL e.g.) and 'file' is the default datasource type (this can be passed as an optional argument to `addbibresource` but defaults to 'file').
