### ISSUE TITLE
Build fails for Linux x86_64-MUSL

### ISSUE THREAD

**Issue by krumeich** [plk/biber#295]
I'm encountering a problem building the x86_64-MUSL version on the `dev` branch. Not knowing a whole lot about Perl, can anybody help me out or give me a pointer in the right direction? Here's a small excerpt of the build log. Complete log is attached as `failure.txt`. I'm building biber in a container. See the attached `Dockerfile.build` for details about the installed modules.

Thanks for your help! 

```
Creating new 'Build' script for 'biblatex-biber' version '2.14'
All prerequisites satisfied
t/annotations.t ........... ok
[…]
t/related-entries.t ....... ok
Can't call method "get_field" on an undefined value at /biber/blib/lib/Biber/DataList.pm line 1784.
# Looks like your test exited with 255 just after 1.
t/remote-files.t ..........
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/2 subtests
t/sections-complex.t ...... ok
[…]
t/xdata.t ................. ok

Test Summary Report
-------------------
t/remote-files.t        (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 2 tests but ran 1.
Files=52, Tests=1231, 71 wallclock secs ( 0.23 usr  0.05 sys + 64.59 cusr  4.02 csys = 68.89 CPU)
Result: FAIL
Failed 1/52 test programs. 0/1231 subtests failed.
```

**Comment by plk** [comment]
I wouldn’t worry about errors in that test - I get them intermittently too as it’s a test of fetching of some remote resources which sometimes disappear or change. I get the same error currently - I’ll fix the test soon.

PK

> On 23 Nov 2019, at 4:21 pm, Alexander Krumeich <notifications@github.com> wrote:
> 
> I'm encountering a problem building the x86_64-MUSL version on the dev branch. Not knowing a whole lot about Perl, can anybody help me out or give me a pointer in the right direction? Here's a small excerpt of the build log. Complete log is attached as failure.txt. I'm building biber in a container. See the attached Dockerfile.build for details about the installed modules.
> 
> Thanks for your help!
> 
> Creating new 'Build' script for 'biblatex-biber' version '2.14'
> All prerequisites satisfied
> t/annotations.t ........... ok
> […]
> t/related-entries.t ....... ok
> Can't call method "get_field" on an undefined value at /biber/blib/lib/Biber/DataList.pm line 1784.
> # Looks like your test exited with 255 just after 1.
> t/remote-files.t ..........
> Dubious, test returned 255 (wstat 65280, 0xff00)
> Failed 1/2 subtests
> t/sections-complex.t ...... ok
> […]
> t/xdata.t ................. ok
> 
> Test Summary Report
> -------------------
> t/remote-files.t        (Wstat: 65280 Tests: 1 Failed: 0)
>   Non-zero exit status: 255
>   Parse errors: Bad plan.  You planned 2 tests but ran 1.
> Files=52, Tests=1231, 71 wallclock secs ( 0.23 usr  0.05 sys + 64.59 cusr  4.02 csys = 68.89 CPU)
> Result: FAIL
> Failed 1/52 test programs. 0/1231 subtests failed.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--
Dr Philip Kime

**Comment by krumeich** [comment]
Thanks for clearing this up. However I was a bit brief in the original post. The issue at hand is that biber fails the `--validate-control` test against the test files on SourceForge:

```
/ # /usr/local/bin/biber --validate-control test-dev.bcf
INFO - This is Biber 2.14 (beta)
INFO - Logfile is 'test-dev.blg'
ERROR - 'test-dev.bcf' failed to validate against schema '/tmp/par-726f6f74/cache-3e56ab69133a48bf58df5b758c17fee30dd89ad8/inc/lib/Biber/bcf.rng'
INFO - ERRORS: 1
/ # cat test-dev.blg
[0] Config.pm:304> INFO - This is Biber 2.14 (beta)
[0] Config.pm:307> INFO - Logfile is 'test-dev.blg'
[75] biber:322> INFO - === Sat Nov 23, 2019, 15:48:23
[91] Utils.pm:320> ERROR - 'test-dev.bcf' failed to validate against schema '/tmp/par-726f6f74/cache-3e56ab69133a48bf58df5b758c17fee30dd89ad8/inc/lib/Biber/bcf.rng'
[92] Biber.pm:132> INFO - ERRORS: 1
```

Retracing my steps I found the failing test mentioned above and assumed that this would be responsible for the failing validation. 

Have you modified the test files? Latest on SF is dated Sep. 11.

**Comment by plk** [comment]
That’s true because the test .bcf is only update after a release and so should validate only against the current released version (2.13) …

PK

> On 23 Nov 2019, at 4:53 pm, Alexander Krumeich <notifications@github.com> wrote:
> 
> Thanks for clearing this up. However I was a bit brief in the original post. The issue at hand is that biber fails the --validate-control test against the test files on SourceForge:
> 
> / # /usr/local/bin/biber --validate-control test-dev.bcf
> INFO - This is Biber 2.14 (beta)
> INFO - Logfile is 'test-dev.blg'
> ERROR - 'test-dev.bcf' failed to validate against schema '/tmp/par-726f6f74/cache-3e56ab69133a48bf58df5b758c17fee30dd89ad8/inc/lib/Biber/bcf.rng'
> INFO - ERRORS: 1
> / # cat test-dev.blg
> [0] Config.pm:304> INFO - This is Biber 2.14 (beta)
> [0] Config.pm:307> INFO - Logfile is 'test-dev.blg'
> [75] biber:322> INFO - === Sat Nov 23, 2019, 15:48:23
> [91] Utils.pm:320> ERROR - 'test-dev.bcf' failed to validate against schema '/tmp/par-726f6f74/cache-3e56ab69133a48bf58df5b758c17fee30dd89ad8/inc/lib/Biber/bcf.rng'
> [92] Biber.pm:132> INFO - ERRORS: 1
> 
> Retracing my steps I found the failing test mentioned above and assumed that this would be responsible for the failing validation.
> 
> Have you modified the test files? Latest on SF is dated Sep. 11.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--
Dr Philip Kime

**Comment by krumeich** [comment]
That figures. Could you maybe upload the dev test files to SF? Somewhere close to the test binaries would be ideal. How about `/biblatex-biber/files/biblatex-biber/development/testfiles`?

**Comment by plk** [comment]
Hmm, I think I might already have done something like this - does the "test-dev.bcf” validate?

PK

> On 23 Nov 2019, at 5:02 pm, Alexander Krumeich <notifications@github.com> wrote:
> 
> That figures. Could you maybe upload the dev test files to SF? Somewhere close to the test binaries would be ideal. How about /biblatex-biber/files/biblatex-biber/development/testfiles?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--
Dr Philip Kime

**Comment by krumeich** [comment]
Unfortunately, it doesn't. I'm using `test-dev.bcf`. Any further ideas?

**Comment by plk** [comment]
Should be fixed now.

PK

> On 23 Nov 2019, at 6:07 pm, Alexander Krumeich <notifications@github.com> wrote:
> 
> Unfortunately, it doesn't. I'm using test-dev.bcf. Any further ideas?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--
Dr Philip Kime

**Comment by krumeich** [comment]
Please check again. The new `test-dev.bcf` is identical to the previous one. This is the sha1sum of the file on SF:

```
ca03ea1bbfc86ffd27b4a67c8567adbe8e67ecc3  test-dev.bcf
```

**Comment by plk** [comment]
I just checked it again - seems fine - you may have to wait for all the Sourceforge mirrors to replicate the upload …

PK

> On 23 Nov 2019, at 9:13 pm, Alexander Krumeich <notifications@github.com> wrote:
> 
> Please check again. The new test-dev.bcf is identical to the previous one. This is the sha1sum of the file on SF:
> 
> ca03ea1bbfc86ffd27b4a67c8567adbe8e67ecc3  test-dev.bcf
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--
Dr Philip Kime

**Comment by krumeich** [comment]
That did it. Thank you! My `dev` build can validate the `test-dev.bcf` file again. I've just uploaded a new snapshot to SF.
