### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by simifilm** [plk/biber#3]
Sometimes biber will report an error like the following and then stop working:

```
data source /var/folders/m6/bn7r45zx6cx55rr9g4qh6s6w0000gn/T/par-agoldst/cache-87e533530c5239fb9f8e3ff008979f1f16ea0e5e//inc/lib/Biber/LaTeX/recode_data.xml not found in .
```

I don't know when this happens and therefore can't give a reproducible test case, but this happens to others as well (see http://humtex.wordpress.com/2011/11/29/biber-first-aid-for-data-source-not-found/ for example).

The solution is to delete the par-directory. Afterwards everything works fine again. Since this error message is rather cryptic and the remedy seems to be straightforward I was wondering whether this could be improved.

**Comment by npdoty** [comment]
Wow, this is challenging. I had this failure immediately upon installing on a new Yosemite machine and there's no documentation to help you besides searching through closed issues and happening to find a link to this blog post. Maybe if this error happens, biber could at least suggest deleting that directory? That workaround worked for me.

**Comment by plk** [comment]
Actually, it's almost impossible to detect internally due to the semantics of the PAR::Packer module but the authors of that module are aware of the issue and are looking into a fix (it's not a biber problem per se).
