### ISSUE TITLE
BibTeX subsystem: warning: comma(s) at end of name (removing)

### ISSUE THREAD

**Issue by maieul** [plk/biber#303]
Hi,

I get "BibTeX subsystem: warning: comma(s) at end of name (removing)".

but there is no information about the line, so I can't correct my database easily.

**Comment by plk** [comment]
I am afraid there isn't much we can do about this as it's a limitation of the btparse library that doesn't report line numbers . A quick  `fgrep ',};` on your .bib shows a few fields with trailing commas.

**Comment by maieul** [comment]
oki, you are right. I made a mistake between "comma" and "dot" and I thought the message was becase I put some first name with a comma after. So we can close.
