### ISSUE TITLE
A graph in the handbook to visualizing the process

### ISSUE THREAD

**Issue by maieul** [plk/biber#307]
Hi, 

maybe it could be nice to add in biblatex or biber handbook a graph explaining the process of compilation and the feature of the different files.

I have produced such graph for a french article
https://geekographie.maieul.net/205

here the code of the graph

https://geekographie.maieul.net/IMG/tex/schemas.tex

you can use it freely if you want

**Comment by plk** [comment]
There is something in the ‘quickstart’ guide I started on - is that useful?

**Comment by maieul** [comment]
do you mean the figure 1? where is the quickstart ?

**Comment by plk** [comment]
https://github.com/plk/biblatex/tree/dev/doc/latex/biblatex

It's in the doc directory and there is a .png file in there which is part of the quickstart doc.

**Comment by maieul** [comment]
yep, it as the idea. So we can close this issue, I guess
