### ISSUE TITLE
Log all errors in blg

### ISSUE THREAD

**Issue by moewew** [plk/biber#309]
Inspired by https://tex.stackexchange.com/q/533659/35864. Related to https://github.com/plk/biber/issues/179

Consider the following MWE
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, bibencoding=ascii, backend=biber]{biblatex}


\begin{filecontents}[force]{\jobname.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {Ò},
  date    = {1980},
}
\end{filecontents}
\addbibresource{\jobname.bib}


\begin{document}
\cite{appleby}
\printbibliography
\end{document}
```
when run with Biber it fails as follows
```
INFO - This is Biber 2.14
INFO - Logfile is 'asciisplosion.blg'
INFO - Reading 'asciisplosion.bcf'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
INFO - Globbing data source 'asciisplosion.bib'
INFO - Globbed data source 'asciisplosion.bib' to asciisplosion.bib
INFO - Looking for bibtex format file 'asciisplosion.bib' for section 0
ascii "\xC3" does not map to Unicode at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-fdb7483801244becd81fb01b3ab99423d7614d1b\inc\lib/File/Slurper.pm line 59.
```
but the `.blg` only contains
```
INFO - This is Biber 2.14
INFO - Logfile is 'asciisplosion.blg'
INFO - Reading 'asciisplosion.bcf'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
INFO - Globbing data source 'asciisplosion.bib'
INFO - Globbed data source 'asciisplosion.bib' to asciisplosion.bib
INFO - Looking for bibtex format file 'asciisplosion.bib' for section 0
```

Would it be possible to send the crucial error message
```
ascii "\xC3" does not map to Unicode at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-fdb7483801244becd81fb01b3ab99423d7614d1b\inc\lib/File/Slurper.pm line 59.
```
also to the `.blg` file.

I think I saw other errors that were only sent to the console and not to the `.blg` before, but I can't remember which errors that were now. Would it be possible to make sure the log on the console and `.blg` contains the same messages?

That would help extremely for people who don't have access to the console log during compilation. (I'm thinking Overleaf.)

**Comment by plk** [comment]
This was a bug - please try DEV.

**Comment by moewew** [comment]
Looks good now. Thank you very much.

**Comment by plk** [comment]
A comment about error logging in general - errors from the perl interpreter itself can't be logged to the `.blg` as the the interpreter itself is throwing this and exiting the entire process. In general, such errors are serious enough that they shouldn't happen and need to be fixed as priority bugs.

**Comment by moewew** [comment]
I see, this is a bummer. When the actual command line output is hard to come by the `.blg` file is often the only thing you can rely on.
