### ISSUE TITLE
biber doesn’t find .bib file with non-ASCII filename due to globbing

### ISSUE THREAD

**Issue by cruessler** [plk/biber#310]
In the following MWE biber can’t find the bibliography because of the filename containing a non-ASCII character.

```
\documentclass{article}

\begin{filecontents}{ä.bib}
@book{key,
  author = {Name},
  title = {Title}
}
\end{filecontents}

\usepackage[backend=biber]{biblatex}
\addbibresource{ä.bib}

\begin{document}
\cite{key}
\printbibliography
\end{document}
```

After `latex umlaut.tex`, the output of `biber umlaut` is:

```
INFO - This is Biber 2.14
INFO - Logfile is 'umlaut.blg'
INFO - Reading 'umlaut.bcf'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
INFO - Globbing data source 'ä.bib'
INFO - Globbed data source 'ä.bib' to aÌ.bib
INFO - Looking for bibtex format file 'aÌ.bib' for section 0
ERROR - Cannot find 'ä.bib'!
INFO - ERRORS: 1
```

This is an issue on current dev, too:

```
INFO - This is Biber 2.15 (beta)
INFO - Logfile is 'umlaut.blg'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
INFO - Globbing data source 'ä.bib'
INFO - Globbed data source 'ä.bib' to 'aÌ.bib'
INFO - Looking for bibtex format file 'aÌ.bib' for section 0
ERROR - Cannot find 'ä.bib'!
INFO - ERRORS: 1
```

Is biber supposed to support non-ASCII filenames or am I better advised to just switch to ASCII filenames?

**Comment by moewew** [comment]
It is my belief that ASCII-only filenames (without spaces!) are the best choice, but since this problem occurs in the globbing phase
```
Globbed data source 'ä.bib' to aÌ.bib
```
maybe this can be fixed.

(I notice that even with pdfLaTeX the `.bcf` correctly contains `ä.bib`, so the LaTeX side is not holding us back here for once. The result is the same with all engines.)

**Comment by moewew** [comment]
Checked the MWE on Ubuntu (TeX live 2020) today with the same result. So the problem is not limited to Windows.

**Comment by plk** [comment]
The best we can do here is to add heuristics as filesystem encoding can be wildly different between OSes and Perl can't determine this flawlessly as it's "external" data. I will look into adding some reasonable guesses.

**Comment by plk** [comment]
Please try DEV 2.15 on Sourceforge. I haven't tested this in Linux yet but in fact the MNWE you give works find on OSX anyway (but has broken filename in the log) because OSX is "unique" in rather stupidly using UTF-8 NFD for the filesystem. I haven't tried the fix on an NFC filesystem yet ...

**Comment by moewew** [comment]
Still no luck on Windows, I now get
```
[0] Config.pm:304> INFO - This is Biber 2.15 (beta)
[0] Config.pm:307> INFO - Logfile is 'ulautitzh.blg'
[103] biber-MSWIN64:327> INFO - === 
[142] Biber.pm:415> INFO - Reading 'ulautitzh.bcf'
[278] Biber.pm:952> INFO - Found 1 citekeys in bib section 0
[300] Biber.pm:4265> INFO - Processing section 0
[301] Utils.pm:75> INFO - Globbing data source 'ä.bib'
[330] Utils.pm:92> INFO - Globbed data source 'ä.bib' to 'ä.bib'
[349] Biber.pm:4464> INFO - Looking for bibtex format file 'ä.bib' for section 0
[734] Utils.pm:321> ERROR - Cannot find 'ä.bib'!
[735] Biber.pm:132> INFO - ERRORS: 1
```

I'm getting inconclusive results on Linux: it appeared to work with the 64bit version uploaded by you earlier today, but didn't with the 32bit version I just compiled and uploaded. I'll have to recompile and recheck tomorrow.

**Comment by plk** [comment]
As I feared, I'll need to try to determine the locale in order to decode the filename.

**Comment by moewew** [comment]
I messed up the 32bit Linux build yesterday. With the build from this morning the MWE works on Linux x86 32bit as well. I also tested on another 64bit Linux. On all Linux machines that I tested the encoding (according to `locale`) was UTF-8.

**Comment by plk** [comment]
Can you try DEV 2.15 again, especially on Windows.

**Comment by moewew** [comment]
Win 10 now says
```
[0] Config.pm:304> INFO - This is Biber 2.15 (beta)
[0] Config.pm:307> INFO - Logfile is 'ulautitzh.blg'
[101] biber-MSWIN64:327> INFO - === 
[125] Biber.pm:415> INFO - Reading 'ulautitzh.bcf'
[280] Biber.pm:952> INFO - Found 1 citekeys in bib section 0
[300] Biber.pm:4265> INFO - Processing section 0
[300] Utils.pm:76> INFO - Globbing data source 'ä.bib'
[337] Utils.pm:93> INFO - Globbed data source 'ä.bib' to '�.bib'
[355] Biber.pm:4464> INFO - Looking for bibtex format file '�.bib' for section 0
[702] Utils.pm:322> ERROR - Cannot find '�.bib'!
[702] Biber.pm:132> INFO - ERRORS: 1
```

**Comment by plk** [comment]
I am afraid I think this is going to marked "wontfix" because it is a lot more of a problem than appears here - it's a general problem with Windows and Unicode file name handling. There will be problems in many places using such names in windows unless a lot of Windows-specific API code is put in to deal with this. It's fine in most OSX/linux systems because UTF-8 is prevalent and we don't have the whole ANSI code page mess. Windows is UTF16-LE for filesystem names at heart and this basically means using the `WIn32::` tree of modules to deal with all file operations like testing, open and creation to ensure Unicode compatibility. I might look at this one day but it's more likely that a future perl version will do something about this.

**Comment by cruessler** [comment]
Thanks for your efforts!

Just for context: I had the problem under Ubuntu 19.10. Would it be an option to treat filenames as opaque and use them as-is, or is that impossible/creates more issues than it solves?

**Comment by plk** [comment]
I'm not entirely convinced that this will help as there are other places where guessing encodings might not work, apart from globbing data sources. However, there is a reasonable case for an option to disable globbing and so in DEV 2.15, there is now the `--noglob` biber option which you can try ...

**Comment by cruessler** [comment]
I just got to trying `--noglob`, and it immediately worked (I used `latexmk` to compile a `*.tex` file that had a bibliography entry containing `ä` in its filename).

Thanks again!

**Comment by moewew** [comment]
`--noglob` doesn't appear to be helping on Windows, but you already expected that.

Given that `--noglob` helps on Linux as confirmed by @cruessler maybe we should think about making no globbing the default and have the user explicitly enable globbing when they want it. My reasoning is that more users are interested in using non-ASCII chars than there are interested in globbing. (And those who want globbing are probably more likely to read the docs.)

I'm thinking it would be nice if users could enable globbing in `biblatex` per `\addbibresource` line:

```latex
\addbibresource{complex name with äßöè.bib} % no globbing by default
\addbibresource[glob=true]{globme*.bib} % enable globbing explicitly
```
