### ISSUE TITLE
Not really an issue, but...

### ISSUE THREAD

**Issue by p-neves** [plk/biber#311]
Sorry if this is not the right place, but I did try to find a forum...
I'm running biber on my bib file and I have a few warnings like this:

WARN - BAD RECURSION! Entry alias 'citekey...' is identical to the entry key, skipping ... 
How can I fix them?

Also, I'm getting these warnings:

INFO - Overriding locale 'pt-PT' defaults 'normalization = NFD' with 'normalization = prenormalized'
INFO - Overriding locale 'pt-PT' defaults 'variable = shifted' with 'variable = non-ignorable'
INFO - Sorting list 'nyt/global//global/global' of type 'entry' with template 'nyt' and locale 'pt-PT'
INFO - No sort tailoring available for locale 'pt-PT'

Anything I can do?

thanks in advance.

Pedro

**Comment by plk** [comment]
Best foru is tex.stackexchange.com as we frequent there and there is a large community of biblatex/biber users - you will usually get rapid help there. The INFO lines are normal for locales - they are only relevant if you are getting the wrong results. The recursion warning could be an issue - best to post this and your .bib to TSE.

**Comment by p-neves** [comment]
thanks. I'll do it...

**Comment by moewew** [comment]
@p-neves The following MWE reproduces a "BAD RECURSION!" warning
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}


\begin{filecontents}{\jobname.bib}
@article{sigfridsson,
  author       = {Sigfridsson, Emma and Ryde, Ulf},
  title        = {Comparison of methods for deriving atomic charges from the
                  electrostatic potential and moments},
  journaltitle = {Journal of Computational Chemistry},
  date         = 1998,
  volume       = 19,
  number       = 4,
  pages        = {377-395},
  doi          = {10.1002/(SICI)1096-987X(199803)19:4<377::AID-JCC1>3.0.CO;2-P},
  ids          = {sigfridsson},
}
\end{filecontents}
\addbibresource{\jobname.bib}


\begin{document}
\autocite{sigfridsson}
\printbibliography
\end{document}
```
It is caused by giving the entry key (`sigfridsson`) again in the `ids` field (`ids = {sigfridsson},`). That isn't needed
```latex
@article{sigfridsson,
  author       = {Sigfridsson, Emma and Ryde, Ulf},
  title        = {Comparison of methods for deriving atomic charges from the
                  electrostatic potential and moments},
  journaltitle = {Journal of Computational Chemistry},
  date         = 1998,
  volume       = 19,
  number       = 4,
  pages        = {377-395},
  doi          = {10.1002/(SICI)1096-987X(199803)19:4<377::AID-JCC1>3.0.CO;2-P},
  ids          = {sigfridsson},
}
```
is enough.

So check your `.bib` file for `ids` fields which contain the actual entrykey.

The `ids` field is only needed if you want to refer to an entry with an additional(!) key that is different from the entry key given at the beginning of the entry.

**Comment by p-neves** [comment]
> So check your `.bib` file for `ids` fields which contain the actual entrykey.

I did it. I've removed all the ids fields and all the warnings are gone. 
Thanks for the info...
