### ISSUE TITLE
Error in processing files with Unicode names.

### ISSUE THREAD

**Issue by NiranjanTambe** [plk/biber#315]
My Biber version is 2.14. I cannot process files with Unicode names. Biber gives some errors. See [this](https://github.com/plk/biber/files/4648594/MWE.zip) MWE.

**Comment by plk** [comment]
Are you on Windows? Can you try with the '--noglob' option in DEV version 2.15?

**Comment by NiranjanTambe** [comment]
I am on a Linux machine. I don't have access to windows machine right now. Also I can't see version 2.15. This is tlmgr on my terminal - 

```
sudo /usr/local/texlive/2020/bin/x86_64-linux/tlmgr update biber
tlmgr: package repository http://mirror.utexas.edu/ctan/systems/texlive/tlnet (verified)
tlmgr: saving backups to /usr/local/texlive/2020/tlpkg/backups
tlmgr: no updates available
```

**Comment by plk** [comment]
There is no update as 2.15 is a DEV version which you would have to install manually from Sourceforge (and you would need DEV version 3.15 of biblatex too). I would expect these versions will be released in a few weeks.

**Comment by NiranjanTambe** [comment]
Okay no problem, I'll do that and update here. Thanks a lot :)

**Comment by moewew** [comment]
On Ubuntu Biber 2.15 dev seems to work fine even without `--noglob`. I get a few info messages about wide characters, but I think they only come from the logging module, so are only minor annoyances
```
m@m-VirtualBox:~/Downloads/niran$ biber चाचणी
INFO - This is Biber 2.15 (beta)
INFO - Logfile is 'à¤à¤¾à¤à¤£à¥.blg'
Wide character in print at /tmp/par-6d/cache-1a4fdf855996638cd8c0ba2830c3db34bc6301de/inc/lib/Log/Log4perl/Appender/Screen.pm line 41.
INFO - Reading './चाचणी.bcf'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
Wide character in print at /tmp/par-6d/cache-1a4fdf855996638cd8c0ba2830c3db34bc6301de/inc/lib/Log/Log4perl/Appender/Screen.pm line 41.
INFO - Globbing data source 'चाचणी.bib'
Wide character in print at /tmp/par-6d/cache-1a4fdf855996638cd8c0ba2830c3db34bc6301de/inc/lib/Log/Log4perl/Appender/Screen.pm line 41.
INFO - Globbed data source 'चाचणी.bib' to 'चाचणी.bib'
Wide character in print at /tmp/par-6d/cache-1a4fdf855996638cd8c0ba2830c3db34bc6301de/inc/lib/Log/Log4perl/Appender/Screen.pm line 41.
INFO - Looking for bibtex format file 'चाचणी.bib' for section 0
INFO - LaTeX decoding ...
INFO - Found BibTeX data source 'चाचणी.bib'
INFO - Overriding locale 'en-US' defaults 'normalization = NFD' with 'normalization = prenormalized'
INFO - Overriding locale 'en-US' defaults 'variable = shifted' with 'variable = non-ignorable'
INFO - Sorting list 'nty/global//global/global' of type 'entry' with template 'nty' and locale 'en-US'
INFO - No sort tailoring available for locale 'en-US'
INFO - Writing 'चाचणी.bbl' with encoding 'UTF-8'
INFO - Output to चाचणी.bbl
```

----

On Windows I can't even call Biber on the file name without error. So Biber doesn't even get to the stage where it could try and find the `.bib` file (where `--noglob` might help).

```
pdfLaTeX चाचणी
```
works.
But
```
biber चाचणी
```
dies with
```
Can't open ?????.blg (Invalid argument) at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-94ec564dc44f673d88301e9538815bffdd899a02\inc\lib/Log/Log4perl/Appender/File.pm line 151.   
```

**Comment by plk** [comment]
This is due to windows horrible legacy codepage handling. It could be done potentially in `biber` but I'd have to conditionalise all file operations on Windows OS, include a pile of special Windows modules and call the "wide" API calls to get this to work. It's a possibility but it's quite a bit of work. On Linux, it just depends on the locale of the shell.

**Comment by moewew** [comment]
I guess it's similar to what you explained in https://github.com/plk/biber/issues/310, right?

I think it would be incredibly nice to have Biber accept non-ASCII chars everywhere, but I can fully understand that you are not keen on digging in the depths of  Perl's and Windows' file handling. Ideally Perl would just support this out of the box (and that doesn't appear to be easy, otherwise Perl would probably have done this by now)

**Comment by plk** [comment]
@moewew - I have had a look at this and 2.15 DEV has some new code to begin to address this if you could test it. I have done some preliminary testing and it seems reasonable and backwards compatible but we need to test a bit more on Windows.

**Comment by moewew** [comment]
That sounds exciting. 



Unfortunately, with the 64bit Windows dev version from SourceForge I get
```
D:\Moritz\Documents\TeX\zhample\314kijk>.\biber.exe totallyfree
INFO - This is Biber 2.15 (beta)
INFO - Logfile is 'totallyfree.blg'
Can't locate loadable object for module Win32::Unicode in @INC (@INC contains: C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-8eb9b68a95838fa5bb6d005b9bd9b0338a246608\inc\lib C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-8eb9b68a95838fa5bb6d005b9bd9b0338a246608\inc CODE(0x38a19d8) CODE(0x38a1fc0)) at /loader/HASH(0x6c4400)/PAR/Heavy.pm line 116.
Compilation failed in require at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-8eb9b68a95838fa5bb6d005b9bd9b0338a246608\inc\lib/Win32/Unicode/Util.pm line 13.
BEGIN failed--compilation aborted at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-8eb9b68a95838fa5bb6d005b9bd9b0338a246608\inc\lib/Win32/Unicode/Util.pm line 13.
Compilation failed in require at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-8eb9b68a95838fa5bb6d005b9bd9b0338a246608\inc\lib/Win32/Unicode/File.pm line 11.
BEGIN failed--compilation aborted at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-8eb9b68a95838fa5bb6d005b9bd9b0338a246608\inc\lib/Win32/Unicode/File.pm line 11.
Compilation failed in require at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-8eb9b68a95838fa5bb6d005b9bd9b0338a246608\inc\lib/Biber/Utils.pm line 115.  
```

![biber-inc32win](https://user-images.githubusercontent.com/6755835/82735654-850f2580-9d23-11ea-8b4e-53a54ab1f964.PNG)

**Comment by plk** [comment]
I thought there might be some dependencies which need manual linking - can you try it again now? Unfortunately, I don't have a vanilla VM to test it on currently.

**Comment by moewew** [comment]
Still no luck, though the message is slightly different now
```
Can't locate loadable object for module Win32::Unicode in @INC (@INC contains: C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-421fdcd4b95ae176acf2a915e665b8789fe2a690\inc\lib C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-421fdcd4b95ae176acf2a915e665b8789fe2a690\inc CODE(0x38c68a8) CODE(0x38c6e90)) at /loader/HASH(0xf0a7a0)/PAR/Heavy.pm line 116.
Compilation failed in require at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-421fdcd4b95ae176acf2a915e665b8789fe2a690\inc\lib/Win32/Unicode/Util.pm line 13.
BEGIN failed--compilation aborted at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-421fdcd4b95ae176acf2a915e665b8789fe2a690\inc\lib/Win32/Unicode/Util.pm line 13.
Compilation failed in require at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-421fdcd4b95ae176acf2a915e665b8789fe2a690\inc\lib/Win32/Unicode/File.pm line 11.
BEGIN failed--compilation aborted at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-421fdcd4b95ae176acf2a915e665b8789fe2a690\inc\lib/Win32/Unicode/File.pm line 11.
Compilation failed in require at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-421fdcd4b95ae176acf2a915e665b8789fe2a690\inc\lib/Biber/Utils.pm line 115.

```

**Comment by plk** [comment]
That issue should be addressed now in DEV.

**Comment by moewew** [comment]
`grüße-fy-bn.tex`: works
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}


\begin{filecontents}[force]{gruesse.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  date    = {1980},
}
\end{filecontents}
\addbibresource{gruesse.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,appleby}
\printbibliography
\end{document}
```
---
`gruesse-fn-by.tex` does not work
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}


\begin{filecontents}[force]{grüße.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  date    = {1980},
}
\end{filecontents}
\addbibresource{grüße.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,appleby}
\printbibliography
\end{document}
```
Biber says:
```
[0] Config.pm:304> INFO - This is Biber 2.15 (beta)
[0] Config.pm:307> INFO - Logfile is 'gruesse-fn-by.blg'
[131] biber-MSWIN64:328> INFO - === 
[157] Biber.pm:415> INFO - Reading 'gruesse-fn-by.bcf'
[308] Biber.pm:952> INFO - Found 2 citekeys in bib section 0
[330] Biber.pm:4271> INFO - Processing section 0
[330] Utils.pm:76> INFO - Globbing data source 'grüße.bib'
[344] Utils.pm:98> INFO - Globbed data source 'gru?ße.bib' to ''
[344] Utils.pm:76> INFO - Globbing data source 'biblatex-examples.bib'
[344] Utils.pm:98> INFO - Globbed data source 'biblatex-examples.bib' to 'biblatex-examples.bib'
[365] Biber.pm:4478> INFO - Looking for bibtex format file 'biblatex-examples.bib' for section 0
[733] bibtex.pm:1656> INFO - LaTeX decoding ...
[1002] bibtex.pm:1474> INFO - Found BibTeX data source 'C:/Program Files/MiKTeX 2.9/bibtex/bib/biblatex/biblatex-examples.bib'
[1047] Utils.pm:335> WARN - I didn't find a database entry for 'appleby' (section 0)
[1059] UCollate.pm:68> INFO - Overriding locale 'en-GB' defaults 'normalization = NFD' with 'normalization = prenormalized'
[1059] UCollate.pm:68> INFO - Overriding locale 'en-GB' defaults 'variable = shifted' with 'variable = non-ignorable'
[1059] Biber.pm:4099> INFO - Sorting list 'nyt/global//global/global' of type 'entry' with template 'nyt' and locale 'en-GB'
[1059] Biber.pm:4105> INFO - No sort tailoring available for locale 'en-GB'
[1063] bbl.pm:652> INFO - Writing 'gruesse-fn-by.bbl' with encoding 'UTF-8'
[1065] bbl.pm:755> INFO - Output to gruesse-fn-by.bbl
[1071] Biber.pm:128> INFO - WARNINGS: 1
```
so globs `grüße.bib` to the empty string and does not find the file.

**Comment by plk** [comment]
Can you try with `--noglob` and also mail me in a zip the test files that don't work? I don't want to copy-paste as this messes up encodings and so I would like to test with your actual files.

**Comment by moewew** [comment]
`--noglob` gives
```
[0] Config.pm:304> INFO - This is Biber 2.15 (beta)
[0] Config.pm:307> INFO - Logfile is 'gruesse-fn-by.blg'
[131] biber-MSWIN64:328> INFO - === 
[156] Biber.pm:415> INFO - Reading 'gruesse-fn-by.bcf'
[332] Biber.pm:952> INFO - Found 2 citekeys in bib section 0
[356] Biber.pm:4271> INFO - Processing section 0
[376] Biber.pm:4478> INFO - Looking for bibtex format file 'grüße.bib' for section 0
[840] Utils.pm:351> ERROR - Cannot find 'grüße.bib'!
[841] Biber.pm:132> INFO - ERRORS: 1
```
oddly enough there is no attempt to load `biblatex-examples.bib`.


Mail is on the way.

**Comment by plk** [comment]
Ah, I think I see the issue - bit more complicated that I had hoped - will look into it tomorrow.

**Comment by moewew** [comment]
In case it is a globbing thing and non-ASCII files need `--noglob`, I'd like to repeat what I said earlier in https://github.com/plk/biber/issues/310#issuecomment-622939403

> Given that `--noglob` helps on Linux as confirmed by **cruessler** maybe we should think about making no globbing the default and have the user explicitly enable globbing when they want it. My reasoning is that more users are interested in using non-ASCII chars than there are interested in globbing. (And those who want globbing are probably more likely to read the docs.)
>
> I'm thinking it would be nice if users could enable globbing in `biblatex` per `\addbibresource` line:
>
>```latex
>\addbibresource{complex name with äßöè.bib} % no globbing by default
>\addbibresource[glob=true]{globme*.bib} % enable globbing explicitly
>```

I think it would be better to have users *enable* globbing explicitly than having them disable it. I'd guess that more users are interested in properly working non-ASCII names and spaces than globbing.

**Comment by plk** [comment]
Can you try 2.15 DEV now? I can get your examples to work now, with and without globbing. I removed the '--noglob' option, made it off by default and added '--glob-datasources' to enable it. I'll have a look at the per-datasource option.

**Comment by plk** [comment]
`\addbibresource` now has a `glob` option which override the `biber` default on a per-resource basis.

**Comment by moewew** [comment]
The new glob handling sounds great! Thank you.

---

`ü`, `í`, `ß` etc. in `.bib` file names work perfectly fine if the `.tex` file name does not contain non-ASCII chars
```latex
% saved as 'gruesse-fn-by.tex'
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}


\begin{filecontents}[force]{grüße-_-íslenska.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  date    = {1980},
}
\end{filecontents}
\addbibresource{grüße-_-íslenska.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,appleby}
\printbibliography
\end{document}
```

**But** `चाचणी` as `.bib` file name does not work
```latex
% saved as `niranjan.tex`
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}


\begin{filecontents}[force]{चाचणी.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  date    = {1980},
}
\end{filecontents}
\addbibresource{चाचणी.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,appleby}
\printbibliography
\end{document}
```
with error
```
INFO - This is Biber 2.15 (beta)
INFO - Logfile is 'niranjan.blg'
INFO - Reading 'niranjan.bcf'
INFO - Found 2 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex format file 'चाचणी.bib' for section 0
ERROR - Data file '?????.bib' cannot be read in encoding 'utf8': Can't call method "binmode" on an undefined value at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-efafc8b49acbcbf5b884725d0b0449f3778ce0b7\inc\lib/Biber/Utils.pm line 113.

INFO - ERRORS: 1
```

Non-ASCII file names also still appear to be a problem
```latex
% saved as `grüße-fy-bn.tex`
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}


\begin{filecontents}[force]{gruesse.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  date    = {1980},
}
\end{filecontents}
\addbibresource{gruesse.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,appleby}
\printbibliography
\end{document}
```
gives
```
[0] Config.pm:304> INFO - This is Biber 2.15 (beta)
[1] Config.pm:307> INFO - Logfile is 'grüße-fy-bn.blg'
[132] biber-MSWIN64:328> INFO - === 
[151] Utils.pm:392> ERROR - Cannot find control file 'grüße-fy-bn.bcf'! - Did latex run successfully on your .tex file before you ran biber?
[152] Biber.pm:132> INFO - ERRORS: 1
```

Files are attached (I had to delete `चाचणी.bib` because Windows would refuse to `.zip` it up) [uml.zip](https://github.com/plk/biber/files/4673756/uml.zip)

**Comment by plk** [comment]
Can you try again now? I think I have found all of the wrinkles in this and I can get all of your examples to work with 2.15 DEV now. It's ironic that Windows won't zip that file as that's likely the same issue as we are dealing with ...

**Comment by moewew** [comment]
That seems to have done it!

* Apparently, there is a bit of an issue when Biber gets called by `latexmk` on a non-ASCII filename, but I'm not sure if that is a `latexmk` or a Biber issue. Things work if I call Biber from the command line or if I have TeXworks call it for me.

* There is a file quoting issue with `\jobname` and several spaces, but that probably needs to be resolved on the LaTeX side and is low priority anyway.

MWE for the `\jobname` issue
```latex
% save as 'file with space.tex'
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}


\begin{filecontents}[force]{\jobname.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  date    = {1980},
}
\end{filecontents}
\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,appleby}
\printbibliography
\end{document}
```
fails with
```
[0] Config.pm:304> INFO - This is Biber 2.15 (beta)
[0] Config.pm:307> INFO - Logfile is 'file with space.blg'
[137] biber-MSWIN64:328> INFO - === 
[170] Biber.pm:415> INFO - Reading 'file with space.bcf'
[385] Biber.pm:953> INFO - Found 2 citekeys in bib section 0
[406] Biber.pm:4272> INFO - Processing section 0
[425] Biber.pm:4471> INFO - Looking for bibtex format file '"file with space".bib' for section 0
[855] Utils.pm:411> ERROR - Cannot find '"file with space".bib'!
[855] Biber.pm:132> INFO - ERRORS: 1
```
since the `.bcf` has
```latex
  <bcf:bibdata section="0">
    <bcf:datasource type="file" datatype="bibtex">&quot;file with space&quot;.bib</bcf:datasource>
    <bcf:datasource type="file" datatype="bibtex">biblatex-examples.bib</bcf:datasource>
  </bcf:bibdata>
```

**Comment by plk** [comment]
The jobname thing is some issue on the LaTeX side, and the `latexmk` is almost certainly the same problem as biber has since I believe that is perl too, I could advise on how to fix it.

**Comment by moewew** [comment]
Yes, the `\jobname` thing definitely comes from the LaTeX side adding quotes around file names with spaces to be able to deal with them properly. I might have a look if it is possible to get rid of the quotation marks easily next week, but if that's not easy, I'll probably not bother.

I was thinking the same thing about `latexmk`. What puzzles me a bit is that the LaTeX runs executed by `latexmk` work just fine, only the Biber runs get mangled (`lärche` becomes `lÃ¤rche`). Maybe `latexmk` treats different programs differently...

**Comment by plk** [comment]
That is a classic utf8 encoding error - probably easy to fix in latexmk. Is that only on windows?

**Comment by moewew** [comment]
I have only tested on Windows so far. I can run a few tests on Linux as well, but that will have to wait until tomorrow (or later next week).

**Comment by moewew** [comment]
I haven't built and tested the 32bit Linux binaries yet, but with the 64bit binaries `latexmk` appears to work fine on 64bit Linux (Ubuntu 18.04 LTS) with all the three MWEs. So I expect the same for 32bit (I'll test on Ubuntu 14.04 LTS).

**Comment by NiranjanTambe** [comment]
Sorry for the late reply. I tried installing `biber-dev 2.15`, but I was not able to. Today I installed the released version of `biber`. It works perfectly on my Linux machine :) Thank you so much for this work. You can close this issue if you want. Just out of curiosity, does this now work with windows?

**Comment by plk** [comment]
Yes, this should work with Windows too.

**Comment by NiranjanTambe** [comment]
Thanks!
