### ISSUE TITLE
Input files in --output-directory not being found

### ISSUE THREAD

**Issue by wdeshazer** [plk/biber#323]
I am using the biber 2.14 which is the latest version managed by MikTek Console 4.0 on Windows 10. I have various latex components putting auxiliary files in a build folder. I have a bib file in one non-local directory and point to it using the --input-directory flag. I then use the --output-directory to point to the build directory to utilize the .bcf file. Instead of finding the file, it reports an error:

INFO - This is Biber 2.14
INFO - Logfile is 'aux-files\gttran_proposal.blg'
ERROR - Cannot find 'gttran_proposal.bcf'!
INFO - ERRORS: 1

If you need more information, please let me know.

**Comment by plk** [comment]
Can you show the exact command line and layout of the input/output files?

**Comment by wdeshazer** [comment]
I am keeping this generic.

 

Directory layout

 

.bcf location

C:\Users\username\project folder\aux-files\project.bcf

 

.bib file location

C:\Users\username\LatexRoot\bibtex\bib\references.bib

 

Inside the project directory the command line that I execute is:

 

Project folder>biber --input-directory=C:\Users\username\LatexRoot\bibtex\bib --output-directory=aux-files gttran_proposal

INFO - This is Biber 2.14

INFO - Logfile is 'aux-files\gttrans_proposal.blg'

ERROR - Cannot find 'gttrans_proposal.bcf'!

INFO - ERRORS: 1

 

Inside the aux-files directory the command results in:

 

Project folder\aux-files>biber --input-directory=C:\Users\username\LatexRoot\bibtex\bib gttran_proposal.bcf

INFO - This is Biber 2.14

INFO - Logfile is 'gttran_proposal.blg'

INFO - Reading 'gttran_proposal.bcf'

INFO - Found 2 citekeys in bib section 0

INFO - Processing section 0

INFO - Globbing data source 'Plasma-Transport-Code.bib'

INFO - Globbed data source 'Plasma-Transport-Code.bib' to Plasma-Transport-Code.bib

INFO - Looking for bibtex format file 'Plasma-Transport-Code.bib' for section 0

INFO - LaTeX decoding ...

INFO - Found BibTeX data source 'C:\Users\username\LatexRoot\bibtex\bib\Plasma-Transport-Code.bib'

WARN - BibTeX subsystem: C:\Users\username\AppData\Local\Temp\biber_tmp_yGw1\Plasma-Transport-Code.bib_6556.utf8, line 6, warning: 172 characters of junk seen at toplevel

INFO - Overriding locale 'en-US' defaults 'variable = shifted' with 'variable = non-ignorable'

INFO - Overriding locale 'en-US' defaults 'normalization = NFD' with 'normalization = prenormalized'

INFO - Sorting list 'nty/global//global/global' of type 'entry' with template 'nty' and locale 'en-US'

INFO - No sort tailoring available for locale 'en-US'

INFO - Writing 'gttran_proposal.bbl' with encoding 'UTF-8'

INFO - Output to gttran_proposal.bbl

INFO - WARNINGS: 1

**Comment by plk** [comment]
The docs are misleading here - `--output-directory` is only checked for *input* files if `--input-directory` is _not_ specified. I have updated the docs in Git DEV. It's a bit confusing otherwise - if input files are not looked for in `--input-directory` when that is explicitly specified ...

**Comment by wdeshazer** [comment]
I understand. Is there a convenient way to specify multiple input directory locations? If not, I have a feature request for multiple input directories. A format for such could either be a semi-colon separated PATH like argument to the –input-directory flag or provision for multiple –input-directory’s.

 

Thanks.

**Comment by plk** [comment]
There is already a multiple-location option effectively as `biber` will use `kpsewhich` to find files if they are not found otherwise - `kpsewhich` is the TeX way of locating files which are in many locations in the TeX tree and you can customise where it looks with environment variables. I wouldn't really want to mirror this in the options for file searching as this would be somewhat over the top I think.
