### ISSUE TITLE
journal field is missing after bibtex extraction and conversion

### ISSUE THREAD

**Issue by stefan11** [plk/biber#328]
As a follow up on #322 I have a problem with disappearing journaltitles. I use the following code to produce a file gt.bib:
```
        xelatex -no-pdf -interaction=nonstopmode -shell-escape bib-creation 
	biber --output_format=bibtex --output-field-replace=location:address,journaltitle:journal,date:year --output-legacy-date bib-creation.bcf -O gt_tmp.bib
	biber --tool --configfile=biber-tool.conf --output-field-replace=location:address,journaltitle:journal,date:year --output-legacy-date gt_tmp.bib -O gt.bib
```
The result has all the "journal" fields missing.

This is bibertool.conf:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<config>
    <output_fieldcase>lower</output_fieldcase>
    <output_indent>2</output_indent>
    <output_align>true</output_align>
    <sourcemap>
        <maps datatype="bibtex" map_overwrite="1">
            <map map_overwrite="1">
                <map_step map_field_set="annotation" map_null="1"/>
                <map_step map_field_set="abstract"   map_null="1"/>
            </map>
        </maps>
    </sourcemap>
</config>
```

**Comment by plk** [comment]
Hmm, does it look correct after the first `biber` run (that is, does `gt_tmp.bib` look correct? By the way, you shouldn't need `data:year` in the `--output-field-replace` since `--output-legacy-date` does that for you and covers dates properly.

**Comment by stefan11** [comment]
Ah, thanks. Removed this. The command

`biber --output_format=bibtex --output-field-replace=location:address,journaltitle:journal --output-legacy-date bib-creation.bcf -O gt_tmp.bib`

gives:
```latex
@ARTICLE{Abbott76a-u,
  AUTHOR = {Abbott, Barbara},
  JOURNAL = {Linguistic Inquiry},
  NUMBER = {4},
  PAGES = {639--642},
  TITLE = {Right Node Raising as a Test for Constituenthood},
  VOLUME = {7},
  YEAR = {1976},
}
```

and a further call of
`biber --tool --configfile=biber-tool.conf --output-field-replace=location:address,journaltitle:journal --output-legacy-date gt_tmp.bib -O gt.bib`

```latex
@article{Abbott76a-u,
  author = {Abbott, Barbara},
  number = {4},
  pages  = {639--642},
  title  = {Right Node Raising as a Test for Constituenthood},
  volume = {7},
  year   = {1976},
}
```

Interestingly if I omit the field replacement, the journaltitle is still missing.

**Comment by plk** [comment]
I have a feeling that the issue is the `biber-tool.conf` that you are using in the tool run is not a modified form of the full default tool config file (you can get the location of this with the `--tool-config` option. The default has the usual default mapping of `journal`->`journaltitle` but yours doesn't and so on the tool run, there is no `journaltitle` field to output at all and `journal` is ignored as it's not a valid `biblatex` field. I would recommend always coping the default tool config file and modifying it to retain all the default settings.

**Comment by stefan11** [comment]
Thank you very much! o I removed the mappings in the first call and only did them with the tool-mode call. This is leaner anyway! I am now a happy fan of biber! (could be a bit faster though. =;-)
