### ISSUE TITLE
Use $HOME/.config if $XDG_CONFIG_HOME is either not set or empty

### ISSUE THREAD

**Issue by logological** [plk/biber#331]
In what I assume is an attempt at compliance with the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), Biber looks for its configuration file in `$XDG_CONFIG_HOME/biber/biber.conf`. However, this seems to work only in the (relatively rare ) case that the `$XDG_CONFIG_HOME` environment variable is actually set to the name of the base directory for user-specific configuration files.

What the specification actually says is that applications should assume that user-specific configuration files are placed in `$HOME/.config` unless `$XDG_CONFIG_HOME` is defined and points to a different directory.  Biber doesn't seem to be in compliance with this specification, since it doesn't find the configuration file if you put it in `$HOME/.config/biber/biber.conf` but (as is the default with most OSes I've used) leave `$XDG_CONFIG_HOME` undefined.

Please consider changing Biber's behaviour so that, if `$XDG_CONFIG_HOME` is not set or empty, it looks for the configuration file in `$HOME/.config/biber/biber.conf`.

**Comment by plk** [comment]
A fair point, should be addressed in 2.16 DEV shortly. We will have to leave `$HOME/.biber.conf` first for backwards compat as many people won't know about the `$HOME/.config` default.

**Comment by logological** [comment]
Oh, of course.  I wasn't suggesting that Biber stop looking for the configuration file in the usual places; only that it *also* look in the default place defined by the XDG Base Directory Specification.
