### ISSUE TITLE
extended names and line breaks

### ISSUE THREAD

**Issue by u-fischer** [plk/biber#333]
In the following example the first entry is fine, but the second crashes biber with a runaway error. The only difference is the placement of the comma:

~~~~
[284] Utils.pm:395> WARN - BibTeX subsystem: C:\Users\NILILA~1\AppData\Local\Temp\biber_tmp_tdtc\aae80d5f89b5757ce671796114d3a467_16456.utf8, line 13, warning: possible runaway string started at line 12
~~~~

~~~~
\begin{filecontents}{extnames.bib}
@article{testA,
    author = {family=Cruz,given=Maria
              ,prefix=De},
    title = {Just a title},
}

@article{textB,
    author = {family=Cruz,given=Maria,
              prefix=De},
    title = {Just a title},
}

\end{filecontents}

\documentclass[]{article}
\usepackage[style=authoryear]{biblatex}
\addbibresource{extnames.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
~~~~

**Comment by plk** [comment]
Hmm, this is very tricky to deal with properly as it's a message from the underlying `btparse` library which would need fixing in the C code and it's already being abused to do all the things we want. It's to do with the equals sign and the internals of bibtex parsing. For example, if you change the `xnamesep`, it's fine:

```
@article{textB,
    author = {family>Cruz,given>Maria,
              prefix>De},
    title = {Just a title},
}
```

and run `biber -xnamesep='>'`

**Comment by u-fischer** [comment]
Hm, I don't think that it would be a good idea to have more than one xnamesep around, imho you then get the same problems as with a special listsep. 

I don't know enough about the technical background to be able to make some suggestion, but imho there should be at least a note and perhaps an example for a multiline entry in the documentation.

**Comment by moewew** [comment]
I'm wondering if it makes sense to at least mention this issue in the Text::BibTeX tracker so they know about it (as I understand things like this are unlikely to be fixed at the moment, but you never know).

**Comment by plk** [comment]
It won't be fixed as I'm the one who fixes the btparse things in `Text::BibTeX` as they pertain to `biber` ... it's a completely `biber` related issue due to the extended name format which `btparse` was never designed to parse - it doesn't happen with commas in the same place for a normal `bibtex` name and has to do with the parser grammer in `btparse` getting confused by the equals sign in the extended name format.
