### ISSUE TITLE
Feature request: use month macros with `--output-legacy-date`

### ISSUE THREAD

**Issue by bersbersbers** [plk/biber#341]
I prefer `jan`, `feb`, etc. instead of `{01}`, `{02}`. Could `biber --tool` use these macros when outputting legacy dates?

**Comment by plk** [comment]
Should now be implemented in 2.16 DEV. By default, standard month macros will be output with `--output-legacy-dates` in tool mode unless the option `--nostdmacros` is used to turn off standard BibTeX macros.

**Comment by bersbersbers** [comment]
First testing suggest this is working. I'll confirm over the weekend.

**Comment by bersbersbers** [comment]
Yes, I believe this is working in 2.16 dev. Thanks!
