### ISSUE TITLE
Feature request: leave strings untouched in tool mode

### ISSUE THREAD

**Issue by bersbersbers** [plk/biber#342]
Assume this bib file:
```
@string{P = {Publisher}}

@article{key,
  author    = {Äuthörs},
  title     = {Title},
  publisher = P
}
```

With `biber --tool --output-safechars bug.bib`, this is what I get:

```
@ARTICLE{key,
  AUTHOR = {\"{A}uth\"{o}rs},
  PUBLISHER = {Publisher},
  TITLE = {Title},
}
```

You see that `@string{P, ...}` is gone, and the `PUBLISHER` is now static.

`biber --tool --output-safechars bug.bib --output-macro-fields=publisher` is not any better (obviously, it concerns only the output):

```
@ARTICLE{key,
  AUTHOR = {\"{A}uth\"{o}rs},
  PUBLISHER = Publisher,
  TITLE = {Title},
}
```

Would there be a way to leave strings untouched?

**Comment by plk** [comment]
Can you try this now? 2.16 DEV tries to auto-detect (full-field) macros and to output them without braces. This deprecates the `output-macro-fields` option which is no longer needed.

**Comment by bersbersbers** [comment]
First testing suggests this is not yet working. In the first example, the string is still replaced (`PUBLISHER = {Publisher}`).

In the second example, the publisher is still missing.

**Comment by plk** [comment]
It was not working. It should be working now in 2.16 DEV. There are two new options to control aspects of this: `--nooutputmacros` will suppress output of macros in the target, by default `biber` will now output the macro definitions that are used in the output entries. You would use this option if you, for example, had your macros in a separate file. The option `output_all_macros` forces writing of all macros read on input, regardless of whether they were used or not. There are perhaps some output formatting options to add for macros but I'm not convinced it's that important. One caveat here is that this won't handle macros which are just part of a field value - it is assumed, as in most of the use cases, that the entire field value is a macro. Reversing this for part-fields would be very messy and almost no-one does this anyway. There are also much cleaner ways (XDATA) to handle this in Biber anyway.

**Comment by bersbersbers** [comment]
Thanks, this is working much better now. Two more questions:

1. Taken together, `--nooutputmacros --output-all-macros` look a bit self-contradictory. I don't personally care since I know what they do, but maybe you want to use different names for new people. Like, `--nooutputmacros` and `--use-macros-in-entries` or something like this.

> There are perhaps some output formatting options to add for macros

2. Yes, in fact: My CamelCase macros are all turned lowercase. As I have noticed that `bibtool` does the same thing essentially (https://github.com/ge-ne/bibtool/issues/79), I wonder if it is just me being awkward to use CamelCase for macros (and whether I should turn to lowercase macros once and for all), or whether it would make sense to maintain their (input) capitalization. I'd expect the latter - for example, you don't touch capitalization of keys, either.

> but I'm not convinced it's that important.

Well, version-control stability is always an interesting thing. If you `biber --tool` a file for the first time, turning all macros lowercase may introduce unnecessary changes and bloat the diff. But again, if there's consensus that macros should preferably be all lowercase, I'd be happy to follow that and change my bib files.

**Comment by plk** [comment]
I have changed this to `--output-no-macrodefs` and `--output-all-macrodefs` for clarity. The option `--output-fieldcase` also determines casing for macro definitions and their use cases in the entries but camelcase is not supported. This shouldn't matter since macro defs/use in bibtex are case insensitive anyway. It's too messy to make input/output of all legacy bibtex format VC idempotent since `biber` has better facilities for macros anyway (XDATA).

**Comment by bersbersbers** [comment]
> The option `--output-fieldcase` also determines casing for macro definitions and their use cases in the entries but camelcase is not supported. This shouldn't matter since macro defs/use in bibtex are case insensitive anyway. It's too messy to make input/output of all legacy bibtex format VC idempotent since `biber` has better facilities for macros anyway (XDATA).

Fair enough. Thank you!
