### ISSUE TITLE
Update build instructions (and build process)

### ISSUE THREAD

**Issue by bersbersbers** [plk/biber#343]
I am building `biber` (on Linux as well as on Windows, mainly because my Linux system has only Perl 5.26 and I am not sure it finishes. edit: it does not, see below). I noticed the following things:

1. Docs
> have a working Perl 5.24+ installation

It now requires Perl 5.30, according to `Build.PL`:
```
    !  perl (5.26.1) is installed, but we need version >= 5.30.0
```

Also later in `build.sh`, I get:
```
/home/bers/perl5/bin/pp: Cannot find file or directory /usr/local/perl/lib/5.30.0/Unicode/Collate/Locale for packing
/home/bers/perl5/bin/pp: Cannot find file or directory /usr/local/perl/lib/5.30.0/Unicode/Collate/CJK for packing
/home/bers/perl5/bin/pp: Cannot find file or directory /usr/local/perl/lib/5.30.0/Unicode/Collate/allkeys.txt for packing
/home/bers/perl5/bin/pp: Cannot find file or directory /usr/local/perl/lib/5.30.0/Unicode/Collate/keys.txt for packing
/home/bers/perl5/bin/pp: Cannot find file or directory /usr/local/perl/lib/site_perl/5.30.0/Mozilla/CA/cacert.pem for packing
/home/bers/perl5/bin/pp: Cannot find file or directory /usr/local/perl/lib/5.30.0/x86_64-linux-thread-multi/PerlIO for packing
/home/bers/perl5/bin/pp: Cannot find file or directory /usr/local/perl/lib/5.30.0/x86_64-linux-thread-multi/auto/PerlIO for packing
/home/bers/perl5/bin/pp: Cannot find file or directory /usr/local/perl/lib/site_perl/5.30.0/Business/ISBN/RangeMessage.xml for packing
```
2. Docs
> source tree from SF

This is now GitHub, I guess.

3. Build.PL
```
> perl ./Build.PL

WARNING: the following files are missing in your kit:
        META.json
        META.yml
Please inform the author.
```

4. Docs
> Run the test suite with `Build test`

This could/should be `./Build test` (also a few more times elsewhere)

5. `pp`
I had to manually install `PAR::Packer` on both Windows and Linux.

6. `Win32::Unicode::File`
I had to force-install `Win32::Unicode::File` (due to https://github.com/xaicron/p5-win32-unicode/issues/7). This is an issue many Windows users may face, see also https://www.perlmonks.org/?node_id=1208723

7. `build.bat`
On Windows, I had to edit `build.bat` as my perl is installed in `C:\Programs\Strawberry`, and not in `C:\Strawberry`.

8. `pp -u`
I also removed from this file `--unicode` for now due to https://github.com/rschupp/PAR-Packer/issues/27 (although I guess this will not be required long-term, for `PAR::Packer>1.050`).

9. `build.sh`
On Linux, I also had to edit `build.sh` as my perl is installed in `/home/bers`, and I had to adapt several library locations (`/usr/lib64`, `/usr/lib`), library names (`libz.so `), and versions (`libssl.so.1.1`).

10. Test
`biber-MSWIN64.exe --validate-control --convert-control test` works, with one warning:

```
INFO - This is Biber 2.16 (beta)
INFO - Logfile is 'test.blg'
INFO - 'test.bcf' validates against schema 'C:\Users\bers\AppData\Local\Temp\par-59616e6e69636b\cache-13c92ab7980b36f3fc123230ca0f3cd98a08e73c\inc\lib/Biber\bcf.rng'
INFO - Converted BibLaTeX control file 'test.bcf' to 'test.bcf.html'
INFO - Reading 'test.bcf'
INFO - Using all citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex format file 'test.bib' for section 0
Use of uninitialized value in subroutine entry at C:\Users\bers\AppData\Local\Temp\par-59616e6e69636b\cache-13c92ab7980b36f3fc123230ca0f3cd98a08e73c\inc\lib/Biber/Utils.pm line 361.
Use of uninitialized value $filename in concatenation (.) or string at C:\Users\bers\AppData\Local\Temp\par-59616e6e69636b\cache-13c92ab7980b36f3fc123230ca0f3cd98a08e73c\inc\lib/Biber/Input/file/bibtex.pm line 121.
WARN - Data source '' is empty, ignoring
INFO - Overriding locale 'en-US' defaults 'variable = shifted' with 'variable = non-ignorable'
INFO - Overriding locale 'en-US' defaults 'normalization = NFD' with 'normalization = prenormalized'
INFO - Sorting list 'nty/global//global/global' of type 'entry' with template 'nty' and locale 'en-US'
INFO - No sort tailoring available for locale 'en-US'
INFO - Writing 'test.bbl' with encoding 'UTF-8'
INFO - Output to test.bbl
INFO - WARNINGS: 1
```

**Comment by plk** [comment]
Docs will be updated for 2.16 accordingly.
