### ISSUE TITLE
"biber -tool -O -" creates file named "-"

### ISSUE THREAD

**Issue by bersbersbers** [plk/biber#344]
This creates an empty file named `-` - this is not intended, is it?

```
echo "@article{test,}" > test.bib
biber --tool test.bib -O -
```

In addition, this puts all the output it into `out/-`
```
mkdir out
echo "@article{test,}" > test.bib
biber --tool test.bib --output-directory out -O -
```

I had expected the output still to go to `STDOUT`, while the log file goes into `out`.

**Comment by plk** [comment]
This must have been a bug for some time - please try 2.16 DEV now.

**Comment by bersbersbers** [comment]
Looks good, thanks!
