### ISSUE TITLE
There should be an option to set Serbian Cyrillic on some bibliography entries when using Serbian Latin for whole document or vice versa

### ISSUE THREAD

**Issue by Fooftilly** [plk/biber#348]
What I mean is that when writing your document in Serbian Latin you may want to cite something which was published in Cyrillic. The problem arises in the compiled bibliography where you get whole citation entry in Cyrillic and those fields that are dictated by serbian.lbx are compiled in Latin. The problem is also present when writing documents in Cyrillic and using Latin sources. Something like an option in bib entry which says which Serbian script should be used when compiling that entry would be useful.
**Example:**
![Literatura](https://user-images.githubusercontent.com/46610174/98997671-263da280-2535-11eb-8ee8-d291cc9e82e5.png)
_sine anno_ should not be looked at because it is set by date entry in bib file. The one I am talking about is the Prevod field (in the second line) which is set in the lbx file.

**Comment by moewew** [comment]
You may want to look into the `langid` field together with the `autolang` option. (There is an example of `langid`/`autolang` at https://tex.stackexchange.com/q/323441/35864. Some more background is at https://tex.stackexchange.com/q/493695/35864.)

**Comment by Fooftilly** [comment]
Thank you for the resources. I've got it working by setting 
...
\usepackage[serbian, serbianc]{babel}
...
\begin{document}
\selectlanguage{serbian}%At the beginning of the document
...
\end{document}

In bib file I used langid = {serbianc} for citation which I wanted in Cyrillic.

**Comment by moewew** [comment]
If your document is mainly in Latin Serbian, it may be easier to load `babel` as
```latex
 \usepackage[serbianc, serbian]{babel}
```
so that `sebian` (Latin Serbian) is the main language. You shouldn't need a `\selectlanguage{serbian}` at the beginning of the document in that case.
