### ISSUE TITLE
biber 2.14 and EDTF dates

### ISSUE THREAD

**Issue by retorquere** [plk/biber#352]
biber 2.14 already understands EDTF dates, correct? I have a user that [reports](https://github.com/retorquere/zotero-better-bibtex/issues/1695) biber 2.14 rejects `2016-01-19T14:20:00.000Z`:

```
WARN - Entry 'ruderOverviewGradientDescent2016' (dp.bib): Invalid format '2016-01-19T14:20:00.000Z' of date field 'date' - ignoring
```

but according to EDTF.js `2016-01-19T14:20:00.000Z` is a valid EDTF timestamp.

**Comment by plk** [comment]
Its unusual for milliseconds to be in bibliographical dates but I suppose it's possible if dates are auto-generated. So, I've added support for this in biber 2.16 in DEV - milliseconds will be accepted and ignored.

**Comment by retorquere** [comment]
As a workaround I've updated BBT to cut off the milliseconds until 2.16 is prevalent.
