### ISSUE TITLE
Interpreting non-ASCII characters as integers

### ISSUE THREAD

**Issue by NiranjanTambe** [plk/biber#356]
Try this code -

```
\documentclass{article}
\usepackage{marathi}
\usepackage[backend=biber, style=authoryear]{biblatex}
\begin{filecontents}[overwrite]{\jobname.bib}
@article{गौरी,
  author       = {मोघे, गौरी},
  title        = {तन्त्रशास्त्राचा परिचय},
  journaltitle = {आलोक मराठी नियतकालिक},
  date         = {२०२१},
  series       = {३},
  pages        = {१-५},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\cite{गौरी}

\printbibliography
\end{document}
```

One might notice that `pp. ` and `In: ` are missing in the output. This is because `३` and `१-५` are understood as characters and not as numerals, but well technically they are numerals. Changing `३` to `3` and `१-५` to `1-5` works. This forces users to use Latin numerals in their `.bib` files. For Marathi at least Devanagari numerals are shown even with the Latin numerals in the code because of the conversion programs by XeLaTeX and LuaLaTeX, but I am not sure if it is true for other languages, which means in the lack of a conversion program the output will show Latin numerals. Can something be done to make `biber` understand that `१`, `२`, `३`, `४`, `५`, `६`, `७`, `८`, `९` are numerals? (At least when these come in the `.bib` file of Marathi/Hindi/Sanskrit/Nepali.)

**Comment by sieversMartin** [comment]
Have you tried to configure numbers with `\DeclareNumChars`?

**Comment by NiranjanTambe** [comment]
Nope. How to do that?

**Comment by sieversMartin** [comment]
Please consult p. 262 of the documentation. Basically you can give a list of characters to be considered as a number.

**Comment by sieversMartin** [comment]
`\DeclareNumChars{१,२,३,४,५,६,७,८,९}`

**Comment by NiranjanTambe** [comment]
Thanks. Closing.

**Comment by moewew** [comment]
Note that `\DeclareNumChars` does not take a comma-separated argument. It just takes an undelimited list of characters. So you'd probably want
```latex
\DeclareNumChars{१२३४५६७८९}
```

**Comment by NiranjanTambe** [comment]
@moewew Thanks, but then is it understood as one number or every character is understood as different a separate string?

**Comment by moewew** [comment]
Each character is processed and treated separately. The argument of `\DeclareNumChars` is treated as an undelimited list of single characters.

**Comment by NiranjanTambe** [comment]
Okay thanks.
