### ISSUE TITLE
One-word strings are turned into macros by removing { and }

### ISSUE THREAD

**Issue by bersbersbers** [plk/biber#357]
TLDR: `biber --tool` changes the reference output by removing curly braces around one-word journal titles.

Consider this `bug.bib`:

```
@article{key,
  journal = {Nature},
}
@string{Nature = "Nature2"}
@article{key2,
  journal = Nature,
}
```

In my document
```
\documentclass{article}
\begin{document}
\cite{key, key2}
\bibliography{bug}
\bibliographystyle{plain}
\end{document}
```

I now see this:
![image](https://user-images.githubusercontent.com/12128514/101373504-4dc22980-38ad-11eb-8151-81a6ebb77ce0.png)

After `biber --tool bug.bib --output-format=bibtex --output-field-replace=journaltitle:journal`, I get this:

```
@STRING{NATURE = "Nature2"}

@ARTICLE{key,
  JOURNAL = Nature,
}

@ARTICLE{key2,
  JOURNAL = NATURE,
}
```

and the corresponding document 
```
\documentclass{article}
\begin{document}
\cite{key, key2}
\bibliography{bug_bibertool}
\bibliographystyle{plain}
\end{document}
```
shows
![image](https://user-images.githubusercontent.com/12128514/101373586-65011700-38ad-11eb-81e3-b02187fec8a4.png)

**Comment by bersbersbers** [comment]
This is using (some) version Biber 2.16 (beta).

**Comment by plk** [comment]
There is, I am afraid, not much that can be done about this. We have to look a the macro table of values to see if a field can/should be written as a macro without escapes and since we are basically trying to undo a change that leaves no traces when it comes out of `btparse`, it will always be imperfect when a field value is the same as a macro name as there is no way of telling these apart without a flag set when reading the source on a per-field basis. I would think that this is an edge case though.

**Comment by bersbersbers** [comment]
It's certainly an edge case, yes, and I have also found a workaround that's OK for me: `journal = {{Nature}}`. I think I was confused by the fact that one-word strings have their curly braces removed while that is not true for two-word strings (or numeric values, for that matter).

**Comment by plk** [comment]
The issue is whether the field value is a macro `@STRING` key or not ... if it is, it will be treated as a macro and will be a bare word. This will of course only apply to "one word" strings as only one word strings are valid macro keys ...

**Comment by bersbersbers** [comment]
Oh, I see - in this case, it becomes much easier to generate edge cases. Look at what happens to "Jan" (German first name) - but not to "Peter":

```
@article{key3,
  author = {Jan},
}
@article{key4,
  author = {Peter},
}
```

```
@ARTICLE{key3,
  AUTHOR = Jan,
}

@ARTICLE{key4,
  AUTHOR = {Peter},
}
```

Also, let's hope there's never a book being published in Mar (places in Iran or Russia), by people with that surname (https://en.wikipedia.org/wiki/Mar_(surname)), or papers about iron Bromide (FeB) or the annual percentage rate (APR). I could go on and on ;)

These are clearly none of my use cases, but if it's (only) the macros that lead to this behavior, this can have very rare, but very hard to debug consequences.

**Comment by plk** [comment]
True but that's very edge - a name field with a single word in it ... also, for month macros, it's easy to fix as they are a special macro type if it ever arises.
