### ISSUE TITLE
Add support for `--output_indent` option being tab?

### ISSUE THREAD

**Issue by alexreg** [plk/biber#362]
It looks like the `--output_indent` is currently only allowed to be N spaces? Would you kindly be able to add support for it being a tab instead?

**Comment by plk** [comment]
Please try 2.17 DEV on Sourceforge - you can now add "t" to the `--output-indent` option value to specify tabs instead of spaces.

**Comment by alexreg** [comment]
Excellent; that was quick! I'll give it a go now.

**Comment by alexreg** [comment]
```
Biber: Invalid non-numeric argument for 'output_indent' option!
```

**Comment by plk** [comment]
My mistake - forgot there was a check in the top-level command that my test suite doesn't use ... you can get it again from SF now.

**Comment by alexreg** [comment]
No worries. I actually just realised the syntax you implemented is, e.g., `1t` and not just `t`, as well. It's possibly a bit odd to have anything other than `1t`, but since you've already added support, why not! Works as expected, in any case. Thanks a lot.
