### ISSUE TITLE
Biber (tool mode) silently ignores entries with non-default separator.

### ISSUE THREAD

**Issue by alexreg** [plk/biber#364]
If I run `biber --tool --listsep='|' --namesep='|' ...` it seems to silently ignore all the bibliographic entries that include this list/name separator (i.e., not output them). I do occasionally get a warning about this, but it's not consistent, for some odd reason.

Running `biber --tool --listsep='|' --namesep='|' --output-listsep='|' --output-namesep='|' ...` works as expected, and includes all entries in my original `.bib` file.

It sounds like this is a matter of slightly improving the warning messages, I suppose?

**Comment by plk** [comment]
I'm not quite sure what the issue is here? Could you give the warnings? Are you saying that without the output options set, there are issue with with the input options for separators?

**Comment by alexreg** [comment]
@plk Without the output options set, any bibliographic entries containing (`|`) (e.g., in the `author` or `editor` field) gets silently omitted from the output. (Well, occasionally it will warn, but not reliably, for some reason.)

**Comment by plk** [comment]
Can you paste an example entry with this issue?

**Comment by alexreg** [comment]
```bibtex
@article{foo,
    author = {Bar1, Foo1 | Bar2, Foo2},
    title = {Foo},
    year = {2020},
    journaltitle = {Baz},
}
```

An entry like this simply gets omitted from the output, unless the `-output-*sep` options are specified (maybe only one of those two is needed, I forget).

**Comment by plk** [comment]
Hmm, can't reproduce this - with your example in file `test.bib` and running:

```
biber --tool --namesep="|" test.bib 
```

I get in the output file:

```
@ARTICLE{foo,
  AUTHOR = {Bar1, Foo1 and Bar2, Foo2},
  DATE = {2020},
  JOURNALTITLE = {Baz},
  TITLE = {Foo},
}
```

**Comment by alexreg** [comment]
Apologies; this is my mistake. I had run the above command *twice*, and the second time it (naturally) did not recognise the `and` separator output by the first run, and emits and error, excluding those entries from output. Looks like expected behaviour, so I'll close this issue.
