### ISSUE TITLE
Date bug in biber 2.16?

### ISSUE THREAD

**Issue by schoeps** [plk/biber#367]
Biber 2.16 complains about the date format in
```
@article{A,
  author = {Name, A.},
  journal = {XYZ},
  date = {2020-01-01},
  number = {1},
  pages = {1--1},
  title = {Paper},
  volume = {1},
}
```
such that `biber --tool --outfile test2.bib test.bib` results in a file `test2.bib` without any dates. This is fixed in 2.17. However 2.16 is currently shipped with texlive. Can you do a quick fix, please?

**Comment by moewew** [comment]
Works for me as expected, `test2.bib` 

```latex
@ARTICLE{A,
  AUTHOR = {Name, A.},
  DATE = {2020-01-01},
  JOURNALTITLE = {XYZ},
  NUMBER = {1},
  PAGES = {1--1},
  TITLE = {Paper},
  VOLUME = {1},
}
```

Maybe your cache is corrupted, see https://tex.stackexchange.com/q/541486/35864.

**Comment by schoeps** [comment]
Yes, deleting the cache folder helped. Thanks! This a rather unexpected behavior and it is the first time for me (albeit using biber quite heavily). 

Out of curiosity: does v2.17 use a different folder or why did that fix my problem?

**Comment by moewew** [comment]
Yeah, each Biber version has its own cache (sub)folder, so your 2.17 cache was probably OK while your 2.16 cache appeared corrupted. I
