### ISSUE TITLE
Invalid format '2020' of date field 'date' - ignoring

### ISSUE THREAD

**Issue by krumeich** [plk/biber#368]
Hi,

this might be a bit obscure: For a few weeks now, I've been experiencing unexpected behavior by biber: it does not accept bib-files that are perfectly acceptable and have not been touched.´:

```
WARN - Entry 'adv_arc' (../common/bibliographies/koco.bib): Invalid format '2020' of date field 'date' - ignoring
WARN - Entry 'adv_fsp' (../common/bibliographies/koco.bib): Invalid format '2020' of date field 'date' - ignoring
WARN - Entry 'alc_ndesign' (../common/bibliographies/koco.bib): Invalid format '2020' of date field 'date' - ignoring
WARN - Entry 'agd_adm' (../common/bibliographies/koco.bib): Invalid format '2020-07-14' of date field 'date' - ignoring
```

I can resolve this by removing the biber cache, as suggested in https://github.com/plk/biber/issues/312#issuecomment-762350156:

```
rm -rf $(biber --cache)
```

On the next run, biber unpacks its PAR cache again and all is well for a couple of days. For about three weeks now, removing biber's cache has become a weekly chore. Since this is not reproducible in an MWE, I've so far restrained from filing an issue. If someone has an idea, please put it forward. For now, I'm saving the current cache before deleting it in case someone needs to look into it.

This is biber 2.16 running under macOS 11.2

Thanks!

**Comment by plk** [comment]
Hmm, this was an issue a long time ago with the cache - it was an issue with the `PAR::Packer` module and its cache policy interacting badly with some OSes which merrily clean up tmp locations. I wonder if OS 11 is doing this but I don't currently have an OS 11 machine and won't have one until the new Macbook Pros come out, likely in Q3. What is the cache location?

**Comment by krumeich** [comment]
The cache that led to the results posted above was located at `/var/folders/5z/m95x5mt53b74vzg5q28d24380000gn/T/par-6b72756d65696368/cache-bc6986241d41958a757fc1df8a704e6d22b2f953`.

I have been on macOS 11 since around New Year. The problem did start after that. I cannot pinpoint whether this coincided with the upgrade to 11.2, but it could very well be. I don't recall having this problem in early January.

**Comment by krumeich** [comment]
Thanks for getting back to me. I don't have any of the variables set. As per your suggestion, I've set `PAR_GLOBAL_TEMP` (with an additional `E`) to a folder in my home directory. If the problem disappears, we can blame macOS. Let's keep the issue open for the time being. I'll set a reminder to close it in two weeks.

**Comment by krumeich** [comment]
The problem didn't occur again after moving the the Cache to somewhere in my home directory. Let's close this for now and see if it becomes an issue again once you get your Apple Silicon MacBook.

**Comment by fintelkai** [comment]
FWIW: This just happened to me on my M1 MacBook Air. biber version: 2.16

Deleting all the intermediate files and doing `rm -Rf "$(biber --cache)"` did the trick.

**Comment by krumeich** [comment]
Now that you mention it, this happened to me once more in the meantime. So far only on an x86_64 machine.

**Comment by moewew** [comment]
I think I saw a few posts on TeX.SX with a similar problem (https://tex.stackexchange.com/questions/linked/543837?sort=newest) most of them seem to use Mac OS.

**Comment by plk** [comment]
Which OSX version?

**Comment by moewew** [comment]
https://tex.stackexchange.com/q/588775/35864 says macOS Big Sur 11.2.3. https://tex.stackexchange.com/q/591740/35864 says just "Big Sur". Couldn't find more references to the OS version.

**Comment by plk** [comment]
I think that this is an issue with OSX 11 but I don't currently have a machine new enough to run it. I think it's clearing out the tmp location of the cache - a workaround until I can get a machine with OSX 11 to have a look is to set the env var `PAR_GLOBAL_TEMP` to some location in, for example, you home directory which won't be cleared by some automated process.

**Comment by fintelkai** [comment]
Just happened again with `biber --tool`. Removing the cache fixed it. (Biber 2.17, macOS Monterey 12.3.1 (21E258), M1 Pro)

**Comment by misilot** [comment]
I tried doing `rm -Rf "$(biber --cache)"` but I am still running into a similar issue

WARN - Entry 'ala-key-action-areas' (dei.bib): Invalid format '2020-04-02' of date field 'date' - ignoring

**Comment by plk** [comment]
@misilot - have you tried using the env variable `PAR_GLOBAL_TEMP` to set the cache location? It looks like your cache is in some location that is getting auto-cleaned by something.

**Comment by guillaume-hps** [comment]
@plk Can you show us an example of how to use this env variable ? I am not very experimented in LateX yet. I am using TeXstudio (v. 4.4.1) and macOS Ventura 13.1 (Macbook M1).

**Comment by plk** [comment]
Under MacOS 13, it's a bit of a pain if you want to set env vars for GUI apps (https://9to5answer.com/setting-environment-variables-in-os-x-for-gui-applications). But if you can start the app that needs the variable (e.g. `biber` from the terminal, then it's easy, just do, in the terminaL

```
export PAR_GLOBAL_TMP=<some path>
biber ....
```
