### ISSUE TITLE
Another platform: aarch64-linux

### ISSUE THREAD

**Issue by krumeich** [plk/biber#379]
What is the Linux distribution that you use to build the x86_64-linux version?

I'd like to run biber in Docker on my Apple Silicon Mac. Docker's target platform in macOS is arm64, which translates to aarch64 in TeX terms. Thus, I need a biber build for aarch64-linux. Of course I'm aware that you don't want to increase your build farm. I'd want to give it a try myself. 

Come to think of it, the arrival of ARM based machines in the market might further the wish for more biber platforms. Not only darwin on arm64 (macOS itself), but also Linux and (of course) Linux-musl on that architecture.

**Comment by plk** [comment]
The Linux 64 distribution being used is Ubuntu 10.10 currently. I plan to get a Apple Silicon machine later in the year when they are more options for them.

PK

> On 3 Jun 2021, at 1:45 pm, Alexander Krumeich ***@***.***> wrote:
>
>
> I'd like to run biber in Docker on my Apple Silicon Mac. Docker's target platform in macOS is arm64, which translates to aarch64 in TeX terms. Thus, I need a biber build for aarch64-linux.
>
> Of course I'm aware that you don't want to increase your build farm. I'd want to give it a try myself. Just to get me started: what is the Linux distribution that you use to build the x86_64-linux version?
>
> Come to think of it, the arrival of ARM based machines in the market might further the wish for more biber platforms. Not only darwin on arm64 (macOS itself), but also Linux and (of course) Linux-musl on that architecture.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

--
Dr Philip Kime

**Comment by krumeich** [comment]
Thanks. Ubuntu 10.10 seems a bit old. I might try something newer but not bleeding edge, e.g. 18.04 LTS. Today, I added support for linux-aarch64-musl (PR #381).
