### ISSUE TITLE
Slightly tweak message

### ISSUE THREAD

**Issue by moewew** [plk/biber#383]
Inspired by https://tex.stackexchange.com/q/601771/35864

The "format" in

> INFO - Looking for bibtex format file 'refrences' for section 0

from

https://github.com/plk/biber/blob/d222bb34312c3a2cc0001903e16475550fa25058/lib/Biber.pm#L4541-L4547

sounds a bit odd to me and almost suggests Biber is looking for a "format file".

Maybe the message would be clearer if it were to drop the "format"?

Personally, I prefer to refer to `.bib` files as "`.bib` files" and not as "BibTeX files" or some such to avoid the impression that the files are only to be used for BibTeX and that `biblatex` would somehow have a different file type or overall syntax.

**Comment by plk** [comment]
I've removed "format" but the the "bibtex" is auto-generated from the modular setup for source formats. This could be revisited at some point since the whole idea of different data sources (Endnote, RIS, DBs etc.) has fallen by the wayside somewhat as there is little demand for this.

**Comment by moewew** [comment]
Thanks!

Yeah, I saw that the bibtex is basically `$type`, so the last suggestion is one for the longer term.
