### ISSUE TITLE
nocited sourcemap does not apply in 2.17 dev

### ISSUE THREAD

**Issue by moewew** [plk/biber#386]
Consider
```latex
\documentclass{article}
\usepackage{biblatex}

\DeclareSourcemap{
  \maps[datatype=bibtex, overwrite]{
    \map{
      \step[nocited=true, final]
      \step[fieldset=note, fieldvalue={I was NOCITED}]
    }
  }
}


\addbibresource{biblatex-examples.bib}


\begin{document}
Lorem \nocite{sigfridsson,worman}

\printbibliography
\end{document}
```

With 2.16 I get

![Two entries showing "I was NOCITED"](https://user-images.githubusercontent.com/6755835/128300929-a219a77c-cab5-4ed8-9e87-d2931b2c2a79.png)

but with 

2.17 I get

![No "I was NOCITED" mark anywhere](https://user-images.githubusercontent.com/6755835/128300976-e509372b-dece-4d41-bfe9-c64065ee9911.png)

It appears that the `nocited` marker no longer applies properly.

**Comment by plk** [comment]
Was a brace placement issue causing writing of nocites twice (one as normal cites) in the `.bcf`
