### ISSUE TITLE
`--configfile` should also look for `.biber.conf in current directory

### ISSUE THREAD

**Issue by alexreg** [plk/biber#389]
It seems only reasonable/consistent to me (and in line with most other tools?) that biber should by default look for its configuration file as both `biber.conf` and `.biber.conf` in the current directory, and not just the former. How does that sound to you?

**Comment by plk** [comment]
Well, it does look for `~/.biber.conf` which is typical for home directly dot files and also in `~/config/.biber.conf` ... we can add `./.biber.conf` too but nobody has every requested it given all the other possibilities ...

**Comment by alexreg** [comment]
I'd appreciate that. It's probably not a common use, but it seems fair to include it for consistency and given that most other tools I know of seem to look for a dot-prefixed file in the current directory too. Thanks.

**Comment by plk** [comment]
Implemented in DEV branch.

**Comment by alexreg** [comment]
Thanks! I'll close this then.
