### ISSUE TITLE
Empty entry in bib-file leads to error when compiling with Biber

### ISSUE THREAD

**Issue by ThiloteE** [plk/biber#391]
**Programm used to create bib-file**

JabRef 5.3 (latest release)

**Programms used to compile the LaTeX document**

Miktex and Texmaker

**Operating system**

Windows, 20H1

**Steps to reproduce the behaviour**

1. open your bib-file (e.g. via Jabref or manually)
2. Create a new Entry (because you intend to enter a new entry, BUT THEN YOU CHANGE YOUR MIND AND FORGET DELETING IT)
3. Do not enter any data into the entry (= An empty entry).
4. This is how an empty entry looks like in the bib-file:

```
@Article{,
}
```

5. Save your libary > use this file for your latex project > try to compile your latex project with Miktex and Texmaker > Error ensues, which prevents me from completing my latex compilation.

**Error message in biber when i try to compile my document:**
```
Process started

INFO - This is Biber 2.16 INFO - Logfile is 'Democratic Backsliding in South-East-Asia (article).blg' INFO - Reading 'Democratic Backsliding in South-East-Asia (article).bcf' INFO - Found 62 citekeys in bib section 0 INFO - Processing section 0 INFO - Looking for bibtex format file 'bibliography.bib' for section 0 INFO - LaTeX decoding ... INFO - Found BibTeX data source 'bibliography.bib' WARN - Invalid or undefined BibTeX entry key in file 'C:\Users\Thilo\AppData\Local\Temp\biber_tmp_2wgH\f4d088b3f9f145b5c3058da33afd57d4_12036.utf8', skipping ... ERROR - BibTeX subsystem: C:\Users\Thilo\AppData\Local\Temp\biber_tmp_2wgH\f4d088b3f9f145b5c3058da33afd57d4_12036.utf8, line 3, syntax error: found ",", expected one of: number, name (entry type, key, field, or macro name), end of entry ("}" or ")") or quoted string ({...} or "...") INFO - WARNINGS: 1 INFO - ERRORS: 1

Process exited with error(s)
```

**Additional notes:**

I just thought i would let you know, since this is relevant for biber AND Jabref.

Here the relevant issue on Jabref:  https://github.com/JabRef/jabref/issues/8096

**Comment by plk** [comment]
Not much to be done about this as it's bad syntax and the internal libbtparse library just dies. We could put in a test for this to catch it but there are lots of ways to provide mangles entries and it's very rare.

**Comment by ThiloteE** [comment]
Trying to solve this on JabRef side via #8645

It has been found that the lack of a citationkey is enough to trigger an error using Biber
