### ISSUE TITLE
Allow configuration of `build.sh` script

### ISSUE THREAD

**Issue by alexreg** [plk/biber#394]
The final step of building & installation is running the `build.sh` script for the appropriate target architecture. For my macOS system, this does not seem to work. The problem is mainly that it hard-codes paths like `/opt/local/lib/perl5/` and `/opt/local/libexec/perl5/`. I have Homebrew Perl installed, which is under `/usr/local`. Also, it might be nice to install in a user-local location like `~/perl5`. Finally, note that the version `pp` on macOS does not accept all the arguments the script passes to it.

**Comment by plk** [comment]
Those scripts aren't really user-facing - they are used to build the `pp` versions for distribution - you should just modify a local copy for you needs if you are for some reason building your own packed version. If your `pp` doesn't recognise some arguments in those scripts then this means you don't have the latest version of `PAR::Packer`.

**Comment by alexreg** [comment]
Oh, I see. What is the recommended way to install biber to my own system then?

**Comment by plk** [comment]
Just install it with TeXLive and use tex TexLive updater to update it - it's all part of the standard distribution. Or, alternatively, if you need a more recent version or can't use TeXLive, just download the relevant binary version from SourceForge.

**Comment by alexreg** [comment]
Okay, thanks.
