### ISSUE TITLE
Reproducible builds: timezone-specific timestamps in PDF

### ISSUE THREAD

**Issue by hpreusse** [plk/biber#395]
In the Debian bug tracker, we got [a request](https://bugs.debian.org/990999) to make the build reproducible. Consider to apply [this patch](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=990999;filename=0001-doc-biber.tex-Do-not-generate-document-ID.patch;msg=5) to your code. Many thanks!

**Comment by plk** [comment]
Applied in DEV, thanks.
