### ISSUE TITLE
'end inside group' error when using `\,`

### ISSUE THREAD

**Issue by titanic-jb** [plk/biber#396]
I had this BibTeX entry:

```bibtex
@Book{broken,
  author = {Bäumer, Wolfram},
  title = {Mit Tempo 20 über Land},
  date = 1992,
  editor = {Deutscher Eisenhahn-Verein e.\,V.},
  subtitle = {Ein Bildführer durch das Kleinbahn-Museum Bruchhausen-Vilsen},
  publisher = {DEV-Kleinbahn-Verlag},
  location = {Postfach 1106, 2814 Bruchhausen-Vilsen},
  isbn = {3-9802233-9-6},
  pages = 116,
  langid = {german},
  keywords = {Technik, Eisenbahn, Kleinbahn, Dampflok, Dampfmaschine, Museum}
}
```

Using this MWE LaTeX file gives errors after `latex ; biber ; latex` (i.e. on the second LaTeX run):
```latex
\documentclass[paper=a4, paper=portrait, fontsize=11pt,twoside,english,french,greek,german,main=ngerman,final]{scrartcl} 
\usepackage{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{csquotes}
\usepackage[style=numeric]{biblatex}
\usepackage{hyperref}
\addbibresource{../bibtex/crash.bib}
\begin{document}
\nocite{*}
\printbibliography{}
\end{document}
```

    (\end occurred inside a group at level 3)
    
    ### semi simple group (level 3) entered at line 20 (\begingroup)
    ### semi simple group (level 2) entered at line 9 (\begingroup)
    ### semi simple group (level 1) entered at line 9 (\begingroup)
    ### bottom level

Replacing the `\,` on the editor field will fix it, but is not correct typeset, accoding to german Duden.

**Comment by moewew** [comment]
There should probably be a test to avoid a trailing `\` in name parts when splitting things up.

But in this case you can and should fix the problem on the `.bib` side. 'Corporate' names must be protected with an additional pair of curly braces from being split up into family and given names (https://tex.stackexchange.com/q/10808/35864).


The following compiles correctly
```latex
\documentclass[ngerman]{article}
\usepackage{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{csquotes}
\usepackage[style=numeric]{biblatex}
\usepackage{hyperref}

\begin{filecontents}{\jobname.bib}
@Book{broken,
  author    = {Bäumer, Wolfram},
  title     = {Mit Tempo 20 über Land},
  date      = 1992,
  editor    = {{Deutscher Eisenhahn-Verein e.\,V.}},
  subtitle  = {Ein Bildführer durch das Kleinbahn-Museum Bruchhausen-Vilsen},
  publisher = {DEV-Kleinbahn-Verlag},
  location  = {Postfach 1106, 2814 Bruchhausen-Vilsen},
  isbn      = {3-9802233-9-6},
  pagetotal = 116,
  langid    = {german},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

To see that the braces are really necessary set the style to `\usepackage[style=authoryear]{biblatex}` and compare
```
author = {Deutscher Eisenhahn-Verein e.V.},
```
with
```
author = {{Deutscher Eisenhahn-Verein e.V.}},
```

**Comment by titanic-jb** [comment]
Thanks, I appreciate your hint.  Stupid me :-)
