### ISSUE TITLE
Biber not updating correctly when PAR_GLOBAL_TEMP is set

### ISSUE THREAD

**Issue by krumeich** [plk/biber#401]
This is a follow-up to issue #368. The consensus was that by setting `PAR_GLOBAL_TEMP` to a directory other than default, `PAR::Packer`'s cache policy wouldn't interfere with the OS's habit of cleaning up caches. That worked well.

Now that biber 2.17 is out, it turned out that the unpacked program in the directory pointed to by `PAR_GLOBAL_TEMP` wasn't updated automatically:

> $ biber --version
> biber version: 2.16
> $ which biber
> /Library/TeX/texbin/biber
> $ /Library/TeX/texbin/biber --version
biber version: 2.16
> $ biber --cache
/Users/krumeich/.bibercache
> $ rm -rf ~/.bibercache/
> $ /Library/TeX/texbin/biber --version
biber version: 2.17

The problem was resolved by manually deleting the unpacked version. Is this an error that should be investigated or is it something we must live with when setting `PAR_GLOBAL_TEMP` to a directory other than default?

Environment: macOS 12.2.1 on intel x86.

**Comment by plk** [comment]
Hmm, I think this is a side-effect of using the env var. On normal use, the temp dir is composed of a hash of the binary executed and so it specific to the version but with a static location like this, I suspect the overwrite behaviour is ill-defined. You could try setting the env var to include some way of identifying the version, perhaps by hash.

**Comment by krumeich** [comment]
That would be an option. There might be a drawback, though: When using the default behavior, the OS reliably cleans up old versions eventually. If, however, I make the directory name specific to a version _and_ place it somewhere the OS doesn't expect it, then I probably end up with several unpacked biber instances of different versions that need to be cleaned up manually in the end. So, there'd not be much gain in there. 

Anyway, since biber isn't on a fast release cycle, it doesn't hurt to remove my `~/.bibercache` directory once in a while.
