### ISSUE TITLE
@preamble shouldn't convert commands to unicode

### ISSUE THREAD

**Issue by u-fischer** [plk/biber#405]
I was trying to create an entry for the author Hàn Thế Thành in a bib. 

The first try 

       author ="H{\`a}n Th{\'{\^e}} Th{\`a}nh",`  

failed as  this leads to `Th{\'ê}` in the bbl.

An additional brace group would work but is incompatible  with bibtex work flows:
     
      author ="H{\`a}n Th{\'{{\^e}}} Th{\`a}nh",`  

Then I tried unicode

       author =       "Hàn Thế Thành",

But that failed as I couldn't provide a suitable declaration for the accent in the bib-file. 

     @preamble{"\DeclareUnicodeCharacter{1EBF}{\'{\^e}}"}

gives  the faulty

~~~~
\preamble{%
 \DeclareUnicodeCharacter{1EBF}{\'ê}%
}
~~~~

Could biber leave the argument of `@preamble` unchanged? Imho it doesn't make sense to apply accent conversion here.

~~~~
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{biblatex}
\addbibresource{test-ecirceacute.bib}
\begin{filecontents}{test-ecirceacute.bib}

@preamble{"\DeclareUnicodeCharacter{1EBF}{\'{\^e}}"}

@misc{test-the,
author ="H{\`a}n Th{\'{\^e}} Th{\`a}nh",
title  ={title}
}

@misc{test-the2,
author =       "Hàn Thế Thành",
title  ={title}
}
\end{filecontents}
 

\begin{document}

H{\`a}n Th{\'{\^e}} Th{\`a}nh %work

% fails in the bibliography as
% given contains Th{\'ê}
%\cite{test-the} 
 
% fails too 
% given is fine: 
% given={Hàn\bibnamedelima Thế},
% but \preamble command is faulty
% \preamble{%
% \DeclareUnicodeCharacter{1EBF}{\'ê}%
% }

% \cite{test-the2}

\printbibliography


\end{document}
~~~~

**Comment by plk** [comment]
Is there a reason to use `fontenc` and T1 instead of fontspec? Are  you forced to use PDFlatex? Just checking as this works fine:

```
\documentclass{article}
\usepackage{fontspec}
\usepackage{biblatex}
\addbibresource{test4.bib}
\begin{filecontents}{test4.bib}
@misc{test-the2,
author =       "Hàn Thế Thành",
title  ={title}
}
\end{filecontents}
\begin{document}
\cite{test-the2}
\printbibliography
\end{document}
```

Decoding every possible thing from LaTeX macros into UTF-8 is a best-effort really - there is no clean way of doing that without a dedicated parser and things with two composed accents like this are very messy to do syntactically which is why they are only "partially" decoded, causing problems for minimal UTF-8 environments like T1. I put in a quick option to disable preamble decoding but that doesn't help due to the partial decoding of `\'{\^e}` in the entry itself so the declaration doesn't match anything.

**Comment by u-fischer** [comment]
> Are you forced to use PDFlatex?

yes, in that project I have.

> Decoding every possible thing from LaTeX macros into UTF-8 is a best-effort really 

I know. And I don't  have a real problem with the partial decoding in the entry: I can use the real utf8 there, or hide everything in a command.
 
But `@preamble` is there to insert arbitrary code needed for work-arounds  and I don't think that this code should change. So if you fix that it would be quite fine and enough for me.

**Comment by plk** [comment]
Sorry to ask, I  assumed you have a reason to use PDFlatex. I have added options to biber to disable decoding of preamble, macros and comments separately and will update the binaries soon.

**Comment by plk** [comment]
Yes, that can be done, just want to check first that it doesn't have regressions.

**Comment by plk** [comment]
Fixed om DEV
