### ISSUE TITLE
*.bib not found

### ISSUE THREAD

**Issue by chenboshuo** [plk/biber#406]
my code is
```latex
\addbibresource{./reference/*.bib}
```

the output use biber is
```text
ERROR - Cannot find './reference/*.bib'!
```

the `*` may cause this error. However, the pattern worked on the previous (about 2 months ago) compile.
How to fix it? Thank you for your attention.

**Comment by plk** [comment]
Did you try:

```
\addbibresource[glob=true]{./reference/*.bib}
```

**Comment by chenboshuo** [comment]
OK, it works, thank you.

**Comment by moewew** [comment]
Globbing by default was disabled due to https://github.com/plk/biber/issues/315. So in newer Biber versions you explicitly have to ask for globbing if you want it. (Which I find much safer than just globbing everything without warning.)
