### ISSUE TITLE
biber tool reformatting regex: how to apply case operator?

### ISSUE THREAD

**Issue by fintelkai** [plk/biber#407]
I am trying to use the tool-mode of `biber` to clean up a bib-file for processing with biblatex. One transformation is to split off subtitles after a colon into the subtitle field. This works great. At the same time, I would like to ensure that the subtitle starts with an uppercase letter. But applying the standard `\u` operator of perl-style regexes doesn't work.

Here's a test `biber-tool.conf`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<config>
  <sourcemap>
    <maps datatype="bibtex" map_overwrite="1">
      <map map_overwrite="1">
        <map_step map_field_source="title" map_match="([^:]*): (.*)" map_final="1"/>
        <map_step map_field_set="title" map_field_value="$1"/>
        <map_step map_field_set="subtitle" map_field_value="\u$2"/>
      </map>
    </maps>
  </sourcemap>
</config>
```

Here's the test bib file:

```bibtex
@Article{atkin-2022-PeirceSpeculativeGrammarLogic,
  author       = {Atkin, A. K.},
  title        = {Peirce's Speculative Grammar: logic as Semiotics},
  journaltitle = {History and Philosophy of Logic},
  date         = {2022-01-09},
  pages        = {1-2},
  doi          = {10.1080/01445340.2021.2017112}
}
```

Now, running `biber --tool --configfile=biber-tool.conf test.bib` results in the following output bib file:

```bibtex
@ARTICLE{atkin-2022-PeirceSpeculativeGrammarLogic,
  AUTHOR = {Atkin, A. K.},
  DATE = {2022-01-09},
  DOI = {10.1080/01445340.2021.2017112},
  JOURNALTITLE = {History and Philosophy of Logic},
  PAGES = {1--2},
  SUBTITLE = {\ulogic as Semiotics},
  TITLE = {Peirce's Speculative Grammar},
}
```

Note that the `\u` operator is not applied but appears verbatim in the output.

The `biber` manual contains a use of the similar `\L` operator in the discussion of sourcemap configuration, but nothing about such operators in the tool-mode section. Is the regex implementation different in tool-mode?

**Comment by plk** [comment]
The issue here is that `map_value` is not a regexp, it's just a literal string with interpolation of past matches. You need to use `map_replace` to be able to use regexps in the replace text. So, the way you would do this is to copy the entire title to the subtitle first and then use a match/replace on the subtitle field to do what you need.

**Comment by fintelkai** [comment]
Thank you. The following `biber-tool.conf` worked for me:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<config>
  <sourcemap>
    <maps datatype="bibtex" map_overwrite="1">
      <map map_overwrite="0">
        <map_step map_field_source="title" map_match="([^:]*): (.*)" map_final="1"/>
        <map_step map_field_set="subtitle" map_origfieldval="1"/>
      </map>
      <map map_overwrite="1">
        <map_step map_field_source="title" map_match="([^:]*): (.*)" map_final="1"/>
        <map_step map_field_set="title" map_field_value="$1"/>
        <map_step map_field_source="subtitle" map_match="([^:]*): (.*)" map_replace="\u$2"/>
      </map>
    </maps>
  </sourcemap>
</config>
```
