### ISSUE TITLE
Invalid or undefined BibTeX entry key in file ...

### ISSUE THREAD

**Issue by dbitouze** [plk/biber#409]
(This is a follow up of https://github.com/plk/biblatex/issues/818.)

With `biblatex` v3.17 and `biber` v2.17, the following MCE:
```latex
\begin{filecontents}[overwrite]{\jobname.bib}
@periodical{0,
  issuetitle = {Issue Title},
}
@article{0-art,
  title={Article's Title},
  author={Last, First},
  crossref={0}
}
\end{filecontents}

\documentclass{article}
\usepackage{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
\autocite{0-art}
\printbibliography
\end{document}
```
gives the following warning during the `biber` compilation:

>WARN - Invalid or undefined BibTeX entry key in file
> '/tmp/biber_tmp_Std3/5a453152acdb3e2485a9d6a17b3ec69c_1859422.utf8', skipping ...

and the given file is removed just at the end of the compilation so cannot be checked.

**Comment by plk** [comment]
Yes, this isn't a valid entry key according to the underlying `btparse` library - it can't begin with a number as far as I remember.

**Comment by dbitouze** [comment]
> Yes, this isn't a valid entry key according to the underlying `btparse` library - it can't begin with a number as far as I remember.

Indeed, thanks.
