### ISSUE TITLE
Handling mistaken author name

### ISSUE THREAD

**Issue by simonmysun** [plk/biber#410]
Hi,

When I cite https://doi.org/10.1007/bf00288730 and render the bibliografy in IEEE style, The result doesn't look good. 

The problem is that the name of the author is `Jean-Pierrer Lévy` and appears as `J.-P. Lévy` in the article, but the name in Springer database is `J. -P. Lévy` (there is an extra space). 

Here's an example:
```tex
\documentclass{article}

\begin{filecontents*}[overwrite]{main.bib}
@article{testcite0,
  author = {Jean-Pierre Lévy}
}
@article{testcite1,
  author = {J.-P. Lévy}
}
@article{testcite2,
  author = {J. P. Lévy}
}
@article{testcite3,
  author = {J. -P. Lévy}
}
@article{testcite4,
  author = {J -P. Lévy}
}
\end{filecontents*}

\usepackage[backend=biber,style=ieee]{biblatex}
\addbibresource{main.bib}

\begin{document}

This\cite{testcite0} is\cite{testcite1} a\cite{testcite2} test\cite{testcite3} citation\cite{testcite4}. 

\printbibliography{}

\end{document}
```

Also you may switch the backend and see the difference they behave. 

As far as I have tested, `Biber::Input::file::bibtex::parsename` has no problem handling correct-written names in such format, but `J. -P.` is not considered. 

Should biber also consider this case? Or should the user dig out the original name and correct it?

**Comment by simonmysun** [comment]
I would like to ask about your opion and if you think such a case should be covered I could make a pull request. 

btw, are the dashes correct for repeated names?

**Comment by perstar** [comment]
I think it would be a dangerous path for biber to take to try to correct erroneous input. Fix the input instead (and optionally ask Springer to fix it upstream as well). Generally don't be afraid of fixing bib entries found on the net. They are often bad.

**Comment by simonmysun** [comment]
Indeed. But bibtex behaves better on such case (haven't looked into its implementation). Maybe we can consider skipping typographical symbols and punctuation marks when getting initials? 

I have wrote emails to a production editor of Springer and unfortunately the reply was that "It is not possible to update this error at current stage."
