### ISSUE TITLE
Biber 2.18 failing to validate test-dev.bcf

### ISSUE THREAD

**Issue by krumeich** [plk/biber#413]
Preparing for the 2.18 release, one of my two integration tests failed:

```
/ # /usr/local/bin/biber --validate-control test-dev.bcf
INFO - This is Biber 2.18
INFO - Logfile is 'test-dev.blg'
ERROR - 'test-dev.bcf' failed to validate against schema '/tmp/par-726f6f74/cache-c0c32362f47309c381de02334ee0e5b081733275/inc/lib/Biber/bcf.rng'
INFO - ERRORS: 1
/ # cat test-dev.blg
[0] Config.pm:306> INFO - This is Biber 2.18
[0] Config.pm:309> INFO - Logfile is 'test-dev.blg'
[112] biber:340> INFO - === Wed Jun 22, 2022, 18:54:33
[135] Utils.pm:410> ERROR - 'test-dev.bcf' failed to validate against schema '/tmp/par-726f6f74/cache-c0c32362f47309c381de02334ee0e5b081733275/inc/lib/Biber/bcf.rng'
[135] Biber.pm:135> INFO - ERRORS: 1
```

`test-dev.bcf` is dated 2022-03-17 and has sha256 of `99dee57a108ba5c030027ea7a6579efb37523e51ff38bff49abf76c2d2e34be9`

Is that something we should be concerned about? The other test , `/usr/local/bin/biber --convert-control test-dev.bcf`, passes without failures.

**Comment by plk** [comment]
You can now try `test.bcf` which is updated but if you've just build `biber` can you pull the v2.18 tag again? There was a rather unexpected XML schema issue I just had to correct and the master head and v2.18 tag have the fix. I will update `test-dev.bcf` when v2.19 dev version deviates from the current `test.bcf`.

**Comment by plk** [comment]
Hmm, looks like you still have the old `test.bcf` - perhaps you got it before SF replicated it - the correct one should have at the top:

```
<bcf:controlfile version="3.9" bltxversion="3.18" xmlns:bcf="https://sourceforge.net/projects/biblatex">
```

**Comment by krumeich** [comment]
Yes, my fault. Sorry for the confusion. Now that I've rebuilt my Docker image, all tests pass. I'll upload the archive to SF tomorrow morning.

**Comment by krumeich** [comment]
(You might want to push an updated `v2.18` tag, though)
