### ISSUE TITLE
64-bit binary from CTAN reports version 2.17 instead of 2.18

### ISSUE THREAD

**Issue by grondina** [plk/biber#415]
After upgrading my TeX Live installation with `tlmgr update --self --all` I noticed that Biber started to fail:

```
ERROR - Error: Found biblatex control file version 3.9, expected version 3.8.
This means that your biber (2.17) and biblatex (3.18) versions are incompatible.
See compat matrix in biblatex or biber PDF documentation.
```

The version reported by the binary is indeed 2.17, and this is the only one installed in the system:

```
[ec2-user@ip-172-31-2-39 ~]$ sudo find / -type f -executable -name "biber"
/usr/local/texlive/2022/bin/x86_64-linux/biber
[ec2-user@ip-172-31-2-39 ~]$ which -a biber
/usr/local/texlive/2022/bin/x86_64-linux/biber
[ec2-user@ip-172-31-2-39 ~]$ biber --version
biber version: 2.17
```

Which is not the same as reported by `tlmgr`:

```
[ec2-user@ip-172-31-2-39 ~]$ tlmgr info biber | grep cat-version
cat-version: 2.18
```

I have the same binary as the one in CTAN:

```
[root@ip-172-31-2-39 ~]# mkdir biber_ctan
[root@ip-172-31-2-39 ~]# cd biber_ctan
[root@ip-172-31-2-39 biber_ctan]# wget -q http://mirrors.ctan.org/biblio/biber/binaries/Linux/biber-linux_x86_64.tar.gz
[root@ip-172-31-2-39 biber_ctan]# ls -l
total 24060
-rw-r--r--. 1 root root 24636893 Jun 22 20:24 biber-linux_x86_64.tar.gz
[root@ip-172-31-2-39 biber_ctan]# tar xvzf biber-linux_x86_64.tar.gz 
biber
[root@ip-172-31-2-39 biber_ctan]# md5sum biber
3f67b6c2fb8f79faf52429df1f20098b  biber
[root@ip-172-31-2-39 biber_ctan]# md5sum $(which biber)
3f67b6c2fb8f79faf52429df1f20098b  /usr/local/texlive/2022/bin/x86_64-linux/biber
[root@ip-172-31-2-39 biber_ctan]# ./biber --version
biber version: 2.17
```

Shouldn't this binary be 2.18? Sorry if this is not the right location to report issues with binaries in CTAN.

**Comment by plk** [comment]
Greetings, yes, this is a known issue with the 64-bit linux build server. I will be updating the binary on SF later today and correcting TL and CTAN after that. You can use the 2.18 DEV binary for now from SF which will work.

**Comment by plk** [comment]
This is now fixed and Sourceforge current linux 64-bit binary is now 2.18. I have requested update of CTAN and TL.

**Comment by aywi** [comment]
@plk  This issue has not been fixed on Windows platforms:

```
ERROR - Error: Found biblatex control file version 3.9, expected version 3.8.
This means that your biber (2.17) and biblatex (3.18) versions are incompatible.
See compat matrix in biblatex or biber PDF documentation.
```

Running `biber.exe --version` will get

```
biber version: 2.17
```

The version of `biber.win32` is 63707.

**Comment by plk** [comment]
Should be fixed now on SF for win32. Have requested update of CTAN/TL too. Win64 was not affected.

**Comment by JonaEngel** [comment]
On macOS this still seams to be an open issue.

**Comment by plk** [comment]
Are you sure? Updating `biber` just now in TexLive:

```
> /Library/TeX/texbin/biber --version
biber version: 2.18
```

**Comment by JonaEngel** [comment]
Oh, I got it!
Some link problem on my side.

```
/Library/TeX/texbin/biber --version
```
Get s me `biber version: 2.18`

However, 
```
biber -v
``` 
is still on 2.17. Turns out that's 
```
which biber
/opt/homebrew/bin/biber
``` 
In short, the home-brew biber seams to still be on 2.17.

**Comment by plk** [comment]
Presumably that homebrew version is just like my macports raw perl version I use for development which is also in my path first ...
