### ISSUE TITLE
first run of biber 2.18 (installed 2022/07/24) looks for debug framework

### ISSUE THREAD

**Issue by herbs** [plk/biber#418]
The first run of todays' update gives

% biber --version
2022-07-24 07:33:19.517 xcodebuild[15287:1861037] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-07-24 07:33:19.517 xcodebuild[15287:1861037] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
biber version: 2.18

on both arm64 and x86-64 on Mac. All is normal on succeeding runs even if I first remove the cache.

**Comment by plk** [comment]
That is output from the MacOS `lipo` command which is run on first unpack to separate the ARM/x86 binaries from the universal binary. It's a message coming from OSX itself and usually means some missing xcode bits - it's a very annoying message which I see sometimes on my machines as it's looking for development environment bundles for things like apple watches which are utterly irrelevant. You can try:

```
sudo xcode-select --install
```
 
Or just software update to update xcode and devtools. I think this happens because `lipo` was run on my end to create the universal binary and I have a newer xode/devtools than you. The warning is irrelevant but annoying.

**Comment by herbs** [comment]
> On Jul 24, 2022, at 8:03 AM, plk ***@***.***> wrote:
> 
> 
> That is output from the MacOS lipo command which is run on first unpack to separate the ARM/x86 binaries from the universal binary. It's a message coming from OSX itself and usually means some missing xcode bits - it's a very annoying message which I see sometimes on my machines as it's looking for development environment bundles for things like apple watches which are utterly irrelevant. You can try:
> 
> sudo xcode-select --install
> 
> Or just software update to update xcode and devtools. I think this happens because lipo was run on my end to create the universal binary and I have a newer xode/devtools than you. The warning is irrelevant but annoying.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
> 

Howdy,

Thank you for the very helpful explanation. It happens only once so is not a problem.

Good Luck,

Herb Schulz
***@***.***

**Comment by plk** [comment]
Just for info - I just ran `git status` - nothing to do with `biber` and got the same message as you reported - it's an annoying MacOS thing.

**Comment by plk** [comment]
See here for a discussion of this and some fixes: https://apple.stackexchange.com/questions/438785/xcode-error-when-launching-terminal

**Comment by herbs** [comment]
> On Jul 24, 2022, at 12:03 PM, plk ***@***.***> wrote:
> 
> 
> See here for a discussion of this and some fixes: https://apple.stackexchange.com/questions/438785/xcode-error-when-launching-terminal

Howdy,

The command line tools were already installed after the last Xcode update. Xcode requests to do that on its first run after an update.

Good Luck,

Herb Schulz
***@***.***
