### ISSUE TITLE
Provide SHA256 hashes on SourceForge project site

### ISSUE THREAD

**Issue by mikefarmer01** [plk/biber#422]
Biber should provide SHA256 hashes with the binaries released on SourceForge, ideally in a way easy to parse with tools like [Scoop](https://scoop.sh).

Currently, hashes are in older formats (SHA1 and MD5) and not easy to parse.

**Comment by plk** [comment]
I don't think that's under our control - there are feature requests in SF to move to SHA256 but that's a SF platform issue.
