### ISSUE TITLE
[Suggestion] sync version with biblatex

### ISSUE THREAD

**Issue by bryango** [plk/biber#427]
As biber is tightly coupled to biblatex, I wonder if it's better to simply version biber with biblatex version... We can then get rid of the "compatibility matrix". Currently biber's version lags behind biblatex's.

**Comment by plk** [comment]
This is planned for biblatex  and biber 4.0 which are the "multiscript" versions supporting multiple scripts in the same bibliography database. This is designed to be backwards compatible with current versions and can be found in the "multiscript" branches of both biblatex and biber:

https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/multiscript/
https://sourceforge.net/projects/biblatex/files/multiscript/

Moves are afoot to make this a separate package in TexLive so allow easier access for testing.
