### ISSUE TITLE
Biber v2.18 for linux-musl

### ISSUE THREAD

**Issue by krumeich** [plk/biber#428]
Finally, I adapted the build pipeline for Linux-MUSL to the CTAN based release process. The v2.18 build is up for review at https://krumeich.de/linux-musl.tar.gz. 

Before I upload v2.18 to CTAN, please take a look at the directory structure and file names.

**Comment by plk** [comment]
Getting "network error" trying to download that link?

**Comment by krumeich** [comment]
Strange, just tested it on my end. Anyway, I've also uploaded it to SourceForge: 

https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/Linux-musl/linux-musl.tar.gz/download

**Comment by plk** [comment]
Looks fine but perhaps you can put a README at the same level as the .tar.gz as per:

https://github.com/plk/biber/blob/dev/BUILDERS.README

That page also details the contents of the README which is just a couple of lines.

**Comment by krumeich** [comment]
Thanks. Finished. I'll upload the archive to CTAN next.

**Comment by krumeich** [comment]
Package has landed on CTAN.
