### ISSUE TITLE
[Suggestion] bundle test files with biber sources

### ISSUE THREAD

**Issue by krumeich** [plk/biber#429]
The test files on SourceForge seem to be out of date. test.bcf dates back to June, test-dev.bcf is older than that. I wasn't able to test my dev build against those files.

Would it be a problem to put those test files into the biber repo itself? 

Then there would be question which version to use for a particular build. This might make it possible to reduce the number of test files from 2 to 1 – just the one that is relevant for the state of the biber repository.

**Comment by plk** [comment]
`test-dev.bcf` is updated. I'll have have look at automating this.

**Comment by plk** [comment]
I think I might just remove those test files since there is a complete test suite with many test files in the testing dir `t/data`. These are the regression tests which are used for release testing and can be used to test binaries too.

**Comment by krumeich** [comment]
Good to know, thanks. I tried to verify my v2.19 binary against all the `.bcf` files in `t/tdata`. Most tests run fine, there are some errors however with undecodable Unicode sequences. Is it safe to ignore those? The are OK during the build process, they only fail when tested with the packed binary.

**Comment by plk** [comment]
It's safe to ignore the UTF8 things - however, I did put the testfiles in git now and changed the documentation to reflect this (see the testfiles directory).
