### ISSUE TITLE
Unicode mistake in @string

### ISSUE THREAD

**Issue by stefan11** [plk/biber#437]
When I apply the following line to the following file, I get a new file in which the Umlaut is broken.
`biber --tool --output-field-replace=location:address,journaltitle:journal,date:year grammar.bib`
```
@string{goettingen = "Göttingen"}


@book{altmannhahnemann:2010,
  author    = {Altmann, Hans and Hahnemann, Suzan},
  publisher = {Vandenhoeck \& Ruprecht},
  address   = goettingen,
  checked   = {lk 2022},
  edition   = {4},
  title     = {{Prüfungswissen Syntax: Arbeitstechniken -- Klausurfragen -- Lösungen}},
  year      = {2010},
}

```

```
@STRING{GOETTINGEN = "GÃ¶ttingen"}

@BOOK{altmannhahnemann:2010,
  AUTHOR = {Altmann, Hans and Hahnemann, Suzan},
  PUBLISHER = {Vandenhoeck \& Ruprecht},
  ADDRESS = GOETTINGEN,
  EDITION = {4},
  TITLE = {{Prüfungswissen Syntax: Arbeitstechniken -- Klausurfragen -- Lösungen}},
  YEAR = {2010},
}
```

**Comment by plk** [comment]
Can you try the development version of biber (2.19) from Sourceforge? I think this might have already been addressed.

**Comment by stefan11** [comment]
Sorry, can you please point me to the exact location? I only find 2.18 and brew has 2.17.

**Comment by stefan11** [comment]
Thanks but now biblatex does not work any longer. Biber wants bcf with 3.10. version. I think I have the most recent biblatex ....

```
ERROR - Error: Found biblatex control file version 3.9, expected version 3.10.
This means that your biber (2.19) and biblatex (3.19) versions are incompatible.
```

**Comment by plk** [comment]
Ah, yes, you'll need the dev (3.19) version of biblatex from sourceforge too but only if you want to use biber in non-tool mode.

**Comment by stefan11** [comment]
I installed this but it does result in the error message above. I extract bibtex items from bcf in my workflow and have unicode problems there as well. So I thought I go for the complete update. But there does not seem to be a biblatex that corresponds to the biber I have.

**Comment by plk** [comment]
This is likely an issue with your tex path - you might just post to tex.stackexchange.com and someone will sort that out for you - there are several threads there about using dev versions and how to install.

**Comment by stefan11** [comment]
I installed the file in my texpath and it finds it, as you can see in the error message above and here:

```
(/Users/..../Library/texmf/tex/latex/biblatex/latex/biblatex.sty
Package: biblatex 2022/07/31 v3.19 programmable bibliographies (PK/MW)
```

But I may have downloaded the wrong biblatex package or the two are just not compatible.

**Comment by plk** [comment]
Hmm, I will check this, that seems odd.

**Comment by plk** [comment]
Try the biblatex 3.19 dev version from SF again:

https://sourceforge.net/projects/biblatex/files/development/

There was some strange issue with SF which was serving up the currently version from the DEV links.
