### ISSUE TITLE
config file: dieondatamodel is not valid according to RNG

### ISSUE THREAD

**Issue by t-b** [plk/biber#439]
The documentation has the `dieondatamodel` config setting
```
$git grep -Hn dieondatamodel
[...]
doc/biber.tex:648:  <dieondatamodel>0</dieondatamodel>
[...]
```

but according to the RNG schema in data/config.rng, this entry is not valid. I think the closest new entry is `nodieonerror`.

**Comment by plk** [comment]
Many thanks. Fixed in DEV branch.
