### ISSUE TITLE
(re-report) With TeXLive 2023 I face two perl scripts biber and biber-ms with same vendor path

### ISSUE THREAD

**Issue by bitstreamout** [plk/biber#441]
which is
```
/lib/perl5/vendor_perl/5.36.0/Biber.pm
/lib/perl5/vendor_perl/5.36.0/Biber/
```
and those files are conflicting. I'd like to avoid to hack e.g. biber-ms by adding a
line like
```
use lib '/lib/perl5/vendor_perl/5.36.0/biber-ms/`;
```
an other solution seems not working. Therefore why we have two versions
of biber and why seems 2.18 not to support multiscript (otherwise biber-ms would
be superfluous)

compare with [#1270](https://github.com/plk/biblatex/issues/1270)

**Comment by plk** [comment]
Can you give more details of the issue? The multiscript version `biber-ms` isn't released in TL yet as it's not quite ready. The multiscript version is a separate things because it's a significant re-write that's currently a lot slower and needs user testing. I haven't really looked into anyone else installing it like this yet.

**Comment by bitstreamout** [comment]
My perl generator script for the spec files does use texlive.tlpdb.xz and for current pretest I see now in texlive.spec the entry
```
%package biber-ms-bin
Version:        %{texlive_version}.%{texlive_release}.svn64180
Release:        0
License:        LPPL-1.0
Summary:        Binary files of biber-ms
Group:          Productivity/Publishing/TeX/Utilities
URL:            https://www.tug.org/texlive/
Requires(pre):  texlive-biber-ms >= %{texlive_version}
#!BuildIgnore:  texlive-biber-ms
Prefix:         %{_bindir}

%description biber-ms-bin
Binary files of biber-ms
```
and
```
%files biber-ms-bin
%defattr(-,root,root,755)
%{_bindir}/biber-ms
```

the archive directory does list
```
texlive/2023> ll archive/biber-ms.*
-rw-rw-r-- 1 werner suse 258716 Aug 28  2022 archive/biber-ms.doc.r64213.tar.xz
lrwxrwxrwx 1 werner suse     26 Aug 28  2022 archive/biber-ms.doc.tar.xz -> biber-ms.doc.r64213.tar.xz
-rw-rw-r-- 1 werner suse    500 Aug 28  2022 archive/biber-ms.r64213.tar.xz
-rw-rw-r-- 1 werner suse 945480 Aug 28  2022 archive/biber-ms.source.r64213.tar.xz
lrwxrwxrwx 1 werner suse     29 Aug 28  2022 archive/biber-ms.source.tar.xz -> biber-ms.source.r64213.tar.xz
lrwxrwxrwx 1 werner suse     22 Aug 28  2022 archive/biber-ms.tar.xz -> biber-ms.r64213.tar.xz
```
and a look into `archive/biber-ms.source.tar.xz` shows
```
texmf-dist/source/bibtex/biber-ms/Changes
texmf-dist/source/bibtex/biber-ms/README.biber-ms-linux
texmf-dist/source/bibtex/biber-ms/README.biber-ms-macos
texmf-dist/source/bibtex/biber-ms/README.biber-ms-windows
texmf-dist/source/bibtex/biber-ms/README.md
texmf-dist/source/bibtex/biber-ms/biblatex-biber-ms.tar.gz
texmf-dist/source/bibtex/biber-ms/utf8-macro-map.html
tlpkg/tlpobj/biber-ms.source.tlpobj
```

**Comment by plk** [comment]
I don't think this has anything to do with TL which does have parallel installs of `biber` and `biber-ms`. If you are building from source, you should probably only be building the normal `biber` from the master branch or tagged 2.x releases. The build/install for the multiscript version is more complicated and I do it only to provide binaries currently as 4.0 is experimental.
