### ISSUE TITLE
Incompatibility with biblatex

### ISSUE THREAD

**Issue by stefan11** [plk/biber#443]
Hi,

Just updated biblatex and biber from texlive 2022 and I get this:

ERROR - Error: Found biblatex control file version 3.9, expected version 3.10.
This means that your biber (2.19) and biblatex (3.19) versions are incompatible.

biblatex was updated on ctan 05.03.23 but it seems to be incompatible. What can I do?

**Comment by plk** [comment]
I just checked CTAN and it looks correct. Can you do `kpsewhich bibatex.sty` and there should be a line near the top of that file like:

```
\def\blx@bcfversion{3.10}
```
