### ISSUE TITLE
Backquotes getting sanitized

### ISSUE THREAD

**Issue by dpthurst** [plk/biber#450]
I want a backquote "\`" to appear in my bibliography, and not an opening single quote "‘". (I am referring to a Mathematica package.) To properly produce this in TeX, you need to do `\textasciigrave`. But Biber doesn't preserve this in its output: the `\textasciigrave` turns into \` in the `.bbl` file, which TeX then turns into an opening single quote.

Here is the relevant entry in the `.bib` file:
```
@misc{QuantumGroups,
	Author = {Scott Morrison},
	Title = {\texttt{QuantumGroups\textasciigrave}, a Mathematica package},
	Year = {2006}}
```
and the resulting output in the `.bbl` file includes:
```
      \field{title}{\texttt{QuantumGroups`}, a Mathematica package}
```

Oddly this doesn't happen with everything, eg `\textbackslash` does not turn into a literal backslash in the output.

This is with Biber version 2.18 on Debian unstable; apologies that I wasn't able to compile the latest version from GitHub to check that. (Debian does not package Mozilla::CA.) Full minimal example below.

File t.tex:
```
\documentclass{amsart}
\usepackage[backend=biber,style=alphabetic,doi=false,isbn=false,url=false,minnames=6,maxnames=6]{biblatex}
\addbibresource{t.bib}

\begin{document}
Test citation of \texttt{QuantumGroups\textasciigrave} \cite{QuantumGroups}
\printbibliography
\end{document}
```

File t.bib:
```
@misc{QuantumGroups,
	Author = {Scott Morrison},
	Note = {\url{http://katlas.org/wiki/QuantumGroups\textasciigrave}},
	Title = {\texttt{QuantumGroups\textasciigrave}, a Mathematica package},
	Year = {2006}}
```

PDF output attached.
[t.pdf](https://github.com/plk/biber/files/11355498/t.pdf)

**Comment by dpthurst** [comment]
That worked! And it works for me as a workaround. But I would still classify this as a bug.

**Comment by plk** [comment]
Yes, will be fixed in the next version.

**Comment by viccie30** [comment]
The same issue happens with `\textquotesingle` and `\textquotedbl` in Unicode engines. `tuenc.def` has [special definitions disabling the default ligatures for `'` and `"`](https://github.com/latex3/latex2e/blob/3c00d05b329fba86e08108e8de2c562399cddb00/base/ltoutenc.dtx#L3096-L3098), but because of biber's mapping the control sequences never make it to TeX and the ligatures aren't disabled.

**Comment by plk** [comment]
2.20 is now released
