### ISSUE TITLE
How does Biber finds its files

### ISSUE THREAD

**Issue by pauloney** [plk/biber#453]
I have a small file

````
\documentclass{book}

\usepackage{biblatex}
\addbibresource{biblio.bib}

\begin{document}
Test!
\nocite{*}
\printbibliography
\end{document}
````

with no "biblio.bib" file in the current directory. When I process with latex/biber/latex I get what I would expect:

````
ERROR - Cannot find 'biblio.bib'!
INFO - ERRORS: 1
````

On a machine of a friend of mine, with almost exactly the same set-up (TeXLive), Biber finds the file:

````
/usr/local/texlive/2023/texmf-dist/doc/latex/msc/biblio.bib
````

and process it.

We checked the environment variables and they are completely void of anything related to TeX. 

How is it fiding that file?

**Comment by plk** [comment]
See page 12 of the `biber` pdf manual (type `texdoc biber` in a shell). It's finding it for your friend because `kpsewhich biblio.bib` is presumably finding it, which is what `biber` tries if all else fails.

**Comment by pauloney** [comment]
But, it does NOT find the file under TeXLive 2023 (it finds under TL 2022). Has this changed recently?

**Comment by pauloney** [comment]
Indeed it is `kpsewhich biblio.bib` the responsible part for finding the file. It find it in TL 2022 (not updated) and no longer finds it in the updated or 2023, which solves the problem from now on.
