### ISSUE TITLE
calling biber throws error: Couldn't load any math lib(s), not even fallback to Calc.pm

### ISSUE THREAD

**Issue by pospiech** [plk/biber#454]
Calling biber on Windows (latest updates from texlive 2023) throws this error:

`C:\Users\matth>biber
Couldn't load any math lib(s), not even fallback to Calc.pm at C:\Users\matth\AppData\Local\Temp\par-6d61747468\cache-96d297aa7563e182b1dd640f406e913a11204801\19c9b262.pm line 25.
BEGIN failed--compilation aborted at C:\Users\matth\AppData\Local\Temp\par-6d61747468\cache-96d297aa7563e182b1dd640f406e913a11204801\19c9b262.pm line 25.
Compilation failed in require at C:\Users\matth\AppData\Local\Temp\par-6d61747468\cache-96d297aa7563e182b1dd640f406e913a11204801\11788edc.pm line 14.
BEGIN failed--compilation aborted at C:\Users\matth\AppData\Local\Temp\par-6d61747468\cache-96d297aa7563e182b1dd640f406e913a11204801\11788edc.pm line 14.
Compilation failed in require at C:\Users\matth\AppData\Local\Temp\par-6d61747468\cache-96d297aa7563e182b1dd640f406e913a11204801\a9813d86.pm line 20.
BEGIN failed--compilation aborted at C:\Users\matth\AppData\Local\Temp\par-6d61747468\cache-96d297aa7563e182b1dd640f406e913a11204801\a9813d86.pm line 20.
Compilation failed in require at C:\Users\matth\AppData\Local\Temp\par-6d61747468\cache-96d297aa7563e182b1dd640f406e913a11204801\85b0182c.pm line 8.
BEGIN failed--compilation aborted at C:\Users\matth\AppData\Local\Temp\par-6d61747468\cache-96d297aa7563e182b1dd640f406e913a11204801\85b0182c.pm line 8.
Compilation failed in require at /loader/HASH(0xf926e8)/parent.pm line 16.
BEGIN failed--compilation aborted at C:\Users\matth\AppData\Local\Temp\par-6d61747468\cache-96d297aa7563e182b1dd640f406e913a11204801\1fa66f73.pm line 5.
Compilation failed in require at script/biber-MSWIN64 line 17.
BEGIN failed--compilation aborted at script/biber-MSWIN64 line 17.`

**Comment by plk** [comment]
Hmm, looks like something to do with your system as win64 is the largest user base and we'd be flooded with complaints if this was a general problem. Try deleting `C:\Users\matth\AppData\Local\Temp\par-6d61747468` and running `biber -v` once to unpack it again. You can always find the cache directory it unpacks to on first run with `biber --cache`.

**Comment by pospiech** [comment]
deleting the temp directory solved the problem

**Comment by plk** [comment]
Just for information, on first run (of a new version), don't interrupt `biber` as it is unpacking itself into the temp directory and it might corrupt the cache, which leads to issues like this. After the first run it's faster as it uses this cache and doesn't need unpack itself again.
