### ISSUE TITLE
Biber crashes on MacOS 12.6.8/MacTex-2023

### ISSUE THREAD

**Issue by lou1306** [plk/biber#459]
I am using MacTex-2023 on a M1 MacBookPro running MacOS Monterey 12.6.8.

Invoking biber 2.19 with any options (even `biber --version` or `biber --help`) fails with the following error message:

```
Compress::Raw::Zlib object version 2.105 does not match bootstrap parameter 2.202 at /loader/HASH(0x147918428)/Compress/Raw/Zlib.pm line 140.
Compilation failed in require at /loader/HASH(0x1478f8fb0)/Archive/Zip.pm line 9.
BEGIN failed--compilation aborted at /loader/HASH(0x1478f8fb0)/Archive/Zip.pm line 9.
Compilation failed in require at -e line 157.
```

Right now I am working around this by using a 3.18 binary from SourceForge, which works correctly.

**Comment by lou1306** [comment]
The buggy binary is the universal one from CTAN. Its release date (from `biber.pdf`) is 5th March 2023, and its SHA256 checksum is `975fc4e9cddc15dc8731c81523d71ed6ea09259df3b5bf0ec574b8753ca6fed6`.

The one I am using as a workaround is also a universal binary (found at `biblatex-biber/2.18/binaries/MacOS/biber-darwin_universal.tar.gz` on SF), with checksum `0f7bc7f73bef50d39c841f9341054e535a717854e0691544912bb4627bbeab77`.

**Comment by plk** [comment]
Have you tried the latest 2.19 universal?

**Comment by plk** [comment]
Apologies, I meant the 2.20 DEV binary:  https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/MacOS/

**Comment by lou1306** [comment]
Thank you for the link. Sadly I get the same error message in this version as well.

**Comment by plk** [comment]
I'm assuming that if you try the ARM64 binary from the same location, you get the same error?

**Comment by lou1306** [comment]
I didn't find an ARM64 binary at that location, but I could run the x86_64 one. Interestingly, that one did not fail!

So, I also tested the 2.19 x86_64 binary and found that that it has no issues either. Therefore I am currently using that one (which allows me to run biblatex 3.19).

**Comment by lou1306** [comment]
Thank you for the instructions. I can confirm that the resulting binary still displays the same error message.

**Comment by plk** [comment]
I think this is because you are running 12.4 and the M1 I build on is 14.1. I assume they've updated zilb. I don't have spare M1s to keep on an older version like I do with x64s - can you update or just use the x64 version in compat mode?

**Comment by plk** [comment]
A new build has been made for 2.20 - you can try that now as it is released.

**Comment by clason** [comment]
Sorry for necroposting, but I currently don't have time for a proper issue; I nevertheless wanted to give a heads-up: macOS 27/Xcode 27 beta broke the scripts since apparently `-extract-family` was removed:
```
usage: lipo <input_file> <command> [<options> ...]
  command is one of:
    -create[_album]
    -info
    -detailed_info
    -thin <arch>
    -extract <arch> [-extract <arch> ...]
    -remove <arch> [-remove <arch> ...]
    -replace <arch> <file_name> [-replace <arch> <file_name> ...]
    -verify_arch <arch> ...
    -archs
  options are one or more of:
    -arch <arch> <input_file>
    -o <output_file>
    -segalign <arch> <alignment>
lipo: unknown option "-extract_family"
biber: extracting arm64 binary with lipo failed (wstatus=256)
```

**Comment by plk** [comment]
I don't think that is used anywhere in our scripts?

**Comment by clason** [comment]
I can't find it either, but it seems baked into the binary? (Sorry, as I said, haven't had time to fully investigate...)

It seems that the Xcode 27 toolchain is much less lenient than previous updates. (Not fully surprising since 27 drops ALL support for Intel...)

**Comment by clason** [comment]
Could be a perl issue...

**Comment by plk** [comment]
It's in PAR::Packer - I made an PR for this a while ago:

https://github.com/rschupp/PAR-Packer/blob/5be78ba413d95ff94ecc03f1f98c2cbe4e00b15e/myldr/boot.c#L321

I will make a PR to fix this.

**Comment by clason** [comment]
I saw that the PR was merged -- thanks! Out of interest, what are the next steps to getting a "fixed" biber? Does `PAR::Packer` need to make a new release, or does biber pull in the latest HEAD?

**Comment by plk** [comment]
Instead of waiting for the `PAR::Packer` release, I incorporated the change onto my build VMs - can you check the latest DEV version on SF?

**Comment by clason** [comment]
`fish: Job 1, './biber' terminated by signal SIGKILL (Forced quit)`

Anything I can run to debug this?

**Comment by plk** [comment]
I can reproduce - looking at it.

**Comment by plk** [comment]
Can you pull the universal binary again? It works for me now.

**Comment by clason** [comment]
Yes, now it works for me, too! Thanks!

**Comment by EmeraJade** [comment]
> Sorry for necroposting, but I currently don't have time for a proper issue; I nevertheless wanted to give a heads-up: macOS 27/Xcode 27 beta broke the scripts since apparently `-extract-family` was removed:
> 
> ```
> usage: lipo <input_file> <command> [<options> ...]
>   command is one of:
>     -create[_album]
>     -info
>     -detailed_info
>     -thin <arch>
>     -extract <arch> [-extract <arch> ...]
>     -remove <arch> [-remove <arch> ...]
>     -replace <arch> <file_name> [-replace <arch> <file_name> ...]
>     -verify_arch <arch> ...
>     -archs
>   options are one or more of:
>     -arch <arch> <input_file>
>     -o <output_file>
>     -segalign <arch> <alignment>
> lipo: unknown option "-extract_family"
> biber: extracting arm64 binary with lipo failed (wstatus=256)
> ```

I am having this exact issue and can't quite figure out how to fix it. I already updated biblatex (I think) — the error persists.

**Comment by plk** [comment]
Probably biber isn't updated - we re-release Biber 2.22 so try force updating from TexLive updater.
