### ISSUE TITLE
biber-linux_aarch64: providing a regular contribution

### ISSUE THREAD

**Issue by krumeich** [plk/biber#462]
Not strictly an issue, but a proposal: Up until now, there has been no regular version of biber for the linux_aarch64 platform. This platform is becoming more and more relevant for people running Linux on their Raspberry Pis or in virtual machines on their Apple Silicon Macs.

Some time ago, @sbrass provided a first aarch64 build based on the containerized build pipeline that was originally developed for linux-musl. Now @sbrass and myself have agreed to collaborate on providing a regular build for linux_aarch64. The build pipeline is in place and we have produced builds of both the v2.19 tag and the current dev branch.

If you're willing to accept this contribution, how do we proceed?

Our resulting `biber-linux.tar.gz` file contains the structure required for CTAN, albeit only the aarch64 build. My approach would be to upload an update and let the fine people at CTAN know that this upload supplements the files that are already there.

For uploads at SourceForge, we'd add the aarch64 build to the `/current/binaries/Linux` directory, assuming that my privileges for the Linux-musl directory also apply to the Linux directory.

We might have to submit some changes to the build script in `/dist` before the next release, so kindly let us know some days in advance before you tag the v2.20 release.

**Comment by plk** [comment]
Does this answer some of the questions?:

https://github.com/plk/biber/blob/dev/BUILDERS.README

**Comment by krumeich** [comment]
It took sometime to get things sorted on our end. I've uploaded the v2.19 build to both the `current` and `development` directories on Sourceforge. I've also submitted the build to CTAN and asked them to put it in the same directory as the regular Linux build. Let's see if it turns up there in the next days.

**Comment by krumeich** [comment]
Finally, biber for Linux on aarch64 is deployed both to SourceForge and to CTAN. @plk please take a look at the message from the CTAN folks that received as cc. I took the liberty to follow Petra's suggestion with the biber-linux-aarch64 platform name. I hope this works for the people at TeX Live.

**Comment by plk** [comment]
2.20 is now released
