### ISSUE TITLE
biber 2.17 biber-darwin_x86_64.tar.gz is missing

### ISSUE THREAD

**Issue by WtfJoke** [plk/biber#463]
Is there a reason why the file `biber-darwin_x86_64.tar.gz` is missing on biber version 2.17 on sourceforge?

Not available:
https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/2.17/binaries/MacOS/

Available in previous version: 
https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/2.16/binaries/OSX_Intel/

Available in next version:
https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/2.18/binaries/MacOS/

Is it possible to upload it? 
Is somewhere documented whats the difference between universal and this file?

Thanks a bunch!

**Comment by plk** [comment]
Should be there now.

**Comment by WtfJoke** [comment]
That was fast, thank you @plk :)
