### ISSUE TITLE
Typo in `biber`

### ISSUE THREAD

**Issue by hvoss49** [plk/biber#465]
The short option should be "-T" (line 954), just like the other ones.

```
voss>bin:$ grep -n "trace|T" biber 
115:           'trace|T',
954:=item B<--trace|T>
```

**Comment by plk** [comment]
Fixed in DEV branch.

**Comment by hvoss49** [comment]
Just saw the line 956:

```Turn on tracing. Also turns on B<--debug|d> and additionally  ...```

should be  `B<--debug|-D>`
