### ISSUE TITLE
Typo in PDF doku

### ISSUE THREAD

**Issue by titanic-jb** [plk/biber#468]
The actual PDF manual file ``biber.pdf``, version 2.19, contains a typo on page 4.  On the second paragraph it says

> There is also a ‘<tool’ mode which operates on  ...

It is missing the closing angle bracket and should instead be contain this: ``<tool>`` .

**Comment by titanic-jb** [comment]
On Page 10 it says on the second paragraph:

> This is conceptually equivalent to the .aux file which LaTeX uses to pass information to BIBTEX.

The LaTeX logo is obviously missing the backslash in the input source.

**Comment by plk** [comment]
2.20 is now released
