### ISSUE TITLE
biber 2.20 musl binaries

### ISSUE THREAD

**Issue by sergiud** [plk/biber#473]
While trying to update to TeXLive 2024 I'm getting the following error in an Alpine docker container:
```
ERROR - Error: Found biblatex control file version 3.11, expected version 3.10.
This means that your biber (2.19) and biblatex (3.20) versions are incompatible.
```
Looking at TeXLive 2024 package archive the musl version of biber binary was last updated on 2023-04-17 while the non-musl version is recent (2024-03-23).

**Comment by plk** [comment]
The MUSL builder has not updated to 2.20 on SF yet - he expects to do it next week, after which it will appear in TL.

**Comment by sergiud** [comment]
Not sure what builder are you talking about. However, one month later there are still no musl binaries in sight.
