### ISSUE TITLE
[for information] biber for OpenBSD

### ISSUE THREAD

**Issue by ralessi** [plk/biber#479]
Hi,

I would like to let anyone interested that since TL 2024 was published I try to provide binaries for a native intallation of TeX Live on OpenBSD: <https://sr.ht/~ralessi/texlive-openbsd>.

This modest project has been updated lately with the support for biber: <https://sr.ht/~ralessi/texlive-openbsd/#biber>.

Unless I'm mistaken, biber for OpenBSD can't be included here as OpenBSD is not officially supported in TL, but the steps of the build process are described here on a separate page should anyone be interested in this: <https://git.sr.ht/~ralessi/texlive-openbsd/tree/HEAD/README.biber.md>.

Thanks,

-- Robert

**Comment by plk** [comment]
Thanks for this - I'll look at adding a mention in the documentation.

**Comment by ralessi** [comment]
Thank you! -- R.
