### ISSUE TITLE
Biber will crash if there are any entries with an extra comma in the author field

### ISSUE THREAD

**Issue by lrcg** [plk/biber#52]
Biber will crash if there are any entries with an extra comma in
the author field. For example, 

```
author = {Sagan, , Carl},
```

causes Biber to segfault with

```
FATAL - Caught signal: SEGV
Likely your .bib has a very bad entry which causes libbtparse to crash: Inappropriate ioctl for device
```

and it must be corrected to

```
author = {Sagan, Carl},
```

`bibtex-mode` in Emacs reports that the construct is syntactically valid though.

**Comment by hensing** [comment]
thank you @lrcg - you gave me the right hint to find my biber SEGV problem :+1:

**Comment by yuttai** [comment]
@lrcg Is run biber with --trace and read the trace report in .blg file solve your problem?
