### ISSUE TITLE
Cannot find "recode_data.xml"

### ISSUE THREAD

**Issue by Ceilican** [plk/biber#56]
When I run Biber in MacOSX Yosemite I obtain the following error message:

```
$ ./biber main
INFO - This is Biber 1.9
INFO - Logfile is 'main.blg'
read_file '/var/folders/91/510dl_y10nl_gj61qq8x7_3r0000gn/T/par-4272756e6f/cache-a3cdad92316c60c9c5179d80d6bb51a7a024393c//inc/lib/Biber/LaTeX/recode_data.xml' - sysopen: No such file or directory at /var/folders/91/510dl_y10nl_gj61qq8x7_3r0000gn/T/par-4272756e6f/cache-a3cdad92316c60c9c5179d80d6bb51a7a024393c/bda77484.pm line 112.
```

Could you tell me why?

Thanks!

**Comment by plk** [comment]
This has been answered many times on tex.stackexchange.com:

Just delete the cache folder and run biber once more. The cache folder for you is:

/var/folders/91/510dl_y10nl_gj61qq8x7_3r0000gn/T/par-4272756e6f/cache-a3cdad92316c60c9c5179d80d6bb51a7a024393c

This is usually to do with some OS automated cleanup deleting files from the cache or can also happen when you interrupt biber's first run when it unpacks itself. The PAR::Packers maintainers (module which controls the cache) are looking at this.
