### ISSUE TITLE
biber crash

### ISSUE THREAD

**Issue by fintelkai** [plk/biber#57]
biber has recently started crashing immediately whenever called. 

```
$ biber -v
IO/Compress/Zlib/Extra.pm did not return a true value at /loader/HASH(0x10105af50)/IO/Compress/Gzip.pm line 16.
BEGIN failed--compilation aborted at /loader/HASH(0x10105af50)/IO/Compress/Gzip.pm line 16.
Compilation failed in require at /loader/HASH(0x10083c738)/Compress/Zlib.pm line 12.
BEGIN failed--compilation aborted at /loader/HASH(0x10083c738)/Compress/Zlib.pm line 12.
Compilation failed in require at -e line 358.
```

This is biber installed by MacTeX. Running on OS X 10.10.2.

**Comment by plk** [comment]
Are you running the "binary" version of biber or running against your own perl install? If the former, try deleting the biber cache.

**Comment by fintelkai** [comment]
It was the binary version. I couldn't find the cache because `biber --cache" also crashed. But I finally found it, deleted it, and things are back to normal. Will there ever be a self-repairing version of biber?

**Comment by plk** [comment]
Yes, this is being addressed now by the Par::Packer module author - this is the module responsible for the unpacking in biber.

**Comment by fintelkai** [comment]
That is very good news. This has been the only challenge with the otherwise glorious transition to biber + BibLaTeX.

**Comment by vincentwj** [comment]
I recently encountered the same problem:

> IO.pm did not return a true value at /loader/HASH(0x1008012d0)/IO/Handle.pm line 269.
BEGIN failed--compilation aborted at /loader/HASH(0x1008012d0)/IO/Handle.pm line 269.
Compilation failed in require at /loader/HASH(0x100801360)/IO/Seekable.pm line 101.
BEGIN failed--compilation aborted at /loader/HASH(0x100801360)/IO/Seekable.pm line 101.
Compilation failed in require at /loader/HASH(0x100801240)/IO/File.pm line 133.
BEGIN failed--compilation aborted at /loader/HASH(0x100801240)/IO/File.pm line 133.
Compilation failed in require at -e line 150.

fintelkai how did you fix this?

**Comment by plk** [comment]
Which version are you using?

**Comment by vincentwj** [comment]
TeXShop 3.51 for Mac OS X

**Comment by plk** [comment]
Which version of biber? You should be able to open a terminal and do "biber -v".

**Comment by vincentwj** [comment]
when i type that command I get 

`IO.pm did not return a true value at /loader/HASH(0x10088ef78)/IO/Handle.pm line 269.
BEGIN failed--compilation aborted at /loader/HASH(0x10088ef78)/IO/Handle.pm line 269.
Compilation failed in require at /loader/HASH(0x10088f008)/IO/Seekable.pm line 101.
BEGIN failed--compilation aborted at /loader/HASH(0x10088f008)/IO/Seekable.pm line 101.
Compilation failed in require at /loader/HASH(0x10088eee8)/IO/File.pm line 133.
BEGIN failed--compilation aborted at /loader/HASH(0x10088eee8)/IO/File.pm line 133.
Compilation failed in require at -e line 150.`

**Comment by vincentwj** [comment]
I tried deleting the cache but that gives me the same error

**Comment by plk** [comment]
Can you run the Tex Live Utility (which comes with MacTeX) and update biber?

**Comment by vincentwj** [comment]
i'll upgrade and let you know if the issue persists. thanks so far!

**Comment by vincentwj** [comment]
it appears the problem has been solved, the update worked. thanks a lot!
