### ISSUE TITLE
map_append does not append to an already defined value

### ISSUE THREAD

**Issue by ChristianWulf** [plk/biber#58]
The following does not work:
```xml
<map_step map_field_set="KEYWORDS" map_field_value="hanus" map_append="1"/>
```

The following, however, works:
```xml
<map_step map_field_set="KEYWORDS" map_field_value="hanus"/>
<map_step map_field_source="KEYWORDS" map_match="^" map_replace="hanus," />
```

**Comment by plk** [comment]
What exactly are you trying to do - can you give an example?

**Comment by ChristianWulf** [comment]
I want to add the keyword ``hanus`` to each bib entry in order to display particular references with ``printbibliography[keyword=hanus]``.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<config>
  <sourcemap>
    <maps datatype="bibtex" map_overwrite="1">
      <map>
        <per_datasource>profile/lit-hanus.bib</per_datasource>
        <!--<map_step map_field_set="KEYWORDS" map_field_value="hanus" map_append="1"/>-->
		<map_step map_field_set="KEYWORDS" map_field_value="hanus"/>
		<map_step map_field_source="KEYWORDS" map_match="^" map_replace="hanus," />
      </map>
    </maps>
  </sourcemap>
</config>

```

**Comment by plk** [comment]
Hmm, this works fine for me, don't forget that you have to append exactly what you want and keywords are xSV fields and so you probably want something like this to cope with entries with and without keywords:

```xml
<map_step map_field_set="KEYWORDS" map_field_value=",hanus" map_append="1"/>
<map_step map_field_source="keywords" map_match="^,\s*" map_replace=""/>
```

**Comment by ChristianWulf** [comment]
Mh, strange. I still cannot append a value to the field by using ``map_append="1"`` if the field is already defined. I use biber 1.9.

**Comment by plk** [comment]
Hm, can you try biber 2.0 DEV version from sourceforge? You'll also need to be using biblatex 3.0 dev version.

**Comment by stevenwdv** [comment]
I have the same issue, even when prepending the field value with a comma
