### ISSUE TITLE
Biber error message "Permission denied"

### ISSUE THREAD

**Issue by schmellen** [plk/biber#59]
Biber doesn't work on my machine. Every time I run biber I get an error message that says: 
"Error in tempfile() using template \XXXXXXXXXX: Could not create temp file \orKgqh7hTi: Permission denied at C:\Users\<user>\AppData\Local\Temp\par-*\cache-*\inc\lib/IPC/Run3.pm line 128."

I installed Biber manually as I use MikTex 64-bit version. I copied the biber.exe into the MiKTeX 2.9/miktex/bin folder and I also tried running biber after I pasted the biber.exe into the folder where the TeX-document is in. I also deleted biber and downloaded it again. I changed the permission properties of the C:\Users\<user>\AppData\Local\Temp folder, but the problem stays the same.
I tried deleting the C:\Users\<user>\AppData\Local\Temp\par-* folder, but I always get the same error message when trying to run biber in the prompt by "biber <document>". Is there any solution to this problem?

**Comment by plk** [comment]
Hmm, that looks like perhaps your windows environment variables are not setting %TEMP% or something strange. Basically, it's nothing to do with the permissions on the par cache, it's dying when biber is trying to create a temporary file in some standard OS location. A path like "\....." isn't a valid windows path. You might want to ask on tex.stackexchange.com to see if anyone knows about this on win64.

**Comment by pi-bie** [comment]
I'm experiencing the same issue on Win10 using MikTex 64-bit, but can circumvent the problem by running biber with elevated privileges/as an admin.
