### ISSUE TITLE
Add more specific information for "comma(s) at end of name" warnings

### ISSUE THREAD

**Issue by jreimone** [plk/biber#60]
Such warnings just occur in the following sense:
```
[577] Utils.pm:144> WARN - BibTeX subsystem: warning: comma(s) at end of name (removing)
[578] Utils.pm:144> WARN - BibTeX subsystem: author, warning: comma(s) at end of name (removing)
```
In a large bib file this is hard to track them down. Please add additional information to such warnings, such as e.g. line numbers or the key.

**Comment by jreimone** [comment]
I could narrow down the entry which produces this warnings:

```
@InCollection{Blanc2009,
  Title                    = {{I}ncremental {D}etection of {M}odel {I}nconsistencies {B}ased on {M}odel {O}perations},
  Author                   = {Blanc, Xavier and Mougenot, and Mounier, Isabelle and Mens, Tom},
  Booktitle                = {Advanced Information Systems Engineering},
  Publisher                = {Springer Berlin Heidelberg},
  Year                     = {2009},
  Editor                   = {van Eck, Pascal and Gordijn, Jaap and Wieringa, Roel},
  Pages                    = {32--46},
  Series                   = {Lecture Notes in Computer Science},
  Volume                   = {5565},

  Doi                      = {10.1007/978-3-642-02144-2_8},
  ISBN                     = {978-3-642-02143-5},
  Language                 = {English}
}
```
But I don't see where it is produced exactly.

**Comment by jreimone** [comment]
Ok, in a german LaTeX discussion platform, we could solve the cause: ```and Mougenot, and``` has no first name after the comma. Nevertheless a more detailed warning would be helpful.

**Comment by plk** [comment]
This is not so easy to do as these messages come from an underlying library which biber uses I'm afraid.

**Comment by jreimone** [comment]
oh, that's a pitty

**Comment by claragici** [comment]
Hi @plk @jreimone 

I have the same issue. 
Very difficult to track down this error without any indication of the line where it may be. 
Best,
Clara

**Comment by jreimone** [comment]
@claragici but with my indications mentioned you could search for `, and` String to identify it.  Does this help you?

**Comment by claragici** [comment]
Hi @jreimone thanks for the quick reply!
Yes I had to extend it a little bit more with RegEx to narrow down the occurrences but I found it!
Thank you :)
Clara

**Comment by jreimone** [comment]
Awesome 👍

**Comment by klieret** [comment]
In case someone is using Zotero with bibtex output: This often happens if you have a collaboration (or anything else with no first/second name) plus additional authors and forget to toggle the author format for the collaboration: 

![image](https://user-images.githubusercontent.com/13602468/158799643-179f6bec-0e1c-4a01-b6fe-a6767cea9aef.png)

You need to click the field next to the "-" on the right of the author names (such that it is "single field") . 
This will cause the `.bib` export to read

```
author = {{The Belle Collaboration} and ....
```

rather than

```
author = {The Belle Collaboration, and ....
```

**Comment by wp-seth** [comment]
it would be great, if biber would at least give a hint to the user how to fix the problem. for example biber could add the information
```
to search your bib files for the problematic entry, a call of 
  grep -nP '(?:author|editor)\s*=.*,\s*(?:and|})' *.bib
might help.
```
to the warning.

or, if biber cannot print the line, it might be able to spit out the problematic string part?

related: #303
