### ISSUE TITLE
Backslash-escaped braces are not treated as such

### ISSUE THREAD

**Issue by aurimasv** [plk/biber#61]
BibLaTeX doesn't seem to comment on escaping special characters (it does state that special characters don't need escaping in verbatim fields, which cannot be true across the board) and I assume defaults to the BibTeX way. [BibTeX "documentation"](http://www.bibtex.org/SpecialSymbols/) states that
> [special characters], like {, " or $ [...] need to be escaped using a backslash (\\)

I'm particularly interested in the brace characters, as that causes multiple problems. Not only does it have to be escaped in non-verbatim fields, but clearly would wreak havoc in any brace-enclosed field (even verbatim) if not escaped.

I was surprised to see that neither BibTeX 0.99d, nor Biber 1.9 support backslash-escaped braces if they are _mismatched_.

The following BibTeX file fails to parse (Windows console output):
```
>type test.bib
@article{test_123,
        title = {How to use \{ in Bib(La)TeX?},
        abstract = {Apparently not this way: \{. But why?},
        file = {How to use \{ in Bib(La)TeX:/some/place/on/my/pc/How to use \{ in Bib(La)TeX.pdf:application/pdf}
}
```
(each one of those fields, which can legitimately contain an unbalanced brace in the actual string, fail individually)
```
>biber.exe --tool test.bib
INFO - This is Biber 1.9 running in TOOL mode
INFO - Logfile is 'test.bib.blg'
INFO - Looking for bibtex format file 'test.bib'
INFO - Decoding LaTeX character macros into UTF-8
INFO - Found BibTeX data source 'test.bib'
WARN - Entry test_123 does not parse correctly
WARN - BibTeX subsystem: C:\*********\test.bib_5644.utf8, line 3, warning: possible runaway string started at line 2
ERROR - BibTeX subsystem: C:\********\test.bib_5644.utf8, line 6, syntax error: at end of input, expected one of: number, name (entry type, key, field, or macro name) or quoted string ({...} or "...")
INFO - WARNINGS: 2
INFO - ERRORS: 1
```

If I'm wrong on my assumption about escaping the `{` inside a field, please correct me.

**Comment by plk** [comment]
You might ask this on tex.stackexchange.com - I am not sure this was every supported in any bibtex version and you are right that it's not supported by the btpartse library which biber uses. You could always just define a macro (there is probably one anyway) which expands to an unmatched brace.

**Comment by aurimasv** [comment]
I actually [already asked this on tex.stackexchange.com](http://tex.stackexchange.com/questions/177201/bibtex-biblatex-verbatim-fields-and-special-characters), but perhaps I need to rephrase the question. It doesn't seem like anyone would be able to really answer the question if none of the current Bib(La)TeX processors support the syntax.

Thanks for pointing me to btparse. I'll try to take this upstream, though, unfortunately, it doesn't look like btOOL is seeing a lot of activity.

**Comment by aurimasv** [comment]
[egreg on TeX.SX](http://tex.stackexchange.com/a/230754/19073) suggested using \textbraceleft, but apparently Biber interprets and expands the macro to an actual brace, which then fails. I haven't actually tested this, but he considered it a bug, so it may be of interest to you to take a look at his answer.

**Comment by plk** [comment]
The only development that goes on in btparse now is by me when I need something for biber. I'll look at that textbraceleft thing - that should probably be a special case.

**Comment by plk** [comment]
I have fixed the `\textbraceleft` and `\textbraceright` in the biber DEV branch. These should never be decoded into chars if they are explicitly mentioned. Using these macros should now work, even if unmatched.
