### ISSUE TITLE
With current master and perl-5.20.2, previously working examples are broken

### ISSUE THREAD

**Issue by zarniwhoop73** [plk/biber#63]
I keep some stupid testfiles at http://higgs.linuxfromscratch.org/~ken/tex-testfiles/tex-test-20150110.tar.xz
which can be invoked with ./configure and make (nothing gets installed).The make targets are biblatex (fairly simple) and bibxelatex (more dependencies). With a fresh from-source build (biblatex-3.0.tds on top of texlive-2014) with all the perl deps present, a lot of perl errors are dumped on stderr:

I've cut that down to a mini example, using pdflatex and biber. On fixed 1.9 and 2014 texlive, it runs. On current master I get errors:
Use of uninitialized value $name in string eq at /usr/lib/perl5/site_perl/5.20.2/Biber/SortLists.pm line 77.
Use of uninitialized value $pre in regexp compilation at /usr/lib/perl5/site_perl/5.20.2/Biber/Internals.pm line 959.
Use of uninitialized value $pre in regexp compilation at /usr/lib/perl5/site_perl/5.20.2/Biber/Internals.pm line 959.
Use of uninitialized value $thislocale in concatenation (.) or string at /usr/lib/perl5/site_perl/5.20.2/Biber.pm line 2767.
Use of uninitialized value $thislocale in concatenation (.) or string at /usr/lib/perl5/site_perl/5.20.2/Biber.pm line 2854.
Use of uninitialized value $thislocale in concatenation (.) or string at /usr/lib/perl5/site_perl/5.20.2/Biber.pm line 2859.
Use of uninitialized value $lname in concatenation (.) or string at /usr/lib/perl5/site_perl/5.20.2/Biber.pm line 1929.
Use of uninitialized value $lssn in concatenation (.) or string at /usr/lib/perl5/site_perl/5.20.2/Biber.pm line 1929.
Use of uninitialized value $lssn in concatenation (.) or string at /usr/lib/perl5/site_perl/5.20.2/Biber.pm line 1943.
Use of uninitialized value $lssn in concatenation (.) or string at /usr/lib/perl5/site_perl/5.20.2/Biber.pm line 1958.
Can't use an undefined value as an ARRAY reference at /usr/lib/perl5/site_perl/5.20.2/Biber/Internals.pm line 949.
make: *** [mini] Error 1

I can't work out how to upload to an issue here, so I've tarred it up as bibmini.tar.gz at http://higgs.linuxfromscratch.org/~ken/tmp/

**Comment by plk** [comment]
I can't reproduce this using your MWE. It all works fine for me - can you pull the "v2.0" tag and try this again?

**Comment by zarniwhoop73** [comment]
On Tue, Apr 21, 2015 at 12:57:08AM -0700, plk wrote:
> I can't reproduce this using your MWE. It all works fine for me - can you pull the "v2.0" tag and try this again?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/plk/biber/issues/63#issuecomment-94685737

Ii updaed, then reset my local tree to v2.0 :

$git reset --hard v2.0
HEAD is now at 62f157d Fixing 2.0 binary deps

But I don't think anything has changed from Sunday's version.  I'm
attaching a tarball which includes the logs as well as the source and
result.  The 'messages' file has both stdout and stderr, created with
'make 2>&1 | tee messages'.

The base system is x86_64 linuxfromscratch-7.7 (binutils-2.25,
gcc-4.9.2,glibc-2.21) with my choice of packages from the matching
beyond- (BLFS) book.  In this case, I built texlive (source) 2014
yesterday, then ran my biber buildscript with what appear to be the
current dependencies.

AFAICS, all the perl tests in this suite passed.  Biber itself
skipped a couple of sets because BIBER_DEV_TESTS was not set, but at
the end it reported:
t/zoterordfxml.t ...... ok
All tests successful.
Files=42, Tests=981, 66 wallclock secs ( 0.21 usr  0.04 sys + 61.70
cusr  2.01 csys = 63.96 CPU)
Result: PASS
Finished testing biber 2.0 using Perl 5.020002 at /usr/bin/perl

Just in case my problem is down to another module, I'll list the perl
modules in build order with their versions: (those up to libwww-perl
were already installed in March).  The direct dependencies should be
reasonably up to date, but the versions of those others that get
pulled in for any 'make test' were last checked for currency in
January.

XML-Parser-2.44 is part of the base system,
XML-Simple-2.20 is part of my Xorg build.

Encode-Locale-1.04
URI-1.65
HTML-Tagset-3.20
HTTP-Date-6.02
IO-HTML-1.001
LWP-MediaTypes-6.02
HTML-Parser-3.71
HTTP-Message-6.06
HTML-Form-6.03
HTTP-Cookies--6.01
HTTP-Negotiate-8.01
Net-HTTP--6.07
WWW-RobotRules-6.02
HTTP-Daemon-6.01
File-Listing-6.04
libwww-perl-6.13

Net-SSLeay-1.68
IO-Socket-SSL-2.010
Mozilla-CA-20141217
LWP-Protocol-https-6.06
Business-ISBN-Data-20140910
Business-ISBN-2.09
Tie-Cycle-1.21
Business-ISMN-1.13
Business-ISSN-0.91
Number-Compare-0.03
Text-Glob-0.09
File-Find-Rule-0.33
Data-Compare-1.25
Data-Dump-1.22
Date-Simple-3.03
Encode-EUCJPASCII-0.03
Encode-JIS2K-0.02
Encode-HanExtra-0.23
File-Slurp-9999.19
IPC-Run3-0.048
Test-Warnings-0.020
Exporter-Tiny-0.042
List-MoreUtils-0.402
List-AllUtils-0.09
Log-Log4perl-1.46
Regexp-Common-2013031301
Capture-Tiny-0.27
Config-AutoConf-0.309
ExtUtils-LibBuilder-0.06
Text-BibTeX-0.70
Text-Roman-3.5
Unicode-Collate-1.12
Encode-ISO2022-0.04
Encode-JISX0213-0.03
MIME-Charset-1.011.3
Unicode-LineBreak-2014.06
XML-NamespaceSupport-1.11
XML-SAX-BASE-1.08
XML-SAX-0.99
XML-LibXML-2.0117
File-Slurp-Tiny-0.003
XML-LibXML-Simple-0.95
XML-LibXSLT-1.94
XML-Writer-0.625
autovivification-0.14
File-Which-1.16
Algorithm-Diff-1.1903
Text-Diff-1.41
Test-Differences-0.63
Test-Pod-1.48
Devel-Symdump-2.14
Pod-Coverage-0.23
Test-Pod-Coverage-1.10

then biblatex-3.0.tds

and biber.

ĸen
-- 
Nanny Ogg usually went to bed early. After all, she was an old lady.
Sometimes she went to bed as early as 6 a.m.

**Comment by plk** [comment]
Where did you attach the intermediary files/logs? I'll need to see these I think - it looks like you are not picking up some of the XML config items.

**Comment by zarniwhoop73** [comment]
On Wed, Apr 22, 2015 at 01:32:54PM -0700, plk wrote:
> Where did you attach the intermediary files/logs? I'll need to see these I think - it looks like you are not picking up some of the XML config items.
> 
I attached them to the mail, guess they got stripped.
I've now uploaded the tarball to
http://www.linuxfromscratch.org/~ken/tmp/ it is called
bibmini-with-logs.tar.gz

ĸen
-- 
Nanny Ogg usually went to bed early. After all, she was an old lady.
Sometimes she went to bed as early as 6 a.m.

**Comment by plk** [comment]
I see this warning:

WARN - Warning: Found biblatex control file version 2.6, expected version 2.7

I see is that the generated .bcf version is 2.6. It should be 2.7 for biblatex 3.0 and that would cause problems, certainly. Are you sure you have installed the new 3.0 version? Did you install over the top of the TL 2014 version? It seems that's what version is being picked up.

**Comment by zarniwhoop73** [comment]
On Wed, Apr 22, 2015 at 07:24:48PM -0700, plk wrote:
> I see this warning:
> 
> WARN - Warning: Found biblatex control file version 2.6, expected version 2.7
> 
> I see is that the generated .bcf version is 2.6. It should be 2.7 for biblatex 3.0 and that would cause problems, certainly. Are you sure you have installed the new 3.0 version? Did you install over the top of the TL 2014 version? It seems that's what version is being picked up.
> 
Oh.  I did not realise I still had a copy of 3.0 from 23rd October.
When I downloaded on 21st April firefox labelled the new one as
.tds(1) and I didn't notice.

I've now installed the correct version and it works fine.  Sorry for
wasting your time, and thanks for your help

ĸen
-- 
Nanny Ogg usually went to bed early. After all, she was an old lady.
Sometimes she went to bed as early as 6 a.m.

**Comment by plk** [comment]
No problem, glad it's fixed.
