### ISSUE TITLE
Will the 2.0 source be uploaded to sourceforge ?

### ISSUE THREAD

**Issue by zarniwhoop73** [plk/biber#64]
Sorry to be a nuisance, but is the 2.0 source going to be uploaded to sourceforge like 1.9 was ? If it is, a version number in the name would be useful. If it isn't, we'll use git. Thanks. ĸen

**Comment by plk** [comment]
I wasn't planning on it as SF now has the ability to link to Github repos so I'd recommend pulling the v2.0 tag from git.

**Comment by zarniwhoop73** [comment]
On Fri, Apr 24, 2015 at 01:00:09PM -0700, plk wrote:
> I wasn't planning on it as SF now has the ability to link to Github repos so I'd recommend pulling the v2.0 tag from git.

OK, thanks.

ĸen
-- 
Nanny Ogg usually went to bed early. After all, she was an old lady.
Sometimes she went to bed as early as 6 a.m.

**Comment by plk** [comment]
Source is back now as it's required by TeXLive.
