### ISSUE TITLE
Incorrect encoding of \"i

### ISSUE THREAD

**Issue by gvdgdo** [plk/biber#65]
In biber 2.0 

\"{\i}

is rendered as 

ı̈  (\u8:̈)

instead of 

ï

**Comment by plk** [comment]
Yes, by default this is true to have consistent accent handling. Is this a problem? The real way to fix this is just use UTF-8 in your .bib and use LuaLatex or XeLatex.

**Comment by gvdgdo** [comment]
It is a problem introduced in biber 2.0. It worked fine in biber 1.9.

The got the bibtex record from DBLP, and I might share the bibtex file with other projects not using biblatex.

All the best

Guido

**Comment by plk** [comment]
I mean, is it really a problem to have it encoded as it is in 2.0? I changed this so that this case is no longer a special case but is a composed char consisting of a diaresis and a dotless i.

**Comment by u-fischer** [comment]
The issue just came up again in the texlive list and in golatex. It is a problem for pdflatex if glyphs with accent are encoded as "glyph + (following) combining accent". pdflatex/inputenc can't handle this as the accent can't look back to find the base glyph.

**Comment by hvoss49** [comment]
run biber with 

biber --output-safechars <file>

**Comment by u-fischer** [comment]
I just remembered this rather old discussion about a similar problem: https://sourceforge.net/p/biblatex-biber/feature-requests/23/

Combining accents are a problem for all engines (for pdflatex always, for xelatex/lualatex if the font doesn't has the accent) -- there are regularly questions when copy&paste on the mac has created umlauts with such accents -- and so should imho be avoided if possible.

**Comment by hvoss49** [comment]
That is the reason why Biber should be run  with --output-safechars in such cases. Then it doesn't change the TeX commands for accented chars.

**Comment by johannesbottcher** [comment]
Another instance popped up: [Upgrading from Biber 1.9 to Biber 2.1 input encoding error](http://tex.stackexchange.com/q/251261/37907)
