### ISSUE TITLE
Biber  2.0 reports an error on name like R{\'egis}

### ISSUE THREAD

**Issue by gvdgdo** [plk/biber#66]
It does report an error when there are multiple authors, not with a single author. 

Here is a MWE.

    \documentclass{article}
    \usepackage[utf8]{inputenc}
    \usepackage{filecontents}
    \usepackage{biblatex}
    
    \begin{filecontents}{\jobname.bib}
    @misc{test,
       author = {Aut\"{\i}or, A{\'e}tor and Governatori, Guido},
       title  = {title},
       year   = 2015,
    }
    \end{filecontents}
    
    \addbibresource{\jobname.bib}
 
    \begin{document}
    \nocite{*}
    \printbibliography
    \end{document}

**Comment by plk** [comment]
This works fine for me using lualatex. pdflatex has problems with some of the UTF8 chars, which is normal - you can try the `--safechars` option to get round this as per the manual. I strongly recommend switching to UTF-8 in your .bib and using Lualatex or Xelatex.

**Comment by gvdgdo** [comment]
The problem is not with a exotic character, and actually it seems it does not depend on the character but by the braces: if I have R{\’e}gis instead of R{\’egis} it works fine.  As far as I know both are legal bibtex expression.  

As I said switching to UTF might not be an option (I don’t want to maintain two bibtex files one in UTF and one in ASCI). 

It used to work fine with biber 1.9.

All the best

Guido

**Comment by plk** [comment]
Can you try with biber 2.1 dev version, just uploaded?

**Comment by gvdgdo** [comment]
I cannot use the script in the bin folder (it gives me some errors about missing libraries) and I cannot build it either. Is there a standalone executable for Mac OS X (10.10)?

**Comment by plk** [comment]
Yes, there should be pre-built binaries for 2.1 in the development folder on SourceForge:

http://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/

**Comment by gvdgdo** [comment]
biber 2.1 dev seems to solve the issue
