### ISSUE TITLE
feature-request: overwrite bib file in tool mode

### ISSUE THREAD

**Issue by thorade** [plk/biber#67]
My bib file is under version control (with git, here on github), so I would prefer to overwrite the existing bib file instead of creating a new one when using biber in tool mode as described here
http://tex.stackexchange.com/q/186733/8569
or in section 3.12 of the documentation.
Would that be possible?

**Comment by plk** [comment]
Yes, this will be possible for tool mode with bibtex output in 2.1. You can do:

```
biber --tool --output_file=foo.bib foo.bib
```

**Comment by thorade** [comment]
Great, thanks. 
With biber 1.9.1 (??) on Kubuntu 14.10 I was getting an empty file.
Looking forward to biber 2.1 then.

**Comment by thorade** [comment]
Just installed Tex Live 2015 with biber 2.1 and I believe this fix changed the default behavior: 
If no output_file is specified, the default was `infile_bibertool.bib` but now it is `_bibertool.bib`.

**Comment by plk** [comment]
Hmm, that is strange - what about the 2.2 dev version on SF?

**Comment by thorade** [comment]
Sorry for answering late. I do not have Perl installed and I have never tested one of the dev versions before. Are there instructions anywhere? I have Xubuntu, Windows 7 64bit and OSX running here.

**Comment by plk** [comment]
You don't perl installed - these are drop-in binary replacements.

**Comment by thorade** [comment]
This is strange: I just downloaded the 2.2 beta and it worked as expected. I then switched back to 2.1 and it also worked as expected. I really tested it before, I guess 10 times!
Looks like this can be closed, sorry for bothering.
