### ISSUE TITLE
Using biber in restricted accounts

### ISSUE THREAD

**Issue by u-fischer** [plk/biber#70]
In a german discussion group a user can't execute biber as it is blocked by a "Gruppenrichtlinie".

Apart from the obvious solution to ask the IT to unblock it, what possibilities are there to use biber in a "portable" way? Is there some environment variable one could use to unpack biber in some local folder? Can one unpack it manually?

**Comment by plk** [comment]
You should be able to set the `PAR_GLOBAL_TEMP` environment variable to choose the extraction cache location - can you see if that works?

**Comment by u-fischer** [comment]
I forwarded the suggestion and will report when I get an answer.

**Comment by plk** [comment]
Did this work?

**Comment by u-fischer** [comment]
No, but I'm not sure if she did everything correctly. I also don't know if she really tried to get around the block or if she found another solution. I now asked if there are news. The thread is here http://golatex.de/biber-der-prozess-ist-abgestuerzt-t15301.html.

**Comment by anatheana** [comment]
I confirm that this is an open issue with Windows biber on computer with Group Policy setting that will deny running exe's, or writing exe's, to %TMP% folder. Centrally administered computers (like mine) may have these kind of restrictions.
I also confirm that setting the environment variable `PAR_GLOBAL_TEMP` to a folder where one can read and execute will solve this problem.

**Comment by mario6097** [comment]
HI 
I think I have a similar issue on a Linux (Fedora 29) machine. How do I set  the environment variable PAR_GLOBAL_TEMP to my web server folder (I use a php script to create my .tex/.pdf files). Thanks.
