### ISSUE TITLE
release-monitoring.org: detects version as 'cygwin32'

### ISSUE THREAD

**Issue by cbm755** [plk/biber#71]
I tried to set-up biber at release-monitoring.org (this is in principle a distro-agnostic service but mainly used by Fedora so far.)

https://release-monitoring.org/project/6443/

It detects the latest version as `cygwin32`, which is not very helpful.  Would it be possible to version these files a little more, maybe in the filename itself rather than just putting them in a `2.1` directory?

I don't know enough about release-monitoring.org to know if that will help but it seems like a good idea anyway.

BTW, biber is now officially in Fedora although unfortunately held back at 1.8 due to old texlive :(

**Comment by plk** [comment]
Can you try to import it again? The OS mappings were broken on SF for some reason and everything was coming up as cygwin.

**Comment by cbm755** [comment]
Same result :(  I'm not the Anitya (software behind release-monitoring.org) and I haven't checked in detail what sort of regex they use to assess this.

But even now when I visit https://sourceforge.net/projects/biblatex-biber/files/ it gives me:

`Looking for the latest version? Download biber-linux_x86_64.tar.gz (15.9 MB)`

But as this has no version, I don't see how it can work...

**Comment by plk** [comment]
What if the URL just goes into the path for linux only binaries? Can it pick up the version from the directly name?:

https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/2.1/binaries/Linux/

**Comment by cbm755** [comment]
Well probably not that URL directly because then when you release 2.2 it won't pick up on it...

(Maybe I should have mentioned: the purpose of this site is to ping distros when new upstream versions are released.)

I could probably write [some kind of custom regex to do it](https://release-monitoring.org/about)... but given that they already have a generic sourceforge script.  I could also try taking it from the git releases page instead....

**Comment by cbm755** [comment]
Ok, that seems to work using github, detects `v2.1`.  Still shows `cygwin32` but maybe that is leftover from previous runs (it does some kind of daily cron).

thanks for your help.
