### ISSUE TITLE
Test problems with perl-5.22 (on the release).

### ISSUE THREAD

**Issue by zarniwhoop73** [plk/biber#72]
The stable version is failing tests with perl-5.22 : Failed 4/42 test programs. 2/959 subtests failed.
Also, excessive output from wide character warnings.
1. A lot of messages (3254 on a quick grep | wc) about UTF-8 characters, which is very odd because you appear to be anticipating these with the no warnings 'utf8'; and the log4perl.appender.Screen.utf8 = 1 lines.
The first few from t/basic-misc.t start
Wide character (U+10FFFD) in lc at (eval 145) line 1.
Wide character (U+10FFFD) in lc at (eval 153) line 1.
Wide character (U+10FFFD) in lc at (eval 154) line 1.
Wide character (U+10FFFD) in lc at (eval 161) line 1.
Wide character (U+10FFFD) in lc at (eval 183) line 1.
Wide character (U+308) in lc at (eval 324) line 1.
Wide character (U+308) in lc at (eval 329) line 1.
Wide character (U+10FFFD) in lc at (eval 329) line 1.
Wide character (U+131) in lc at (eval 330) line 1.
These are just annoying, it looks as if the tests still run. I am not familiar enough with perl to suppress these.
2. A number of warnings, mostly
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\ding{ <-- HERE ([2-9AF][0-9A-F])}/ at /scratch/ken/biblatex-biber-2.1/blib/lib/Biber/LaTeX/Recode.pm line 239.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\A{ <-- HERE \X+}\z/ at /scratch/ken/biblatex-biber-2.1/blib/lib/Biber/Input/file/bibtex.pm line 762.
but also one each of
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\textsuperscript{ <-- HERE ((?^u:SM|y|i|w|=|\+|r|n|8|h|4|5|\)|9|6|0|7|j|\())}/ at /scratch/ken/biblatex-biber-2.1/blib/lib/Biber/LaTeX/Recode.pm line 233.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\textsuperscript{ <-- HERE \\((?^u:textturnrrtail|textinvscr|textturnr|texthth))}/ at /scratch/ken/biblatex-biber-2.1/blib/lib/Biber/LaTeX/Recode.pm line 236.
The end result is 
Failed 4/42 test programs. 2/959 subtests failed.
If I escape the left braces, that becomes
Failed 2/42 test programs. 0/959 subtests failed.
3. After that, with ./build test verbose=1 I can see a little more detail (hashes escaped, the github preview thinks they are markup)
3A bcfvalidation.t
\# Looks like you planned 44 tests but ran 43.
t/bcfvalidation.t ..... 
1..44
[1 to 43 are reported, so I assume the 44th test failed]
ok 43 - Validation of tdata/zoterordfxml.bcf
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/44 subtests 

3B. t/dm-dateformats.t 
\# Looks like your test exited with 255 before it could output anything.
t/dm-dateformats.t .... 
1..33
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 33/33 subtests 
I don't have a git tree for this, and since I don't know what I'm doing on most of it I don't think there is much point me setting one up. For the escapes, a diff against the release is at  http://www.linuxfromscratch.org/~ken/tmp/biber-escapes-for-perl-5.22.diff

**Comment by plk** [comment]
I will need to upgrade to perl 5.22 and look into this, thanks for reporting it.

**Comment by plk** [comment]
I have addressed all of these now - they were caused by some perl 5.22 changes and deprecations. DEV branch on github (version 2.2) now passes cleanly for me with 5.22.

**Comment by zarniwhoop73** [comment]
On Sun, Jun 21, 2015 at 01:26:41AM -0700, plk wrote:
> I have addressed all of these now - they were caused by some perl 5.22 changes and deprecations. DEV branch on github (version 2.2) now passes cleanly for me with 5.22.
> 
Thanks.  It is not yet passing cleanly for me, even using the dev
branch with what is in the biblatex dev branch.  At the moment, I'm
getting two reported failures:

Test Summary Report
-------------------
t/sort-complex.t    (Wstat: 256 Tests: 9 Failed: 1)
  Failed test:  9
  Non-zero exit status: 1
t/sort-order.t      (Wstat: 256 Tests: 15 Failed: 1)
  Failed test:  12
  Non-zero exit status: 1
Files=42, Tests=993, 84 wallclock secs ( 0.40 usr  0.07 sys + 79.68
cusr  4.39 csys = 84.54 CPU)
Result: FAIL
Failed 2/42 test programs. 2/993 subtests failed.

(this is with Unicode-Normalize-1.17 - I saw your bug report)

and the details from the log are:
t/sort-case.t ......... ok

#   Failed test 'sortorder - 3'
#   at t/sort-complex.t line 248.
#     Structures begin differing at:
#          $got->[0] = 'L2'
#     $expected->[0] = 'L1'
# Looks like you failed 1 test of 9.
t/sort-complex.t ...... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/9 subtests 

#   Failed test 'location - sortcase=1'
#   at t/sort-order.t line 504.
#     Structures begin differing at:
#          $got->[6] = 'L6'
#     $expected->[6] = 'L5'
# Looks like you failed 1 test of 15.
t/sort-order.t ........ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/15 subtests 
t/sort-uc.t ........... ok

I'll come back to this in a few days, it is almost certainly
something I'm doing differently.  Meanwhile, your fixes to remove
the warnings about wide characters make it much  more readable.
Thanks.

ĸen
-- 
Nanny Ogg usually went to bed early. After all, she was an old lady.
Sometimes she went to bed as early as 6 a.m.

**Comment by plk** [comment]
I've pushed a couple of fixes for you to try. I think these could be ignored but it would be nice to make it clean if you can try. Can you paste here anyway the output of the "env" command on your test system?

**Comment by zarniwhoop73** [comment]
On Mon, Jun 22, 2015 at 12:50:25AM -0700, plk wrote:
> I've pushed a couple of fixes for you to try. I think these could be ignored but it would be nice to make it clean if you can try. Can you paste here anyway the output of the "env" command on your test system?
> 
I've tried with 'Test fixes for Fedora', no change.

env on this system has:
KDE_MULTIHEAD=false
DM_CONTROL=/var/run/xdmctl
TERM=rxvt-unicode
DESKTOP_STARTUP_ID=deluxe;1434992848;606447;1389_TIME84989
SHELL=/bin/bash
XDG_SESSION_COOKIE=d3e31c08a57b850f9f0f1a1d557bbf06-1434992790.30913-267019222
XDM_MANAGED=method=classic
GS_LIB=/home/ken/.fonts
WINDOWID=44040201
LC_ALL=en_GB.UTF-8
KDE_FULL_SESSION=true
USER=ken
SESSION_MANAGER=local/deluxe:@/tmp/.ICE-unix/1373,unix/deluxe:/tmp/.ICE-unix/1373
DESKTOP_SESSION=default
PATH=/usr/local/bin:/usr/bin:/bin:/usr/games:/opt/texlive/2015/bin/x86_64-linux:/home/ken/bin
INPUTRC=/etc/inputrc
PWD=/scratch/ken/biber-dev
LANG=en_GB.UTF-8
KDE_SESSION_UID=500
PS1=\u@\h \w \$
COLORFGBG=15;0
SHLVL=2
HOME=/home/ken
LANGUAGE=
KDE_SESSION_VERSION=4
XCURSOR_THEME=Oxygen_White
LOGNAME=ken
XDG_DATA_DIRS=/usr/share:/usr/share:/usr/local/share
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-sLzcuGQkSY,guid=fd1251b0ddcceeaf424704cb55884097
WINDOWPATH=7
DISPLAY=:0
QT_PLUGIN_PATH=/home/ken/.kde/lib/kde4/plugins/:/usr/lib/kde4/plugins/
XDG_CURRENT_DESKTOP=KDE
COLORTERM=rxvt
OLDPWD=/scratch/ken
_=/usr/bin/env

NB there is nothing in /usr/local/bin, and neither /usr/games nor
/home/ken/bin exist.

ĸen
-- 
Nanny Ogg usually went to bed early. After all, she was an old lady.
Sometimes she went to bed as early as 6 a.m.

**Comment by plk** [comment]
I think you can ignore this. It's almost certainly to do with minor difference in locales between OSX and Linux. You are using the same locale as I am (en_GB.UTF-8) in the OS and this usually means that the collation tables for the locale are different between OSes. Since the default is to use the Unicode Collation algorithm anyway, this hardly matters. I only use OS locales in the tests to speed them up a bit.

**Comment by zarniwhoop73** [comment]
On Mon, Jun 22, 2015 at 12:40:47PM -0700, plk wrote:
> I think you can ignore this. It's almost certainly to do with minor difference in locales between OSX and Linux. You are using the same locale as I am (en_GB.UTF-8) in the OS and this usually means that the collation tables for the locale are different between OSes. Since the default is to use the Unicode Collation algorithm anyway, this hardly matters. I only use OS locales in the tests to speed them up a bit.

OK, thanks for the explanation.

-- 
Nanny Ogg usually went to bed early. After all, she was an old lady.
Sometimes she went to bed as early as 6 a.m.

**Comment by zarniwhoop73** [comment]
On Mon, Jun 22, 2015 at 12:40:47PM -0700, plk wrote:
> I think you can ignore this. It's almost certainly to do with minor difference in locales between OSX and Linux. You are using the same locale as I am (en_GB.UTF-8) in the OS and this usually means that the collation tables for the locale are different between OSes. Since the default is to use the Unicode Collation algorithm anyway, this hardly matters. I only use OS locales in the tests to speed them up a bit.

No worries.  I found out why the bcfvalidation tests were failing in
2.1 - the bibtex-forms bcf and bib files are missing from the
sourceforge tarball.  I can see they are in the master branch at
github, so I guess that was just "one of those things".  Feel free
to close this issue.  Thanks again.

ĸen
-- 
Nanny Ogg usually went to bed early. After all, she was an old lady.
Sometimes she went to bed as early as 6 a.m.

**Comment by cbm755** [comment]
@zarniwhoop73 thanks for this, it helped with my fedora package.

@plk: I've opened a new bug for the missing bibtex-forms files, #100.
