### ISSUE TITLE
Accent crashes latex_decode

### ISSUE THREAD

**Issue by abusse** [plk/biber#76]
The following entry crashes the latex_decode function in Recode.pm:

```
@article{Test,
	author	= {\'{A}},
}
```

```
[370] Biber.pm:3115> INFO - Looking for bibtex format file 'arch.bib' for section 0
[371] bibtex.pm:113> TRACE - Entering extract_entries() in driver 'bibtex'
[371] bibtex.pm:224> DEBUG - Caching data for BibTeX format file 'arch.bib' for section 0
[372] bibtex.pm:1021> INFO - Decoding LaTeX character macros into UTF-8
[373] bibtex.pm:1022> TRACE - Buffer before decoding -> '@article{Test,
	author	= {\'{A}},
}'
[373] Recode.pm:210> TRACE - String before latex_decode() -> '@article{Test,
	author	= {\'{A}},
}'

[EOF]
```

I just upgrade from 1.9 to 2.1. Before, this was parsed perfectly fine without any issues.

**Comment by plk** [comment]
Yes, this is a tricky edge case since the recoding was generalised in 2.1. It's rather odd to have a field be just one accented character. It works with:

``` {{\'{A}}}```

**Comment by abusse** [comment]
Thanks for the quick answer. This was only a minimal example. The actual problematic entry looks this way:

```
@article{McIntosh-Smith-2012-CPUGPU,
	author	= {McIntosh-Smith, Simon and Wilson, Terry and Ibarra, Amaurys \'{A}vila and Crisp, Jonathan and Sessions, Richard B.},
	title 	= {Benchmarking Energy Efficiency, Power Costs and Carbon Emissions on Heterogeneous Systems},
	journal = {The Computer Journal},
	volume	= {55},
	number	= {2},
	month	= feb,
	year	= {2012},
	issn	= {0010-4620},
	pages	= {192--205},
	numpages = {14},
	doi		= {10.1093/comjnl/bxr091},
	acmid	= {2139582},
	publisher = {Oxford University Press},
	address = {Oxford, UK},
}
```

In the meantime I also identified another issue with the new latex_decode. I use the macro `mkbibsuperscript`, which also results in a crash with an entry like this (I know this issue is most likely very specific to me). Again it was working flawlessly with 1.9.:

```
@inproceedings{Thompson-2002-GPGPU,
	author	= {Thompson, Chris J. and Hahn, Sahngyun and Oskin, Mark},
	title	= {Using Modern Graphics Architectures for General-purpose Computing: A Framework and Analysis},
	booktitle = {Proceedings of the 35\mkbibsuperscript{th} Annual International Symposium on Microarchitecture}
```

**Comment by plk** [comment]
Hmm, do you have the ability to try the DEV version on Sourceforge? With that version I have no problem with your examples.

**Comment by abusse** [comment]
So...I tried the development download from sourceforge. That one seems to work. I cannot confirm it completely because I'm missing the right biblatex package so I got `Warning: Found biblatex control file version 2.6, expected version 2.7`, but I doesn't seem to crash. I also tried the dev branch from the repository here and it showed the same problem as the current 2.1.

**Comment by plk** [comment]
The dev branch version from github doesn't work? You have your own Perl install with all the right modules to try this?

**Comment by abusse** [comment]
I'm using MacPorts, so I have installed everything from source and therefore I have the dependencies. 

However, you gave me an idea. I just upgrade my Perl environment to 5.20 and everything is working fine so far. So either my old Perl installation was corrupted (which I doubt, because I had the problem on two separate installations) or the code somehow requires Perl 5.20 to work.

**Comment by plk** [comment]
Yes, that's true so this was likely the issue.

**Comment by abusse** [comment]
Yes, so thank you for the quick support and keep up the great work!
