### ISSUE TITLE
Wrong sorting with sl-SI locale.

### ISSUE THREAD

**Issue by u-fischer** [plk/biber#78]
I get a different sorting of Ž in sl-SI locale with biblatex/biber of texlive 2014 and texlive 2015 on a windows 7 PC. In tl14 the Ž is behind Z, and in tl15 (and miktex) before. 

See this discussion: http://tex.stackexchange.com/a/255623/2388

~~~~~
\documentclass[12pt]{article}
\usepackage[american]{babel}
\usepackage[backend=biber,style=apa,bibencoding=utf8,sortlocale=sl-SI]{biblatex}
\DeclareLanguageMapping{american}{american-apa}
\addbibresource{bib.bib}
\begin{document}

First Citation: \parencite{Znider}

Second Citation: \parencite{Zupavec}

Third Citation: \parencite{Zach}

\printbibliography
\end{document}
~~~~~~

~~~~~
@ARTICLE{Zach,
   author = {Zachry, John},
   title = {Foo},
   journal = {Bar},
   volume = {1},
   number = {2},
   pages = {123-345},
   year = {1999},
}

@ARTICLE{Znider,
  author = {Žnider, Jože},
  title = {Bar},
  journal = {Foo},
  volume = {12},
  number = {123},
  pages = {11-12},
  year = {1999},
}

@ARTICLE{Zupavec,
  author = {Zupavec, Miha},
  title = {FooBar},
  journal = {BarBar},
  volume = {100},
  pages = {132-154},
  number = {2},
  year = {1999},
}
~~~~~~

**Comment by nejctrdin** [comment]
I can confirm that with pdfTeX 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian) and biber 1.9 I get the same result as @u-fischer on tl14.

**Comment by plk** [comment]
I get the correct result on TL 15 however, on OSX.

**Comment by u-fischer** [comment]
I tried with \v{Z}, with Z + combining Caron, with other chars with Caron, I also moved the caron inside the word but it is still wrong. And as I wrote in tex.sx: with biber 4.0 (beta) it works correctly again.  This is quite curious ...

**Comment by plk** [comment]
Any updates with biber 2.2?

**Comment by u-fischer** [comment]
Just tested with biber 2.2 (beta) and the sorting is correct (on windows 10). If I find time I will test on windows 7 tomorrow.

**Comment by plk** [comment]
biber 2.2 is released now so you can try it with the official version. You'll need biblatex 3.1

**Comment by u-fischer** [comment]
I got the new biber with texlive but not yet the new biblatex (ditto with miktex). With the old biblatex I get the expected warning but also the correct sorting.
