### ISSUE TITLE
Some tests fail using perl 5.22

### ISSUE THREAD

**Issue by hpreusse** [plk/biber#80]
http://bugs.debian.org/796944

After upgrading to perl 5.22 some tests from the test suite are failing (see issue above). A few of them could be solved by a patch from Gregor Hermann[1], but not all. Please be so kind to look at this. Instructions how to setup perl 5.22 on Debian can be found in the issue.

Hilmar

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=796944;att=1;msg=40;filename=fix-perl-regex-braces

**Comment by plk** [comment]
Are you testing the DEV branch? This should already be fixed.

**Comment by hpreusse** [comment]
Works in dev branch. Do you have a release date for biber 2.2 or could you provide a patch? Thanks!

**Comment by plk** [comment]
Will be in September I think. You can always just use git and make a patch against the master branch?

PK

> On 28 Aug 2015, at 12:27 pm, hpreusse <notifications@github.com> wrote:
> 
> Works in dev branch. Do you have a release date for biber 2.2 or could you provide a patch? Thanks!
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Dr Philip Kime

**Comment by hpreusse** [comment]
Commit fe8fe2df01c507392983d5c81e5d04406ba6cec0 solves the problem. Sorry for the noise!
