### ISSUE TITLE
Understanding the handling of diacretics

### ISSUE THREAD

**Issue by u-fischer** [plk/biber#82]
This is not an issue. But a question on tex.sx made me curious.

When I run `biber --tool bib.bib` on this bib-file

~~~~~~
@misc{exampleone,
author = {Jos{\'{e}} and  H{\'{\i}}drica},
title = {Title}
}
~~~~~~

then the accented chars in the authors are encoded like this:

~~~~~
  AUTHOR = {Jos U+00E9 and H U+0131 U+0301drica},
~~~~~

I understand why the {\'{\i}} is converted to `U+0131 U+0301`, but why is the é  `U+00E9` and not `U+0065 U+0301`? I have been now looking for an hour at recode.pm and recode_data.xml and can't see the reason. (Just to avoid a misunderstanding: it is good that é is U+00E9).

**Comment by plk** [comment]
It's just down to the complexities of dealing with these things. There are special Unicode code points for these things but without lots of hard-coded special cases, it's quite tricky. Dotless i and j are a pain to deal with.
