### ISSUE TITLE
Inconsistency when overriding date fields

### ISSUE THREAD

**Issue by moewew** [plk/biber#83]
I'm not entirely sure if that really is the right place to ask, but here goes.

In the MWE

```
\documentclass[]{article}
\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
@book{date:year,
  author       = {Uthor, Anne},
  title        = {Date and Year},
  date         = {2005-10-16},
  year         = {2015},
  month        = {11},
  day          = {27},
}
@book{year:date,
  author       = {Uthor, Anne},
  title        = {Year and Date},
  year         = {2015},
  month        = {11},
  day          = {27},
  date         = {2005-10-16},
}
\end{filecontents*}
\usepackage[style=verbose]{biblatex}
\addbibresource{\jobname.bib}

\begin{document}
\nocite{*}

\printbibliography
\end{document}
```

you will find that in both cases the `date` field overrides the `month` and `year` given; but only if the `date` comes after the `day` field does it also override an explicit `day`. There is also no warning issued about the `day` field. (I will admit though that a `day` field is not even mentioned as a field in chapter 2 of the `biblatex` documentation.)

**Comment by plk** [comment]
`day` is not s field you should use in the .bib, that's why it's not in the docs. `date` is automatically split into `year`, `month` and `day` by biber. Either use `year` and `month` or `date` but not both.

**Comment by moewew** [comment]
Mhhh, I thought as much since `day` is not mentioned in the docs. But I still find the behaviour somewhat odd. Especially that `day` seems to work very well even though it probably should have no influence at all. Maybe one could just set Biber to discard ore any input it gets from the `day` field.

**Comment by plk** [comment]
I could put in a sourcemap to remove it but since it's not in the docs, I didn't expect anyone to try to use it ...

**Comment by moewew** [comment]
That could be one solution that could at least prevent unwanted behaviour in that since `day` isn't mentioned as a valid field it should have no influence on the output.
(Would it be sensible and possible to issue a warning about a `day` field? - I'm still struggling a bit with the fact that it is handled so differently from `month` and `year`.)

**Comment by plk** [comment]
Try biblatex 3.1 DEV on SF - I have put in a map to remove explicit DAY fields.

**Comment by moewew** [comment]
That works very well, thank you?

Just out of interest: Is it Biber that issues the "Overwriting field 'year' with month value from field 'date'" warnings or does that come from the underlying parsing library?
And while I'm at it, my solution to [the TeX.SX question already mentioned](http://tex.stackexchange.com/q/265895/35864) was to introduce a source map to the `.conf` for tool mode, but in a way I feel that is wasting Biber's resources as the decomposition into `year` and `month` is done automatically. Would it be possible to add an option for converting `date` fields to `year` and `month` fields in order to make `.bib` files downward compatible to the tool mode?

**Comment by plk** [comment]
It's biber that issues those messages, yes. A sourcemap is the way to go really here since the date field is a standard ISO format and therefore easy to parse.

**Comment by moewew** [comment]
I see, thank you.
The sourcemap works well enough (and my version could probably be modified a bit so that one could call it elegant), I was just thinking there might be away to make Biber output the work it does anyway. But I have really no idea what that would need in terms of modifications to the Perl code.
