### ISSUE TITLE
If month is specified, biber exits early, and bbl is empty

### ISSUE THREAD

**Issue by jonathanunderwood** [plk/biber#84]
I am using biber 1.8 and biblatex 2.8 on Fedora 22, which I realize are old versions, but right now I can't test the current version to see if this is still an issue, so I wanted to report it here in the hope it can be confirmed fixed in the latest biber/biblatex.

The following file causes biber to exit early, with no message, and leaves the bbl file empty. Removing the month= {May} field allows biber to run properly. However, it should cope with the Month tag. Also happens for booklet and techreport types.

````
\documentclass[a4paper]{article}

\usepackage[utf8]{inputenc}
\usepackage{csquotes}

\RequirePackage{filecontents}
\begin{filecontents}{refs.bib}
@book{doe13,
    address    = {City},
    title      = {A nice title},
    shorttitle = {Short title},
    publisher  = {Publisher},
    author     = {Doe, John},
    month      = {May},
    year       = {2013}
}
\end{filecontents}

\usepackage[backend=biber]{biblatex}
\addbibresource{refs.bib}

\begin{document}

Hello. \cite{doe13}.

\nocite{*}

\printbibliography

\end{document}
````

**Comment by plk** [comment]
Months should be specified by number, not string as they can be localised - try `month = 05` for example.

**Comment by jonathanunderwood** [comment]
On 6 Oct 2015 09:44, "plk" <notifications@github.com> wrote:
>
> Months should be specified by number, not string as they can be localised
- try month = 05 for example.
>

Sure. But biber really shouldn't just bail with no warning/error, which is
what happens with 1.8. Has the situation improved with current biber?

**Comment by plk** [comment]
True - it works fine for me with the latest biber. Internally, biber tries to convert any months like that into numbers as this is what biblatex needs.

**Comment by jonathanunderwood** [comment]
OK, great, thanks for confirming it's fixed in recent biber. I don't suppose you know which commit fixed the issue? If so, I'll ask the Fedora maintainer to backport the patch.

**Comment by plk** [comment]
I can't find the commit quickly, can you upgrade biber/biblatex with the usual texlive tools?
