### ISSUE TITLE
Write an error in the .log file whenever a cache clean up is necessary

### ISSUE THREAD

**Issue by dbitouze** [plk/biber#85]
I just had to help a user who didn't understand what was wrong with its bibliography (he was running `latexmk` from his (La)TeX editor). I asked him to run `biber` in the (somehow frightening) console and it returned:

```
read_file
'/var/folders/qb/c8m79qfj6639r8yf_1bqn2mh0000gn/T/par-736d66/cache-6bef3f811cde577dd70e44f9f5046ebc66712c46//inc/lib/Biber/LaTeX/recode_data.xml' -
sysopen: No such file or directory at
/var/folders/qb/c8m79qfj6639r8yf_1bqn2mh0000gn/T/par-736d66/cache-6bef3f811cde577dd70e44f9f5046ebc66712c46/60940e05.pm
```

Whenever `biber`'s compilation fails for this kind of reasons, `biber` should write an error in the `.log` file with appropriate help message (such as "Please delete directory ... or run in a console `` rm -rf `biber --cache` ``"): most of (La)TeX editors filter errors from `.log` but not from `.blg`.

**Comment by plk** [comment]
This error is well known and should no longer occur in the latest DEV version. It's impossible to write a message as it's a really fundamental error in a module which biber uses. This was fixed recently in the module in question.

**Comment by dbitouze** [comment]
Very good news! :) Thanks!

**Comment by dbitouze** [comment]
>This error is well known and should no longer occur in the latest DEV version.

Does the last `biber`'s version (2.2) implement this?

**Comment by plk** [comment]
yes ...

**Comment by dbitouze** [comment]
BTW, `biber` version 2.2 has been released but not `biblatex` version 2.8, hence the current warning during `biber` compilations:

> WARN - Warning: Found biblatex control file version 2.7, expected version 2.8

**Comment by plk** [comment]
They are working on it - they forgot to pull biblatex 3.1 into CTAN.

**Comment by dbitouze** [comment]
> This error is well known and should no longer occur in the latest DEV version.

The `biber`'s doc (version 2.3) still contains a section about "Binary Caches" which says:

> This is particularly true if you are regularly testing new versions of the Biber binary. It is a good idea to delete the caches for older binaries as they are not needed and can take up a fair bit of space.

Should this section be dropped or updated?

**Comment by plk** [comment]
Actually no, this is still relevant. The error was about corrupt caches, not multiple caches for alternate versions.
