### ISSUE TITLE
biber --tool mode does not preserve @comment entries

### ISSUE THREAD

**Issue by bluebirch** [plk/biber#86]
Using biber --tool for sorting the BibTeX file removes all @comment entries.

**Comment by plk** [comment]
Yes, it's somewhat impossible to retain them since tool move can arbitrarily re-shuffle entries about in the file and it's impossible to know where to put the comments back again. Biblatex+biber uses .bib files essentially as databases, not freeform text files where position in the file matters. As soon as .bib data is read into biber, you have lost the text file semantics of the .bib file and so positional comments are meaningless.

**Comment by bluebirch** [comment]
`@comment{}` is also used by JabRef (and probably other bibliography managers as well) to store information about groups and such things. In this case, it does not matter where in the file comments are stored (JabRef just adds it at the end of the file). From a bibliography data processing point of view, `@comment{}` entries can be ignored, but users who insist on using biber as a pretty-printing tool (like me) would certainly appreciate if `biber` could just retain `@comment` entries ontouched and lumped together at the end of the BibTeX file. :-)

**Comment by plk** [comment]
Ok, please try biber 2.2 DEV version on SourceForge - tool mode should now preserve comments at the end of the file.

**Comment by bluebirch** [comment]
JabRef metadata is preserved, exactly as requested, and I am amazed as well as grateful for such a quick response! Thank you!

**Comment by bluebirch** [comment]
Some further testing reveals that biber removes newlines from `@comment` entries. Unfortunately, this breaks parsing of the JabRef group tree.

**Comment by plk** [comment]
Can you give me an example of such comments?

**Comment by bluebirch** [comment]
```
@comment{jabref-meta: groupstree:
0 AllEntriesGroup:;
1 ExplicitGroup:Doktorandkurser\;2\;;
2 KeywordGroup:Från könsroll till genus\;0\;course\;UCGS Från könsroll
till genus\;0\;0\;;
2 KeywordGroup:Historiska och filosofiska perspektiv på psykologi\;0\;
course\;Historiska och filosofiska perspektiv på psykologi\;0\;0\;;
2 KeywordGroup:Kurs i introduktion\;0\;course\;Kurs i introduktion\;0\
;0\;;
2 KeywordGroup:Fenomenologi, kön och genus\;0\;course\;UCGS Fenomenolo
gi\;0\;0\;;
2 KeywordGroup:Quantitative Research Methods\;0\;course\;QMR\;0\;0\;;
2 KeywordGroup:Multivariate Analysis\;0\;course\;MVA\;1\;0\;;
}
```

Examining it at closer range, it seems that JabRef writes fixed-width lines. And joining them works in one of my .bib files, but not the other. There must be something going on here that is not as simple as newlines, but I have to delve deeper into it. Anyway, treating comments verbatim should do it.

**Comment by plk** [comment]
Please try 2.2 again - it is a pain because the underlying btparse library strips spaces and newlines from comments but I have put in a hack to detect jabref comments and reinstate them.

**Comment by bluebirch** [comment]
I haven't tried the 2.2 version yet, I just want to mention that I have filed a bug report with the JabRef team (https://github.com/JabRef/jabref/issues/250), since I actually consider this a JabRef and not a `biber` bug.

**Comment by bluebirch** [comment]
With the latest development build of JabRef, I consider this issue solved.

**Comment by ClaudiusL** [comment]
Would it be possible to make this new behaviour optional?

I used `biber --tool` *because* this removed the JabRef comments. A sourcemap removing the `@comment` entries is ignored:

    <map>
      
      <per_type>comment</per_type>
      <map_step map_entry_null="1"/>
    </map>

**Comment by plk** [comment]
I have added a "--strip-comments" option to biber for this in version 2.3 (in development folder on Sourceforge). You will need to be using biblates 3.2 development version too. `@COMMENT` entries are not a real "type" in bibtex, they are a separate meta-type and this makes a sourcemap for them rather tricky.

**Comment by ClaudiusL** [comment]
Great, thank you!
