### ISSUE TITLE
Biber website: Forum and bug tracker links don't work

### ISSUE THREAD

**Issue by logological** [plk/biber#90]
According to Biber's PDF documentation, the project's bug tracker is here on GitHub.  However, the footer of the [Biber website](http://biblatex-biber.sourceforge.net/) still points users to the bug tracker on SourceForge, which is locked down.  The website also instructs users to seek help via a forum, but the link goes only to a page which says "No forums exist".

**Comment by plk** [comment]
Fixed, thanks for reporting this.
