### ISSUE TITLE
biber --tool crashes when inheriting author/editor

### ISSUE THREAD

**Issue by ClaudiusL** [plk/biber#91]
The following example from the Biber manual works: 

	@BOOK{b1,
	TITLE = {Booktitle},
	CROSSREF = {mvalias}
	}
	@MVBOOK{mv1,
	IDS = {mvalias},
	TITLE = {Maintitle},
	SUBTITLE = {Mainsubtitle},
	TITLEADDON = {Maintitleaddon}
	}

Running `biber --tool --output_resolve test.bib` works smoothly. 

However, as soon as the `@MVBOOK` entry has a field `AUTHOR` or `EDITOR`, Biber crashes:

	@BOOK{b1,
	TITLE = {Booktitle},
	CROSSREF = {mvalias}
	}
	@MVBOOK{mv1,
	IDS = {mvalias},
	TITLE = {Maintitle},
	AUTHOR = {TEST},
	TITLEADDON = {Maintitleaddon}
	}

Output:

	biber --tool --output_resolve test.bib
	INFO - This is Biber 2.2 running in TOOL mode
	INFO - Logfile is 'test.bib.blg'
	INFO - Looking for bibtex format file 'test.bib'
	INFO - Decoding LaTeX character macros into UTF-8
	INFO - Found BibTeX data source 'test.bib'
	Can't locate object method "count_names" via package "TEST" (perhaps you forgot
	to load "TEST"?) at Somepath\AppData\Local\Temp\par-436c61756469757320
	4c\cache-c35805b2066c48f7e049902e2c35ce42442bae88\inc\lib/Biber.pm line 1817.

I updated to Biber 2.2 today; this worked with the previous version I used (1.7).
OS: Windows 7 with Strawberry Perl 5.20.3.1.

**Comment by plk** [comment]
Please try version 2.3 from Sourceforge. You will need biblatex 3.2 from Sourceforge too.

**Comment by ClaudiusL** [comment]
Yes, Biber 2.3 works. Thanks for the quick fix!
