### ISSUE TITLE
Biber can't call method “get_field” on an undefined value

### ISSUE THREAD

**Issue by cfr42** [plk/biber#93]
Biber is exiting with an error of the following kind when processing data which caused no error until very recently. 

The error is of the following kind:

```bash
Can't call method "get_field" on an undefined value at /tmp/par-636672656573/cache-c198dfb38941e814f5331b149bc84facd9e9c2e6/inc/lib/Biber.pm line 2247.
```

The following example can be used to reproduce the problem using `pdflatex` -> `biber`.

```latex
\begin{filecontents}{\jobname.bib}
@bookinbook{entry1,
  ids			=	{entry3},
  title			=	{Original Title},
  crossref		=	{entry2},
  origdate		=	1098}
@bookinbook{entry4,
  title			=	{Another Original Title},
  crossref		=	{entry2},
  origdate		=	1076}
@inbook{entry2,
  author		=	{Author, A. N.},
  title			=	{Collected Works},
  publisher		=	{Old Books 'n Stuff},
  location		=	cam,
  date			=	{2003}}
\end{filecontents}
\begin{filecontents}{places.bib}
@string{cam		=	{Cambridge}}
\end{filecontents}
\documentclass{article}
\usepackage[backend=biber]{biblatex}
\bibliography{places,\jobname}
\begin{document}
\textcite{entry1}
\begin{refsection}
  \textcite{entry3,entry4,entry2}
  \printbibliography
\end{refsection}
\end{document}
```

Further details at http://tex.stackexchange.com/questions/278305/biber-cant-call-method-get-field-on-an-undefined-value?noredirect=1#comment670148_278305.

This has been confirmed by at least two other members of TeX SE (one in comments and one in chat) and I have reproduced the error on two machines running different GNU/Linux distros (Fedora and ArchLinux).

Biber is version 2.2.. Biblatex is version 3.1 (2015/10/21).

**Comment by plk** [comment]
Please try version 2.3 DEV version from Sourceforge. I'm surprised this ever worked as it's a very specific situation.
