### ISSUE TITLE
Unicode-Normalize >= 1.22 has XS stuff again

### ISSUE THREAD

**Issue by cbm755** [plk/biber#96]
I haven't actually tested yet:

[Citation](http://codeverge.com/perl.perl5.porters/unicode-normalize/2038431) and see also [perl-U-N changelog](http://cpansearch.perl.org/src/KHW/Unicode-Normalize-1.24/Changes).

**Comment by plk** [comment]
This is already rolled into the 2.3 DEV release.

**Comment by cbm755** [comment]
Ah, sorry I checked master but didn't notice the dev branch.  thanks!
