### ISSUE TITLE
OK to remove unnecessary deps?

### ISSUE THREAD

**Issue by cbm755** [plk/biber#98]
Can you comment on the following deps?  Is it right to drop these from `Build.PL`?

- [x] See PR #97.
- [ ]
Encode::EUCJPASCII, Encode::HanExtra, Encode::JIS2K seem to be unused as well, but they are mentioned in various build scripts:
````
grep * -r -i -e hanextra
Build.PL:        'Encode::HanExtra' => 0,
dist/darwin_x86_64/build.sh:  --module=Encode::HanExtra \
dist/cygwin32/build.sh:   --module=Encode::HanExtra \
dist/linux_x86_64/build.sh:  --module=Encode::HanExtra \
dist/linux_x86_32/build.sh:  --module=Encode::HanExtra \
dist/darwin_x86_i386/build.sh:  --module=Encode::HanExtra \
dist/MSWin32/build.bat:  --module=Encode::HanExtra ^
````

- [ ] List::MoreUtils?
````
grep * -r -i -e moreutil
Build.PL:        'List::MoreUtils' => 0,
Build.PL:        'List::MoreUtils::XS' => 0,
dist/darwin_x86_64/build.sh:  --module=List::MoreUtils::XS \
dist/darwin_x86_64/build.sh:  --module=List::MoreUtils::PP \
dist/cygwin32/build.sh:   --module=List::MoreUtils::XS \
dist/cygwin32/build.sh:   --module=List::MoreUtils::PP \
dist/linux_x86_64/build.sh:  --module=List::MoreUtils::XS \
dist/linux_x86_64/build.sh:  --module=List::MoreUtils::PP \
dist/linux_x86_32/build.sh:  --module=List::MoreUtils::XS \
dist/linux_x86_32/build.sh:  --module=List::MoreUtils::PP \
dist/darwin_x86_i386/build.sh:  --module=List::MoreUtils::XS \
dist/darwin_x86_i386/build.sh:  --module=List::MoreUtils::PP \
dist/MSWin32/build.bat:  --module=List::MoreUtils::XS ^
dist/MSWin32/build.bat:  --module=List::MoreUtils::PP ^
````

**Comment by plk** [comment]
The Encode stuff can't be removed as it can be loaded dynamically based on encoding choices from the user. The Encode modules are often like this - they are not mentioned in the code but various command-line flags might well cause them to be needed. The PP more utiles modules. Hmm. There was some reason I included the pure perl ones as well but I can't quite remember offhand.

**Comment by cbm755** [comment]
Encode: ok.  We haven't been depending on those in Fedora but I can add them.

`List::MoreUtils`: I meant why is this module a dep?  PP or XS, I don't see either used.

**Comment by plk** [comment]
This is because `List::AllUtils` is used a lot and this is just some sort of wrapper for `List::MoreUtils` and, as I remember, without this dep packed, it fails. This often happens with `Module::Scandeps` - sometimes the auto-detection fails for wrapped modules and you have to explicitly add them as dependencies.

**Comment by cbm755** [comment]
thanks for your help, I'll update the deps in Fedora.  How about #97?  Is it wrong too?
