### ISSUE TITLE
`biber --tool` silently fails/crashes with utf8 chars

### ISSUE THREAD

**Issue by cbm755** [plk/biber#99]
I hesitate to file this, b/c my understanding of what biber is supposed to do with utf-8 is so poor...

This file containing a single utf-8 char causes `biber --tool` to crash:
https://bugzilla.redhat.com/attachment.cgi?id=1076155

This is a Fedora bug report:
https://bugzilla.redhat.com/show_bug.cgi?id=1265601

Its reported [downstream](https://bugzilla.redhat.com/show_bug.cgi?id=1265601) against biber 1.8, but I think I can confirm with dev branch.

**Comment by plk** [comment]
Might need a bit more information - if I take that entry into `testx.bib" and run:

`biber --tool testx.bib`

with the 2.3 DEV version, it's fine.

**Comment by cbm755** [comment]
Oops, yes its fine, even in 2.1, sorry for the noise.
